### ISSUE TITLE
Issue with Selection

### ISSUE THREAD

**Issue by cloviswarlop229** [felixge/node-mysql#1005]
CODE:
```js
var my_query_login = "SELECT * FROM accounts WHERE username='"+query['username']+"' AND password='"+query['password']+"'";
connection.query(my_query_login, function(err, rows, fields) {
```
DEBUG:
```sql
SELECT * FROM accounts WHERE username='test' AND password='foutpass'
```
SERVER REPLY: 
```js
{ fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '(Rows matched: 1  Changed: 0  Warnings: 0',
  protocol41: true,
  changedRows: 0 }
```
If i type the same query as in the debug field into Phpmyadmin i get " MySQL returned an empty result set (i.e. zero rows). (Query took 0.0008 sec)" which is correct as there is no row with username = test and password = foutpass

Thanks in advance

**Comment by dougwilson** [comment]
Can you add a `connection.config.debug = true` right before your `.query` and paste the output it provides for that query?

**Comment by cloviswarlop229** [comment]
SELECT * FROM accounts WHERE username='test' AND password='testpass'
--> ComQueryPacket
{ command: 3,
  sql: 'SELECT * FROM accounts WHERE username=\'test\' AND password=\'testpass\'' }

<-- ResultSetHeaderPacket
{ fieldCount: 7, extra: undefined }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'id',
  orgName: 'id',
  charsetNr: 63,
  length: 32,
  type: 3,
  flags: 16899,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'username',
  orgName: 'username',
  charsetNr: 33,
  length: 384,
  type: 253,
  flags: 20489,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'password',
  orgName: 'password',
  charsetNr: 33,
  length: 384,
  type: 253,
  flags: 4097,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'email',
  orgName: 'email',
  charsetNr: 33,
  length: 384,
  type: 253,
  flags: 20481,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'balance',
  orgName: 'balance',
  charsetNr: 63,
  length: 32,
  type: 3,
  flags: 4097,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'last_login',
  orgName: 'last_login',
  charsetNr: 63,
  length: 19,
  type: 7,
  flags: 1249,
  decimals: 0,
  default: undefined,
  zeroFill: true,
  protocol41: true }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'session',
  orgName: 'session',
  charsetNr: 33,
  length: 384,
  type: 253,
  flags: 4097,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- EofPacket
{ fieldCount: 254,
  warningCount: 0,
  serverStatus: 2,
  protocol41: true }

<-- EofPacket
{ fieldCount: 254,
  warningCount: 0,
  serverStatus: 2,
  protocol41: true }

[]

**Comment by sidorares** [comment]
that does look strange. I would expect empty rows array and 7 element fields array  in the callback
@cloviswarlop229  the result you see looks more like insert/set etc response. Are you sure your it is printed from my_query_login query callback?

**Comment by cloviswarlop229** [comment]
MY CODE :
var my_query_login = "SELECT * FROM accounts WHERE username='"+query['username']+"' AND password='"+query['password']+"'";
					connection.config.debug = true;
					console.log(my_query_login);
					connection.query(my_query_login, function(err, rows, fields) {
OUTPUT :
SELECT * FROM accounts WHERE username='test' AND password='foutpass'
--> ComQueryPacket
{ command: 3,
  sql: 'SELECT * FROM accounts WHERE username=\'test\' AND password=\'foutpass\'' }

<-- ResultSetHeaderPacket
{ fieldCount: 7, extra: undefined }
...

There is only one other database event fired and that's this one right after it : 

--> ComQueryPacket
{ command: 3,
  sql: 'UPDATE accounts SET session=\'56092033-b818-469f-93e8-41b0cb14ee1b\' WHERE username=\'test\'' }

<-- OkPacket
{ fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '(Rows matched: 1  Changed: 0  Warnings: 0',
  protocol41: true,
  changedRows: 0 }

{ fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '(Rows matched: 1  Changed: 0  Warnings: 0',
  protocol41: true,
  changedRows: 0 }

There's only these 2 database events being triggered and the output corresponds with my debugging lines.

**Comment by sidorares** [comment]
ok, so your result is for `UPDATE accounts SET session='56092033-b818-469f-93e8-41b0cb14ee1b' WHERE username='test'` query, not for select

**Comment by cloviswarlop229** [comment]
This is from update : (which works and is correct)
--> ComQueryPacket
{ command: 3,
  sql: 'UPDATE accounts SET session=\'56092033-b818-469f-93e8-41b0cb14ee1b\' WHERE username=\'test\'' }

<-- OkPacket
{ fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '(Rows matched: 1  Changed: 0  Warnings: 0',
  protocol41: true,
  changedRows: 0 }

{ fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '(Rows matched: 1  Changed: 0  Warnings: 0',
  protocol41: true,
  changedRows: 0 }

This is from SELECT : (doesn't work)
SELECT * FROM accounts WHERE username='test' AND password='foutpass'
--> ComQueryPacket
{ command: 3,
  sql: 'SELECT * FROM accounts WHERE username=\'test\' AND password=\'foutpass\'' }

<-- ResultSetHeaderPacket
{ fieldCount: 7, extra: undefined }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'id',
  orgName: 'id',
  charsetNr: 63,
  length: 32,
  type: 3,
  flags: 16899,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'username',
  orgName: 'username',
  charsetNr: 33,
  length: 384,
  type: 253,
  flags: 20489,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'password',
  orgName: 'password',
  charsetNr: 33,
  length: 384,
  type: 253,
  flags: 4097,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'email',
  orgName: 'email',
  charsetNr: 33,
  length: 384,
  type: 253,
  flags: 20481,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'balance',
  orgName: 'balance',
  charsetNr: 63,
  length: 32,
  type: 3,
  flags: 4097,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'last_login',
  orgName: 'last_login',
  charsetNr: 63,
  length: 19,
  type: 7,
  flags: 1249,
  decimals: 0,
  default: undefined,
  zeroFill: true,
  protocol41: true }

<-- FieldPacket
{ catalog: 'def',
  db: 'lsdl',
  table: 'accounts',
  orgTable: 'accounts',
  name: 'session',
  orgName: 'session',
  charsetNr: 33,
  length: 384,
  type: 253,
  flags: 4097,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- EofPacket
{ fieldCount: 254,
  warningCount: 0,
  serverStatus: 2,
  protocol41: true }

<-- EofPacket
{ fieldCount: 254,
  warningCount: 0,
  serverStatus: 2,
  protocol41: true }

[]

**Comment by dougwilson** [comment]
I am closing this, because all the evidence posted here shows no problem at all; you seem to be confusing the SELECT with the UPDATE. I can reopen if you provide a db schema, data yo load into it, and a complete script we can run that demonstrates the issue. Otherwise all I see here is that you are confusing the output from your UPDATE with your SELECT.

**Comment by bigorangemachine** [comment]
I'm experiencing results similar to this.  Its a very strange bug.
