### ISSUE TITLE
How to remove group from PoolCluster?

### ISSUE THREAD

**Issue by MalyshevDmitry** [felixge/node-mysql#1006]
Hello.

I need to remove some group of PoolCluster by pattern. For example:

```
poolCluster.add('shard1', config);
poolCluster.add('shard2', config);
poolCluster.add('shard3', config);
```

Sometime later I need to remove one of group:
```
poolCluster.remove('shard2');
```

**Comment by dougwilson** [comment]
Currently there is no way to remove nodes from the pool cluster, but PRs are welcome!

**Comment by MalyshevDmitry** [comment]
Ok. Do you think it necessary to make `emit('remove', node.id)` if the removal is a manual? Or maybe add `emit('removeManually', node.id)` in this case?

**Comment by MalyshevDmitry** [comment]
Please pay attention on PR #1007 for current issue.
