### ISSUE TITLE
Getting object  has no method 'createPool' error

### ISSUE THREAD

**Issue by Mikejonesab12** [felixge/node-mysql#1008]
I have created single connections and gotten them to work, but when I try to create a pool I get this error in my console:

<pre>
TypeError: Object #<Object> has no method 'createPool'
    at Object.<anonymous> (/home/michael/dev/brijjer/server.js:4:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

</pre>

I am calling it like this:

<pre>
var mysql = require('mysql');

var pool = mysql.createPool({
            connectionLimit: 10,
            host: 'host',
            user: 'user',
            password: 'password',
            database: 'database'
        })
</pre>

Any reason why?

**Comment by dougwilson** [comment]
If that is the _only_ code you have and still have that error, there are only two answers:

1. You are using some really old version of this module that doesn't have pools
2. require('mysql'); is not returning this module.

**Comment by Mikejonesab12** [comment]
I'm an idiot. I was using this https://www.npmjs.com/package/node-mysql thinking it was your node-mysql. It works as expected when I use 'mysq'l as my npm dependency instead of 'node-mysql'.

Thanks for the quick response and great library!

**Comment by dougwilson** [comment]
No problem! I didn't even realize that there was a published module "node-mysql" on npm :(
