### ISSUE TITLE
no callback assignment in query(sql, values, cb)

### ISSUE THREAD

**Issue by whyzcandy** [felixge/node-mysql#1009]
In Connection.createQuery in Connection.js
for the query(sql, values, cb) case, cb = cb is missing.

**Comment by dougwilson** [comment]
This is as-intended. The callback should be provided to the `.query` method.

**Comment by whyzcandy** [comment]
hmm,  but query calls Connection.createQuery(sql, values, cb), so cb is never assigned?

**Comment by dougwilson** [comment]
Actually, `cb` is assigned right here: https://github.com/felixge/node-mysql/blob/master/lib/Connection.js#L60 then https://github.com/felixge/node-mysql/blob/master/lib/protocol/sequences/Query.js#L12 then https://github.com/felixge/node-mysql/blob/master/lib/protocol/sequences/Sequence.js#L21

So, are you experiencing an issue? What is the issue you are experiencing, what version of this module are you using, and can you provide a code example that reproduces the issue?

**Comment by whyzcandy** [comment]
for insert query, the callback is never called.

**Comment by whyzcandy** [comment]
I discovered it because I had connection.release in the callback, and the connections never got released. I'm using 2.5.3.

**Comment by dougwilson** [comment]
Ok. I'm not able to reproduce at all and the callback is definitely being assigned as `query._callback` like it should. Can you provide code that reproduces the issue?

**Comment by dougwilson** [comment]
The only thing I have to go off so far is your intial report that `connection.createQuery` doesn't store the callback; using 2.5.3, I'm seeing the opposite behavior (notice that `my_func` appears in the object under `_callback`, as it should):
```
$ node -pe 'require("SELECT 1").createQuery("SELECT 1", function my_func(){})'
{ domain: null,
  _events: {},
  _maxListeners: 10,
  _callback: [Function: my_func],
  _callSite: null,
  _ended: false,
  _timeout: undefined,
  _idleNext: null,
  _idlePrev: null,
  _idleStart: null,
  _idleTimeout: undefined,
  _repeat: null,
  sql: 'SELECT 1',
  values: undefined,
  typeCast: true,
  nestTables: false,
  _resultSet: null,
  _results: [],
  _fields: [],
  _index: 0,
  _loadError: null }
```

**Comment by sidorares** [comment]
`require("SELECT 1")` ?

**Comment by dougwilson** [comment]
@sidorares lol, sorry, fixed :) I just had to change it to be `require("mysql")` instead of `require("./index")` and I wasn't thinking...

**Comment by sidorares** [comment]
for a second I thought it's your custom node build to save on typing :)
`node -e "requite('select 1').then( print )"`
