### ISSUE TITLE
New AWS RDS certificates aren't working

### ISSUE THREAD

**Issue by chanakyagujju** [felixge/node-mysql#1016]
New AWS RDS ca file isn't working. Always gives me handshake error. 

Version : 2.5.5

**Comment by sidorares** [comment]
can you give more details please? What is the error code? Could you post stack trace? Can you connect with the same code, but without `ssl` config parameter? Thanks!

**Comment by chanakyagujju** [comment]
ERROR : { [Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE] code: 'HANDSHAKE_SSL_ERROR', fatal: true }.

I am able to connect if I make rejectUnauthorized : false.

I was able to connect with that RDS instance previously with 2010 CA file.

**Comment by dougwilson** [comment]
What version of Node.js are you using, as well?

**Comment by chanakyagujju** [comment]
v0.10.29

**Comment by dougwilson** [comment]
@sidorares would you mind testing with Node.js 0.10.29 with version 2.5.5?

**Comment by sidorares** [comment]
I'll try with 0.10.29
My manual tests were using 0.10.36 / iojs 1.2 ( original PR certificates, but as far as I can see you only added comments @dougwilson )

**Comment by dougwilson** [comment]
Correct, my only modification from the original PR was just to add the comments to know which certificates are which :)

**Comment by sidorares** [comment]
@chanakyagujju you can try with original certificate instead of using bundled profile: download ca from http://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem and then

```js
  var connection = mysql.createConnection({
    ssl: { ca : fs.readFileSync('/path/to/rds-combined-ca-bundle.pem' }
  });
```

( or use pre-rotation CA which is going to expire on on 23 March 2015 )

**Comment by sidorares** [comment]
works fine for me with mysql@2.5.5 from npm and node 0.10.29 ( installed with n )

`show status like 'Ssl_cipher';` => ` [ { Variable_name: 'Ssl_cipher', Value: 'AES256-SHA' } ]`

**Comment by chanakyagujju** [comment]
@sidorares  I am using original certificate from aws. Below is my code with which I am trying to connect.

var connection = mysql.createConnection({
  host     : 'host',
  user     : 'user',
  password : 'xxxxxxxxx',
  ssl  : {
          ca : fs.readFileSync(__dirname + '/rds-combined-ca-bundle.pem')
      }
});

with pre-rotation CA same code was successful in connecting to RDS instance. I am sure that instance was configured correctly as I was able to connect to instance from command line with same certificate and also double checked it from AWS.

Should I be using cipher?

**Comment by chanakyagujju** [comment]
@sidorares  @dougwilson  you guys there?

Please let me know if I am doing something wrong with my implementation

Thanks!

**Comment by dougwilson** [comment]
We are :) I don't have access to RDS to know. I mean, this change was contributed by two people, so I assume they didn't have an issue. Unless people are not upgrading, I would also have expected to see other people with your issue drop by here as well.

The thing is, all that was done here was certificates were added to a list. The old cert is still there. Unless there is some problem with your node.js, we're not sure what the issue is. Can you try reinstalling your node.js? Try from a different machine?

**Comment by chanakyagujju** [comment]
Hi,

I was doing a mistake, previously AWS gave us single certificate to connect. But now they made it like 11 certificates 1 per each region all in one bundled file. I was using that file thinking your module would handle it. I broke it into 11 files and it worked. 

Thanks a lot for your time!

**Comment by dougwilson** [comment]
No problem. All we do is take your argument to ssl option and pass it to node.js and let it handle whatever format it handles.

**Comment by dougwilson** [comment]
From our readme, you can see whatever node.js has documented for the arguments to "ca" here: http://nodejs.org/api/crypto.html#crypto_crypto_createcredentials_details

**Comment by danielsantiago** [comment]
@chanakyagujju I'm having the same problem. What was the solution for you? The code

Thanks

**Comment by chanakyagujju** [comment]
@danielsantiago Previously to connect to aws rds we need to give only one ca file which contains only one ca certificate. Now they are providing us with a bundle which contains 11 ca certificates.

open the ca bundle you downloaded from aws and break that file into 11 files and provide all those files in for sql connection you will find success.

Let me know about failure/success status.

**Comment by dougwilson** [comment]
None of that should be necessary. Just `npm install mysql@2.5.5` and then simply set the `ssl` option to `"Amazon RDS"` and we provide the certificates for you. Our SSL section explains this in greater detail: https://github.com/felixge/node-mysql#ssl-options

```js
var connection = mysql.createConnection({
  host: '<your amazon rds host name>',
  user: '<your username>',
  password: '<your password>',
  database: '<your database>',
  ssl: 'Amazon RDS'
})
```

**Comment by Muqito** [comment]
I had the EXACT same problem as this one:

    ERROR : { [Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE] code: 'HANDSHAKE_SSL_ERROR', fatal: true }.

I can happily tell you that it works if you don't bundle the certificates in the ca file.

instead split it up in arrays the different certificates like this:

    ca : [
	    fs.readFileSync(__dirname + '/../certificate/AddTrustExternalCARoot.crt'),
	    fs.readFileSync(__dirname + '/../certificate/USERTrustRSAAddTrustCA.crt'),
	    fs.readFileSync(__dirname + '/../certificate/SSLcomDVCA_2.crt'),
    ],

**Comment by nebulade** [comment]
Since I just had that issue, just letting you know, the normal use case using `ssl: 'Amazon RDS'` works just fine, but in my case, I first forgot to reboot the RDS instance to take effect.

**Comment by gongfan99** [comment]
I had the same issue when Amazon upgraded the old certificate (rds-ca-2010) to the new one (rds-ca-2015). My node version is 0.10.35, and mysql version is 2.5.4. My Amazon RDS instance is in us-east zone. I have downloaded all the Amazon SSL certificates into /certificate folder in my application.

ssl : 'Amazon RDS'
This did not work. It showed [Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE]

ssl  : { ca : fs.readFileSync(__dirname + '/certificate/rds-combined-ca-bundle.pem') }
This did not work. It showed [Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE]

ssl  	: {
	ca : [
		fs.readFileSync(__dirname + '/certificate/rds-ca-2015-root.pem'),
		fs.readFileSync(__dirname + '/certificate/rds-ca-2015-us-east-1.pem')
	]
},
This works. Both pem files have to be added for it to work.

**Comment by dougwilson** [comment]
What version of this module are you using?

**Comment by dougwilson** [comment]
Oh, you are using 2.5.4.

I am locking this thread now. You HAVE TO use version 2.5.5+ of this library for "Amazon RDS" setting to work with new certificates.
