### ISSUE TITLE
handle double column names?

### ISSUE THREAD

**Issue by AdriVanHoudt** [felixge/node-mysql#1017]
How does `node-mysql` handle double column names?

Example: 
`SELECT person.*, 'man' AS gender FROM person`

Where `person` also has a `gender` column.
(not realistic example but you get the point)

From some testing it looks like the lib will use the value of the latests column. But I want to be sure that this is by design and will not change.

**Comment by dougwilson** [comment]
So you can find full information in our readme: https://github.com/felixge/node-mysql#joins-with-overlapping-column-names

But as for the exact behavior of "which column's value is the end result" is this: MySQL server sends us a list of field names from your query results. I believe MySQL always sends them in the order you specified, but you'll have to verify with your MySQL server itself and it's manual. After that, when we populate the result object, we populate the properties in that order, which we overwrite whatever the old value is with the latest value.

**Comment by AdriVanHoudt** [comment]
Woops overlooked that.
Thanks for the info!  As far as I know MySQL always returns the columns in order specified in the query so that will work for me.

**Comment by dougwilson** [comment]
Yep :) As for us, we'll always keep this behavior for object results :)

**Comment by AdriVanHoudt** [comment]
Ok then I can use it reliably, thanks!
