### ISSUE TITLE
query sql with in() 

### ISSUE THREAD

**Issue by caoy83** [felixge/node-mysql#1020]
help me,

```js
var arguments = [1,2,3];
var sql='SELECT * from t_customer where customer_id in('+arguments.join(',')+')';
run  this code is success.

var arguments = [1,2,3];
var sql='SELECT * from t_customer where customer_id in(?)';
connection.query(sql,arguments);
```

run this code  is err.

 i don`t want concat strings,how to write code.

**Comment by sidorares** [comment]
If your list is variable length I'd review your db structure - you might want to use joins. If it's fixed length, just use as much '?' as you have ids.

One more option: concatenate array of "?"s ( not values):

```js
var args = [1,2,3];
var placeholders = args.map(function() { return '?'; }).join(',');
var sql='SELECT * from t_customer where customer_id in(' + placeholders + ')';
connection.query(sql,args,handler);
```
This is safer as parameter escaping is performed by driver

**Comment by caoy83** [comment]
Sidorares , Thank you .

**Comment by adrianblynch** [comment]
@caoy83 - Your second example should work. What error do you get?

**Comment by dougwilson** [comment]
@adrianblynch it doesn't work, because the call to `.query()` is wrong :) If @caoy83 changed it to the following, it would work:
```js
connection.query(sql,[arguments]);
```

**Comment by adrianblynch** [comment]
Ah yes! Sorry. ^^^ what he said ^^^ :+1:

**Comment by sidorares** [comment]
@dougwilson you are right, that's even simpler. I keep thinking of sql in query() as function with parameters and not template string

**Comment by caoy83** [comment]
```javascript
var arguments = [1,2];
var query=connection.query('SELECT * from t_customer where id in(?)', arguments,function(err, rows, fields) {
  if (err) throw err;
  console.log('query result length：'+rows.length);
});
console.log('query sql：'+query.sql)
connection.end();

table t_customer data
1	A
2	B

command 
E:\node index.js
query sql：SELECT * from t_customer where id in('1')
query result length：1

it would work.
I want to get two results[{id:1,...},{id:2,...}],But returns only one[{id:1,...}] .
:(

**Comment by dougwilson** [comment]
You are still not calling query correctly. It needs to be

    var query=connection.query('SELECT * from t_customer where id in(?)', [arguments],function(err, rows, fields) {

**Comment by caoy83** [comment]
@dougwilson
I change my code,now it is right.
thank you.

**Comment by davidrinnan** [comment]
makeing a comma separated list of arguments is an easy way to get into trouble :) 
Thankfully found this post, was going mad. 

there needs to be a ? for each argument, I guess. So a comma separated string of let's say five values have to have five question marks in the SQL.
