### ISSUE TITLE
field/column conflicts

### ISSUE THREAD

**Issue by Verikon** [felixge/node-mysql#1021]
Consider;
```sql
Select table1.*, table2.* from database;

table 1 has 2 fields, id:int, and t1:varchar
table 2 has 2 fields, id:int,and t2:varchar
```
results from this library:
id : <table2id>, table1field : 'foo', table2field: 'bar'

from myslql-cli:
id: <table1id>, t1: 'foo', id : <table2id>, t2: 'bar'

from navicat GUI:
id: <table1id>, t1: 'foo', id2: <table2id>, t2: 'bar'

whilst the mysql-cli result is naturally not going to work the navicat resultset ( fieldname + i ) is desirable.

Thoughts? and is there a way I can have this lib output conflicting fields by returning all, but with an incrementing integer on the fieldname?

**Comment by dougwilson** [comment]
Please see the readme: https://github.com/felixge/node-mysql#joins-with-overlapping-column-names

**Comment by Verikon** [comment]
Thank you
