### ISSUE TITLE
how to cancel query?

### ISSUE THREAD

**Issue by freeman983** [felixge/node-mysql#1026]
how to cancel query? like break

**Comment by sidorares** [comment]
if you want to cancel long running query server side - open another connection and use threadId from first one - see http://dev.mysql.com/doc/refman/5.0/en/kill.html

If you just want to ignore what you have sent and start another query as soon as possible - 1) if you are using pool - release connection, get new one and fire a query 2) if no pool - close existing connection, open new one and send new query to it

**Comment by freeman983** [comment]
I using pool,but release connection cannot cancel the query。

    pool.getConnection(function (err, conn) {
    if (!err) {
        console.log("begin query! " + new Date());


        conn.query("SELECT * FROM PHONE limit 0,1", function (err, ret) {
            console.log("query callback! " + new Date());
            if (err) {
                console.log("query err:" + err);
            } else {
                console.dir(ret);
                conn.release(function (err) {
                    console.log(err);
                });
            }
        });
        //method 1
        conn.release(function (err) {
            console.log(err);
        });


    } else {
        console.log("err:" + err);
    }
    })

**Comment by sidorares** [comment]
@freeman983 what problem are you trying to solve? If it's "at some point you know that you don't need results and want to avoid CPU-intensive computation mysql server side" then you need to kill process from another connection. If you just don't want query callback to be called - no, there is no such functionality in the driver. Just set some flag ("don't need to process results anymore") in your code and return early from query callback if it's set.

**Comment by sidorares** [comment]
Theoretically we might add "cancel query if it's still in the client side queue" functionality, this might be useful to some optimisations, but I'm not sure if that applies to you

**Comment by freeman983** [comment]
Thank you for your reply！
Yes, this function should be useful to me.I'll try your suggestion，Thanks again.
