### ISSUE TITLE
Using NOW();

### ISSUE THREAD

**Issue by thejae** [felixge/node-mysql#1031]
In relation to the posts #701 and #893 

Hello guys, am looking to use NOW() in my inserts. Are there any easy ways to do it without install extra modules like sequels using node-mysql's current implementation?

Here is the query am trying to execute:
```javascript
	var post = {
				symbol: stockCode,
				board_lot: boardLot,
				board_name: job.data.boardName,
				security_type: job.data.securityType,
				market: job.data.market,
				remark: remark,
				updated_at: 'NOW()'
			};

	connection.query('INSERT INTO `data` SET ? WHERE `id` = 1', post, function(error, result){
		//Code here
	});
```

**Comment by dougwilson** [comment]
No, there is no way to do it with that syntax, which is as-designed. You would have to use a true object-to-SQL library on top of this library. This library is really only meant to just take raw SQL, though it does provide extremely simple `?`-line syntax for convenience, but not as a full-fledged feature.

**Comment by thejae** [comment]
Thanks for your fast reply!

**Comment by dougwilson** [comment]
You always have the option of having your web server calculate the time, though :)
```js
    var post = {
                symbol: stockCode,
                board_lot: boardLot,
                board_name: job.data.boardName,
                security_type: job.data.securityType,
                market: job.data.market,
                remark: remark,
                updated_at: new Date() // NOW(), but on the server-side
            };

    connection.query('INSERT INTO `data` SET ? WHERE `id` = 1', post, function(error, result){
        //Code here
    });
```

**Comment by thejae** [comment]
Oh neat! I believe it's good enough for the time being, we have NTP set up across our servers :+1: 

Thanks again!

**Comment by sevisilex** [comment]
Hello, I can help you :)
Of course, I can to do the "new Date()" but the Mysql is not from localhost (sometimes problem time about the difference ~10 seconds between server-mysql and server-nodejs), that why i used the code:
```javascript
var config = require('./config');
var SqlString = require('mysql/lib/protocol/SqlString');
var mysql = require('mysql');

config.mysql.queryFormat = function(sql, values, timeZone) {
  sql = SqlString.format(sql, values, false, timeZone);
  sql = sql.replace(/'NOW\(\)'/g, 'NOW()'); 
  sql = sql.replace(/'UNIX_TIMESTAMP\(\)'/g, 'UNIX_TIMESTAMP()'); // if you want
  return sql;
};

var pool = mysql.createPool(config.mysql);
```

**Comment by thejae** [comment]
@sevisilex Looks like this might work. I agree sometimes server/ network lag might create unwanted results.

Thanks for the suggestion, will try this on our next revision. :+1:
