### ISSUE TITLE
"read ECONNRESET" being thrown asynchronously from PoolCluster

### ISSUE THREAD

**Issue by jessie93** [felixge/node-mysql#1033]
An exception is thrown when connecting to a server, then dropping all the packets going to the sql server and then requesting a new connection.

Stack Trace:
```
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
    --------------------
    at Protocol._enqueue (mysql-test\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at Protocol.quit (mysql-test\node_modules\mysql\lib\protocol\Protocol.js:87:36)
    at PoolConnection.end [as _realEnd] (mysql-test\node_modules\mysql\lib\Connection.js:215:18)
    at Pool._purgeConnection (mysql-test\node_modules\mysql\lib\Pool.js:231:16)
    at Pool.end (mysql-test\node_modules\mysql\lib\Pool.js:167:10)
    at PoolCluster._increaseErrorCount (mysql-test\node_modules\mysql\lib\PoolCluster.js:152:17)
    at mysql-test\node_modules\mysql\lib\PoolCluster.js:170:12
    at Handshake.onConnect (mysql-test\node_modules\mysql\lib\Pool.js:54:9)
    at Handshake.Sequence.end (mysql-test\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at mysql-test\node_modules\mysql\lib\protocol\Protocol.js:390:18
```

Steps to reproduce the "bug":
* Run the nodejs script
* Once it has made the first connection, drop all packets to the sql server. This has to be done before the 2nd connection is made (there is 3 seconds between making the first connection and making the second connection). Dropping the packets can be done with the following command: sudo /sbin/iptables -D INPUT -p tcp --dport 3306 -j DROP (port may need to be changed)
* Wait around 30 seconds

Code to run:
```js
var mysql = require('mysql');
var http = require('http');

var pool = mysql.createPoolCluster({ defaultSelector: 'ORDER' })
pool.add({
	host     : 'host',
	port     : portNumber,
	user     : 'root',
	password : '****',
	database: "adminconsole",
	connectionLimit: 15
})

var requestCon = function(){
	console.log("Requesting a connection." )
	try {
		pool.getConnection(function(err, con){
			if(err){
				console.log("An error happened, no connection was returned!")
			}
			else {
				console.log("Got a connection!")
				con.on('error', function(err){
					console.log("Event listener received an error.")
				})
			}
		})
	}
	catch (exp) {
		console.log("Error thrown on my thread.")
	}
}

requestCon()
setTimeout(function(){
	requestCon()
}, 3000) 
```

After looking at the code I think the following is happening:
* A valid connection is created ( I haven't started dropping the packets yet )
* We start dropping all the packets
* We try to create a new connection. Internally this increases the error count in the pool PoolCluster object until we reach the limit (because all the packets are being dropped).
* Once we have reached the limit, pool cluster tries to end the pool by calling pool.end() ( without giving the optional callback). As there is no optional callback, this passes a callback which will throw an error when given an error, to the  _purgeConnection in Pool.js
* Closing the first connection will call the callback with an error ( because all packets are dropped ), which causes an error to be thrown.

If the first connection is released just after being created then this "bug" doesn't happen.

I am using what I believe is the latest git version of node-mysql ( commit number: 2c0c3249ae916de165e73a61c7d4b668276a8807 ). Something similar happens when running this code with node-mysql v2.4.4 ( but this time I get a: Handshake inactivity timeout instead of a read ECONNRESET)

**Comment by dougwilson** [comment]
I'm looking into this now. The only reason I can think of between you getting ECONNRESET vs ETIMEDOUT is simply exactly watch raw TCP packets got through before you dropped everything is all. It's the same issue in the end.

**Comment by dougwilson** [comment]
In the `PoolCluster` code, there are three places where `pool.end()` is called without a callback, making it impossible to handle any errors that may come from there. I have fixed one of the three so far :)

**Comment by dougwilson** [comment]
Ok, should be fixed now with a test for the future :) I plan to publish this with 2.6.0, probably tonight.
