### ISSUE TITLE
not setted insertId when call stored procedure

### ISSUE THREAD

**Issue by breaklee** [felixge/node-mysql#1035]
this is result of calling of stored procedure
```
{ fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  protocol41: true,
  changedRows: 0 }
```

and blow is calling query directly

```
{ fieldCount: 0,
  affectedRows: 1,
  insertId: 912,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  protocol41: true,
  changedRows: 0 }
```

when i use stored procedure, insertId field is not setted.

how can i handle it?

**Comment by dougwilson** [comment]
This is just how MySQL works. You will need to do a second `SELECT LAST_INSERT_ID()`. You can either add that in your sproc and out an out variable, or manually call that after the stored procedure.
