### ISSUE TITLE
Update bignumber.js to v2.0.5

### ISSUE THREAD

**Issue by MikeMcl** [felixge/node-mysql#1037]
Regrettably, a critical (though very rarely manifesting) bug has been found in the division operation in versions v2.0.0 - v2.0.3 of bignumber.js.

Please update to v2.0.5.

**Comment by sidorares** [comment]
https://github.com/MikeMcl/bignumber.js/issues/58

it probably does not directly affect this library as we are only constructing bignum and not doing any math (but users might have the issue by using result)

**Comment by dougwilson** [comment]
Thanks, @MikeMcl for the note!

And @sidorares all we do is `.plus` and `.times` and then we call `.toString()` and give the user a string; the users do not have any idea that we are even using `bignumber.js` :)
