### ISSUE TITLE
npm WARN deprecated bignumber.js@2.0.0: critical bug fixed in v2.0.4

### ISSUE THREAD

**Issue by ezekel** [felixge/node-mysql#1038]
Hi, Install the mysql client for node in my root project, npm install mysql, and this is the result
```
npm WARN deprecated bignumber.js@2.0.0: critical bug fixed in v2.0.4
mysql@2.6.0 node_modules\mysql
├── require-all@1.0.0
├── bignumber.js@2.0.0
└── readable-stream@1.1.13 (inherits@2.0.1, string_decoder@0.10.31, isarray@0.0.1, core-util-is@1.0.1)
```
why is I always get warn deprecated?is that okay ?

**Comment by dougwilson** [comment]
It is OK and you can ignore it. We're going to fix it soon in a patch release.

**Comment by ezekel** [comment]
@dougwilson , Thank you for the quick reply.

**Comment by ezekel** [comment]
@dougwilson, can I ask, how can i know if the patch is now available and how to install in my project?

Thank you in advance.

**Comment by dougwilson** [comment]
We're going to fix it _soon_. There is nothing available yet.

**Comment by ezekel** [comment]
@dougwilson , yes i know , I just want to ask if ever the patch is available how can i install it.do I need to issue the command again "npm install mysql" inorder to get the patch?

**Comment by dougwilson** [comment]
Gotcha. Typically you would edit your `package.json` file and change the `mysql` entry to require at least the version that contains the patch and then you run `npm install mysql` again.

**Comment by ezekel** [comment]
Okay. That's it thank you :)
