### ISSUE TITLE
How to produce multidimensional array ?

### ISSUE THREAD

**Issue by ezekel** [felixge/node-mysql#1039]
How do I convert this to node-mysql.

      $results = array(
        'theid' => array(),
	'thename' => array(),
        'themeaning' => array(),
        'thegender'=> array()
       
    );

	
	$result = mysql_query("SELECT * from names
                           ") or die("problem in query = ".mysql_error());
						   
				
    while($row=mysql_fetch_array($result,MYSQL_BOTH)){

        $results['theid'][] = $row['id'];
        $results['thename'][] = $row['name'];
        $results['themeaning'][] = $row['meaning'];
	$results['thegender'][] = $row['meaning'];

    }

    return json_encode($results);
				

Thank you in advance.

**Comment by dougwilson** [comment]
Hopefully someone who knows PHP will drop by. Otherwise, I suggest asking your question on something like Stackoverflow.com

**Comment by LinusU** [comment]
I can't for the life of me figure out why you would want to do this, but here goes:

```js
connection.query('SELECT * FROM `names`', function (err, res) {
  if (err) {
    console.err('problem in query =', err.description);
    process.exit(1);
  }

  var results = {
    theid: [],
    thename: [],
    themeaning: [],
    thegender: []
  };

  res.forEach(function (row) {
    results.theid.push(row.id);
    results.thename.push(row.name);
    results.themeaning.push(row.meaning);
    results.thegender.push(row.gender);
  });

  // Do something with the value here
  var returnValue = JSON.stringify(results);
});
```

**Comment by dougwilson** [comment]
Looks answered to me :+1:

**Comment by ezekel** [comment]
@LinusU , sorry for the late reply....Thank you :)
