### ISSUE TITLE
How to LOCK TABLES with node-mysql ?

### ISSUE THREAD

**Issue by waza123x** [felixge/node-mysql#1042]
How to `LOCK TABLES` with `node-mysql` ?

I don't understand the way it can be done with `UNLOCK TABLES`.

Please example.

Thanks
p.s. searched google, no examples found.

**Comment by waza123x** [comment]
http://stackoverflow.com/questions/29321160/node-mysql-with-lock-tables

**Comment by dougwilson** [comment]
It's pretty much impossible to answer your question unless you show what the variable `sql` is in your Stackoverflow.com post.

**Comment by dougwilson** [comment]
If `sql` comes from `mysql.createConnection()`, then I don't see any issue, as your code is working just fine for me. If you can post more information, like what you are doing to try and verify that your `LOCK TABLES` is working or not, that would also be helpful :)

**Comment by waza123x** [comment]
var mysql = require('mysql');
var sql = mysql.createConnection({
    multipleStatements: true,
    host : 'localhost',
    user : 'a',
    database : 'b',
    password : 'c'
});
sql.connect();

it not working as expected, when user sends a large amount of requests which are runs that code with LOCK TABLES, he rewrites my table several times without locks. In PHP it works like a charm in nodejs locks are not working. 

Feels like ther user unlocks table before first user finish work with table.

**Comment by dougwilson** [comment]
> when user sends a large amount of requests which are runs that code 

Does each request use the same `sql` object, or are you doing `mysql.createConnection()` for each request?

**Comment by waza123x** [comment]
same sql object. So you think all should be fine ?

**Comment by dougwilson** [comment]
Ah, that's the problem: each `createConnection()` is an individual MySQL session. `LOCK TABLES` just locks the tables to that session. if all requests are using the same session, then obviously locking the tables won't actually do anything for you. You need to `createConnection()` for each request, rather than re-using the same `sql` object for every request. This is a key difference between Node.js and PHP programming :)

**Comment by waza123x** [comment]
ah i don't really understand what do you mean..
I have to create new connections for every sql query ? or only for that block where i need locking ?

**Comment by dougwilson** [comment]
If you read the MySQL manual, you'll see `LOCK TABLES` will lock the tables to the _current session_. Since every single query you are making, including ones you don't want to happen while the tables are locked, you are doing in the _same session_, of course they all act as if the tables are not locked. You need to use different sessions (i.e. different connections) in order to get the behavior you're looking for.

**Comment by waza123x** [comment]
ok i think now all will work fine. thanks for help!

**Comment by dougwilson** [comment]
No problem :)

**Comment by smhk** [comment]
If you're still around, thanks for that great tip @dougwilson 

Question from just a Swift programmer,

```
var mysql = require('mysql')
var dc = mysql.createConnection({
	// When node test.js is launched, >one connection only< is made
	host: 'localhost', ... user, password, database
})
dc.connect(err => {
	if (err) {
		console.error('Could not connect to mysql')
		throw err
  }
})

exports.findUserByEmailPass = function(email, password, cb) {
	dc.query(
		'select * from users where email = ? and password = ?',
		[email, password],
		(error, users, fields) => {
			if (error) { throw error }
			console.log("which connection? ... " + dc.threadId)
			cb(null, (users.length == 1) ? users[0] : false)
		})
}
```

So on my aws instance on the shell I launch the web site, `node project.js`

So then hundreds of people hit the login screen.  On the console, I see `which connection? 666`

**Exactly as you explain, it is always** `666`

(If on the shell I quit the app, and launch it again, hundreds more folks visit, it will be some new instance of "dc", say, `333` - again the same for all the users.)

So dc is a lazy class var (if that's the terminology y'all would use - I don't even know if the file db.js is a "class" or if these are just "globals" .. or, whatever! :O )

Anyways just as you explain we **need a new connection for each call**.

Here's my attempt:

I tried to add a function...

```
var mysql = require('mysql')
freshConnection = function() {
	var fresh = mysql.createConnection({
		host: 'localhost',
		user: 'nodeuser',
		password: '1234Nodeuser',
		database: 'basic_sessions'
	})
	fresh.connect(err => {
		if (err) {
			console.error('Could not connect to mysql in freshConnection')
			throw err
	  }
	})
	return fresh
}

exports.findUserByEmailPass = function(email, password, cb) {
	var f = freshConnection()
	f.query(
		'select * from users where email = ? and password = ?',
		[email, password],
		(error, users, fields) => {
			if (error) { throw error }
			console.log("so now ... " + f.threadId)
			cb(null, (users.length == 1) ? users[0] : false)
		})
}
```

This now works correctly.  I launch the app once, a hundred folks login, and for each of the hundred I see on the console `so now nnn` **where the integer nnn is different every time**.

Fantastic, but ...

1. Is my function total crap? How bad is it?  :) 
2. I'm sure I'm not handling / passing the error properly if couldn't connect?
3. Should I be f.end() or perhaps destroy() , how/where would I do that? Or would it disconnect automatically?
4. Here's a curiosity, I added this code:

```
exports.findUserByEmailPass = function(email, password, cb) {
	// return the struct or false via the callback
	var f = freshConnection()
	console.log("check ... " + f.threadId)
	f = freshConnection()
	console.log("check ... " + f.threadId)
	f = freshConnection()
	console.log("check ... " + f.threadId)
	f = freshConnection()
	console.log("check ... " + f.threadId)
	f.query(
		'select * from users where email = ? and password = ?',
```

I thought i'd see four different ids.  In fact they are all just null.  It would seem that the guts of my function freshConnection, is not actually run until the .query.   This further suggests I do not have a clue what I am doing  :)

BTW not expecting a full massive 101 node lesson here, just thought it would be helpful to accumulate info for others out there!  Thanks again for the key tip on this page!!
