### ISSUE TITLE
How to UPDATE a query with different arguments.

### ISSUE THREAD

**Issue by grass0916** [felixge/node-mysql#1043]
## At first

I could have `one argument 'aaa'` or `two arguments 'aaa' and 'bbb'`.

    UPDATE user SET email = 'aaa' WHERE uid = 'xxx';
    UPDATE user SET email = 'aaa', password = 'bbb' WHERE uid = 'xxx';

## My problem

How could I use one query to overcome above cases? Like below ...

    var sql = "UPDATE user SET email = ?, password = ? WHERE uid = ?;"
	dbclient.query(sql, [email, password, uid], function (err, results) {
		...
	});

1. If two arguments were `defined`, variable `sql` was :

        sql = "UPDATE user SET email = 'test@mail.com', password = 'abcd' WHERE uid = 1;";

2. If someone argument was `undefined`, variable `sql` was :

        sql = "UPDATE user SET email = 'test@mail.com', password = password WHERE uid = 1;";

**Comment by grass0916** [comment]
I found the [#escaping-query-values](https://github.com/felixge/node-mysql#escaping-query-values) can solve it. 

Sorry :")

**Comment by adrianblynch** [comment]
If you want to make the SQL more dynamic to handler more column-value pairs, take a look at:

```
var sql = [
	'UPDATE user SET',
	'email = ?'
]
var params = [email]

if (password) {
	sql.push(', password = ?')
	params.push(password)
}

sql.push('WHERE uid = ?')
params.push(uid)

dbClient.query(sql.join('\n'), params, function(err, results) {
	console.log(err, results)
})
```
