### ISSUE TITLE
Need help for the format of date

### ISSUE THREAD

**Issue by ezekel** [felixge/node-mysql#1044]
Hi node-mysql people can I ask some help, 

I have this result for my inner join query.my problem is that the date it display like this

dateregister: Thu Feb 05 2015 16:02:32 GMT+0800 (Taipei Standard Time)

how do I display like this example which is in my table 

dateregister: 2015-02-02 23:43:49

Thank you in advance.

```javascript
    connection.query(options,function(err, results) {

                if(err){
                    console.log(err);
                }
                console.log('result is: ', results);
            });



```

**Comment by dougwilson** [comment]
If you would like to see the date in the exact string format that MySQL sends instead of the format that JavaScript uses, you can use the `dateStrings` option (from https://github.com/felixge/node-mysql#connection-options):
```js
var connection = mysql.createConnection({
  dateStrings: true,
  // the rest of your connection options here
});
```

**Comment by ezekel** [comment]
@dougwilson ,

Thank you it works now :)
