### ISSUE TITLE
Sequence.js Line 89 is Missing a Catch Block :D

### ISSUE THREAD

**Issue by Dillybob92** [felixge/node-mysql#1053]
Line 89: 

 ```js
// try...finally for exception safety
  try {
    if (err) {
      this.emit('error', err);
    }
  }
  finally {
    try {
      if (this._callback) {
        this._callback.apply(this, arguments);
      }
    } finally {
      this.emit('end');
    }
  }
 ```

New Line that I made that doesn't crash the server on mysql errors :) (And you still get the errors shown in the console! )

```js
 // try...finally for exception safety
  try {
    if (err) {
      this.emit('error', err);
    }
  }catch(e){
	console.log(e);
  }
  finally {
    try {
      if (this._callback) {
        this._callback.apply(this, arguments);
      }
    } finally {
      this.emit('end');
    }
  }
```
Far better to have the errors show in the console instead of crashing the server. Especially since script kiddies will play around with your queries or whatnot. Especially when you run a gameserver like myself that needs 100% uptime! :dancers:

**Comment by dougwilson** [comment]
Hi! This is a misunderstanding on why the catch block is not there; we're not in the business of catching typos from your own code (and of course, no libraries are allowed to ever have `console.log` statements in them, because you can't turn them off). The only errors that would pass through that would be ones that are from within your own source files. If you need to catch errors, please make sure you have `try` `catch` blocks in your own code to handle your own errors :)
```js
conn.query('SOME SQL', function (err, rows) {
  try { // try catch your own code
   // do stuff
  } catch (e) {
    // handle your errors
  }
})
```

If you can paste a way to cause an unhandled exception that wasn't from your own code, I would like to get it fixed ASAP. If this is happening to you, please post how to reproduce the issue :)

**Comment by Dillybob92** [comment]
Dougwilson, thanks but in a production server, if there is a mysql error (especially when you're running a live gameserver in nodejs) for my web game, YOU NEED 100% uptime regardless of errors. The server cannot be shutting down based on mysql errors, console log approach is more appropriate.

For example, take a look at this simple query:
```
 db.query('UPDATE rpg_user_items2 set item_equipped = 1 where itemid = '+db.escape(item_id)+'');
```
rpg_user_items2 does not exist, so this will output an error and crash the nodejs server. This is not good for a production server.  And, we cannot use try/catch blocks inside that query. Ofcourse, we can use the callback, function(err, results) and check for the err, and console.log that? If that is what you're talking about, then yes, that would be the fundamental approach.

But, when having simple 1 line queries like this, is great for code optimization, readability, and what if the user is inputting some fishy code through the item_id variable? Irregardless if it's properly casted as a string, number, or checked thoroughly, there's always room for an error of occuring. And having a typo or error in a query SHOULD NOT shut down the nodejs server. They should be outputted to the console log or logged somewhere.

**Comment by dougwilson** [comment]
You may want to look into using a different MySQL library, like `mysql2`.

**Comment by dougwilson** [comment]
Fundamentally, you're complaining about shortcomings of Node.js itself, rather than anything this library does. An unhanded exception makes Node.js crash completely, affecting everyone. It's a fundimental Node.js problem. Libraries don't handle exceptions you cause in your own code, I'm sorry.

**Comment by Dillybob92** [comment]
@dougwilson  It's fine now, there is no turning back. Too much code has been written for the gameserver using this module, it would be counter intuitive to make the switch.  

But, I do like this module it's fine I just am very picky I guess.

Edit: Saw your new reply.
Yes, well, the only reason why I switched to node is so I can have monster AI using setTimeout...... (Threaded app)..Was using a php socket server for a while :( I hate how the unhandled exceptions crash the server and the use of try{catch} blocks are very annoying but I guess it's the price to pay to make the switch.

**Comment by dougwilson** [comment]
You're also free, BTW, to fork this library and maintain your own version that handles user errors; the code is licensed under MIT so you can do whatever you wish with it.

**Comment by dougwilson** [comment]
There is a module on npm that can make all those try catches in your code easier to write. I'm trying to find the name of it...

**Comment by dougwilson** [comment]
https://github.com/CrabDude/trycatch

**Comment by dougwilson** [comment]
```js
var trycatch = require('trycatch')

// ...

conn.query('SQL', trycatch(function (err, rows) {
  // .. stuff
}), console.error.bind(console))
```

**Comment by Dillybob92** [comment]
Yeah, that looks like a cool module. But honestly, the simple try{catch} in my first post is so simple and works fine for me lol. Although it goes against the core philosophy of the module... I guess it boils down to whatever works for me, right? 

Anyways, thanks for your help. I just love talking about nodejs I can go and on, I freaking love Websockets :)

**Comment by dougwilson** [comment]
Cool :) Though event-loop based programming with WebSockets isn't actually unique to Node.js/JavaScript ;)

**Comment by Dillybob92** [comment]
It's been around since C right? If so, I guess I shouldn't be getting too excited.. lol

**Comment by dougwilson** [comment]
Personally, I use http://mojolicio.us/ ;)

**Comment by Dillybob92** [comment]
Wait, is that a Perl Websocket server?

**Comment by dougwilson** [comment]
It sure is, even based on an event loop your async wonders :) I come from Perl, so it fits well with my language lineage is the main thing.

**Comment by Dillybob92** [comment]
Jesus, little bit too late for me to learn a new language. I'd rather just do the best I can with what I already know. Perl is so sexy though, but the syntax throws me off. I guess it's just something you're accustomed to when growing up learning it or whatnot, or maybe that's just me lol.

**Comment by adrianblynch** [comment]
I might be missing the point, but are you asking for node-mysql to not pass DB errors back but to swallow them with a console.log?

I'm with you on the pain of having to `if (err) { // Do something }` in lots of places.

It sound like you just want Node to stay up on unhandled errors?

Domains and the `on('error')` handler might be what you need.

https://www.google.co.uk/search?q=how+to+stop+node+from+crashing+on+unhandled+errors
