### ISSUE TITLE
return results instead of callback

### ISSUE THREAD

**Issue by TheColorRed** [felixge/node-mysql#1054]
Is there a way to allow for results to be returned to a variable instead of posted through a callback?

    var conn = mysql.createConnection({...});
    var rows = conn.query("select * from my_table limit 10");

passing the results to a callback is nice, but not always needed and/or wanted.

**Comment by dougwilson** [comment]
No; this is a limitation of Node.js. Network calls must always be async.

**Comment by TheColorRed** [comment]
@dougwilson I believe that we can just use yield to solve that problem.

**Comment by dougwilson** [comment]
Whatever we do has to work in Node.js 0.6, 0.8, 0.10, and 0.12. As far as I know, yield only exists is 0.12+, so it's not usable here. Someone more familiar with yield can chime in, or feel free to make a PR (our CI will validate it works in our supported Node.js environments).
