### ISSUE TITLE
Escaping queries strips backslash characters from strings

### ISSUE THREAD

**Issue by naveensnayak** [felixge/node-mysql#1055]
tried a simple query like this 

```javascript
db.query("insert into test(fname, path) values (?, ?)", ['test', 'C:\wamp\www']);
```

when i look at the insert in the database, value of the path column is C:wampwww 
back slashes have been stripped 

what am i missing ?

**Comment by dougwilson** [comment]
You are simply making a classic JavaScript mistake. You'll notice that if you console.log your string without even using this library your blackslashes will be missing. You need two blackslashes to get a literal blackslash in a JavaScript string.

**Comment by adrianblynch** [comment]
And if you're wondering why they get removed, it's because the JS engine thinks you're trying to escape the `w` in `wamp` and the first `w` in `www`, which is cool, but neither need escaping.

`db.query("insert into test(fname, path) values (?, ?)", ['test', 'C:\\wamp\\www']);` should do it.

**Comment by naveensnayak** [comment]
thank you - sry for the false alarm

**Comment by dougwilson** [comment]
It's no problem :)
