### ISSUE TITLE
Extract SqlString

### ISSUE THREAD

**Issue by LinusU** [felixge/node-mysql#1059]
I found that I often want to escape strings for mysql query constructions. Currently I pass the connection handle to the function that generates the sql, but this isn't ideal at all. Especially when writing libraries that construct sql strings.

E.g. is a library that takes a json-patch and returns an array of sql-queries.

Would you be open to move the `SqlString` class to a separate npm package so that it can be depended on and required individually?

Thx

**Comment by dougwilson** [comment]
There are already much, much better libraries out there that do what SqlString does.

**Comment by LinusU** [comment]
Can you point me to any of them? I haven't found any.

The ones that I do found does a lot more than just escaping the strings. I really only need the low level escape. I don't want query-building.

**Comment by dougwilson** [comment]
Yes, they are full query builders. If you are not building a query, then I'm not sure what you need to do. If you just want to construct a query for this library to process, simply construct a string + array of values and pass those into this library. This has the bonus of, for example, serializing `Date` objects with the correct connection timezone.

```js
function genQuery() {
  // ... do something
  return {
    sql: 'SELECT * FROM ?? WHERE id = ?',
    values: ['table', 42]
  };
}

// ... later

var query = genQuery();
conn.query(query, callback);
```

**Comment by LinusU** [comment]
Hmm, maybe an object with sql and values is the way to go. The reason I don't want to use a query builder is because I'm constructing to complex queries. E.g. generating sql code to create table + audit table with triggers for insert, update and remove.

The downside with that is that it won't work for other sql library (e.g. postgres). It's hard to fix both using connection timezone and being database agnostic thought. In this instance I don't use dates thought so I think that using just SqlString would be the way to go...

**Comment by dougwilson** [comment]
> I don't use dates thought so I think that using just SqlString would be the way to go...

Right, but it's a reason why I won't extract the escaping library (besides the fact that MySQL and postgres have different escaping mechanisms, so you still would have cross-db issues).

**Comment by LinusU** [comment]
I understand and I actually agree, better to return `{ text: _, values: _ }`
