### ISSUE TITLE
Recommended node-mysql pool usage for nested queries

### ISSUE THREAD

**Issue by emjoseph** [felixge/node-mysql#1064]
Hey, 

Thanks for an amazingly useful node module. Really appreciate the work you've done!

Wondering what's best way to perform nested queries using the node-mysql pool. The reason being is that my node-server suddenly stops responding to HTTP calls after a while without triggering any errors and I want to make sure it's not because of the nested-query pool syntax I'm using. My general structure is as follows:

```javascript
pool.getConnection(function(err, connection) {
    // Use the connection
    connection.query( 'query1', function(err, rows) {
        connection.query( 'query2', function(err, rows) {
             connection.release();
        });
     });
});
```
Does that look okay? Or should the connection be released immediately after the first query? Also, if handling errors, is it important to release the connection in the first query's error case as well?

```javascript
pool.getConnection(function(err, connection) {
    // Use the connection
    connection.query( 'query1', function(err, rows) {
        if(err){
              connection.release()
        }else{
             connection.query( 'query2', function(err, rows) { 
                  connection.release();
             });
        }
     });
});
```

Thanks again!
-emjoseph
^_−☆

**Comment by dougwilson** [comment]
> Also, if handling errors, is it important to release the connection in the first query's error case as well?

It is _extremely_ important that after a `getConnection`, every single possible code path needs to call `connection.release()`, otherwise you'll get the exact behavior you described. Otherwise, everything else you said is perfectly fine.

**Comment by emjoseph** [comment]
Awesome
Thanks!
