### ISSUE TITLE
transaction when loop

### ISSUE THREAD

**Issue by c941010623** [felixge/node-mysql#1065]
if i want use transaction in loop
how can i do it ??

**Comment by dougwilson** [comment]
Unfortunately your question is quite vague. Can you provide more details on what you're trying to do?

**Comment by c941010623** [comment]
if i want use transaction and run insert into 10 times

if err how can i rollback ??
if i=10 and how can i commit ??

**Comment by dougwilson** [comment]
Gotcha. This is an extension to just using callbacks in Node.js in general, but with this module :) Example for using transactions is mainly take from the readme at https://github.com/felixge/node-mysql#transactions
```js
var async = require('async');

connection.beginTransaction(function(err) {
  if (err) throw err;
  async.times(10, function(n, next){
    connection.query('INSERT INTO counter SET n=?', [n], next);
  }, function(err, users) {
    if (err) {
      connection.rollback(function() {
        throw err;
      });
    }  
    connection.commit(function(err) {
      if (err) { 
        connection.rollback(function() {
          throw err;
        });
      }
    });
  });
});
```

**Comment by c941010623** [comment]
if "throw err" the system will stop
but i don't want stop it 
only want rollback and release() or end() the connection
how can i do it ??

**Comment by dougwilson** [comment]
That was just a starting point; I'm not really here to write our your whole app :) I'm sure you can figure it out. You didn't mention any of those requirements in your initial two posts, so I didn't know you wanted to see that in the example as well.

**Comment by c941010623** [comment]
you use async is a good idea
i think i can do it
thank youy help ~~
