### ISSUE TITLE
Question about closing connection after transaction commit

### ISSUE THREAD

**Issue by sarunl** [felixge/node-mysql#1066]
From the example in Transaction section,  the transaction ends with commit or rollback. I am wondering if i should connection.release() after the transaction is commit or rollback?

if yes, where should it put it? inside function or just after this statement
```js
connection.commit(function(err) {
        if (err) {
          connection.rollback(function() {
            throw err;
          });
        }
e.log('success!');
      });
```

**Comment by sarunl** [comment]
same question
https://github.com/felixge/node-mysql/issues/934

**Comment by dougwilson** [comment]
Let us know if you have any follow-up questions :)!

**Comment by dreamcatcha** [comment]
Im getting a "Error: Connection already released" error for this

    // commit and return
    connection.commit(function(err) {
        if (err) { connection.rollback(function() { logger.error('mysql transaction commit error', err); connection.release(); }); return done({ status: 422, body: someError }); }

        // release the connection
    --> connection.release();
    }):

I thought the commit didn't release the connection and I have grab the connection from a pool cluster also, any ideas?

Cheers
