### ISSUE TITLE
How do Insert an Array of data and including data which is not array

### ISSUE THREAD

**Issue by ezekel** [felixge/node-mysql#1069]
Hi, can I ask some help how can I insert array of data 
```js
[100,200,300,400,500]
```
also this non array 
```js
var clientid = '44444';
```
Now I want to insert this to my table with the array of data and the clientid,it looks like this
```
clientid                        jobid
4444                          100
4444                           200
4444                          300
```

```js
 pool.getConnection(function (err, connection) {

                connection.query('INSERT INTO tblename SET ?', post, function(err, result)  {


                    if(err){
                        console.log(err);
                    }
                    connection.release();

                });

            });

```

Thank you in advance

**Comment by dougwilson** [comment]
Hi @ezekel ! You just need to form the final array with a map operation:
```js
var clientId = 44444;
var  jobIds = [100,200,300,400,500];

var rows = jobIds.map(function (jobId) {
  return [clientId, jobId];
});

pool.getConnection(function (err, conn) {
  if (err) throw err;
  conn.query('INSERT INTO `jobs` (`client_id`, `job_id`) VALUES ?', [rows], function (err) {
    conn.release();
    if (err) throw err;
  });
});
```

**Comment by ezekel** [comment]
@dougwilson , thank you for the reply...where did you get the .map ? is there on the docs of node-mysql ?

**Comment by dougwilson** [comment]
It's part of the JavaScript language itself.

**Comment by ezekel** [comment]
@dougwilson , Ahh I see. Thank you so much

**Comment by ezekel** [comment]
@dougwilson ,

I just want to ask, why it will not insert if there is data duplicate to the table ?...how can I insert  the other data which is not duplicate or does not exist to the table...the script will not insert the data if there is duplicate.

**Comment by dougwilson** [comment]
Probably because they table does not allow it. Can you paste the output of SHOW CREATE TABLE jobs ?

**Comment by ezekel** [comment]
@dougwilson ,
```
CREATE TABLE `jobs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) DEFAULT NULL,
  `job_id` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `job_id` (`job_id`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8

```

**Comment by dougwilson** [comment]
Gotcha. So it is the `job_id` that is causing the issue. Depending on what you want to do, you can either use `REPLACE` to replace the non-unique rows, or `INSERT IGNORE` to just ignore the errors. You can read more about MySQL syntax and the different possibilities you have over at https://dev.mysql.com/doc/refman/5.1/en/insert.html

**Comment by ezekel** [comment]
ok thank you
