### ISSUE TITLE
Char and varchar can return Buffer

### ISSUE THREAD

**Issue by LinusU** [felixge/node-mysql#1071]
I don't see it documented but both `CHAR` and `VARCHAR` can return a `Buffer` if they have `CHARACTER SET binary` set. Is this intentional?

I opted for `CHAR(60) CHARACTER SET binary` instead of `BINARY(60)` specifically so that I would get strings instead. My use case is this: I'm storing the hash from `bcrypt` which is 60 characters ascii. I don't want the database to assume anything about the content and I don't want it doing case-insensitive matching, so therefor I choose `CHARACTER SET binary`.

Should I be rethinking this or should the library be updated?

**Comment by dougwilson** [comment]
Yes, this is intentional, unfortunately. You can always define your our `typeCast` to override this, but when I created the same type of column for my own stuff, I have always used the following: `CHARACTER SET ascii COLLATE ascii_bin`.

**Comment by LinusU** [comment]
Thanks, I've updated my database to that. Do you think that it would be relevant to add this to the readme? Feel free to close the issue otherwise...

**Comment by dougwilson** [comment]
Yes, I agree docs should note this.

**Comment by LinusU** [comment]
:+1: nice!
