### ISSUE TITLE
Best practice for error handling in pools - No `pool.on('error'`

### ISSUE THREAD

**Issue by bitsoflogic** [felixge/node-mysql#1073]
In the docs, it is recommended to watch `connection.on('error'`, yet I'm not sure how this ties into `pool.query(...)`.  Does the `pool.query` method watch that event and provide the error via the callback?

I want to ensure I'm not missing errors.  The `pool.query` method adds a ton of simplicity, so I would ideally like to stick with it.

**Comment by dougwilson** [comment]
Hi @bitsoflogic , sorry for the delay. So with the `pool`, the way it was designed to work is such that you do not need to add any error listeners at all; simply acting on the `err` arguments to your callback functions should be enough with the pool.

**Comment by bitsoflogic** [comment]
Awesome, thanks!
