### ISSUE TITLE
Going from single mysql-queries to mysql-pool

### ISSUE THREAD

**Issue by AlexioVay** [felixge/node-mysql#1076]
I'm trying to switch from single mysql-queries to mysql-pool connection using the node-mysql-module, so users can share one mysql-connection, but I'm not familiar with this at all (also new to nodejs/socket.io).

The following code is what I've tried so far to send data every second to the socket in an array:

But this doesn't send me any data to the WebSocket. Is this approach (code-structure) even correct? 

Previously I used `query.on('results')` to get data like this:
```js
var selection = "SELECT * FROM auctions";            
var query = mysql.query(selection), auctions = []; 
query.on('result', function(auction) {
console.log ('id: '+auction.id+' ('+auction.duration+') ');
});
```
This worked fine showing data with auction.row but how to do this in my mysql pool connection?

Also after some seconds I'm getting an error that release() isn't even defined, but it's listed in the mysql-module documentation. I think my whole logical process is somehow incorrect?

- Should I use `connection.end()` and `.release()` at all? Because the
connection should never end.
- Should I still use `setInterval(function () { mysql.query('SELECT 1'); }, 5000);` as answered in another StackOverflow question to keep the connection alive here? (nodejs mysql `Error: Connection lost The server closed the connection`)

(Appreciate any tips or answers to even some of my questions! Better some answers than none, because I experienced that this topic isn't answered much at all.)

**Comment by dougwilson** [comment]
I have to look through your code, which will take a while because it's a lot and a lot of questions, I'm sorry, but I can say you have a programming error here:
```js
mysql.getConnection(function(err,connection){
if (err) {
  connection.release(); // this line is wrong; remove it, as there is no connection if there is no err
  console.log({"code" : 100, "status" : "Error in connection database"});
  return;
}
// ...
```

**Comment by dougwilson** [comment]
> Should I use connection.end() and .release() at all? Because the connection should never end.

You should keep calling `.getConnection()` and `.release()` for every query. Unfortinately you cannot guarantee your connection will stay open: network issues, "hiccups", even restarting MySQL or someone calling `KILL` on your connection for some reason.

**Comment by AlexioVay** [comment]
This whole topic confuses me so much and I can barerly find someone who has enough knowledge to accomplish this task. Would you be open in some hours/days to rewrite the code if I pay you?

At StackOverflow someone just suggested me that I have to rewrite it, because of my setTimeout is like unstoppable with this code and the whole logic is kinda messed up.

See this picture of our chat: http://postimg.org/image/igynwe685/

**Comment by AlexioVay** [comment]
Also I know I posted so many links to get into my problem, but this is the actual situation minimized to the important things: http://stackoverflow.com/questions/30052273/cant-send-fetched-data-to-my-socket-io-stream/30057900#30057900

**Comment by AlexioVay** [comment]
Just one question: Is it possible to exclude specific field items from `fields` when you perform connection.query(selection, function(err, fields, results){ ?

**Comment by sidorares** [comment]
@AlexioVay fields array always match keys in every row of results array ( after all the "join tables" name mangling is applied, if enabled )
