### ISSUE TITLE
Return object instead of array

### ISSUE THREAD

**Issue by MartinWeb** [felixge/node-mysql#1078]
Hi,

I have a question relative to selection queries. When we make a selection with a where clause based on the primary key of the table it give us an array with one element as excepted.
Could it be possible to return only an object when one line is returned and an array when more ? 

It's not a bug or anything like that but i think that could be nice to have this option. If not it's not a problem.

Thanks in advance for your reply, and thanks for the work you do on the lib :)

**Comment by AdriVanHoudt** [comment]
it would be an option and it would probably be more effort to set it in the queries which return just 1 object then just doing `results[0]` imo

**Comment by dougwilson** [comment]
You can always do this yourself, but this has been brought up before and we feel pretty strongly that always returning an array and your code just doing rows[0] is more robust.

**Comment by MartinWeb** [comment]
Thanks for the quick responses guys.
It's not really a big issue that's certain, i just ask to know if maybe you were working on this.
