### ISSUE TITLE
Convert array in object to IN (..) instead of = ...

### ISSUE THREAD

**Issue by AdriVanHoudt** [felixge/node-mysql#1079]
When doing 
`format('update tableA set ? where ?', [{ columnA: 1 }, { columnB: [4,5] }])`

The result is 
`update tableA set columnA = 1 where columnB = 4, 5` 
which is not desirable.

Would it be possible to detect arrays and convert them into
 `update tableA set columnA = 1 where columnB IN (4, 5)`
 instead?

**Comment by dougwilson** [comment]
I'm not sure if previous PRs attempted this is not. You're always welcome to try and if it's detection is reliable we can accept it, though at some point you may want to switch to using a SQL builder rather than only this module, which is intentionally low-level.

**Comment by AdriVanHoudt** [comment]
wouldn't it come down to check if the value is an array here https://github.com/felixge/node-mysql/blob/master/lib/protocol/SqlString.js#L115 and push another value into values?
Also any builders you recommend?

**Comment by dougwilson** [comment]
> wouldn't it come down to check if the value is an array here https://github.com/felixge/node-mysql/blob/master/lib/protocol/SqlString.js#L115 and push another value into values?

Possibly; would have to look in a bit to say for sure.

>  Also any builders you recommend?

Probably https://hiddentao.github.io/squel/

**Comment by AdriVanHoudt** [comment]
ok thanks, if I can find some time i might take a shot(but that won't be for the near future) also with the sql builder you lose the escaping of the values that node-mysql does not?

**Comment by dougwilson** [comment]
I'm not really sure what you mean, exactly. Typically with squel you build up your query and call `.toParam()` and then pass that to MySQL:
```js
var query = squel.update()
  .table('tableA')
  .setFields({columnA: 1})
  .where('column B IN ?', [4,5])
  .toParam();
conn.query(query.text, query.values, function (err, rows) {
  // ...
});
```

**Comment by AdriVanHoudt** [comment]
Ah like that, cool I might try it. Although at first sight I don't like the readability but that is probably because I'm not familiar with it
