### ISSUE TITLE
stream new data without polling

### ISSUE THREAD

**Issue by behrad** [felixge/node-mysql#1080]
I have a mysql db with 50 inserts/sec:

Is there any method I can stream new inserts into my node.js process without polling?
Something like configuring the node-mysql's query stream not to emit `end` but also let new inserted data in...

**Comment by dougwilson** [comment]
This module can only do stuff that is possible using the MySQL protocol, which that really isn't. I think you can find binlog monitoring modules which can accomplish a similar task.

**Comment by dougwilson** [comment]
https://www.npmjs.com/package/mysql-live-select

**Comment by behrad** [comment]
thank you @dougwilson , great feedback
