### ISSUE TITLE
db.end() Protype Extension Issue

### ISSUE THREAD

**Issue by Dillybob92** [felixge/node-mysql#1083]
# **Disclaimer:**
**This is NOT an issue with node-mysql in itself, this is an extension I'm trying to add to it for easier coding and less arthritis. This is a great nodejs plugin and I do not mean any disrespect when posting these errors, these are 100% my fault and not the module's.**

Hey guys, as pertinent to my thread here about issuing a `db.end()` command after each query: https://github.com/felixge/node-mysql/issues/1081 (Authored by: EnzoMartin)  I have been getting this error:

[TypeError: Cannot read property 'prototype' of undefined]

```javascript
var mysql = require('mysql');
					var db_config = {
						host: 'localhost',
						user: 'root',
						database: 'forum',
						password: 'blowme'
					};
					var db;
					
 var query = db.prototype.query;
db.prototype.query = function(){
    var args = Array.prototype.slice.call(arguments);
    var callback = args.pop();

    args.push(function(){
        db.end();
        callback.apply(this,arguments);
    });

    query.apply(this,args);
};
```javascript

Which seems odd because db is already set and my connection is working, any ideas?

**Comment by dougwilson** [comment]
When the line `var query = db.prototype.query;` is executed, `db` is still `undefined`. You have to actually set `db` to something before trying to do anything with it.

**Comment by Dillybob92** [comment]
But I can use `db.query('select blah');` right below it and it works...

**Comment by dougwilson** [comment]
Is what you pasted the exact code you are running, or did you just put a bunch of things together? It's hard to tell, because as far as I would know, what you pasted in the original is _exactly the source code you are running_. If it's not, then I'm not sure how to help...

**Comment by dougwilson** [comment]
You see, if what you pasted, you have the line `var db;` and then one blank line below that you have the line `var query = db.prototype.query;` which of course would throw the error `TypeError: Cannot read property 'prototype' of undefined` because you never set the variable `db` to anything.

**Comment by Dillybob92** [comment]
Full code for my MYSQL to initiate a connection and not produce a FATAL error that crashes NODEJS when the connection to mysql is lost:

```javascript
// Only use MYSQL for specific functions ~
				if(['JOIN', 'ATTACKMOB', 'JOINGAME', 'PINFOUPDATE','FA', 'BR', 'BL', 'CG', 'EQI','SU'].indexOf(Command) != -1){
				 
					var mysql = require('mysql');
					var db_config = {
						host: 'localhost',
						user: 'root',
						database: 'forum',
						password: 'ezpk123'
					};
					var db;
					
 var query = db.prototype.query;
db.prototype.query = function(){
    var args = Array.prototype.slice.call(arguments);
    var callback = args.pop();

    args.push(function(){
        db.end();
        callback.apply(this,arguments);
    });

    query.apply(this,args);
};

function handleDisconnect() {
  db = mysql.createConnection(db_config); // Recreate the connection, since
                                                  // the old one cannot be reused.

  db.connect(function(err) {              // The server is either down
    if(err) {                                     // or restarting (takes a while sometimes).
      console.log('error when connecting to db:', err);
      setTimeout(handleDisconnect, 5000); // We introduce a delay before attempting to reconnect,
    }                                     // to avoid a hot loop, and to allow our node script to
  });                                     // process asynchronous requests in the meantime.
                                          // If you're also serving http, display a 503 error.
  db.on('error', function(err) {
    console.log('db error', err);
	 
    if(err.code === 'PROTOCOL_CONNECTION_LOST') { // Connection to the MySQL server is usually
	console.log("MONKEY?");
     handleDisconnect();                         // lost due to either server restart, or a
    } else {                                      // connnection idle timeout (the wait_timeout
         //throw err;                                  // server variable configures this)
		 
    }
  });
 
}
 
 
 
handleDisconnect();

```

**Comment by dougwilson** [comment]
Unfortunately what you just posted is such an anti-pattern that you'll be guaranteed to run into all sorts of issues in the future. But in order to just get you paste this hump, your code should look like this:
```js
// Only use MYSQL for specific functions ~
                if(['JOIN', 'ATTACKMOB', 'JOINGAME', 'PINFOUPDATE','FA', 'BR', 'BL', 'CG', 'EQI','SU'].indexOf(Command) != -1){

                    var mysql = require('mysql');
                    var db_config = {
                        host: 'localhost',
                        user: 'root',
                        database: 'forum',
                        password: 'ezpk123'
                    };
                    var db;

function handleDisconnect() {
  db = mysql.createConnection(db_config); // Recreate the connection, since
                                                  // the old one cannot be reused.

 var query = db.query;
 db.query = function(){
    var args = Array.prototype.slice.call(arguments);
    var callback = args.pop();

    args.push(function(){
        db.end();
        callback.apply(this,arguments);
    });

    query.apply(this,args);
  };

  db.connect(function(err) {              // The server is either down
    if(err) {                                     // or restarting (takes a while sometimes).
      console.log('error when connecting to db:', err);
      setTimeout(handleDisconnect, 5000); // We introduce a delay before attempting to reconnect,
    }                                     // to avoid a hot loop, and to allow our node script to
  });                                     // process asynchronous requests in the meantime.
                                          // If you're also serving http, display a 503 error.
  db.on('error', function(err) {
    console.log('db error', err);

    if(err.code === 'PROTOCOL_CONNECTION_LOST') { // Connection to the MySQL server is usually
    console.log("MONKEY?");
     handleDisconnect();                         // lost due to either server restart, or a
    } else {                                      // connnection idle timeout (the wait_timeout
         //throw err;                                  // server variable configures this)

    }
  });

}



handleDisconnect();
```

**Comment by Dillybob92** [comment]
Okay, now I'm receiving:

`db error { [Error: Cannot enqueue Quit after invoking quit.] code: 'PROTOCOL_ENQ
UEUE_AFTER_QUIT', fatal: false }`

This is most likely because the prototype function is pushing the db.end already and I have tons of db.end's() scattered all over the place, right? lol

**Comment by dougwilson** [comment]
Yea, you got it, lol. You can only call db.end() once on a connection, and so this addition will cause all those calls to produce that error.

**Comment by Dillybob92** [comment]
Yeah figured! And thanks for putting that piece of code block in it's proper place.. Gosh now knowing all about how this mysql runs, while looking over my code I want to throw up.

That prototype function that EnzoMartin made doesn't push or create another query does it, it just pushes db.end()? I heard you mentioning something about creating a new query in your other posts, and that scared me.

**Comment by Dillybob92** [comment]
i'm confused on what this does...

```javascript
 var args = Array.prototype.slice.call(arguments);
    var callback = args.pop();
```

Where is the arguments variable set?

**Comment by dougwilson** [comment]
db.end() doesn't run another query, but it does send a command to the MySQL server: the quit command to end the connection.

The arguments variable is a special object that is part of the JavaScript language.

**Comment by dougwilson** [comment]
Basically "where does `arguments` come from" is the same as "where does `function` come from": it's just part of JavaScript :) nothing to do with this library.

**Comment by Dillybob92** [comment]
LOL. While fixing some salmon burgers.. I just realized.. I cannot use this prototype.. Why? Because of nested queries.......Haha.

**Comment by dougwilson** [comment]
Right, since `.end()` is being called automatically after a `.query()`, you'll only ever be able to do a single query. And I guess it's used a lot in Node.js? It certainly exists in JavaScript itself (you'll see it in Firefox, IE, Chrome, Opera, etc.), though you don't typically use it until you're trying to accomplish real goals in JavaScript, which is typically occurring on the server side, in Node.js.

**Comment by Dillybob92** [comment]
Yeah, starting to see it now more often. Especially looking in the source of these ws and mysql 
plugins.. ^_^ Stuff that is way over my head, but interesting. I just get confused when I see all the .this and _.this crap. The underscore stuff makes my head boggle.  I understand the objects though and how they're being used. Way more than I did 3 months ago, that's for sure. Which is good because I store my players RPG data in an object called RPGDATA ^_^.. Which is nice.

**Comment by dougwilson** [comment]
Yes, internal communications we have used single character property names and other tricks for saving network traffic.
