### ISSUE TITLE
ER_PARSE_ERROR

### ISSUE THREAD

**Issue by GowinChouhan** [felixge/node-mysql#1084]
You have an error in your SQL syntax; check the manual
 that corresponds to your MySQL server version for the right syntax to use near '
Error no=1064,
sqlState=42000

**Comment by sidorares** [comment]
can you put your query here if it does not contain sensitive data? You have error in the query itself, likely it's not a driver's fault

**Comment by GowinChouhan** [comment]
//i get data in  req.body.MessageData 

    connection.query('INSERT INTO `message` ( `MessageData`)
 VALUES("' + req.body.MessageData+ '");', function (error, results, fields) {
        console.log('inserted');
       
        
    });

**Comment by GowinChouhan** [comment]
thanks in advance..your help will be appreciated

**Comment by dougwilson** [comment]
It's because your `MessageData` has a single quote in it. It's a security flaw, actually. Just change your query to this, at the minimum :)
```js
connection.query('INSERT INTO `message` (`MessageData`) VALUES(?)', req.body.MessageData, function (error, results, fields) {
  console.log('inserted');
});
```

**Comment by dougwilson** [comment]
And, to be extra careful, assuming that MessageData can only ever be a string, you should validate MessageData is what you expect before proceeding:
```js
if (typeof req.body.MessageData !== 'string') {
  throw new Error('invalid!')
}

connection.query('INSERT INTO `message` (`MessageData`) VALUES(?)', [req.body.MessageData], function (error, results, fields) {
  console.log('inserted');
});
```
