### ISSUE TITLE
Parse error while updating

### ISSUE THREAD

**Issue by digvijayzala** [felixge/node-mysql#1085]
```js
 connection.query('UPDATE `watchlistsymbols` SET `Ticker`= "'+req.body.Ticker+'" WHERE `Id`=40)', function (error, results, fields) {                       
                    // UPDATE `oems`.`watchlistsymbols` SET `Ticker`='asdd' WHERE `Id`='25';
        console.log('data updated');
     }).on('error', function (e) {
        console.error(e);
        });
```
```
ERROR:
{ [Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual
 that corresponds to your MySQL server version for the right syntax to use near
')' at line 1]
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0 }
```

**Comment by AdriVanHoudt** [comment]
the query seems fine, but start by reading https://github.com/felixge/node-mysql#escaping-query-values

**Comment by shaoner** [comment]
You can use the configuration option `debug = [ 'ComQueryPacket' ]` to check what is really send to the server.

**Comment by digvijayzala** [comment]
connection.query('UPDATE watchlistsymbols SET Ticker= "'+req.body.Ticker+'" WHERE Id="'+req.body.Id+'"', function (error, results, fields) {                       
  function (error, results, fields) { 
        console.log('data updated');
     }).on('error', function (e) {
        console.error(e);
        });

**Comment by dougwilson** [comment]
@digvijayzala what @AdriVanHoudt is trying to get at is that your query needs to look like the following:
```js
connection.query('UPDATE `watchlistsymbols` SET `Ticker`= ? WHERE `Id`=40)', [req.body.Ticker], function (error, results, fields) {                       
```
