### ISSUE TITLE
Unescape mysql functions

### ISSUE THREAD

**Issue by shaoner** [felixge/node-mysql#1086]
Hi,

Simple question, I was wondering if it would make sense to have the ability to "unescape" values while using `format`.
It may sound ridiculous, but using format with an array or an object is pretty convenient, and you may want some values to be "unescaped" (especially MySQL functions):

```javascript
connection.query('INSERT INTO ?? (??) VALUES ?', [ 'table', [ 'field1', 'field2', 'field2' ], [ [ 1, 2, 'DEFAULT' ], [ 'DEFAULT', 3, 4 ] ])
```

or

```javascript
connection.query('INSERT INTO ?? SET ?', [ 'table', { field1: 1, field2: 2, field3: 'NOW()'  } ])
```

Of course, I could use my own formatter or create the query string myself. I just wanted to bring the idea on the table. Maybe by providing a function as a value ?

```javascript
connection.query('INSERT INTO ?? SET ?', [ 'table', { field1: 1, field2: 2, field3: function () { return 'NOW()'; }  } ])
```

Cons: It doesn't seem very natural to use '?' as a placeholder to something which is finally not escaped, so maybe there are better ideas to achieve this, or maybe the whole feature would be a bad idea in a low-level module after all.

**Comment by dougwilson** [comment]
You may actually want to use an actual query builder like https://hiddentao.github.io/squel/

**Comment by shaoner** [comment]
Thanks, I just wanted to know if it was something to consider. I'm already using a kind of query builder.

**Comment by dougwilson** [comment]
Gotcha. As for my philosophy: a dedicated query-building library like Squel.js can do a much, much better job and allows that work to apply across not only the different MySQL Node.js libraries, but also other query languages, so it's nice for it to be separate.
