### ISSUE TITLE
Mysql Fabric

### ISSUE THREAD

**Issue by PratheepV** [felixge/node-mysql#1087]
Hi,

We are trying to setup the mysql HA with mysql fabric. We would like to know whether current library supports the mysql fabric. 

Is there any future plans for supporting Mysql fabric ? Now the mysql Fabric is Generally available. 

Thanks,
Pratheepv

**Comment by dougwilson** [comment]
This library is just the MySQL protocol, so any server using the MySQL protocol will work (think even MariaDB, which works just fine, since it uses the MySQL protocol). Did you try this library and it didn't work?

**Comment by PratheepV** [comment]
No, I haven't tried it. I will try and let you know. 

This is what I can see in Mysql official site

>MySQL Fabric-Aware connectors are currently available for Java, .Net and Python. These connectors automatically fetch routing information from MySQL Fabric and then cache it in order to route queries and transactions directly to the correct MySQL Server. The application simply provides the sharding key - with no knowledge of the topology of the server farm or the state of any server.

**Comment by dougwilson** [comment]
Ah. From the sound of that, it seems to support fabric, someone may need to write a new Node.js module for that routing data; then the actual queries can use this or another protocol library (this is just speculation based on that blurb, though).

**Comment by dougwilson** [comment]
Closing due to 24 days of inactivity; please let me know if you would like it re-opened.

**Comment by vnykmshr** [comment]
Any heads up? I am currently exploring my chances to make this work.

**Comment by dougwilson** [comment]
Please use #1139 for fabric discussion. Of course, contributing a PR is the quickest way to see support in this module :)!
