### ISSUE TITLE
what is serverStatus?

### ISSUE THREAD

**Issue by iyjian** [felixge/node-mysql#1089]
i issued a insert sql into mysql using node-mysql
```js
conn.query('insert into articles (memberID,title,date) values (?,?,?)',
[memberID,title,date],function(error,result){
                        conn.release();
                        if(error){
                            cb('insertDataQueryError',null);
                        }else{
                            console.log(JSON.stringify(result));
                            cb(null,result.insertId);
                        }
                    });
```
the *articles* table is a table with a auto incremental id

i can get the insertId correctly, but i cannot find the data in database.
then i print the result out:
```
{"fieldCount":0,"affectedRows":1,"insertId":292,"serverStatus":3,"warningCount":0,"message":"","protocol41":true,"changedRows":0} 
```
i found there is a serverStatus column,and when the insert act correctly,the column is 2.

could you give some advise why the data can not insert correctly?

**Comment by dougwilson** [comment]
The `serverStatus` is what comes back from your MySQL server. The values are documented at http://dev.mysql.com/doc/internals/en/status-flags.html

As for why your data is not inserted, I really have no idea, because there is not enough information. Your serverStatus = 3 means you have both `SERVER_STATUS_AUTOCOMMIT` and `SERVER_STATUS_IN_TRANS`, so perhaps you were missing a `COMMIT` query to end your transaction you started?

**Comment by iyjian** [comment]
i don't perform a commit after insert operation,but i thought the node-mysql perform auto-commit after the insertion,and this strange issue only appear after server repeat call(it insert correctly at the first beginning calls)

**Comment by dougwilson** [comment]
node-mysql does nothing for you--it just sends the queries as you ask to the MySQL server.

**Comment by dougwilson** [comment]
But in the end, without full code and schema I can use to reproduce, it's hard to really provide any help. The information given so far only goes so far, I'm sorry.

**Comment by iyjian** [comment]
ok, i would post the full code in minute

**Comment by iyjian** [comment]
https://gist.github.com/iyjian/383b83314639a0bba537

**Comment by iyjian** [comment]
the refined code as above , many thanks if you can give it a look

**Comment by dougwilson** [comment]
I gave it a look, but nothing looks wrong. Is that the only query you ever make? I ask because based on your statement that it works when serverStatus is 2, but doesn't when 3, the different between them is because somewhere in your code, you are starting a transaction but not ending it.

**Comment by iyjian** [comment]
yes , i perform a serval call befroe this operation , i can only using *mocha* to reproduce this error. when i call the service in browser or i my application, it is normal.

i would refined the mocha test script and tell you the result, i would waste your time if post the full script.

thanks in advance .

**Comment by dougwilson** [comment]
No problem, but I assume that when you try in the browser, all you're doing is simply calling the one route? Then in your mocha you are probably calling a whole bunch of things and it just takes one thing to be wrong to get the hang up, most likely. Also, calling `.release()` doesn't do anything to your connection, just as a FYI. There is also the possibility that there is some race condition in the tests? I'm not sure :/

**Comment by araker** [comment]
Sorry to bump an old topic, but the url to the server status flags has become outdated. The new url is https://dev.mysql.com/doc/dev/mysql-server/latest/PAGE_PROTOCOL.html, but I can't find the serverStatus in there. Can someone point me in the right direction?

**Comment by ruiquelhas** [comment]
@araker should be there.

https://dev.mysql.com/doc/dev/mysql-server/latest/mysql__com_8h.html#a1d854e841086925be1883e4d7b4e8cad

**Comment by araker** [comment]
Thanks for the assist.
