### ISSUE TITLE
Float Truncate

### ISSUE THREAD

**Issue by beinnova** [felixge/node-mysql#1091]
Hi,
I have problem with float numbers. My table row is set float but when i try to insert a float number i see in a only decimal part.

**Comment by dougwilson** [comment]
Can you provide some more information? What does your query look like? Table schema?

**Comment by beinnova** [comment]
Hi,
My query is Luke ' INSERT INTO table (col_1, col_2, col_n) VALUES (val_1,
val_2, val_n).
The row where I find that problem are setted float.

Il giorno mer 13 mag 2015 17:22 Douglas Christopher Wilson <
notifications@github.com> ha scritto:

**Comment by dougwilson** [comment]
Sure, but what is the table schema? And what is the actual JavaScript code you are using to perform the insert?

**Comment by beinnova** [comment]
Ok, I'm sorry it's my problem. I forgot to set decimal range :). Thanks for
all and very compliments for the module.

2015-05-13 17:33 GMT+02:00 Douglas Christopher Wilson <
notifications@github.com>:

> Sure, but what is the table schema? And what is the actual JavaScript code
> you are using to perform the insert?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felixge/node-mysql/issues/1091#issuecomment-101716860>
> .
>



-- 
*Be**innova* di *Giorgio Cerruti*
*WebSites | IT consultant | Web Developer*
*Phone: +39 340/87.68.326 :: Skype: beinnova*
*P.IVA: 10755560017*
*Visit Beinnova <http://www.beinnova.it> Site*

   - Giorgio Cerruti
   <http://it.linkedin.com/pub/giorgio-cerruti/31/422/852/>

**Comment by dougwilson** [comment]
Ah, glad you figured it out :)
