### ISSUE TITLE
.query() causing a memory leak

### ISSUE THREAD

**Issue by UnacceptableUse** [felixge/node-mysql#1093]
Hi, I've noticed a memory leak issue being caused by connection.query().   
  
In an test I ran, running a mysql query every 1 millisecond with no callback and logging the memory usage every 1000 ticks, this was the result: ![Graph 1](http://files.unacceptableuse.com/ss/84ef3650.png)
  
If I remove the query, and leave all the rest of the code intact then a much more pleasing graph is created: ![Graph 2](http://files.unacceptableuse.com/ss/90995a7b.png) this shows that the query is certainly what is causing the memory leak, for the query I'm using:         
```javascript
    var q = tickConnection.query(SQL_TICK, undefined);
     q = null; 
```   
  
to minimize any leaks I may cause myself.     

I'm using the latest version of node-mysql from the repository. I hope you can sort this out, if you require any more information just ask and I'll do my best!

**Comment by dougwilson** [comment]
Cool, I will try to check it out, but if you or anyone else can determine the cause of the leak, that would be awesome (and even better if there is a PR)!

**Comment by dougwilson** [comment]
It's going to be hard for me, because I don't know how `tickConnection` was created, etc. I could try to look into it if you can provide an app I can copy and paste to see the memory leak in action, though...

**Comment by UnacceptableUse** [comment]
Here is what I was running: http://pastebin.com/UpAM0Nmh

**Comment by dougwilson** [comment]
Where in the code are you releasing the connections back to the pool?

**Comment by dougwilson** [comment]
Nevermind, it seems you are only ever grabbing one connection.

**Comment by UnacceptableUse** [comment]
Yeah, it's a pool because in the real server I use multiple connections, one connection is reserved for the tick which is all that's going on in the abridged version of the server I have posted here.

**Comment by dougwilson** [comment]
Anyhow, please test again by changing `setInterval(tick, 1);` to something slower than it takes to perform the query. As far as I can tell, you are calling `.query` so fast, that you are basically just queuing up infinite queries, which is where your "memory leak" is. Does it "leak" if you change it to `setInterval(tick, 3000);` ?

**Comment by UnacceptableUse** [comment]
it was previously at 8 and I still had a memory issue. The queue never seems to be filled up at all as the "enqueue" event never fires. I'll try it with 3000 and report back shortly

**Comment by dougwilson** [comment]
> it was previously at 8 and I still had a memory issue

8 is still _8 milliseconds_; your MySQL server cannot reply that fast, sorry to tell you.

> The queue never seems to be filled up at all as the "enqueue" event never fires

The `enqueue` event on which object: the connection or the pool? They represent different thing.

**Comment by UnacceptableUse** [comment]
The enqueue event is from pool. I never really considered how fast the server can respond... it is running on the same server as  nodejs so I didn't think there would be latency, but hey.

**Comment by dougwilson** [comment]
> The enqueue event is from pool

This represents queued `pool.getConnection` calls. If you only do it once, then of course you'll never see anything queued. You want to listed to that event on the connection to know if you are queuing queries in your memory.

> it is running on the same server as nodejs 

Yea, but MySQL cannot process and perform all those network calls in under 8 milliseconds, even on the same server. To really know if it's because your code is making too many connections, simply use this for your test:

1. Replace `setInterval(tick, 1);` with `tick()`
2. Replace `var q = tickConnection.query(SQL_TICK, undefined);` with `var q = tickConnection.query(SQL_TICK, tick);`

This way you are not queuing a bunch of queries in memory.

**Comment by UnacceptableUse** [comment]
Ah right. This makes sense now that I think about it. I ran the test with 3000 millisecond interval and there was no memory issue. I feel silly now, Thanks!

**Comment by dougwilson** [comment]
No problem :) If you do find something, though, always feel free to report it, because there certain could be memory leaks (though I haven't seen any in what parts I use) :)
