### ISSUE TITLE
When inserting multiple rows, why do I need to use a nested array two levels deep instead of one?

### ISSUE THREAD

**Issue by alexbooker** [felixge/node-mysql#1095]
Imagine that I want to insert multiple rows at once, from an array. I would do something like this:

```javascript
var tags = [
  [
    ['Angular'],
    ['JavaScript']
  ]
];
connection.query('INSERT INTO tags VALUES ?', tags);
```

I am curious, why do I need to use the outer-most array? Intuitively, I would have done this: 

```javascript
var tags = [
  ['Angular'],
  ['JavaScript']
];
```

Thanks!

**Comment by dougwilson** [comment]
Because the second argument to query is an array of your values. Each item in the array corresponds to a single ? in the SQL. Thus your intuitive value is right, as the first element of the values array.

**Comment by dougwilson** [comment]
It may help if you wrote it this way:

    var values = [tags];
    connection.query('INSERT INTO tags VALUES ?', values);
