### ISSUE TITLE
always 'ER_PARSE_ERROR'

### ISSUE THREAD

**Issue by ezekel** [felixge/node-mysql#1097]
why I get always this kind of error

`[Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND userdev.user_id
 = '1' order by dv.dateTime_created DESC LIMIT 60' at line 1]
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0 }
`

here is my code

```javascript 
      var options = {
                    sql: 'select dv.device_id as "devid",dv.dateTime_created as "thetime",' +
                    'userdev.device_name as "devname",'+
                    'dv.id from devicetable as dv inner join' +
                    ' user as userdev on dv.device_id = userdev.device_id ' +
                    'where dv.device_id in ( ? ) AND userdev.user_id = ? order by dv.dateTime_created DESC LIMIT 60'};

    connection.query(options,[clientid,logid],function (err, results) {

                    if (err) {
                        console.log(err);
                    }

                   //All is well here

                    socket.emit('show', results);
                 

    });


```

Thank you in advance

**Comment by ezekel** [comment]
@dougwilson 

why I get always parese error ?

**Comment by dougwilson** [comment]
So the error comes from you sending your MySQL server invalid SQL. In order to know what the error is, I need to either see the entire formatted SQL (if you set `debug: true` in the options, or at least know what the values are for the variables `clientid` and `logid` in your code above that causes the error.

**Comment by ezekel** [comment]
@dougwilson 
is this how to put the debug option

```javascript

    
    pool.getConnection(function (err, connection) {
		 var options = {
						sql: 'select dv.device_id as "devid",dv.dateTime_created as "thetime",' +
						'userdev.device_name as "devname",'+
						'dv.id from devicetable as dv inner join' +
						' user as userdev on dv.device_id = userdev.device_id ' +
						'where dv.device_id in ( ? ) AND userdev.user_id = ? order by dv.dateTime_created DESC LIMIT 60',debug: true
					};
					
			   connection.query(options,[devid,logid],function (err, results) {

                    if (err) {
                        console.log(err);
                    }
					
				});	
					
					
    });	


```

**Comment by dougwilson** [comment]
No, you need to pass it as an option to createConnection (see https://github.com/felixge/node-mysql/blob/master/Readme.md#connection-options).

**Comment by ezekel** [comment]
Like this

```javascript
   var pool = mysql.createPool({
    host: 'localhost',
    user: 'root',
    password: '',
    dateStrings: true,
    database: 'mydb',
    debug: true

});



```

**Comment by dougwilson** [comment]
Exactly. Then you will get a lot of information printed to your console, including the full SQL that has the error.

**Comment by ezekel** [comment]
@dougwilson ,

what does it says ?

```javascript
{ command: 3,
  sql: 'select dv.device_id as "devid",dv.dateTime_created as "thetime",userdev.device_name as "devname",dv.id from devicetable as dv inner join user as userdev on dv.de
vice_id = userdev.device_id where dv.device_id in ( \'05504372\', \'06547999\', \' \\t02700556\' ) AND userdev.user_id = \'1\' order by dv.dateTime_created DESC
LIMIT 60' }
```

**Comment by dougwilson** [comment]
The SQL in that debug message is 100% valid. Did you get that error message with that exact query? What happens if you try the query on your MySQL server directly?

**Comment by ezekel** [comment]
I tried to directly run the query in my heidisql,it works fine I see results.the error occurs when I tried to refresh my page.after that it display the records.

**Comment by dougwilson** [comment]
Gotcha. I tried the query you pasted and it worked for me as well. I need you to get the query that is actually causing the error to be able to say why you're getting it.

**Comment by dougwilson** [comment]
You can try changing your code to the following:
```js
               var query = connection.query(options,[devid,logid],function (err, results) {

                    if (err) {
                        console.log(err);
                        console.log('SQL: ' + query.sql);
                    }

                }); 
```
and pasting the output from that here (where you have the error line and then the SQL line).

**Comment by ezekel** [comment]
@dougwilson 

I wonder why in the `in` is blank
`
SQL SAYS: select dv.device_id as "devid",dv.dateTime_created as "thetime",userdev.device_name as "devname",dv.id from devicetable as dv inner join user as userdev on dv.
device_id = userdev.device_id where dv.device_id in (  ) AND userdev.user_id = '1' order by dv.dateTime_created DESC LIMIT 60
`

**Comment by ezekel** [comment]
@dougwilson 

Thank you I fixed it.

**Comment by ezekel** [comment]
Hi @dougwilson ,

if I do like this

```javascript
 var query = connection.query(options,[devid,logid],function (err, results) {

                    if (err) {
                        console.log(err);
                        console.log('SQL: ' + query.sql);
                    }

                }); 

```

how do i close the connection ?

`query.release()` ?

**Comment by dougwilson** [comment]
You do not have to do anything with the query variable.

**Comment by ezekel** [comment]
ok thank you
