### ISSUE TITLE
Batching with multi-dimensional arrays doesn't work

### ISSUE THREAD

**Issue by ding444** [felixge/node-mysql#1098]
Batching queries with multi-dimensional seems to be broken.  After looking around at some example code and trying with my code below I was unable to get it to work.  

	var sql = 'INSERT INTO hand_readings (reading_date, user, unit, value) VALUES(?) ON DUPLICATE KEY UPDATE value=VALUES(value)';
	 var data = [
	 	['2015-05-21', 1, 2, 2],
	 	['2015-05-21', 1, 4, 2],
	 	['2015-05-21', 1, 3, 8]
	 ];
	 connection.query(sql, data, function(err, results) {
	 	 ...
	 })

The debug output for the code above is:

    sql: 'INSERT INTO hand_readings (reading_date, user, unit, value) VALUES(\'2015-05-21\', 1, 2, 2) ON DUPLICATE KEY UPDATE value=VALUES(value)' }

It doesn't convert the multi-dimensional array into `...VALUES('2015-05-21', 1, 2, 2),('2015-05-21', 1,4,2),...` as expected.

**Comment by ding444** [comment]
I just figured out that I'm a version behind....

False alarm everyone! :$

**Comment by dougwilson** [comment]
This is because the second argument to `connect.query` is an _array of values_, not the value itself, your code needs to be the following:
```js
var sql = 'INSERT INTO hand_readings (reading_date, user, unit, value) VALUES(?) ON DUPLICATE KEY UPDATE value=VALUES(value)';
 var data = [
    ['2015-05-21', 1, 2, 2],
    ['2015-05-21', 1, 4, 2],
    ['2015-05-21', 1, 3, 8]
 ];
 connection.query(sql, [data], function(err, results) {
     ...
 })
```
