### ISSUE TITLE
Publish 2.7.0

### ISSUE THREAD

**Issue by dgb** [felixge/node-mysql#1108]
Hello,

Is 2.7.0 released yet? I see a reference to it in the changelog and issue #1072, but it doesn't appear to be on npm. I've got my project pointed to what's on Github, but it'd be nice to use the npm version.

Thanks!
Derek

**Comment by dougwilson** [comment]
This is the second time recently I did everything to release a version except publish to npm, idk what is up recently :)

I will publish tonight, thanks for the note!

**Comment by sidorares** [comment]
@dougwilson that happened with me several times. Really want to write script which runs on travis and publishes to npm each time there is a semver tag

**Comment by dougwilson** [comment]
Yea. It's typically with projects with AppVeyor, since they take forever to run, so sometimes I have to go to sleep before I can publish, then totally forget about publishing the next day :)

**Comment by dougwilson** [comment]
```
$ npm publish
+ mysql@2.7.0
```
