### ISSUE TITLE
Data consistency

### ISSUE THREAD

**Issue by AdriVanHoudt** [felixge/node-mysql#1109]
Not really a question about the module but more a general node + mysql question.

I have a usecase where I need to check if a row exists in table A.
* If exists --> use id to insert into table B
* If not --> create row in table A and use new id to insert into table B

The problem I'm having is because of async. Between check and insert the data can change due to another async function. Is there a way to prevent this or deal with this?

**Comment by AdriVanHoudt** [comment]
Only possible solution I can think of is `inert ignore` and if `insertId === 0` select again to get the id wanted

**Comment by dougwilson** [comment]
There are a few solutions:

1. Put the logic in a procedure and call the procedure from your code.
2. Enable multi statements and send multiple statements at once.
3. Use MySQL transactions properly, though this will just make some of the COMMIT statements error due to a conflict.
4. Use transactions to lock the read on the relevant rows and release it after you insert. This would make your reads serial.

**Comment by AdriVanHoudt** [comment]
Is there a prefered way? Or is what I propose bad?
I don't really like multi statements, locking read doesn't seem to solve this, procedure gives the same result as multi statements not and now I also get errors so errors on commit won't solve it either I think

**Comment by dougwilson** [comment]
I mean, a stored procedure with the proper transaction settings is the main way I would implement what you describe; the issue is actually nothing to do with Node.js and async, as simply using any language where you have multi threads serving requests will have the same issue, btw ;)

**Comment by dougwilson** [comment]
But the simplest method of all that I can come up with is to do INSERT IGNORE on table A, then do an INSERT in table B, getting the id from table A with a sub query.

**Comment by AdriVanHoudt** [comment]
Yeah I talked to some other people and got the same response, this is just the first time I ran into it, I have use stuff like Hibernate for Java where, I assume, Hibernate solves this for you. And yeah the subquery thing is nice! thanks!
