### ISSUE TITLE
mysql pooling and releasing connections

### ISSUE THREAD

**Issue by venkatsep14** [felixge/node-mysql#1111]
We are trying to using mode-mysql connection pool and releasing the connections inside the callback of "query" however it is not releasing the connection and giving connection limit reached error.

For even just few users app is not able to work with 200 connections.

Is there any known limitations that I need to take care?

**Comment by dougwilson** [comment]
> giving connection limit reached error

Can you paste the error here (so I can see where it's coming on based on the stack trace)?

**Comment by dougwilson** [comment]
Closing due to 6 days of a lack of response; please let me know if you have a response to the question and I can reopen :)!
