### ISSUE TITLE
How to solve the transaction problem of multiple processes

### ISSUE THREAD

**Issue by cd0304** [felixge/node-mysql#1112]
you konw,node.js are multiple processes, and transaction must use the same connection To ensure that. how to use it ,in my multiple processes environment.

**Comment by dougwilson** [comment]
Hi! Unfortunately your question is too broad for it to be an issue report. If you are looking for general help, you may want to ask on Stackoverflow.com which has many developers just waiting to answer questions like yours.

**Comment by dougwilson** [comment]
Closing due to 6 days of no response; please let me know if you can make this much more specific and I can always reopen :)
