### ISSUE TITLE
Possible Memory Leak when Load Testing Node mysql pool connections.

### ISSUE THREAD

**Issue by venkatsep14** [felixge/node-mysql#1113]
Please find the below error stack and if you would like to send me the code I am testing I can and we are trying to do the load testing and that is when we are running into this only for some connections.
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at PoolConnection.addListener (events.js:160:15)
    at /Users/venkat/dev/git/nodemysqlpooltest/pool.js:63:20
    at Ping.onPing [as _callback] (/Users/venkat/dev/git/nodemysqlpooltest/node_modules/mysql/lib/Pool.js:94:5)
    at Ping.Sequence.end (/Users/venkat/dev/git/nodemysqlpooltest/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Ping.Sequence.OkPacket (/Users/venkat/dev/git/nodemysqlpooltest/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/Users/venkat/dev/git/nodemysqlpooltest/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/venkat/dev/git/nodemysqlpooltest/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/venkat/dev/git/nodemysqlpooltest/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/venkat/dev/git/nodemysqlpooltest/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:95:17)
```

**Comment by dougwilson** [comment]
Yes, please send your code. So far every time this is reported, it has always been user code error.

**Comment by dougwilson** [comment]
It's basically saying whatever you have at `/Users/venkat/dev/git/nodemysqlpooltest/pool.js` line 63 is wrong and is leaking.

**Comment by dougwilson** [comment]
Most likely you are attaching your own event listener on a connection from the pool on line 63, but then, since we re-use pool connections (it's the point of the pool), if you don't also write in your code a removal of that event listener you added, you'll basically end up adding the same listener to the same object over and over again.

**Comment by venkatsep14** [comment]
May be you are right it might be the same issue as 979 where I am trying to have a listener inside the pool.getConnection.

connection.on('error', function(err) {
            res.json({
                "code": 100,
                "status": "Error in connection database"
            });
            return;
        });

`var app = express();

var pool = mysql.createPool({
    acquireTimeout:50000,
    connectionLimit: 800, //important
    host: '',
    user: 'root',
    password: '',
    database: '',
    debug: false
});

function handle_database(req, res) {

    pool.getConnection(function(err, connection) {
        if (err) {
            connection.release();
            res.json({
                "code": 100,
                "status": "Error in connection database"
            });
            return;
        }

        console.log('connected as id ' + connection.threadId);

        connection.query("select * from user_tbl LIMIT 2", function(err, rows) {
            connection.release();
            if (!err) {
                res.json(rows);
            }
        });

        connection.on('error', function(err) {
            res.json({
                "code": 100,
                "status": "Error in connection database"
            });
            return;
        });
    });
}

app.get("/", function(req, res) {
    -
    handle_database(req, res);
});

app.listen(10000);`

**Comment by dougwilson** [comment]
Yes, it is. You have `connection.on('error', function(err) {`, but you never removed the listener at any point, thus you end up adding the listener for every request.

**Comment by dougwilson** [comment]
The easiest fix for your code, keeping the listener, is the following:
```js
function handle_database(req, res) {

    pool.getConnection(function(err, connection) {
        if (err) {
            connection.release();
            res.json({
                "code": 100,
                "status": "Error in connection database"
            });
            return;
        }

        console.log('connected as id ' + connection.threadId);

        connection.query("select * from user_tbl LIMIT 2", function(err, rows) {
           // remove your listener before release
           connection.removeListener('error', onConnectionError);

            connection.release();
            if (!err) {
                res.json(rows);
            }
        });

       // add your listener
       connection.on('error', onConnectionError);

        // you must have a named function
        function onConnectionError(err) {
            res.json({
                "code": 100,
                "status": "Error in connection database"
            });
            return;
        });
    });
}
```

**Comment by dougwilson** [comment]
And just as a P.S., your function can be significantly simplified, retaining the same behavior:
```js
function handle_database(req, res) {
    pool.query("select * from user_tbl LIMIT 2", function(err, rows) {
        if (err) {
            res.json({
                "code": 100,
                "status": "Error in connection database"
            });
            return;
        }

        res.json(rows);
    });
}
```

**Comment by venkatsep14** [comment]
Thank you very much and this solved me the issue. However in the last solution don't we need to release the connection?

**Comment by dougwilson** [comment]
The pool object provides you a convince method: pool.query. Using this allows you to skip the entire getConnection -> query -> release dance if you only needed to make a single query. You can see in the last example, there is no connection variable to even call release on. You can read more about pool.query in our readme :)
