### ISSUE TITLE
SELECTing a big integer - last number becomes 0

### ISSUE THREAD

**Issue by Cludch** [felixge/node-mysql#1114]
Hey,

I already described the problem here http://stackoverflow.com/questions/30547874/node-mysql-is-returning-a-slightly-modified-int.

I think there is a bug in the node_mysql module, because when I run the exact same query per CLI, it returns the right value.

**Comment by dougwilson** [comment]
It is literally a limitation of JavaScript itself. You have to use the  supportBigNumbers option, at least (see the readme for options at https://github.com/felixge/node-mysql/blob/master/Readme.md#connection-options).

**Comment by dougwilson** [comment]
The main problem is that JavaScript itself cannot handle numbers that big (you can test it yourself by making a script, assigning your number to a variable and then printing it). Your only option is to store those numbers as strings and we provide a couple options that help you do that in the connection options.
