### ISSUE TITLE
How to detect when connection.query().stream() is end

### ISSUE THREAD

**Issue by quangbuule** [felixge/node-mysql#1117]
I tried this but no luck.

```js
connection.query('select * from posts')
  .stream()
  .on('end', () => {
    console.log('End.');
  });
```

**Comment by dougwilson** [comment]
You'll need to learn more about Node.js streams over at https://nodejs.org/api/stream.html .

The reason your example doesn't work is because the stream starts out paused and does not actually start running until you attach a `data` listener, call `.resume()`, or call `.pipe()`.
