### ISSUE TITLE
When system idle automatically through the error ? 

### ISSUE THREAD

**Issue by bgobi1991** [felixge/node-mysql#1118]
i am using this method mysql.createConnection, how can i solve this ?
{ [Error: read ECONNRESET]
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  fatal: true }

**Comment by dougwilson** [comment]
That is something you would have to troubleshoot yourself; it is a Node.js error saying that the TCP connection was reset.
