### ISSUE TITLE
TypeError: Object #<RowDataPacket> has no method 'parse'

### ISSUE THREAD

**Issue by xanto** [felixge/node-mysql#1119]
Hi, i  have this error on mysql module :  ( i'm not nodejs expert and i'm not sure if this is a bug or not)

node_modules/mysql/lib/protocol/Parser.js:82
```
TypeError: Object #<RowDataPacket> has no method 'parse'
    at Query.RowDataPacket (...../node_modules/mysql/lib/protocol/sequences/Query.js:148:10)
```
nodejs version v0.10.25
mysql module 2.7.0

on ubuntu 14.05

in debug mode before error: 
```
--> ComQueryPacket
{ command: 3, sql: 'SELECT * FROM USER WHERE `id` = 1' }

Server now accepting connections!
<-- ResultSetHeaderPacket
{ fieldCount: 8, extra: undefined }

<-- FieldPacket
{ catalog: 'def',
  db: 'test',
  table: 'USER',
  orgTable: 'USER',
  name: 'id',
  orgName: 'id',
  charsetNr: 63,
  length: 10,
  type: 3,
  flags: 16931,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

etc..

<-- EofPacket
{ fieldCount: 254,
  warningCount: 0,
  serverStatus: 2,
  protocol41: true }
```
Some suggestion?

Thanks in advance.

**Comment by xanto** [comment]
i have upgraded to nodejs to v0.12.4 and now the error is TypeError: undefined is not a function.
In my opinion this is my code problem not a bug.

**Comment by dougwilson** [comment]
Hi @xanto ! Interesting. Well, I see you ended up closing this issue, but let me know if you have any questions; getting the full stack trace of the errors posted above will help if you are still having problems resolving :)

**Comment by xanto** [comment]
Thanks @dougwilson . Next Monday I will do other tests. For now I made a minimal test that works. So I excluded problems on mysql module. My suspicion is that for some reason the connection breaks down during the query. It 's my first experience with nodejs and are also in search of a way to make debugging. Someone suggests using node-inspector.
