### ISSUE TITLE
Select returns only one result value instead of all

### ISSUE THREAD

**Issue by cybercfd** [felixge/node-mysql#1121]
I have tested and retested the query below in the MySQL console with no error but when I run it in Node.js I only get an array with one result back instead of five.  

I have been unable to root cause the problem. Here are the steps I took to try to narrow it down.

1) At first I thought it was a bug with the greatest function but i removed it and had the same problem.
2) Then I removed the left join (used just a join) and still had the issue.
3) Then I added a timeout option of 40s, but the problem persisted.
4) I verified that run had a value and even tried it hardcoded.....same problem...one row returned

I am completely baffled as to why this runs in MySQL but differently via node-mysql.  Note I have also updated all of my npm's so I am running 2.7.0.  This whole app is running local on a Windows 7 system, Mysql version 5.6.2-log, node version 0.10.33
```
select data.rack,x.rackname, floor, top, midHigh, middle, midLow,bottom,greatest(floor,top, midHigh, middle, midLow, bottom) as max from cybercfd.data left join racks as x on data.rack=x.idracks where run=? order by max desc;", run, function(error,rows,fields)
```

**Comment by dougwilson** [comment]
Hmm. So, what is the value of your run variable?

Your code is slightly wrong if you intend yo have the run variable appear in the question mark: the second argument to query is an array of values, so you probably want to write it as query(..., [run], function... where the run variable is the first element of the array.

Also, if that doesn't work, can you try with the npm module mysql2? That has a compatible API but is completely different, so it would rule out bugs in this module.

**Comment by cybercfd** [comment]
the value of run changes but I verified it was being properly populated with a console.log.  Also I tested it by hand by hard coding it to different values and it had no effect..

as to the [run], that too had no effect. 

It would be a shame to have to switch to a new module but I will write a test app and try...

**Comment by cybercfd** [comment]
On the off chance there is a larger, non-mysql issue at hand, here is the code snippet.

socket.on('getHotCold', function(run){
		var hottest, coldest = [];
		connection.query('select data.rack,x.rackname, floor, top, midHigh, middle, midLow,bottom,greatest(floor,top, midHigh, middle, midLow, bottom) as max from cybercfd.data left join racks as x on data.rack=x.idracks where run=? order by max desc;',[run], function(error, hrows, fields) {
			if (error){
				console.log(error);
			} else {
				//console.log(rows[rows.length-1]);
				hottest = hrows[0];
				connection.query('select data.rack,x.rackname, floor, top, midHigh, middle, midLow,bottom, least(floor,top, midHigh, middle, midLow, bottom) as min from cybercfd.data left join racks as x on data.rack=x.idracks where run=? order by min asc limit 100;',[run], function(error, crows, fields){
					console.log(crows);
					if (error){
						console.log(error);
					} else {
							coldest = crows[0];
							socket.emit('loadingHotCold',hrows[0], crows[0]);
							console.log('Hot and Cold are',hottest, coldest, 'at run', run);
					}
				});					
			}
		});
	});

**Comment by adrianblynch** [comment]
Hardcode the SQL. Remove the ? and put the value you think should work in its place. Does that give the correct result?

**Comment by dougwilson** [comment]
In your code, console.log('Hot and Cold are',hottest, coldest, 'at run', run); will of course only ever log the first row, because you made those variables only the first row by taking the 0th index. Where in your code are you expecting to see all the rows, exactly? I only ever see you explicitly using just the first row.

**Comment by dougwilson** [comment]
Also, to help, try adding the debug: true connection option (see the readme) and post everything that gets printed to your console when you run that code, please.

**Comment by cybercfd** [comment]
Before I select the first row my console should show all. 

On June 9, 2015 9:59:37 AM EDT, Douglas Christopher Wilson <notifications@github.com> wrote:
>In your code, console.log('Hot and Cold are',hottest, coldest, 'at
>run', run); will of course only ever log the first row, because you
>made those variables only the first row by taking the 0th index. Where
>in your code are you expecting to see all the rows, exactly? I only
>ever see you explicitly using just the first row.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/felixge/node-mysql/issues/1121#issuecomment-110364292

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by cybercfd** [comment]
No

On June 9, 2015 9:53:04 AM EDT, Adrian Lynch <notifications@github.com> wrote:
>Hardcode the SQL. Remove the ? and put the value you think should work
>in its place. Does that give the correct result?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/felixge/node-mysql/issues/1121#issuecomment-110362831

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by dougwilson** [comment]
We still cannot reproduce the issue. I'm going to close due to a month without activity, but please feel free to reply and we can update :) The best next steps is either a PR to fix the potential issue or a full file (i.e. including all require calls and everything) we can copy and paste and run to reproduce the issue, including DDL in case it is related to your specific SQL.

**Comment by rahular** [comment]
I am facing the same issue
```   
 using(connectionPool.getSqlConnection(), function(connection) {
        return connection.queryAsync('SELECT * from table_name');
    }).spread(function(rows, fields) {
    	console.log('Rows: %j', rows);
    	console.log('Fields: %j', fields);
        res.json(rows);
    }).error(function(err) {
        console.log(err);
    });
```
I know that there are 50 rows in the table. But I am getting only 1 in `rows`. Also, strangely `fields` has the 2nd row. Any idea why this is happening? I have used the same query elsewhere with no problems.

**Comment by dougwilson** [comment]
Hi @rahular, the issue is probably whatever that weird wrapper you are using is. For example, this module has no such thing has `.queryAsync`, so you are using something that is changing the interface of this module and is not something supported here.

**Comment by dlong500** [comment]
@rahular I know this is an old issue, but for anyone coming across this in the future I thought I'd point out that the problem you were having was simply due to using Bluebird's `spread` handler.  Why did you use that?  If you had just used the standard `then` handler everything would have worked fine.  The `spread` handler is precisely used to separate each array value into a distinct function argument.

Other than that, using something like Bluebird to promisify node-mysql is exactly what you want to do in order to avoid callbacks (at least until node-mysql gets native Promise support at some point in the future...)
