### ISSUE TITLE
call stored procedure with OUT parameter.

### ISSUE THREAD

**Issue by breaklee** [felixge/node-mysql#1122]
how can i handle OUT parameters?
below is my sample code to excure query.

test1 sp's parameter is one 
  => CREATE PROCEDURE test1(OUT outvar INT);

========================================================
var info = { value : 0 };
connection.query("CALL eazler.test1(:value)", info, function(err, result) {
		connection.release();
		if(err) {
		}
		else {			
                   // want to get info.value form sp OUT param.
                   var res = info.out;
		}
	});

**Comment by sidorares** [comment]
you need to execute at least 3 statements ( in 3 queries or in one if multiple statements are enabled) - see https://dev.mysql.com/doc/refman/5.5/en/call.html

```js
connection.query(mysql, "SET @outvar = 10");
connection.query(mysql, "CALL test1(@outvar)");
connection.query(mysql, "SELECT @outvar", function(err, res) {
   console.log(res);
});
```

**Comment by breaklee** [comment]
@sidorares great! thanks for your help :)

**Comment by prashantnirgun** [comment]
can be done like this also
connection.query("SET @outvar = 10; CALL test1(@outvar); SELECT @outvar""), function(err, res) {
   console.log(res);
});
