### ISSUE TITLE
MySQL buffering issue

### ISSUE THREAD

**Issue by joyson-17** [felixge/node-mysql#1123]
Hi, 

I am working on a transaction processing system. I was doing some stress testing on the same by sending in 5000 concurrent requests. Looks like mysql is buffering the requests and firing it all at once. Please let me know if there is a better way to do this.

Regards,
Joyson.

**Comment by dougwilson** [comment]
Hi! Please share your code so we can take a look :)

**Comment by joyson-17** [comment]
Look at the following function. For 5000 concurrent transactions, this function will be called 5000 times that means 5000 queries in may be a few seconds which creates buffering.

function GetDeviceRules() {
   var getdevrules = "select * from devicerules;";
   conn.query(getdevrules, function (err, rows) {
       if (err) {
           log.error(err);
       }
       if (rows == "") {
           log.info("no rows found for : ", getdevrules);
       }
       else {
               devicerules = '';
               devicerules = rows;
       }
   });
}

**Comment by sidorares** [comment]
A you sure it's 5000 _concurrent_ connections? Mysql server is not very good at handling such big number of connections ( usually default max is 100 ) and it creates os thread for each connection

**Comment by joyson-17** [comment]
I am using a single connection. The query will be run 5000 times for as many transactions coming in to the system.

After a few transactions come in, the response time increases with the number of requests coming in as all queries are buffered and run together.

**Comment by sidorares** [comment]
That means all queries run sequentially one after another

**Comment by joyson-17** [comment]
Is there a way where I can run the queries concurrently?

**Comment by sidorares** [comment]
yes, open new connections

**Comment by joyson-17** [comment]
Thanks. 
I would like to ask one more thing. Sometimes mysql takes 7-8 seconds to respond even if node.js server is not under load. If we restart both node.js server and mysql server it doesn't happen for till specific period of time. Is it the issue with nodes or mysql server? And what could be the cause for it?

**Comment by dougwilson** [comment]
> Is it the issue with nodes or mysql server? And what could be the cause for it?

It's really hard to say, unfortunately. It could be something with idling machine, idling network connection, perhaps something going on in the Node.js causing a lot of garbage collections, not sure. It would definitely be something to check into, but outside the realm of this module. But if you do determine the issue, and can issue a PR to us, that would be awesome :)
