### ISSUE TITLE
Callback of pooled queries not called

### ISSUE THREAD

**Issue by gclem** [felixge/node-mysql#1124]
Hello,

I'm facing a strange problem, maybe I'm doing it wrong :-) 

I'm pooling up some queries in a short period ( 50-60 / seconds ).
I received the first query callback, but not the next.

Pool configuration : 

```
    this.pool = mysql.createPool({
        host     : this.host,
        user     : this.user,
        password : this.password,
        database: this.database,
        waitForConnections : true,
        connectionLimit : 100,
        queueLimit : 0
    });
```

Method : 

```
MysqlProvider.prototype.queryFormat = function(query, values, callback) {
    console.log("New query started");
    
    var q = this.pool.query(query, values, function(err, result, fields) {
        console.log("Callback pooled query");
        
        if (callback && typeof(callback) === "function")
            callback(err, result, fields);
    });
};
```

N.B : I'm using the same instance of mysqlprovider for all the request.

I have set the event on new connection : 

```
    this.pool.on('connection', function (connection) {
      console.log("NEW CONNECTION ");
    });
```

I have set a timer to test, of 3s between request.
All the executed request are SELECT statement.
The error variable is always tested, and will console.log if raised.

Console log : 

```
New query started
New query started
NEW CONNECTION 
NEW CONNECTION 
Callback pooled query
New query started
New query started
New query started
New query started
New query started
New query started
New query started
```

I don't know why with a limit of pooled connection 100, i'm stuck to 2 connections ( no new connection for the others requests). 

Thanks for your help.

**Comment by dougwilson** [comment]
Hmm... Nothing is jumping out at me from the above information as clearly wrong :) What version of Node.js are you using and what version of this module? Can you also show the code that is calling `MysqlProvider.prototype.queryFormat`?

**Comment by gclem** [comment]
Thank you Doug.

Node version 
```
v0.10.31
```

Module version
```
"version": "2.6.2"
```

The code : 

```
WalkerService.prototype.SanitizeWalkerActivity = function(callback) {
    
    var self = this;
    
    //// 11 months
    this.getInactiveWalkerFor11Months(function(err, results) {
        
        if(err)
        {
            console.log(err);
            return;
        }
        
        results.forEach(function(element) {
            
            //// Send notification
            self.NotifyInactivity(element, function(err, result) {
                
                if(err)
                {
                    console.log(err);
                    return;
                }
            });
            
            var now = new Date().getTime();
            while(new Date().getTime() < now + 3000){ /* do nothing */ } 
              
        }, this);
    });
};


```
WalkerRepository.prototype.getInactiveWalker = function(month, callback, condition, warnKind) {
    
	if(!condition)
        condition = ">=";
        
    this.provider.queryFormat("QUERY", [month, warnKind], callback);
};
```

In NotifyInActivity ( called each element in the loop), the query call : 

```
                         translationRepository.getBySet(category, lang, function(err, results){ 
                         
                         if(err)
                         {
                             console.log(err);
                             return;
                         }
                         
                         if(results)
                         {
                             results.forEach(function(element) {
                                 console.log(element);
                                 //// Storing to cache
                                 fromStore.set(generateStoreKey(element.key, lang), element);
                             }, this);
                         }
                         
                         if (callback) callback(err, results ? normalizeTranslationsKeys(fromStore.mget(fromStore.keys())) : []);
                     });
```

**Comment by dougwilson** [comment]
Hi! Sorry, this is just a lot of partial information for me to think about there (and nothing I can actually just run to try and debug myself, since it's just a bunch of snippets). Are you still having the issue? Would you be willing to try using 2.7.0 of this module? Is it possible you can reduce the code down to something I can just copy and paste and run to see the issue at all?

**Comment by gclem** [comment]
I have done some debugging.

Is it possible that the lib doesn't support multiple instance of a pool connection ?
Strange thing, if I pool from a single instance multiples queries, it works, but it doesn't work when 2 connections pools are instanciated.

**Comment by dougwilson** [comment]
Many people, including the PoolCluster, use multiple pools at the same time without issue, so I know it's certainly possible for multiple pools to all exist fine. The test suite also uses multiple pools in many of it's files.

**Comment by dougwilson** [comment]
Hi @gclem , I haven't been able to reproduce the issue, including by trying to piece together your various snippets. I'm going to close this for now due to lack of activity or a confirmed issue, but please feel free to post an update and we can reopen :) The best next steps is either a PR to fix the possible issue or provide a complete file (and not snippets) that I can copy and paste and run to reproduce the issue.
