### ISSUE TITLE
Access values of all columns with dublicated names in a select query.

### ISSUE THREAD

**Issue by alexn1** [felixge/node-mysql#1127]
Mysql allows to have a columns with the same names in a select query. 
There is no way to fetch row as an array to be able access each column with the same name. Fetcing as an object override all columns by the last one. Please add this feature.

**Comment by dougwilson** [comment]
Hi! So there are two solutions to your issue:

1. Use the remapping feature already a part of the library. Documentation: https://github.com/felixge/node-mysql#joins-with-overlapping-column-names
2. We have the issue #770 still open asking for getting back an array; we're just waiting for someone to offer a PR. Perhaps you can be that person :)

**Comment by alexn1** [comment]
Thank you very much! Option 1 works for me.
