### ISSUE TITLE
Assigning conn to new var

### ISSUE THREAD

**Issue by AdriVanHoudt** [felixge/node-mysql#1130]
What happens when I do this?
```js
var conn = pool.getConnection(...);
var connCopy = conn;
connCopy.query(...);
conn.release;
reply();
```
Does `conn` get released? Or only `connCopy`? And if so should I be aware to never assign a connection to another var?

**Comment by dougwilson** [comment]
So JavaScript itself doesn't let us do anything special, unlike other languages. This means that both variables are simply a reference to the same connection object, just aliases. Of course "both" get released, as they are simply two pointers to the same object.

**Comment by AdriVanHoudt** [comment]
Ok thanks, I keep forgetting when it is copy by value or by reference :P
