### ISSUE TITLE
database tables not updating

### ISSUE THREAD

**Issue by gokarter24** [felixge/node-mysql#1132]
For some reason when I use the query SHOW TABLES, its not displaying the most recent tables I've added to my database. I'm not quite sure why this it but if anyone can help me fix this would be greatly appreciated.

**Comment by dougwilson** [comment]
Hi! You may be in two different databases. From the place you are creating tables, please run `SELECT DATABASE();` and then from this client, also run `SELECT DATABASE();` and see if the values are the same or not.

**Comment by gokarter24** [comment]
Not quite sure what you mean, basically when I'm trying to query one of my tables it says it can't find it. and then I queried SHOW TABLES and there is a couple tables that aren't showing.

**Comment by dougwilson** [comment]
Ok. I'm just trying to help :) If you perform those queries at the places listed, you would at least know if you are even in the same database in the two locations, because one MySQL server can have any number of databases. Otherwise, perhaps show the output of this query, please: `SELECT table_schema, table_name FROM INFORMATION_SCHEMA.TABLES` from this client as well as from where ever you are creating the tables from.

**Comment by gokarter24** [comment]
Its not showing it in that query.

**Comment by dougwilson** [comment]
From both places? I'm trying to work with you here, but you're not giving me like any information to really do anything or make any further suggestions.

**Comment by gokarter24** [comment]
Like I made a small NodeJS application, and I ran it from there, but if I run it from my phpMyAdmin its there.

**Comment by dougwilson** [comment]
Cool. I cannot help further without the following, though: 1. run the `SELECT` query from your Node.js app and paste it here; 2. run the `SELECT` query froom phpMyAdmin and paste it here.

**Comment by dougwilson** [comment]
Basically, you need to see if the table is there and what the `table_schema` is for that table and be sure that same value is what you are using as the `database` connection option for this library. If it is, then do a `SELECT @@hostname` on both this module and phpMyAdmin and ensure they match.

**Comment by dougwilson** [comment]
Hi @gokarter24 , I'm going to close this issue for inactivity, but if you have any more information from my questions, please feel free to reply here and I'll happily re-open and continue to help :)
