### ISSUE TITLE
Is it possible to remove the [ ] from the resulting parameter?

### ISSUE THREAD

**Issue by Dillybob92** [felixge/node-mysql#1135]
For example:

```
db.query('SELECT rpg_friends.* from rpg_friends left join users on rpg_friends.user_id=users.id where rpg_friends.user_id = '+user.RPG.user_id, function(error, results){
						 console.log(results);
								});
```

Will output:
http://i.gyazo.com/11b3351c3feab433eb9544530befcc00.png

But, I don't want the brackets to be coming I just want the object itself. I know I could do JSON.parse/substring/etc to remove them, but I was wondering if you know a global way or somewhere inside MYSQL itself to output the results without the array brackets. 

Thanks!

**Comment by dougwilson** [comment]
Hi! So you are asking about controlling what the `console.log` method does; fortunately MySQL module has nothing to do with what `console.log` is outputting to your screen, as this is part of Node.js.

One potential "solution" is to use the following instead:
```js
results.forEach(console.log.bind(console))
```
but if that doesn't get you the output you want still, you may want to ask for help from Node.js directly :)
