### ISSUE TITLE
Question: Are `threadId` returned on connections from a poolCluster unique?

### ISSUE THREAD

**Issue by shamasis** [felixge/node-mysql#1136]
I am trying to create a hash based on all unique connections returned from a `poolCluster`. I figured out `connection.threadId` could be a good choice.

My question is that will `threadId` ever collide when a cluster pool has a number of configs from same or different database instances?

**Comment by dougwilson** [comment]
The threadId is directly from your MySQL server, and not generated by this module. The ID is only unique per server, and then, only among the active connections. Essentially you can think of it as behaving exactly as a PID.

**Comment by shamasis** [comment]
Thanks. :-) Is there any other property (public or private) that you store in the connection object that can be treated as unique?

**Comment by dougwilson** [comment]
That's probably the closest you have to unique, apart from the JavaScript level equality of the underlying Node.js socket object.

If you use threadId, if you combine that with the server host+port from the configuration and track when connections disconnect, that would be the easiest way to get uniqueness.

**Comment by shamasis** [comment]
Thank you for the help.I am sure that myself and many others will benefit from your assistance. :-)

**Comment by dougwilson** [comment]
No problem :) and feel free to continue to ask questions here, even if closed, as I will respond :)
