### ISSUE TITLE
When inserting posts using an object, is the data already escaped?

### ISSUE THREAD

**Issue by Dillybob92** [felixge/node-mysql#1137]
For example:

```js
var post  = {
				user_id: user.RPG.user_id,
				friend_id: results.user_id,
				friend_accountname: results.username,
				friend_charactername: results.character_name,
				friend_added: Date.now()/1000
			};
			
			
 db.query('INSERT INTO rpg_friends SET ?', post, function(err, results) {
	console.log(err);
	
});
```

Is all the data already being escaped through post? Or do we need to add db.escape(post) ?

**Comment by dougwilson** [comment]
Anything that is inserted through a ? is escaped, yes. That includes all the values in your example.

**Comment by Dillybob92** [comment]
I see, thanks.

I am wondering about this: https://github.com/felixge/node-mysql/issues/1120

If we don't use ?, and use db.escape(VARIABLEHERE) would be fine right? We don't have to use ?, although I can see how ? makes this very easy as compared to insert into table (col1, cold2) values (val1,value2).  I didn't even know about the ? and going to be using now a lot more :)

**Comment by dougwilson** [comment]
Yes, you can use db.escape instead :) using db.escape is identical to using the ? with that value, just using string concatenation instead

**Comment by Dillybob92** [comment]
Alrighty, makes better sense now!! Thanks for clarifying this.

**Comment by joepie91** [comment]
@Dillybob92 It's safer to use the parameterized syntax, because it's too easy to forget to use `db.escape` somewhere, leading to a vulnerability. See also [here](https://github.com/felixge/node-mysql/issues/1120#issuecomment-116437233).

Unless what you want to do *can't* be done with parameterized syntax, you should never use `db.escape`.

Also, are you who I think you are? :)

**Comment by Dillybob92** [comment]
Yeah I am, small world? :)

Yeah, definitely going to doing the parameterized syntax and I 100% agree with you, while looking over some game code I see there is 1 spot where I missed an escape, that's not good.  I didn't realize how epic the parameterized syntax was until I saw how easy it is to insert data into a db. (Just need an object) and the plugin does the rest, so easy as compared to the bullshit 'INSERT INTO table (col1, cold2) values (val1, val2) bullshit. Plus, those can get very long in node and would need a line break on the query code to read it, just awful.  Love this way, wayy better.
