### ISSUE TITLE
ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'mycolumn' at row 1

### ISSUE THREAD

**Issue by bgobi1991** [felixge/node-mysql#1140]
```
{ [Error: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'mycolumn' at row 1]
  code: 'ER_WARN_DATA_OUT_OF_RANGE',
  errno: 1264,
  sqlState: '22003',
  index: 0 }
```

**Comment by dougwilson** [comment]
Hi! So that error is simply an error from your MySQL server based on whatever the query you are doing is. You can read more about that error in the MySQL manual: https://dev.mysql.com/doc/refman/5.5/en/out-of-range-and-overflow.html
