### ISSUE TITLE
Check connection status 

### ISSUE THREAD

**Issue by Alex-Nabu** [felixge/node-mysql#1141]
Lets say I'm running a query in a loop. and the query errors out. I want to close the connection and stop whatever I'm doing only I'm stuck in the query callback function so I cant just 'break;' and my only option is to use 'return' and have the query callback not go any further. However The for loop will still continue trying to execute subsequent 'query' function calls and if on the first query error I had 'destroyed()' or 'end()' the connection. My program will crash telling me the connection has been closed or if I had opted not to close it then the connection is kept open and will get a timeout error later on. How would I use this feature to check the connection state to know if I should execute subsequent calls to query or not?

**Comment by Alex-Nabu** [comment]
for(var i= 0; i<offer.items_to_give.length; i++)
								{
									connection.query("DELETE FROM `backpack` WHERE `assetid` = ? AND `appid` = ? AND `contextid` = ?", [offer.items_to_give[i].assetid, offer.items_to_give[i].appid, offer.items_to_give[i].contextid], function(query_error, results, feilds) {
										 if(query_error)
										 {
										 	logger.log("error", "query error : failed to delete items :"+query_error.code);
										 	connection.rollback();
										 	return;
										 }
                                                                    // everything went for all the queries so commit


If there is a better way to achieve what I'm trying to do I'm open to suggestions.

**Comment by Alex-Nabu** [comment]
I guess for now, On a query_error I could simply check if we are at the last iteration and only destroy the connection then. But I really do suppose I must be doing this wrong (I'm in the functional learning curve)

**Comment by IngwiePhoenix** [comment]
@Alex-Nabu  Have you found any solution? I'd like to check mysql connectivity on my app's startup as part of my dependency checking.

**Comment by Alex-Nabu** [comment]
@IngwiePhoenix not particularly. I ended up doing something similar that I demonstrated above for my specific case. There was a kind of patch for what you want though am not 100% sure if its in the latest versions. see: https://github.com/felixge/node-mysql/pull/338

**Comment by IngwiePhoenix** [comment]
This is what I did to see if I can safely connect:

```javascript
                log.info("Testing MySQL...");
                var conn = require("mysql").createConnection({
                    host:       "localhost",
                    user:       config.DB.user,
                    password:   config.DB.pass,
                    database:   config.DB.mydb
                });
                conn.connect(function(err){
                    if(err) {
                        log.error("MySQL failed.");
                        cb(err);
                    } else {
                        log.info("MySQL works.");
                        cb();
                    }
                });
```

`cb()` is the callback passed by `async.parallel`, since i was testing a few services t obe active before my app actually starts to avoid unexpected behaviour. Maybe it helps you ^^
