### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by kavolorn** [felixge/node-mysql#1143]
Hi

Thank you very much for your library :) I have short question. You have the following code in your readme file:

```javascript
connection.beginTransaction(function(err) {
  if (err) { throw err; }
  connection.query('INSERT INTO posts SET title=?', title, function(err, result) {
    if (err) { 
      connection.rollback(function() {
        throw err;
      });
    }

    var log = 'Post ' + result.insertId + ' added';

    connection.query('INSERT INTO log SET data=?', log, function(err, result) {
      if (err) { 
        connection.rollback(function() {
          throw err;
        });
      }  
      connection.commit(function(err) {
        if (err) { 
          connection.rollback(function() {
            throw err;
          });
        }
        console.log('success!');
      });
    });
  });
});
```

I think error handling is not correct. Should there be a code with "else" clauses? Like that:

```javascript
...
connection.commit(function(err) {
  if (err) { 
    connection.rollback(function() {
      throw err;
    });
  } else {
    console.log('success!');
  }
});
...
```
Thanks

**Comment by dougwilson** [comment]
No, because `throw` stops the execution flow, so `else` is redundant and just makes indentation worse.

**Comment by kavolorn** [comment]
I see in debugger situation then throw happens after the console.log. I was also expecting your code to work though. I'm using you library under Adobe CC environment with node 0.8.22 integrated.

**Comment by dougwilson** [comment]
Actually, there should be some `return` statements in there!

**Comment by kavolorn** [comment]
In the if-error block after rollback I guess?

**Comment by dougwilson** [comment]
I just pushed a change that should fix the code flow. That's lame that the mistake was in the readme and thanks for the find!

**Comment by kavolorn** [comment]
Thanks :)
