### ISSUE TITLE
LiveMysql

### ISSUE THREAD

**Issue by ihsanberahim** [felixge/node-mysql#1145]
Is it Node-Mysql can do LiveMysql like this:

https://github.com/numtel/meteor-mysql/

**Comment by dougwilson** [comment]
Hi! I'm not sure what the underlying question is, but yes, that module has a dependency on this module to perform the MySQL functionality.

**Comment by dougwilson** [comment]
That module's readme does a good job at explaining what modules are used and how, at leat to me.

**Comment by ihsanberahim** [comment]
meteor-mysql can listen for new row added and a row updated.
I read the list of this package features. I saw that this package can do like that right?

**Comment by dougwilson** [comment]
You have to use this module plus a bin log watcher. The https://github.com/numtel/mysql-live-select module combines the two together for you, which is what the meteor module uses. You'll want to use mysql-live-select if you want that functionality :)
