### ISSUE TITLE
date_format and str_to_date fail

### ISSUE THREAD

**Issue by kingram6865** [felixge/node-mysql#1148]
A call to date_format or str-to_date fails when the %d parameter is used.
%d is interpreted as an element of sprintf and lands in the output as NaN

More details here: http://stackoverflow.com/questions/31282057/why-is-date-format-d-b-y-failing-in-node?noredirect=1#comment50572790_31282057

**Comment by dougwilson** [comment]
It's not clear to me what is going on in that post, can you please re-describe the exact issue here, including code to reproduce? Comments on that say it's not even reproducible with the current version of this module, is that correct?

**Comment by dougwilson** [comment]
```
$ node -pe 'require("./index").format("INSERT INTO data (data_date, data_value) VALUES (date_format(?,'"'"'%d-%b-%y'"'"'),?)", [new Date(), 50])'
INSERT INTO data (data_date, data_value) VALUES (date_format('2015-07-09 18:49:53.917','%d-%b-%y'),50)
```

As you can see, we are not doing anything with `%d` except keeping it the same.

If you can provide something reproducible, or better yet, a PR to fix, that would be the best way to address :)

**Comment by kingram6865** [comment]
Ok. Maybe the issue i not with the module.
