### ISSUE TITLE
Memory leak? [v2.8.0, node: v0.10.25]

### ISSUE THREAD

**Issue by miriti** [felixge/node-mysql#1152]
Or am I doing something wrong? This simple code eats up to 2GB RAM:

```javascript
var mysql = require('mysql');

var conn = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'dbname',
    charset: 'utf8'
});

var data = {
    date: '2015-07-15',
    engine: 'google'
};

for(var i=0; i<1000000;i++){
    data['site_id'] = i;
    conn.query('INSERT INTO tablename SET ?', data);
    console.log('insert n', i);
}
```
![pm2-monit](https://cloud.githubusercontent.com/assets/1500502/8697066/a9a6fd3c-2afa-11e5-8361-11579301aacc.png)

**Comment by sidorares** [comment]
you doing it wrong. You insert 1000000 commands into command queue before any network IO even starts

**Comment by miriti** [comment]
@sidorares Do you mean that connection should be established first? Documentation says that connection will be established be invoking the query.. anyways I changed the code like this:

```javascript
var mysql = require('mysql');

var conn = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'qaces',
    charset: 'utf8'
});

conn.connect(function(err) {
    if(err) throw err;

    var data = {
        date: '2015-07-15',
        engine: 'google'
    };

    for(var i=0; i<1000000;i++){
        data['site_id'] = i;
        conn.query('INSERT INTO STATSerp SET ?', data);
        console.log('insert n', i);
    }
});
```

Same result...

**Comment by miriti** [comment]
Okay.. I've changed my code like this:

```javascript
    var i = 0;

    var insertData = function(err) {
        if(!err) {
            if(i++<1000000) {
                conn.query('INSERT INTO STATSerp SET ?', data, insertData);
                console.log('insert ', i);
            }
        }
    }

    insertData();
```

And now there is no memory issues... I think I got it.

**Comment by sidorares** [comment]
All your code ( and any JS code in node ) is synchronous. All async stuff happens when you leave control back to event loop ( e.i exit your execution path ). That way you allow IO to be "executed" in parallel. But because IO is external to your code it's not "execution" in parallel - event loop helps you to organise code flow to _wait_ for as much as possible in parallel

**Comment by miriti** [comment]
I didn't realize that... Thank you! Sorry for bothering :)

**Comment by sidorares** [comment]
no problems, you actually figured it out yourself in your last example
