### ISSUE TITLE
createCredentials() is deprecated, use tls.createSecureContext instead

### ISSUE THREAD

**Issue by rogierschouten** [felixge/node-mysql#1154]
It seems that the createCredentials() method is deprecated. I'm not sure if this is the same as #737 as the suggested solution that pops up when you use Node 0.12 is different

**Comment by rogierschouten** [comment]
Hint: other libraries use the following code to switch between Node 0.10 and 0.12:

```
 if (tls.createSecureContext) {
      credentials = tls.createSecureContext(config.options.cryptoCredentialsDetails);
} else {
      credentials = crypto.createCredentials(@config.options.cryptoCredentialsDetails);
}
```

**Comment by dougwilson** [comment]
Hi! What version of this library are you using? With the latest version of this library and Node.js 0.12 I don't get that warning. Can you perhaps make a PR?

**Comment by rogierschouten** [comment]
Sorry, I see in the code that your package already has an if-statement prior to the createCredentials() call. Another package generated the warning. I just searched all code for createCredentials().

**Comment by dougwilson** [comment]
You can start your node program with trace deprecation in the future, to know where the warning is coming from:

    node --trace-deprecation program.js
