### ISSUE TITLE
How can I shut down my node app instantly if mysql is offline?

### ISSUE THREAD

**Issue by McFarts** [felixge/node-mysql#1160]
For example, I am using this to detect when the mysql server is offline.

For my game, I NEED MYSQL running and if it doesn't, my app needs to shut down.

```
function handleDisconnect() {
  setTimeout(handleDisconnect, 2000);
  db.on('error', function(err) {
    console.log('db error', err);
  //shut down server
  });
}
handleDisconnect();
```

But, I don't want to be using setTimeout, I was wondering if it's possible to check it instantly?

**Comment by AdriVanHoudt** [comment]
afaik just do the `db.on` when the error event is emitted it will call the listener

**Comment by McFarts** [comment]
Adri, can u give an example please? Thanks

**Comment by sidorares** [comment]
just something simple like
```js
 db.on('error', process.exit.bind(process, -1));
```

**Comment by McFarts** [comment]
Oh, hey sideorares,

Yeah, I tried that, but I'm getting:

http://i.gyazo.com/293da526453f97ec0a0318c9240f3aec.png


I'm using

```
function handleDisconnect() {
  setTimeout(handleDisconnect, 2000);
  	console.log('checking for errors');
   db.on('error', process.exit.bind(process, -1));
   
   
}
handleDisconnect();

```

Any idea?

**Comment by sidorares** [comment]
that's because you add event listener every 2 seconds. Why do you need that? As @AdriVanHoudt suggested, do this only once as simple `db.on('error', yourCleanupAndExitHandler)`;

**Comment by McFarts** [comment]
Oh, didn't know the .on method acts as an event listener.

I do it every 2 seconds because I need to somehow check dynamically if the DB is down.

When someone connects to the WS server they can stay idle in a game not send any commands, but I need something to check when mysql goes down to disconnect them.

**Comment by sidorares** [comment]
You just add a handler every 2 seconds, and not checking for server state with `db.on('error', handler)`

The 'error' event is fired immediately when there is unexpected end of tcp stream. This is not 100% reliable and time when reported differ based on various settings of your tcp stack

If you need more control, try to issue simple query ( or `ping()` command ) every 2 seconds and treat "took more than a second to respond" as error

**Comment by McFarts** [comment]
Oh i know the issue.. I'm using a pool.. Hmm

**Comment by McFarts** [comment]
@sideorares, I think this solution is best for me cause I'm using pooling.

```
setInterval(function(){
	
db.query('SELECT 1', function(err) {
		if(err){
			process.exit(1);
			//We have a big issue here boys
		}
});

}, 2000);
```

My problem is, is this bad? Will it kill performance?

**Comment by sidorares** [comment]
You want to exit even if one single connection fail? Why are you using pool in that case?

**Comment by McFarts** [comment]
Well, I'm only wanting to check if the MYSQL server is offline :P So that works as if I shut down the server (mysql) and wait 2 seconds, it will exit node which is what I want. I just don't know if the 2 second interval will have performance issues ~
