### ISSUE TITLE
How can we detect when mysql is too busy writing to a .MYD file?

### ISSUE THREAD

**Issue by McFarts** [felixge/node-mysql#1163]
For example, see this:

```

	for(i=0; i < 25005;i++){
	
				    db.query('INSERT INTO rpg_user_items SET ?', item_data, function(err, results) {
						//console.log(err);
					});
	}
```

and my item_data is:

```
var item_data = {
    //itemid: 431,  unique index...
    rpg_items_id: C_ITEMS[item_id],
    user_id: user.RPG.user_id,
    rpg_character_id: user.RPG.character_id,
    slot_position: first_open,
    item_equipped: 0,
    item_baselife: 0,
    item_upgradelevel: 0,
    item_addstr: 0,
    item_adddex: 0,
    item_addint: 0,
    item_addvita: 0,
    item_adddefense: 0,
    item_addquality: 0,
    item_addmf: 0,
    item_quantity: 5,
    item_addlifepercent: 0,
    item_addlightningresist: 0,
    item_addfireresist: 0,
    item_addcoldresist: 0,
    item_usable: 0,
    item_bound: 0,
    item_cooldown: 0,
    item_sockets: 0,
    item_mindmg: 0,
    item_maxdmg: 0,
    item_dmgpercent: 0,
    item_intransit: 0,
    item_inmarket: 0,
    item_identify: 0,
    item_ilvl: 0
}
```

It takes roughly 15 or 20 seconds to fully complete over 25,000 insertions on my computer.

But, while MYSQL IS performing this... MYSQL cannot be used [in other instances](http://i.gyazo.com/f1efe53e3391450cedf0578a2763097e.png) ( a back log if you will), so how do I detect that MYSQL is still busy (processing), in the second parameter?

```
db.query('QUERYE', function(){
//Need to check here IF MYSQL IS BUSY for processing so I can tell the user we are processing high server load, etc
});
```

Thanks!

AS pertinent to this:
http://stackoverflow.com/a/11615095/1254837

I think I need to use INNODB instead? So it doesn't lock the table.

**Comment by dougwilson** [comment]
Hi! Unfortunately this low-level form of detection is not likely going to happen by this driver module, but you may be able to achieve something using some kind of system status query. This is probably beyond anyone here, but a question to Stackoverflow.com would probably serve best :)

**Comment by McFarts** [comment]
Yeah weird.. If I put the query in a for loop that iterates 25,000 times it starts to lock up.
but, if I put a db query inside a setTimeout call with 0 set as miliseconds, I get thousands of queries generated instantly and there is no lock up... weird
