### ISSUE TITLE
Timeouts does not abort query execution on mysql server

### ISSUE THREAD

**Issue by euglv** [felixge/node-mysql#1164]
https://github.com/felixge/node-mysql#timeouts

If I execute the following code several times:
```javascript
connection.query({sql: 'SELECT SLEEP(200)', timeout: 10}, function (err, rows) {
  if (err) {
    console.log(err);
  }
});
```
I see PROTOCOL_SEQUENCE_TIMEOUT errors in log, but if I run query `show full processlist` I see several queries `SELECT SLEEP(200)` continue running on mysql server.

Is there any possibility to abort query execution on mysql server?

**Comment by dougwilson** [comment]
Unfortunately this is a limitation of the MySQL protocol; the only way to abort the underlying query is to create a second connection with super privs and run a KILL on the query you want to abort.

The limitations are outlined in the documentation at https://github.com/felixge/node-mysql#timeouts

> It is important to note that these timeouts are not part of the MySQL protocol, and rather timeout operations through the client. 

If you can help expand this text to describe this, that would be most welcome :)!

**Comment by euglv** [comment]
I don't think that this is limitation of mysql protocol. 
When I use, for example dbForge Studio for MySQL, I can run there `SELECT SLEEP(200)` query then press "stop" button. After that running `show full processlist` doesn't show any `SELECT SLEEP(200)` query. May be  dbForge Studio for MySQL is using binary protocol to communicate with mysql server.

**Comment by dougwilson** [comment]
It's possible, or perhaps dbForce Studio is keep multiple connections and doing a `KILL` (if this is the case, you'd have to implement this yourself with this module). If it's doing something at the protocol level, then a PR is welcome, but we've looked into this extensively and could not figure out any way to do it without using two connections (which is beyond this module, which is low-level).

**Comment by dougwilson** [comment]
Ok, so I'm going to close after reading your comment at https://github.com/sidorares/node-mysql2/issues/185#issuecomment-125806391 . Let me know if you would like this re-opened, though, and I can.
