### ISSUE TITLE
The db.query function hangs when mysql is busy

### ISSUE THREAD

**Issue by McFarts** [felixge/node-mysql#1165]
How can we detect this?

For example, I'm inserting over 15,000 rows into my table for testing purposes, I refresh the browser to starting another query, and anything inside my db.query() function doesn't get executed until ALL these inserts are completed? It just hangs.

I'm using innodb as well, switched from MYSIAM. And using pooling as well ~

Any idea? I could atleast check to see if it's busy and give the user a error warning message that we're experiencing high server load.

**Comment by ravi** [comment]
Code inside your db.query() would be code, I assume, in your callback... in which case it will not get executed until the query is done, yes?

**Comment by McFarts** [comment]
> Code inside your db.query() would be code, I assume, in your callback... in which case it will not get executed until the query is done, yes?

Yeah, but I want to detect that somehow so I can tell users that the system is experiencing high load

**Comment by ravi** [comment]
Sorry, I think I should first try to understand your problem better. You inserting 15000 rows in query Q1 and the db.query() for that query has a callback CB1. CB1 will not be called until all 15000 rows are successfully inserted. While that is going on, you refresh your browser -- i.e., reload the web page? -- and this starts a new query... Q2... and that hangs?

**Comment by McFarts** [comment]
Not really let me try to explain better.

I am just testing the performance with mysql and doing a db.query('INSERT'); with no callback 15000 times.  While this insert is still finishing, (if a user tries to access a function inside of any OTHER db.query) they cannot.  As the db.query function hangs until those 15000 rows are completed.

I'm trying to find a way to detect that so I can tell the user we're experiencing high-load.

**Comment by McFarts** [comment]
Found it

waitForConnections: Determines the pool's action when no connections are available and the limit has been reached. If true, the pool will queue the connection request and call it when one becomes available. If false, the pool will immediately call back with an error. (Default: true)
