### ISSUE TITLE
Error when using a non default port for the connection

### ISSUE THREAD

**Issue by DSigmund** [felixge/node-mysql#1168]
"database":{
			"server":"localhost",
			"port":6033,
			"user":"B3-Promo",
			"password":"",
			"database":"mis"
		},

		var connection = mysql.createConnection({
			host: conf.database.server,
			user: conf.database.user,
			password: conf.database.password,
			database: conf.database.database,
			port: conf.database.port,
			connectTimeout: 15000
		});
I get the following error:
` ER_DBACCESS_DENIED_ERROR: Access denied for user ''@'localhost' to database 'mis'`

I am using the newest Version of node-mysql.

I mapped the database via ssh:
` ssh -L 6033:localhost:3306 mis@hf-mis03.hf.brnet.int`

**Comment by sidorares** [comment]
the error itself means that you can connect to server, you just need to give access user ''@'localhost' ( double check credentials - is it empty string you want to use as user name? ) and check that this user has access to 'mis' database. From server point of view you connecting from localhost to a standard port 3306

**Comment by DSigmund** [comment]
`( double check credentials - is it empty string you want to use as user name? )`  
No, as i have my config posted above... i want the User "B3-Promo" to connect, as given in the parameters of the createConnection()-function...
  
I know the current way i am connecting:  
`CLIENT --> 6603 --> SSH <-- 3306 <-- SERVER`  

But this should be no problem, as i node-mysql should believe, there is a local server with the port 6603...

And the Error states that i try to the localhost with no user.  
What i really do (after i changed localhost in the config to 127.0.0.1):  
`B3-Promo:@127.0.0.1:6033/mis`

**Comment by sidorares** [comment]
does the same code runs with no errors on the server if you change port to 3306 and host to 127.0.0.1? (  note that config field for this is `host`, not `server` )

**Comment by DSigmund** [comment]
It then runs correctly, trying to connect to the local mysql server (as
expected).

Of course, the User does not work there.

Andrey Sidorov <notifications@github.com> schrieb am Fr., 31. Juli 2015 um
14:13 Uhr:

**Comment by sidorares** [comment]
> Of course, the User does not work there.
what do you mean?

**Comment by DSigmund** [comment]
Well, i defined a user, password, database combination for the database i
am trying to reach via a ssh-tunnel.
this is why i am using not port 3306.

on 3306 is a local mysql-database running, where my combination does not
exist.

Problem still remains, that the user is not used when having another port
than 3306

Andrey Sidorov <notifications@github.com> schrieb am Mo., 3. Aug. 2015 um
08:19 Uhr:

**Comment by sidorares** [comment]
Can you ssh to a server and run simple node script there? The question was, can you connect to a 127.0.0.1:3306 when you run script on the same server as database ( hf-mis03.hf.brnet.int ) ?

**Comment by DSigmund** [comment]
Ah OK, sry read it wrong.

Yes, that works.



Andrey Sidorov <notifications@github.com> schrieb am Mo., 3. Aug. 2015 um
08:24 Uhr:

**Comment by biels** [comment]
This should get closed

**Comment by sidorares** [comment]
@biels this is not resolved yet, "Yes, that works" is about running script on the same server as db, we are investigating behaviour "remote db + connect to local ssh forwarded port"

**Comment by DSigmund** [comment]
You could even formulate it more simple:

If connecting to non-default port using user but no password, the user is
not used to connect

Andrey Sidorov <notifications@github.com> schrieb am Di., 4. Aug. 2015 um
02:36 Uhr:

**Comment by dougwilson** [comment]
@DSigmund @sidorares this issue has become quite stale. I'm going to close it, but let me know if it should be re-opened and if there is any additional information we can act on (and if it's even an issue this module can address).
