### ISSUE TITLE
Results are not letting me get object literal data.

### ISSUE THREAD

**Issue by McFarts** [felixge/node-mysql#1169]
For example when selecting this field from mysql:

http://i.gyazo.com/8f00936448dfe46ef0d72ed7b4d6c7d5.png

It's not letting me use it as object literal, it keeps putting a quote infront of it and after it, resulting in:

http://i.gyazo.com/f54ddf11136701809a3bada90b26279d.png

Any idea? (When the second s/s should say Object)

**Comment by sidorares** [comment]
Can you show schema of that table? This driver does very little data conversions, if you have string in your column you'll get it as string, not JSON-parsed object. There is a way to do custom type cast, see documentation at the end of https://github.com/felixge/node-mysql#type-casting

**Comment by McFarts** [comment]
Hey Sidorares,

Yeah sure: http://i.gyazo.com/7f1bd0f0448352070b932f289168a09b.png

4th one from the bottom up

It's set as a char data type is that why?

**Comment by sidorares** [comment]
yes, it's a string an a database. Why should driver connect it to an object?
And Id rather just add `JSON.parse` in the app code, not in db config / typeCast

**Comment by McFarts** [comment]
Hmm, it's not working

```
var AuthenticationQuery = {sql:'SELECT u.*, g.*, rpg.*, o.logged, o.idle FROM users AS u INNER JOIN groups AS g ON u.group_id=g.g_id LEFT JOIN online AS o ON o.user_id=u.id LEFT JOIN rpg_characters AS rpg ON rpg.user_id=u.id AND rpg.character_id=u.selected_characterid WHERE u.id = '+db.escape(user_id)+' AND u.password = '+db.escape(user_password)+'', typecast:false};
	db.query(AuthenticationQuery,  function(err, results){
console.log(typeof results[0].equipped);

});

Still echo's string.

**Comment by McFarts** [comment]
I have to use it as an object literal though, I don't JSON.parse it because it's still literal and I save data from not using double quotes across websockets :)

**Comment by sidorares** [comment]
just adding `typecast:false`, read docs until the end - `typeCast` needs to be a function

**Comment by McFarts** [comment]
Yeah, my bad. I typed typecast wrong. It's `typeCast`

Anyways, here is what is being displayed:

http://i.gyazo.com/75bd66b0fde52d03c54c9f3c0c03e18a.png

The fucking object is still in strings even with typeCast disabled.. LOL WOW.

**Comment by sidorares** [comment]
updated previous comment a bit. You need to do something similar to example in the docs:

```js
connection.query({
  sql: '...',
  typeCast: function (field, next) {
    if (field.name === 'equipped') {
      try {
        return JSON.parse(field.string());
      } catch(e) {
        return null; // not sure what would be the best way to report malformed json, but try/catch is importsant here
      }
    }
    return next();
  }
});
```

**Comment by dougwilson** [comment]
I'm going to close the issue, though discussion can continue. As @sidorares says, you have to add some kind of type conversion if you want it to read back as an object. Basically, MySQL only understands it's own types. Your column, for example, is a char, so we're only ever going to give it back to you as that: a string.

To form that string you put into MySQL you did something for the object -> string conversion. What @sidorares is saying is you're going to have to implement the corresponding string -> object conversion you need and then put that into the `typeCast` function.

**Comment by McFarts** [comment]
Sweet, no problems! Thank you Doug for the help!!  I wonder if MYSQL will support an object data type in the future though, would make it easier!

**Comment by dougwilson** [comment]
Yea, it would :) I know Postgres has a "JSON" type now, which is basically that: store some kind of object in the db and it'll be automatically inflated/deflated. I would also like that feature to exist in MySQL :)

**Comment by sidorares** [comment]
@dougwilson  it's much more than inflation/deflation for postgres - you can have individual object fields indexed

**Comment by McFarts** [comment]
If i were to switch to postgres.. this plugin wouldn't work with it right? I learned and been using this plugin forever I wouldn't want to leave it haha.

**Comment by sidorares** [comment]
@McFarts this is a low level layer that implements binary mysql wire protocol (and PG protocol is completely different). You can use some kind or ORM library that allows you to choose underlying driver ( I used [node-orm2](https://github.com/dresende/node-orm2) on some projects together with mysql and postgres )

**Comment by McFarts** [comment]
Sweet, thanks for the info @sidorares

**Comment by McFarts** [comment]
BOOM! Just found the best solution!!

```
eval('var EQD = '+results[0].equipped);
``

Then I apply that EQD to whatever.

Finally!

And trust me, EVAL is fine because this data cannot be manipulated by the user. (equipped field is never touched by the user).
