### ISSUE TITLE
bulk insert not working

### ISSUE THREAD

**Issue by maeishoj** [felixge/node-mysql#1170]
Hey everyone, 

I need to do bulk insert and was trying to do as outlined in #230 .

However it does not work for me :(

I get the following error:
```
'INSERT INTO `myTable` (\'a\', \'b\', \'c\', \'d\', \'e\', \'f\', \'g\', \'h\', \'l\') VALUES (\'667750695845051\', 330, 2637, 1609, 77, 1436652000000, 1893, 1434060000000, \'9851970837621556\'), (\'534182666343258\', 1993, 1798, 2201, 82, 1436652000000, 2569, 1434060000000, \'0354893586110173\'), (\'334225310280525\', 708, 993, 2592, 88, 1436652000000, 1426, 1434060000000, \'2821794011330095\')' }

<-- ErrorPacket
{ fieldCount: 255,
  errno: 1064,
  sqlStateMarker: '#',
  sqlState: '42000',
  message: 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'a\', \'b\', \'c\', \'d\', \'e\', \'f\', \'g\', \'h\', \'l\ at line 1' }

error adding mcu:  { [Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''imei', 'reporting_interval', 'sleep_interval', 'alarm_triggered_reporting_inter' at line 1]
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0 }
response: undefined
```
I have objects in nodejs representing the entities / tables. Normally I just added them by "INSERT INTO ?? SET ?" where ?? is the table and ? the json obj directly.

However to follow the example, I do:
1) Object.keys(myObj) to retrieve the columns
2) Object.values(myObj) to retrieve the values

I did make it work by writing the columns manually, but I would like to have it more "flexible".

Any suggestion?

**Comment by dougwilson** [comment]
Hi! I'm not sure right now, but your error does not correspond to the query you provided. Can you provide the exact query and the corresponding error for that query? When they don't match like above, the error is not very meaningful to assist off of :(

It may be very important to note how MySQL's SQL syntax works for bulk inserts: you have to list the column up front and then every row you insert must include all those column exactly; the columns per row cannot vary.

**Comment by maeishoj** [comment]
hi dough, The query is exactly as I executed it, i am not sure why you think it does not correspond.. I only changed the table name, and the columns name because they are not essential to the problem and did not want to share my application's DB details.

The fields did not vary and always corresponded to the columns, so much so that the way this worked, is by me typing the column names manually in the query string and then inserting the values as an array of arrays(of strings). This way worked. So the only difference is actually in the entering column names without having mysql adding \' columnName \' i guess. I tried both using my object skeleton via Object.keys(myObj).toString() which returned a string of comma separated property which i then fed to my query string, as well as by iterating through the keys and manually creating the string. neither worked.

**Comment by dougwilson** [comment]
The reason I said you didn't include the original query is because you didn't; you can see the error you provided above says

> syntax to use near \'\'imei\'

Well, I see no text "imei" at all in the query you provided, so I don't have anyway to see what specifically the syntax error is that is occurring...

**Comment by maeishoj** [comment]
oh i see, :+1:  thats' just me that forgot to replace the names everywhere.  anyway you made me see where the problem is (i.e. the order of the columns). Thanks a lot!

**Comment by dougwilson** [comment]
Ah, glad you got it sorted out :) I tried to look at the provided query, but the syntax error was not popping out at me and since it didn't happen to match up, I didn't know if I was just overlooking it or something.
