### ISSUE TITLE
Cannot read property 'end' of unedfined

### ISSUE THREAD

**Issue by Stackoverload** [felixge/node-mysql#1172]
Query: function(string, fn) {
		this.connection.query(string, function(err, rows) {
			if(err) { console.log(err); fn(null); this.connection.end(); }
			else {
				fn(rows); 
				this.connection.end();
			}
		});
	}

My Query function runs the Query perfectly, but I cannot end the connection afterwards.

**Comment by dougwilson** [comment]
Hi! This is a common mistake when first learning JavaScript :) Inside another function (like the callback), the "this" is not the same as in the other function unless you use bind. The best thing to do is simply store the other this in a variable and reference that variable from in the callback:

    Query: function(string, fn) {
        var that = this;
        this.connection.query(string, function(err, rows) {
            if(err) { console.log(err); fn(null); that.connection.end(); }
            else {
                fn(rows); 
                that.connection.end();
            }
        });
    }
