### ISSUE TITLE
MySql Null integrer fields are returned with value 0

### ISSUE THREAD

**Issue by omerko** [felixge/node-mysql#1174]
I stumbled into this when I saw I am not getting null values from my integer fields into node.js
while I do get null values for string DB fields.

The specific type I'm getting is NEWDECIMAL

Is there a way to workaround this using the typeCast option?

**Comment by omerko** [comment]
Sorry, my bad, it's an issue not related to the package

**Comment by dougwilson** [comment]
Ah, thanks for the update. Feel free to let us know if you have any other questions!
