### ISSUE TITLE
Is there any way to see last query ?

### ISSUE THREAD

**Issue by enGMzizo** [felixge/node-mysql#1176]
Hello , 
I tried to execute some SQL but I get unexpected results , due to unexpected escaping , the question is : 
Can I read the last query value after escaping ? 

Thanks

**Comment by dougwilson** [comment]
Hi! The .query method returns a Query object and you can print the .sql property:

    var query = conn.query(...)

and then later, when you want to see the escaped query:

    console.log(query.sql)

**Comment by enGMzizo** [comment]
Thanks a lot.
