### ISSUE TITLE
Connection Query Callback has no Rows

### ISSUE THREAD

**Issue by randomsilo** [felixge/node-mysql#1181]
I am struggling to get rows back from the mysql package.

Can you tell me what I am doing wrong?

I tried with 2.7.0 and 2.8.0

=== npm-mysql-tests.js ===
```js
var expect = require('expect.js')
    , mysql = require('mysql');

describe('Npm-MySql-Testing', function() {

    it('Query', function() {

        var pool =  mysql.createPool({
            host: 'localhost'
            , port: 3306
            , user: 'root'
            , password: 'PASSWORD'
            , database: 'DATABASE'
            , waitForConnections: true
            , connectionLimit: 100
            , queueLimit: 10
        });

        pool.getConnection(function(err, connection){
            connection.query('SELECT (1+1) AS solution', {}, function(err, rows, fields) {
                if( err) {
                    console.log('Error while performing Query.');
                }

                // Never Shows
                console.log(rows);

            });

            connection.release();
        });

    });

});
```

**Comment by dougwilson** [comment]
Hm, I'm not sure. I see a few possibilities:

1. You are calling `connection.release()` too early--you should be waiting until you're done with the connection, i.e. the call should be inside the callback to `connection.query` instead of outside it.
2. I'm not familiar with the testing library you are using, but how does the test know you are performing an async action? Typically your testing library should be requiring you to call `done()` or something within the `connection.query` callback.

**Comment by randomsilo** [comment]
First, let me say thanks for responding.  I really appreciate you getting
back to me.  My company is experimenting with the node stack.  The fact
that you contacted me on a Sunday with suggestions is amazing.  You are
representing the node community in an extremely positive way.

I didn't realize that testing async in mocha required the done function as
the second parameter in the "it" section.  My code is at work; I will hit
it first thing in the morning.   You may have just solved my problem.  I
really appreciate you taking the time to help me.  I am so close to getting
my persistence service to work. Thank you for the assist.

**Comment by dougwilson** [comment]
It's no problem! Now that I know it's mocha, I'll try to run your example there to see what happens on my machine and see what I can find out for you :)

**Comment by dougwilson** [comment]
So some testing looks like what is happening is mocha is force shutting down the Node.js app if it thinks all the testing is complete (which is usually not how Node.js works, where usually all pending actions have to be completed before the app shuts down). The changes for the simple test above would be as follows:
```js
var expect = require('expect.js')
    , mysql = require('mysql');

describe('Npm-MySql-Testing', function() {

    it('Query', function(done) { // <-- the done argument tells mocha this is an async test, not completed until done() is called

        var pool =  mysql.createPool({
            host: 'localhost'
            , port: 3306
            , user: 'root'
            , password: 'PASSWORD'
            , database: 'DATABASE'
            , waitForConnections: true
            , connectionLimit: 100
            , queueLimit: 10
        });

        pool.getConnection(function(err, connection){
            connection.query('SELECT (1+1) AS solution', {}, function(err, rows, fields) {
                connection.release(); // <-- call release here

                if( err) {
                    console.log('Error while performing Query.');

                    done(err); // and then, you usually want to "handle" the error, which mocha lets you pass to done
                    return; // and stop executing this function; you can alternatively omit this and put everything after this in an "else"
                }

                console.log(rows);

                pool.end(done); // because this makes a new pool, you'll also want to clean it up when done by calling pool.end and just give "done" as the callback for pool.end
                // done(); // if you didn't want to end the pool, you'd just call done() here
            });

            //connection.release(); // <-- rather than here
        });

    });

});
```

**Comment by randomsilo** [comment]
Created a new droplet, installed MySql 5.7, and built a new test case with
your code. Your solution works flawlessly.  I really appreciate the quick
turn around.  You sir are a rock star.  Thanks again.

**Comment by dougwilson** [comment]
It's no problem! I hope the comments I added to the code helped as well :) Please feel free to open issues whenever you have a question/issue :)
