### ISSUE TITLE
DATETIME casting for UTC

### ISSUE THREAD

**Issue by Ting-y** [felixge/node-mysql#1182]
DATATIME column only return local time which is return the result of new Date()

Is there will any ways to not cast the specific column?

**Comment by dougwilson** [comment]
Hi @Ting-y ! So we have various options that allow you to change the behavior of how this module interprets DATETIME columns:

Documentation from https://github.com/felixge/node-mysql#connection-options

* Setting the value of the `timezone` option to `"Z"` will tell this module your server uses UTC and then created `Date` objects in the correct timezone.
* Setting the value of the `dateStrings` option to `true` will simply not convert them to `Date` objects and instead just pass-through the strings provided from your MySQL server.
* If all else fails, you can use the `typeCast` option to implement your own custom behavior.

**Comment by Ting-y** [comment]
Thanks for quick response! I added the dateStrings to option and its working perfect now!

**Comment by dougwilson** [comment]
No problem!
