### ISSUE TITLE
Bug with Bulk Inserts?

### ISSUE THREAD

**Issue by m-reiniger** [felixge/node-mysql#1189]
Hi,

I was stumbling over this issue today, when I tried to make Bulk Inserts working. I might be totally off here by missing something. Please correct me if I am wrong.

The Problem:

if I do an insert query like the following: 

```javascript
con.query('INSERT INTO table (...) VALUES ?', [ [1,2], [3,4] ], ...);
```
I expected it to insert 2 rows into table. Instead it gave me an SQL Syntax Error.
The SQL it created looked like this:

```sql
INSERT INTO table (...) VALUES 1, 2
```

First Issue: the brackets around my values where missing.
Second Issue: only the first set of data was inserted into the SQL Statement.

After I did a little digging in the Code, I came across this part in SqlString.js:

```javascript
SqlString.format = function(sql, values, stringifyObjects, timeZone) {
  values = values == null ? [] : [].concat(values);

  var index = 0;
  return sql.replace(/\?\??/g, function(match) {
    if (index === values.length) {
      return match;
    }

    var value = values[index++];

    return match === '??'
      ? SqlString.escapeId(value)
      : SqlString.escape(value, stringifyObjects, timeZone);
  });
};
```

I see two Problems here with Bulk Inserts:

First: If I have only one '?' in my SQL Statement, only the first value set is beeing used.

Second: Since in this case, a part of the value array, and not the whole array is passed onto escape(), the arrayToList function actually never being called with a nested array and has no chance to do its magic. :)

```javascript
SqlString.arrayToList = function(array, timeZone) {
  return array.map(function(v) {
    if (Array.isArray(v)) return '(' + SqlString.arrayToList(v, timeZone) + ')';
    return SqlString.escape(v, true, timeZone);
  }).join(', ');
};
```

I could work around this Problem by adding another dimension to the values Array:

```javascript
con.query('INSERT INTO table (...) VALUES ?', [[ [1,2], [3,4] ]], ...);
```

But this looks not like it should look. At least not like it is stated in the documentation.

**Comment by dougwilson** [comment]
```js
con.query('INSERT INTO table (...) VALUES ?', [[ [1,2], [3,4] ]], ...);
```

Is the correct way.

Here is how that comes into play: the function is `conn.query(sqlString, values, ...)`. The variables `values` is an array where each element of the array corresponds to a `?`. Since your `?` needs to be 2 dimensional, you end up with the following:
```js
var row1 = [1,2]
var row2 = [3,4]
var rows = [row1, row2]
var values = [rows]

conn.query('INSERT INTO table temp VALUES ?', values)
```

This becomes more obvious why `values` is an array when you have more than one `?`:
```js
var row1 = [1,2]
var row2 = [3,4]
var rows = [row1, row2]
var tableName = 'temp'
var values = [tableName, rows]

conn.query('INSERT INTO table ?? VALUES ?', values)
```

**Comment by m-reiniger** [comment]
Yes. That makes sense. Thanks for the clarification.

**Comment by dougwilson** [comment]
No problem!
