### ISSUE TITLE
Does setting the timezone automatically convert retrieved timestamps to the correct zone?

### ISSUE THREAD

**Issue by LordWingZero** [felixge/node-mysql#1192]
I just inserted a record into my DB using CURRENT_TIMESTAMP, from what I understand MySQL will insert the time as UTC. I created a connection object for the nodejs MySQL module and have timezone variable set to 'PST'. One would think that this query:

```javascript
connection.query('SELECT Timestamp FROM message ORDER BY Timestamp DESC LIMIT 1', function(err, rows, fields) {
  if (err) throw err;
  console.log(rows);
});
```

would return the timestamp in the timezone I requested using that config option. This article seemed to suggest the same this as well.
http://iswwwup.com/t/ad37cdae97ed/nodejs-responded-mysql-timezone-is-different-when-i-fetch-directly-fro.html

**Comment by dougwilson** [comment]
Hi! The time zone that `CURRENT_TIMESTAMP` is not inserted in UTC (at least by default), but defaults to the time zone of the system the MySQL server is running on. Your server can have the time zone MySQL server uses changed, so you should consult your MySQL server's settings.

As for what time zone this library converts it to, it's whatever you have your `timezone` connection setting set to (https://github.com/felixge/node-mysql#connection-options). To get everything working right, you need to set your `timezone` setting of this library to exactly the same value that your MySQL server is using.

The `timezone` option does not do anything but allow you to indicate the time zone your server is using; it does not tell your MySQL server what time zone you want to use or anything.

**Comment by dougwilson** [comment]
To expand on this some more, the way MySQL protocol works is that the date/times come across the protocol as simply text strings (and they don't even include the time zone information). This library, by default, will try to expand these strings into a JavaScript `Date` object. In order to do this, this library needs to know what time zone that string from MySQL is in. This is where the `timezone` option comes into play: you tell the library what that time zone is that your MySQL server is sending the date strings as.

**Comment by LordWingZero** [comment]
That clarifies it much much better.

**Comment by LordWingZero** [comment]
What are my options for this issue if my database is distributed across different servers? I dont want to hard code some time changing logic if I can help it.

**Comment by dougwilson** [comment]
It really depends on how you are connecting to those other servers. The configuration is on the connection options, so you can just, for each server's connection options, include the corresponding `timezone` option for that server.

**Comment by LordWingZero** [comment]
Okay, I am going to insert the timestamps with my application code, and ill tell node-mysql what timezone to use instead of relying on the DBMS.

**Comment by lukeavsec** [comment]
I see that this is closed; however I have actually been gotcha'd with this twice (I forgot about what I learned from the first gotcha...), perhaps we could improve the documentation for the timezone configuration option, something like:

`timezone`: Set this to the timezone of the machine running your MySQL server. See issue 1192. (Default: `'local'`).

**Comment by LordWingZero** [comment]
I just resorted to inserting the time stamps manually, it's the easiest
option IMO.
