### ISSUE TITLE
 SqlString.escape  for example: select......from  where content like "%?%"   will be change   like "%'test'%"  sql error

### ISSUE THREAD

**Issue by aaagu1234** [felixge/node-mysql#1193]
sql error

**Comment by tolgaek** [comment]
Can you give code example of how this is happening.it's unlikely they escape is adding quotes

**Comment by dougwilson** [comment]
Hi! So the `?` placeholders are meant to works similar to the placeholders in the MySQL binary protocol. That protocol, just like us, do not allow you to use the placeholders within strings. The difference between us is that we just replace all `?`s in the string, whereas the MySQL binary protocol has a full SQL parser and would have left your string as `'%?%'` and done no replacement.

The solution is what you use for the `?` must be the complete string, or use the `CONCAT` function inside your SQL.

Examples:
```js
conn.query('SELECT * FROM  foo WHERE bar LIKE ?', ['%' + str + '%'])

// or

conn.query('SELECT * FROM foo WHERE bar LIKE CONCAT(\'%\',?,\'%\')', [str])
```
