### ISSUE TITLE
Return an instance of a function

### ISSUE THREAD

**Issue by Petah** [felixge/node-mysql#1194]
If I have a function 

```
function Foo() {
    this.bar = null;
}
```

and a query:

```
SELECT bar FROM foos;
```

can I have results returned as instances of `Foo`?

**Comment by sidorares** [comment]
just create it manually when data is returned? ( and if you have no arguments to constructor or fixed number of arguments just use `new Foo(...)` directly )

```js
conn.query("SELECT bar FROM foos", function(err, foos) {
  var foosHydrated = foos.map( function(f) { return new (Function.prototype.bind.apply(Foo, arguments)); 
  // ...
});
```

**Comment by Petah** [comment]
Hmm ok, was just wondering if there was a builtin way.

I will just 

```
result.map((row) => {
    Object.setPrototypeOf(row, object.prototype);
    return row;
})
```

**Comment by dougwilson** [comment]
Right, nothing is built-in, as this is a very low-level library, while that is a feature more akin to an ORM. You may be able to implement something using the `typeCast` hooks, perhaps.
