### ISSUE TITLE
handleDisconnect does not work

### ISSUE THREAD

**Issue by QuantumMechanics** [felixge/node-mysql#1195]
Hi,

I do not understand what's wrong with my connection, it just can't stay alive more than ~6 hours... 

Basically, my program check every 5 minutes (with setInterval) for user payment requests in the db. 

```
//setInterval function

//DB connection
	var mysql      = require('mysql');
	var connection = mysql.createConnection({
	  host     : _DBhost,
	  user     : _DBuser,
	  password : _DBpassword,
	  database : _database
	});
	connection.connect(function(err){
	if(!err) { 
	    console.log("Database is connected ... \n\n");  
	} else {
	    console.log("Error connecting database ... \n\n");  
	}
	});

function handleDisconnect(myconnection) {
  myconnection.on('error', function(err) { 
    console.log('Re-connecting lost connection'); 
    connection.destroy(); 
    connection = mysql.createConnection({ 
	  host     : _DBhost, 
	  user     : _DBuser, 
	  password : _DBpassword, 
	  database : _database 
	});
    handleDisconnect(connection); 
    connection.connect();
  }); 
}

handleDisconnect(connection);

connection.query('SELECT * from mytable WHERE balance=? AND requested=0 LIMIT 10', [_amount/1000000], function(err, rows, fields) {

	if (rows.length == 0)
	{
	     console.log('No transaction to initiate, waiting...');	
	} else{	
	// Send transaction if meeting rules requirements, Update the user requested bool to 1 then connection.end(). 
```
After some hours working well, I got 10 checks with:
```
Re-connecting lost connection
Database is connected
No transaction to initiate, waiting...
```
Then:
```
Re-connecting lost connection
Error connecting database
```
It shows an error and the program stop:
```
typeError: "cannot read property 'length' of undefined". 
```
It is absolutely necessary for the program to run 24/24 with no downtime, but this keep disconnecting and I have to wait for hours to see if fix I tried worked...

Thanks

**Comment by dougwilson** [comment]
Hi! I'm not sure where you came up with that function, but it seems to have a few problems. In general, for what you are trying to do, you need to use connection pooling built into this library, rather than trying to manage a single connection for infinite time.

You can find some examples for how to use this here: https://github.com/felixge/node-mysql#pooling-connections

Let me know if you have any questions about using the pool :)

**Comment by QuantumMechanics** [comment]
Thanks :) 

Just made the change, waiting now ;)

**Comment by QuantumMechanics** [comment]
Seems that it did work :)

This program never run that long before (almost 16h so far).

Why did I got "Error connecting database" now ?

It still works but after few hours this message started showing up with every check. 

This console.log message is here:

```
pool.getConnection(function(err,connection){
        if (err) {
          connection.release();
          console.log("Error connecting database");
          return;
        } 

	//my queries

});
```

Even if it works there is something wrong.

If you want to look at the actual code: https://github.com/QuantumMechanics/XEMsend/blob/master/XEMsend.js#L123

**Comment by dougwilson** [comment]
> Why did I got "Error connecting database" now ?

Hi! I'm not sure. Can you say what the contents of the `err` variable is when you trigger that log? That will hold the reason for the error.

**Comment by QuantumMechanics** [comment]
It's only showing this message, nothing more regarding the error. I'm going to add ```throw err;``` to see but it will take some hours before it happens.

If I remember correctly, at first when tried to use pools, got ```ECONNREFUSED``` but worked too, maybe i removed the part that was showing it. 

Still beginner on nodejs so.. ^^ I'll let you know

**Comment by dougwilson** [comment]
Ok, sounds good! If you change your `console.log("Error connecting database");` to `console.log("Error connecting database: " + err.message);` that should also help a lot with providing extra information in the message :)
