### ISSUE TITLE
How to use changedRows in OkPacket?

### ISSUE THREAD

**Issue by wilfrem** [felixge/node-mysql#1197]
I wonder about changedRows in OkPacket.js

* changedRow is not affectedRows.
* node-mysql fetch changedRows from OkPacket.message.
* but it seems message always empty, so changedRow always 0.

https://github.com/felixge/node-mysql/blob/master/lib/protocol/packets/OkPacket.js#L25

So, when and how to use changedRows value?

**Comment by dougwilson** [comment]
All that does is parse the message, and doesn't have anything to do with the MySQL protocol, so I'm not sure. Looking through the history of this repo, it was added from https://github.com/felixge/node-mysql/issues/251

If that doesn't help explain what it does, then I'm at a loss :)

**Comment by dougwilson** [comment]
Hi @wilfrem , I have not heard back from you since my post, so I'm going to close this issue as resolved. Please let me know if you're still having issues!
