### ISSUE TITLE
Strange behaviour with Date.now()

### ISSUE THREAD

**Issue by NikosEfthias** [felixge/node-mysql#1198]
I keep last operation time in miliseconds in db.

Everything is fine however when i monitor the process through node-inspector timestamp is right but when it is saved into db it turns into this value 2147483647

Which is equal to Sun Jan 25 1970 23:31:23 GMT+0300 (MSK)

Column is formatted as int(20) i cant understand why it happens this way

**Comment by dougwilson** [comment]
The number 2147483647 is the maximum positive value for a 32-bit signed binary integer. `Date.now()` currently returns 1440687263761, which is bigger. You need to use a BIGINT to store something larger than an integer.

**Comment by NikosEfthias** [comment]
ah thank you
