### ISSUE TITLE
TypeError: '[object Object]' is not a constructor

### ISSUE THREAD

**Issue by shaunymca** [felixge/node-mysql#1201]
I'm getting the following error trying to connect to mysql: 
```
/Users/smcavinney/Documents/My Documents/app/node_modules/mysql/lib/Connection.js:1
  /Users/smcavinney/Documents/My Documents/app/node_modules/mysql/lib/Connection.js:420
TypeError: '[object Object]' is not a constructor (evaluating 'new Connection({config: new ConnectionConfig(config)})')

  /Users/smcavinney/Documents/My Documents/app/node_modules/mysql/index.js:12 in createConnection
  test.js:9
```
relevant code is below:
```
var Q = require("q");
var page = require('webpage').create();
var mysql = require('mysql');

var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'shaun',
  password : 'voicepassport',
  database : 'jokes'
});
```

**Comment by dougwilson** [comment]
That's so weird, I've never seen that before, Travis CI is not having that issue, etc. What version of Node.js are you using?

**Comment by dougwilson** [comment]
The error string "`TypeError: '[object Object]' is not a constructor (evaluating 'new Connection({config: new ConnectionConfig(config)})')`" looks like it's probably from WebKit. This module is only for Node.js and doesn't work in non-Node.js runtimes, if that is what you are trying to do. You're welcome to make a pull request adding support for a runtime, if you like.

**Comment by shaunymca** [comment]
Ah, I was running this in a phantojs script. I've modified my app, and it is now working, thanks!

**Comment by dougwilson** [comment]
Ah, that makes sense :)

**Comment by stephengoodwin** [comment]
@shaunymca What did you modify to get your app to work?

**Comment by aroramayank2002** [comment]
Facing the same issue with PhantomJS but with bunyan.

`TypeError: undefined is not a constructor (evaluating 'util.inherits(assert.AssertionError, Error)')

  phantomjs://platform/assert.js:84
TypeError: Object is not a constructor (evaluating 'new Emitter()')

  phantomjs://platform/index.js:28
ReferenceError: Can't find variable: process

  phantomjs://platform/bunyan.js:95
TypeError: undefined is not a constructor (evaluating 'bunyan.createLogger')

  phantomjs://code/test07.js:14 in global code
`
