### ISSUE TITLE
createCredentials() is deprecated, use tls.createSecureContext instead

### ISSUE THREAD

**Issue by yagobski** [felixge/node-mysql#1203]
Hy,
I get this error :

createCredentials() is deprecated, use tls.createSecureContext instead

Please fix this in the file :
mysql/lib/Connection.js

line 310 :
 var credentials = Crypto.createCredentials({
      key        : this.config.ssl.key,
      cert       : this.config.ssl.cert,
      passphrase : this.config.ssl.passphrase,
      ca         : this.config.ssl.ca
    });

**Comment by dougwilson** [comment]
What version of this library are you using? We cannot reproduce on the latest version with the latest version of Node.js. The code you are referring to only executes on Node.js 0.10 and below.

**Comment by dougwilson** [comment]
Simply grepping for code does not prove that code is triggering the message. You can start you Node.js with the --trace-deprecation command line option to determine where that message is coming from.

**Comment by dougwilson** [comment]
You can also find more information in #1154 where a user also just did a grep and found our code, but it turned out to be somewhere else and this module was not generating the message.
