### ISSUE TITLE
Does node-mysql pooling support clustering?

### ISSUE THREAD

**Issue by McFarts** [felixge/node-mysql#1206]
Just curious where exactly to put the code? Inside the main `cluster.IsMaster` block, or underneath?

**Comment by dougwilson** [comment]
Hi @McFarts ! So when you use clusters in Node.js, since they are different processes, they cannot easily share state like this. Essentially you have to create a pool in each of your workers (so create the pool when `cluster.isWorker` is true).

**Comment by McFarts** [comment]
@dougwilson  Thank you! Yeah I put them inside the IsWorker block, and now I have 6 proccesses basically running and doing there thing. I can only see a noticable increase in performance once I start getting large amounts of traffic right?
