### ISSUE TITLE
Is there any way to store JSON with ? without all " getting escaped?

### ISSUE THREAD

**Issue by jnbarlow** [felixge/node-mysql#1208]
I'm using the express-mysql-session plugin, and noticed that the JSON it puts into the database is getting escaped.

Here's the code snippit:

```Javascript
data = JSON.stringify(data);

	var sql = 'INSERT INTO ?? (??, ??, ??) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE ?? = VALUES(??), ?? = VALUES(??)';

	var params = [
		this.options.schema.tableName,
		this.options.schema.columnNames.session_id,
		this.options.schema.columnNames.expires,
		this.options.schema.columnNames.data,
		session_id,
		expires,
		data,
		this.options.schema.columnNames.expires,
		this.options.schema.columnNames.expires,
		this.options.schema.columnNames.data,
		this.options.schema.columnNames.data
	];
```

Data Element: 
> {"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}}

Generated SQL:
> INSERT INTO `sessions` (`session_id`, `expires`, `data`) VALUES ('705L-OuRjyiksGE0iosiCj81LOfoxmQo', 1441302828, '{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"}}') ON DUPLICATE KEY UPDATE `expires` = VALUES(`expires`), `data` = VALUES(`data`)

It seems that the JSON string going through ? is causing things to be escaped.  Is there a way to make this not happen (other than changing the query, of course).

**Comment by dougwilson** [comment]
HI! All `?` means is a single value. If you want the express-mysql-session plugin to actually fill in your tables, they can definitely do it, but it would be a feature that library would have to implement. This is a simple low-level driver that just does what libraries like express-mysql-session ask.

If I am misunderstanding the request, please let me know with more details.

**Comment by jnbarlow** [comment]
@dougwilson Somewhat misunderstood :).

So, the code I posted above is how the express-mysql-session plugin is using the mysql driver to save to the database. However, in my case, I'm noticing that the JSON string is being saved with all " escaped to "\ (which makes it invalid JSON, and causes errors when it is read back out).  I was just trying to understand why the construct above was causing that to happen, and if it was intentional.

**Comment by dougwilson** [comment]
It's hard to answer, because it depends on what exactly is adding that backslash. Can you provide some code I can copy, paste, and run on my machine that replicates the issue? I tried the following code and do not have any escaping problems:
```js
var mysql = require('mysql');
var conn = mysql.createConnection();

var str = JSON.stringify({"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}});
conn.query('INSERT INTO `test_db` (`column_name`) VALUES(?)', [str], function (err) {
  if (err) throw err;
  conn.query('SELECT * FROM `test_db` LIMIT 1;', function (err, rows) {
    if (err) throw err;
    console.log(JSON.parse(rows[0].column_name));
  });
})
```
Which works just fine, and the data goes in and comes up without escapes and is parsed just fine.

Doing the SELECT in the MySQL command line:
```
$ mysql
> SELECT * FROM `test_db` LIMIT 1;
{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}}
```

**Comment by jnbarlow** [comment]
@dougwilson That's weird... What you did is pretty much exactly what it is doing.

If you do a con.format() of that query, does it spit out escaped or normal values in the generated query?

**Comment by dougwilson** [comment]
It returns the double-quotes escaped, but that's because it's a MySQL command; for a literal backslash to actually get into the MySQL's column, you would need _two_ backslashes, since that's how escaping with backslashes works.
```
$ node -pe 'require("./index").format("INSERT INTO `test_db` (`column_name`) VALUES(?)",[JSON.stringify({"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}})])'
INSERT INTO `test_db` (`column_name`) VALUES('{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"}}')
```

**Comment by jnbarlow** [comment]
@dougwilson ok, I think that might be the issue then -- my MySQL configuration.  I have 'NO_BACKSLASH_ESCAPE' turned on, and I think that might be causing it.... let me test that real quick

**Comment by dougwilson** [comment]
> I have 'NO_BACKSLASH_ESCAPE' turned on

OH, haha. I didn't even think about that :) Yes, that setting would cause the backslashes to come through as literals.

**Comment by dougwilson** [comment]
https://dev.mysql.com/doc/refman/5.0/en/sql-mode.html#sqlmode_no_backslash_escapes

>  Disable the use of the backslash character (“\”) as an escape character within strings. With this mode enabled, backslash becomes an ordinary character like any other. (Implemented in MySQL 5.0.1)

**Comment by dougwilson** [comment]
At the very least, we need documentation regarding the NO_BACKSLASH_ESCAPE option in the readme for this module.

**Comment by jnbarlow** [comment]
Yeah, that did the trick.  The only issue is that if an app actually needs to insert backslashes, things get complicated real quick.  It IS valid to insert " directly into MySQL, so maybe adding something to not escape a string if it is valid JSON would be a way around it (I know it auto escapes strings now).

I'll let the maintainer of the mysql-express-session also know of the issue.

**Comment by dougwilson** [comment]
The point of using the `?` is to get the backslashes added. If you don't want them added, you need to concatenate strings together and not use `?`.

**Comment by jnbarlow** [comment]
Yeah, I think he was using ? as a way of making it more like a prepared statement.  It could easily be updated to just concat the JSON into the query.

**Comment by dougwilson** [comment]
We escape anything that is delimiters, because people are free to do `sql = 'WHERE column = "' + conn.escape('some "thing" else') + '"'` and we have no way to know if they surrounded us with single or double quotes.

**Comment by jnbarlow** [comment]
That's fair

**Comment by dougwilson** [comment]
Ah. From our documentation in https://github.com/felixge/node-mysql#escaping-query-values we document the `?` as

> This looks similar to prepared statements in MySQL, however it really just uses the same connection.escape() method internally.
