### ISSUE TITLE
mysql restart breaks clusterPool

### ISSUE THREAD

**Issue by tomasz-jomedia** [felixge/node-mysql#1209]
Hi, 

Consider the following piece of code:

```js
var mysql = require('mysql');

var pool = mysql.createPool({
	host: 'localhost',
	user: 'root',
	password: ''
});

setInterval(function() {
	pool.getConnection(function(err, conn) {
		if (!err) {
			conn.query('SELECT 1', function(err, result, fields) {
				if (err) {
					console.error(err);
					conn.release();
				} else {
					console.log('Done')
					conn.release();
				}
			});
		} else {
			console.error('Failed to aquire connection');
		}
	});
}, 1000);
```

If I execute it, and stop/start mysql, pool will reconnect and when mysql comes back resulting in this output:

```
$ node plain.js 
Done
Done
Failed to aquire connection
Failed to aquire connection
Failed to aquire connection
Failed to aquire connection
Done
Done
Done
```

Now, if I setup the connection in a pool cluster with this code:
```
var mysql = require('mysql');

var cluster = mysql.createPoolCluster();
cluster.add('master', {
	host: 'localhost',
	user: 'root',
	password: ''
});

setInterval(function() {
	cluster.getConnection('master', function(err, conn) {
		if (!err) {
			conn.query('SELECT 1', function(err, result, fields) {
				if (err) {
					console.error(err);
					conn.release();
				} else {
					console.log('Done')
					conn.release();
				}
			});
		} else {
			console.error('Failed to aquire connection');
		}
	});
}, 1000);
```
and again stop/start mysql while it is running, the pools in the cluster will never reconnect:
```
$ node cluster.js 
Done
Done
Done
Failed to aquire connection
Failed to aquire connection
Failed to aquire connection
Failed to aquire connection
Failed to aquire connection
Failed to aquire connection
Failed to aquire connection
Failed to aquire connection
Failed to aquire connection
Failed to aquire connection
Failed to aquire connection
Failed to aquire connection
```
Is this a bug, a config issue, or I do not understand something ?

Thanks

**Comment by dougwilson** [comment]
> Is this a bug, a config issue, or I do not understand something ?

Unfortunately, due to some bad history on the pool cluster, it was added to our code base with this behavior. It has since been fixed, but you have to opt-in to the behavior to prevent breaking people.

The options for `createPoolCluster()` can be found at https://github.com/felixge/node-mysql#poolcluster-option with the following the option you want:

> restoreNodeTimeout: If connection fails, specifies the number of milliseconds before another connection attempt will be made. If set to 0, then node will be removed instead and never re-used. (Default: 0)

```js
var cluster = mysql.createPoolCluster({ restoreNodeTimeout: /* your value */ });
```

**Comment by dougwilson** [comment]
Hi @tomasz-jomedia I haven't heard anything back since my post above, so I'm going to close the issue for now as resolved. Please let me know if you're still having issues!
