### ISSUE TITLE
ETIMEOUT when doing zillions of sequential inserts

### ISSUE THREAD

**Issue by dtruel** [felixge/node-mysql#1210]
Hi,

Thanks for making a great plugin!  I've got an error though that seems out of place.

I'm looping through a big text file and inserting the rows into mysql with a `REPLACE` query.  Everything works fine when I do it for a limited number of lines, but when I just let it run, I think it uses all it's processing power queuing inserts, and doesn't actually run them against the DB.  I have a counter that increments when the query insert callback is run.  It accurately says the number of items inserted if I do a small number, but when I just let it run, I get the timeout error:

number of items inserted = 1

Error: connect ETIMEDOUT

This indicates that this error is the first time the callback function was executed.  It seems like what is happening is that nodemysql is getting overloaded with queuing insert queries, and hasn't even executed one.  Or maybe mysql might be getting overloaded.  Either way, something is wrong, and I would appreciate the help in fixing it.

**Comment by dougwilson** [comment]
Hi! What you describe is a common mistake in the Node.js event loop world. Your code is doing too much sync work is the problem. I can help you, but as it involves rewriting your code, we would need you to provide your code to proceed :)

**Comment by dtruel** [comment]
Hi Doug,

I realize that my code does too much sync work.  However this is not for a public facing process, so I thought I could get by ;)  I'm just going through a file I grab and translating it to a db.  This happens once a month on a cron job, so I don't really care if it blocks the IO because there's only one thing I need to run.  It would be nice if there was some way that this accommodated that possibility.  However, I do need it to run, and I appreciate your willingness to help.  


My code goes like this

connection = mysql.createConnection({...});
fs.open('filename', 'r', function(status, fd) {
  var totalNumBytesRead = 0;
  var buffer = new Buffer(100); 
  //go through file one line at a time - each line in file represents a row in mySQL
  while(totalNumBytesRead < fileSizeInBytes){
    //read bytes into a buffer
    //then create query using it
    query = "...";
    //then insert into database
    connection.query(query, function(err,result) {
                if (err){   throw err; }                   
                ++numRecordsInserted;
                console.log("number of records inserted = " + numRecordsInserted)
            });
      }
}

**Comment by dougwilson** [comment]
Gotcha, and that's OK. Unfortunately I cannot help you very much, but the gist is that you have to use Node.js property if you want it to work. If you desire to do sync, you cannot use Node.js, since Node.js does not have sync networking (use the right tools for the right job, as they say).

Otherwise, you have to rewrite your sync `while` to be async. The most popular option is to use https://github.com/caolan/async#whilst

```
connection = mysql.createConnection({...});
fs.open('filename', 'r', function(status, fd) {
  var totalNumBytesRead = 0;
  var buffer = new Buffer(100); 
  //go through file one line at a time - each line in file represents a row in mySQL
  async.whilst(
    function () { return totalNumBytesRead < fileSizeInBytes; },
    function (next) {
      //read bytes into a buffer
      //then create query using it
      query = "...";
      //then insert into database
      connection.query(query, function(err,result) {
                if (err){   return next(err); }                   
                ++numRecordsInserted;
                console.log("number of records inserted = " + numRecordsInserted)
                next();
            });
      },
      function (err) {
        if (err) throw err;
        console.log('done!');
      }
}
```

**Comment by dtruel** [comment]
Hi Doug, why would doing an async while loop fix this?  It seems like it would feed queries into node mysql as a synchronous loop would, and thus would still break it.  Why is this not the case?  My best guess would be that keeping the main thread running somehow blocks the event loop and thus prevents it anything else from going.  But even in that case, could I just spawn another process to handle the inserts?

**Comment by dougwilson** [comment]
I'm not able to provide any real answers, unfortunately, without code. If you feel like you are experiencing a bug in this library, please, by all means open a PR with a fix :) I wouldn't be able to do anything without the ability to reproduce the issue, of course.

If you also don't even want to try out my suggestion, then I'm out of ideas.

**Comment by dtruel** [comment]
Hi Doug, I implemented what you said, but the process just stopped after a second or so.  I couldn't get any output to the console because the main process terminates quickly due to the async function, I believe.  I will take some time to try and figure this out, and if I can't I may just start snooping through the source code.  Thanks!

**Comment by dtruel** [comment]
Fixed!  I was not familiar with how `async.whilst` works, and failed to include or call the `next()` callback.  Thanks for the help, that was the right way to solve it.
