### ISSUE TITLE
Is there a way to automatically activate Promises on error?

### ISSUE THREAD

**Issue by McFarts** [felixge/node-mysql#1212]
For example:

```
.then(db.query('SELECT * from users2', function(error, results){
	console.log(results)
	console.log(error)
	
}))
```

users2 does not exist. And ofcourse the error data will be parsed down through the error parameter.

But... I do not want to be using 'if error, throw this',  on every damn single mysql query.. I have literally tens of thousands of them. i'd rather just have if there is a database error or some sort to return something that will activate promises and stop the chain reaction.  Do you kind get what I'm saying?  Maybe somewhere in the lib I can find something and add it to return a promise error.
Thanks!

**Comment by dougwilson** [comment]
Hi! This module is a low-level driver and currently has no support for promises, only classic Node.js-style callbacks. There are several modules on npm like https://www.npmjs.com/package/promise-mysql that will provide a promise interface to this module.

**Comment by McFarts** [comment]
Oh! This is great! Thanks Doug!
