### ISSUE TITLE
Recently updated node

### ISSUE THREAD

**Issue by McFarts** [felixge/node-mysql#1214]
and now I get

```
connections property is deprecated. Use getConnections() method
```

Whenever I use db.query, any idea? :P Seems odd..

**Comment by dougwilson** [comment]
Hi @McFarts , I don't think we use that in our code anywhere, but to be sure, please run your node executable with the switch `--trace-deprecation` and post back what the stack trace is for that deprecation.

**Comment by dougwilson** [comment]
i.e. `node --trace-deprecation my_script.js`

**Comment by McFarts** [comment]
Wow.

![](https://i.gyazo.com/fb7071f9139c1a2b97ef33a930df65cf.png)

My bad, lol.  Sorrry about that!  Had leftover code floating around
