### ISSUE TITLE
Multiple statements issue

### ISSUE THREAD

**Issue by billyandika** [felixge/node-mysql#1216]
I'm able to generate a page using this code in my js file:
```
router.get('/home', function(req, res) 
{
  connection.query('select * from tableA;', function(err, rows, fields) 
  {
  	if (err) throw err;
 	  res.render('home',{result: rows});
 	  console.log(rows);
  });   
});
```
In my handlebars I am able to get the data using `{{#each result}}`. However, I want to be able to perform more than one select statement. So I did something like this:
```
router.get('/home', function(req, res) 
{
  connection.query('select * from tableA; select * from tableB;', function(err, rows, fields) 
  {
  	if (err) throw err;
 	  res.render('home',{result: rows});
 	  console.log(rows);
  });   
});
```
And this doesn't work, even after setting `multipleStatements = true` in `mysql.createConnection()` and trying to returns `rows[0]` instead of just `rows`.

**Comment by sidorares** [comment]
> And this doesn't work
"doesn't work" == do you get error or just layout or result is not what you expect or you get only last result?

If you really need to perform two selects as part of one single query I'd suggest to create stored procedure.  Also double check that your server ( and your account ) allow MULTI_RESULTS flag

**Comment by billyandika** [comment]
If I put two statements instead of one, the error is `Error: ER_PARSE_ERROR: You have an error in your SQL syntax;`. If I leave it at one statement and try to return `rows[0]`, instead of X entries being shown if I return `rows`, I get 2X blank entries. Will look into the second part of your response.

**Comment by dougwilson** [comment]
Hi @billyandika , can you paste the exact createConnection command you are using (you can exclude host/user/pass), the exact SQL you are trying to execute, as well as the full error message given (the error you provided seemed to be only the first part)?

**Comment by billyandika** [comment]
Apparently I just solved my problem. My previous solution was to perform the `update` query and have it direct to a blank page with just one button, and when you press the button it will return you to the original page but it queries the `select * from` so I can view the original content.

Now the proper solution (or maybe not) that worked for me is to simply use two `connection.query`, something like this:

```
router.get('/home', function(req, res) 
{
  connection.query('update * from tableA;', function(err, rows, fields) 
  {
    if (err) throw err;
  });   
  connection.query('select * from tableA;', function(err, rows, fields) 
  {
    if (err) throw err;
      res.render('home',{result: rows});
  });   
});
```

**Comment by dougwilson** [comment]
Hi @billyandika , if you are just going to `throw err` in your callback, you can actually just leave it off altogether (callbacks are optional in this library if you don't mind if errors throw):
```js
router.get('/home', function(req, res) 
{
  connection.query('update * from tableA;');   
  connection.query('select * from tableA;', function(err, rows, fields) 
  {
    if (err) throw err;
      res.render('home',{result: rows});
  });   
});
```
