### ISSUE TITLE
Update query not working - JS Precision Error - InfiniDB

### ISSUE THREAD

**Issue by ericuldall** [felixge/node-mysql#1220]
UPDATE table SET value = 'value' WHERE id = 431

I'm using a query like that and for some reason i'm getting this error:

    { [Error: parseLengthCodedNumber: JS precision range exceeded, number is >= 53 bit: "18446744073709551615"] offset: 2, code: 'PARSER_JS_PRECISION_RANGE_EXCEEDED' }

This is weird because there are no large integers or negative integers anywhere in my entire query.

Any ideas on this? Inserts work fine.

**Comment by ericuldall** [comment]
229   if (high >>> 21) {                                                                                                                                                                             return connection.end();
    230     value = (new BigNumber(low)).plus((new BigNumber(MUL_32BIT)).times(high)).toString();                                                                                                }
    231                                                                                                                                                                                      };
    232     if (this._supportBigNumbers) {                                                                                                                                               
    233       return value;                                                                                                                                                                  this.get_instance = function(host, user, pass, db){
    234     }                                                                                                                                                                                    if( !(instances.hasOwnProperty(host)) ){
    235                                                                                                                                                                                              instances[host] = new infinidb(host, user, pass, db);
    236     var err    = new Error(                                                                                                                                                              }
    237       'parseLengthCodedNumber: JS precision range exceeded, ' +                                                                                                                  
    238       'number is >= 53 bit: "' + value + '"'                                                                                                                                             return instances[host];
    239     );                                                                                                                                                                               };
    240     err.offset = (this._offset - this._packetOffset - 8);                                                                                                                        };
    241     err.code   = 'PARSER_JS_PRECISION_RANGE_EXCEEDED';                                                                                                                           
    242     //throw err;                                                                                                                                                                 module.exports = new Db_Infinidb;
    243   }  

I commented out line 242 in mysql/lib/protocol/Parser.js and the query now works. I'm not sure why this library is throwing an error when the resulting query would still work?!?!

**Comment by dougwilson** [comment]
The query would have still occurred on the server, but the failure is likely reading the response packet from your MySQL server.

Can you list what version of MySQL server you are using, what version of this module, what version of Node.js, and the DDL of the table you are updating?

In addition to all that, can you add "debug: true" to your connection options and paste here the resulting logs?

**Comment by dougwilson** [comment]
Hi @ericuldall ! I'm closing this issue due to a lack of response to my inquiry. Please feel fee to update this issue with the information and I can always re-open :)
