### ISSUE TITLE
connect callback not called

### ISSUE THREAD

**Issue by CamJN** [felixge/node-mysql#1221]
Simple example as follows:
```
require('fs').readFile('/etc/mysql/mysql-ssl-ca-cert.pem','utf8',function(err,caFile){
    if(!err){
        var conn = require('mysql').createConnection({
            host     : 'localhost',
            user     : 'mysql',
            password : 'password',
            database : 'mydb',
            ssl      : { ca : caFile }
        });
        console.log('before');
        conn.connect(function(err){
            console.log('inside');
            if(!err){
                connection.query('select count(*) as found from `codes` where `id` = ?', ['aaa111a1'], function(err, rows, fields) {
                    if (!err) {
                        console.log(rows[0].found?'found':'not found');
                        connection.end(function(err) { if(err) console.error('Error On DB Close.'); });
                    }else{
                        console.log(err);
                    }
                });
            }else{
                console.log(err);
            }
        });
        console.log('after');
    }else{
        console.log(err);
    }
});
```
the output is simply:
```
before
after
```
The connection worked up until I updated to node 4.1.0

**Comment by CamJN** [comment]
still busted on 4.2.1

**Comment by dougwilson** [comment]
Hi @CamJN , I don't think it was expected for this to be fixed in 4.2.1 :) It's really bad that Node.js 4.1.0 would break something that worked in 4.0.0.

1. Have you filed a bug with Node.js? Have you been able to dig in?
2. I tried the repo you gave above on 4.2.1 just now on Windows 7 x64 and MySQL 5.6.27 and it worked fine over SSL. Is there a possibility you could offer up a PR?
3. Does the `mysql2` module work?

**Comment by CamJN** [comment]
I've not had the time to dig into this much. And I wouldn't begin to know what node is doing that is breaking things for this module.

with mysql2 i get:
```
(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: 140735225872384:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:769:

    at Error (native)
    at SlabBuffer.use (_tls_legacy.js:42:18)
    at CleartextStream.read [as _read] (_tls_legacy.js:260:29)
    at CleartextStream.Readable.read (_stream_readable.js:328:10)
    at EncryptedStream.write [as _write] (_tls_legacy.js:174:25)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at EncryptedStream.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
```

I'm on node 4.2.1 and mysql 5.6.27 both from homebrew on OS X.

**Comment by dougwilson** [comment]
Gotcha. The weirdest part is, as far as I know, you're the only user reporting this issue at all. Has all your testing been on the same computer or different ones? I'm starting to wonder if there is something up with the machine (or a configuration on that machine) you are using if the issue is isolated to the machines.

**Comment by CamJN** [comment]
The same thing happens when I try on my other box. So if it's a problem on my end it's reproducible.

- I install mysql, node, and openssl from homebrew. (latest stable versions, as binaries from bottles)
- I create a set of self signed certs / keys / ca-cert with openssl. (https://github.com/CamJN/dot-files/blob/master/etc/mysql/mysql-certs.sh & https://github.com/CamJN/dot-files/blob/master/etc/openssl/openssl.cnf)
- I setup mysql via my.cnf to use the self signed cert to encrypt traffic. (https://github.com/CamJN/dot-files/blob/master/etc/mysql/my.cnf)
- I create my db in mysql, then populate it.
- I require ssl to connect to the db. (via GRANT USAGE ON \*.\* TO 'root'@'localhost' REQUIRE SSL )
- I point node at my ca cert when it tries to connect to the db. (as above)
- The connection callback is never called.

**Comment by dougwilson** [comment]
Gotcha. Tests with SSL connections are running on Travis CI environment, and they are all successful, even on Node.js 4.2.1. I don't personally have any access to a Mac OS X machine, so unless you're able to rule out it's a Mac OS X issue (by confining it all to Windows of Linux), then we can't rule that out, either, which would also put it out of my reach to ever be able to reproduce & debug.

**Comment by CamJN** [comment]
So travis supports OS X as a CI env. I don't know if using more than two envs costs money on travis but if not I could likely port your linux scripts/config for you if you like.

**Comment by dougwilson** [comment]
AFAIK Node.js is not supported on Max OS X on Travis CI (according to https://github.com/travis-ci/travis-ci/issues/2311).

**Comment by CamJN** [comment]
Yeah I'd have to get node.js from homebrew, but since that's how many/most os x developers will get it that's probably a good thing.

**Comment by dougwilson** [comment]
Gotcha. It also looks like MySQL is also not a service on the Travis CI Mac OS X, so I suppose you have to get that from homebrew as well. The test suite for this module already takes a while, so hopefully installing all these things doesn't make the tests take a really long time.

**Comment by dougwilson** [comment]
Otherwise, yes, especially if you can setup Travis CI to test on Mac OS X and it reproduces this issue, though I'm not sure how much that will even help me, because I cannot attach a debugger to the Node.js that runs in Travis CI to debug anything about the issue...

**Comment by CamJN** [comment]
Ok. I'd make you a VirtualBox VM but technically you are only supposed to run OS X on apple hardware so depending on how you feel about EULAs that might not be of much interest to you.

**Comment by dougwilson** [comment]
Let's at least see if it can reproduce on Travis CI first.

**Comment by CamJN** [comment]
Well I couldn't get the CI to work on OSX at a reasonable speed (also lots of random npm errors). But a combination of updates to mysql 5.7.9 and node 5.1 fixed the issue.

**Comment by dougwilson** [comment]
Interesting. If you experience it again or are able to determine what the root cause was, we would love to hear it, especially if there is some version of MySQL we are not compatible with (perhaps we an fix it or at least document it somewhere).

**Comment by CamJN** [comment]
I had an idea, when I upgraded to mysql 5.7.9, I had to stop using CAMELLIA128-SHA as my cipher which I had been using previously per (http://www.couyon.net/blog/if-all-of-your-mysql-ssl-clients-just-broke), so that might be related.
