### ISSUE TITLE
Get columns schema

### ISSUE THREAD

**Issue by rikantro** [felixge/node-mysql#1225]
how get schema without execute query on table?, alredy exist method for this task ?
Currently execute query DESCRIBE TABLE_NAME

Thanks for all help

**Comment by sidorares** [comment]
on a protocol level there is [COM_FIELD_LIST](http://dev.mysql.com/doc/internals/en/com-field-list.html) command which is currently not implemented, so right now the only option is to do `db.query("describe mytable", cb)`

**Comment by sidorares** [comment]
from official [http://dev.mysql.com/doc/refman/5.7/en/mysql-list-fields.html](documentation):

> Calling mysql_list_fields() is similar to executing the query `SHOW COLUMNS FROM tbl_name [LIKE wild].`
It is preferable to use `SHOW COLUMNS FROM tbl_name` instead of `mysql_list_fields()`.

So I guess there is little benefit from implementing  COM_FIELD_LIST command
