### ISSUE TITLE
Pass multiple value in sql_mode in session startup.

### ISSUE THREAD

**Issue by sapkal-manish** [felixge/node-mysql#1231]
How do I pass multiple values in sql_mode in connection? I would like to set sql_mode = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION' for my connection pool.

Thanks.

**Comment by dougwilson** [comment]
Hi! You would just run that query in the `connection` event on your pool:
```js
var pool = myql.createPool(...);
pool.on('connection', function (conn) {
  // This will be invoked whenever a new connection is made
  conn.query('SET sql_mode = ?', ['STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION']);
});
```
