### ISSUE TITLE
looking for advice -- error connecting: Error: Handshake inactivity timeout

### ISSUE THREAD

**Issue by bennettatoms** [felixge/node-mysql#1239]
Hi, 

I have been using node-mysql for development purposes for the past few months, and it's been great. Thus far I have been connecting to the same Amazon RDS instance from my local machine, but we recently deployed our app code to an Amazon VPC, and now I'm getting the above error when the app tries to connect to the same MySQL database we were developing off of. 

The full error stack trace is:
```
error connecting: Error: Handshake inactivity timeout
   at Handshake.<anonymous> (/var/app/current/node_modules/mysql/lib/protocol/Protocol.js:154:17)
   at Handshake.emit (events.js:104:17)
   at Handshake._onTimeout         (/var/app/current/node_modules/mysql/lib/protocol/sequences/Sequence.js:116:8)
   at Timer.listOnTimeout (timers.js:119:15)
   --------------------
   at Protocol._enqueue (/var/app/current/node_modules/mysql/lib/protocol/Protocol.js:135:48)
   at Protocol.handshake (/var/app/current/node_modules/mysql/lib/protocol/Protocol.js:52:41)
   at PoolConnection.connect (/var/app/current/node_modules/mysql/lib/Connection.js:123:18)
   at Pool.getConnection (/var/app/current/node_modules/mysql/lib/Pool.js:45:23)
   at execQuery.mysql (/var/app/current/api/utilities/connection.js:90:12)
   at exports.runQuery (/var/app/current/api/utilities/connection.js:223:3)
   at _fulfilled (/var/app/current/node_modules/q/q.js:834:54)
   at self.promiseDispatch.done (/var/app/current/node_modules/q/q.js:863:30)
   at Promise.promise.promiseDispatch (/var/app/current/node_modules/q/q.js:796:13)
   at /var/app/current/node_modules/q/q.js:556:49
   at runSingle (/var/app/current/node_modules/q/q.js:137:13)
   at flush (/var/app/current/node_modules/q/q.js:125:13)
   at process._tickDomainCallback (node.js:381:11)
```
Exactly what's happening on the attempt to connect is a little opaque. I'm guessing it's probably not an issue with the node-mysql module, but if anyone has experienced something similar and might be able to offer advice on how to connect successfully, I would greatly appreciate it.

**Comment by GoNode5** [comment]
Same here, ubuntu 14.04 after update / upgrade... after error did upgrade to node 4.2.1 and mysql latest... to be sure. No solution. Never happened in 2.5 year Nodejs/Mysql updates/upgrades it always worked/stable.

**Comment by bramvandervoet** [comment]
reboot with 4.2.1 solved the problem thnx. I saw my problem an duplicate, please dont solve and close to quick :-)

**Comment by dougwilson** [comment]
Hi @bennettatoms can you provide the following information:

1. Version of Node.js
2. Version of this module
3. Version of your MySQL server.

**Comment by Fatalityap** [comment]
I had this problem also but Node 4.2.1 solved my problem too... :) I see that many people have this problem on Node 4.2.0 ))))

**Comment by bennettatoms** [comment]
I should mention that the app is running on node v0.12.4, node-mysql v2.9.0, and MySQL v5.6.23. Was hesitant to upgrade to node > 4.0 as we began deployment the same week 4.0 was released. I can still connect via localhost without problem.

**Comment by hezedu** [comment]
I have this problem too on node 4.2

**Comment by gquemener** [comment]
Upgrading node to 4.2.1 solved the problem for me too :+1:

**Comment by bennettatoms** [comment]
I made a mistake on the node version. My local version, where everything is still working without issue, is 0.12.4, but the AWS EC2 instance is running 0.12.6, which is apparently the latest version they support.

**Comment by rasensio** [comment]
Updated with brew to 4.2.1 and problem solved.

**Comment by raffi-minassian** [comment]
Saw the same problem just connecting to a local mysql like ...

    var con = mysql.createConnection({
      database: "mydb",
      host: "localhost,
      user: "admin",
      password: "nonononono"
    });

Would give when trying con.query( *etc...* ) ...

    { [Error: Handshake inactivity timeout]
      code: 'PROTOCOL_SEQUENCE_TIMEOUT',
      fatal: true,
      timeout: undefined }


**Just updating to Node.js v4.2.1 fixed the issue!!.**
:)

**Comment by s992** [comment]
Just wanted to chime in and note that I was experiencing the same issue with the sails-mysql adapter, which uses node-mysql behind the scenes. Upgrading to Node 4.2.1 fixed it for me as well.

**Comment by dougwilson** [comment]
@bennettatoms werre you able to resolve the issue? We test this module with 0.12, though looking at Travis CI, the current version is 0.12.7. I don't remember having having an issue with 0.12.6, though, and I ran against 0.12.6 locally and all the tests passed, so I'm not really sure what else to really suggest :(

**Comment by bennettatoms** [comment]
@dougwilson, I'm so sorry for not posting this earlier. Thank you for looking into it, but the problem, as I suspected but (unfortunately) took about a week to confirm, was on the AWS side, the way the permissions were configured on our outbound servers. It was all unfamiliar terrain for me. It is good to know, though, that this became a known and resolved issue with the upgrade to node 4.2.1.

**Comment by salfredogonzalez** [comment]
Yes, upgrading node version do the fix

**Comment by Aidurber** [comment]
Experiencing this issue in Node v5.0.0
