### ISSUE TITLE
Handshake inactivity timeout error

### ISSUE THREAD

**Issue by Fatalityap** [felixge/node-mysql#1240]
Hi. I faced with "Handshake inactivity timeout" error. I am using Node v4.2.0 on MacOS X El Capitan, and latest version of your library and MySQL (I tried differed versions: 5.14, 5.6). I try to change settings but nothing helps me. Then I have commented this code: 
```javascript
.on('timeout', function() {
      var err = new Error(sequence.constructor.name + ' inactivity timeout');

      err.code    = 'PROTOCOL_SEQUENCE_TIMEOUT';
      err.fatal   = true;
      err.timeout = sequence._timeout;

      self._delegateError(err, sequence);
    }) 
```
at Protocol.js file or your library all is working fine. But maybe you can fix this issue.

**Comment by dougwilson** [comment]
This is a regression in Node.js 4.2.0. You'll need to upgrade to 4.2.1 for their fix.

**Comment by Fatalityap** [comment]
Thanks a lot. It's help for me.
