### ISSUE TITLE
Handshake Inactivity Timeout - PROTOCOL_SEQUENCE_TIMEOUT in 4.2.0

### ISSUE THREAD

**Issue by chenxizhang** [felixge/node-mysql#1241]
Handshake Inactivity Timeout - PROTOCOL_SEQUENCE_TIMEOUT in 4.2.0

please help to this bug

**Comment by dougwilson** [comment]
This is a bug in Node.js 4.2.0. It is fixed in Node.js 4.2.1

**Comment by chenxizhang** [comment]
It's work, thanks
