### ISSUE TITLE
Potential memory leak when using domains

### ISSUE THREAD

**Issue by emptyemail** [felixge/node-mysql#1242]
Hi, not sure this is an issue, but I discovered that `connection._socket` will maintain a link to the domain that was active when the connection was first utilized. Since we usually use a connection pool its very likely that the domain in question is no longer valid but the socket is still referencing it. My suggestion would be to bind the connect method to the domain that was active when the connection was created.

**Comment by dougwilson** [comment]
I have never used domains, rather the current implementation was donated via a PR :) Domains in Node.js have been deprecated for a while (https://nodejs.org/api/domain.html), so I'm not sure if this is a bug in domains themselves or here. Please feel free to provide a PR.

**Comment by dougwilson** [comment]
We'll make sure that the connection end up bound to the same domain that the pool is bound to.
