### ISSUE TITLE
ER_CON_COUNT_ERROR eventhough using connection.release()

### ISSUE THREAD

**Issue by dineshkumarreddyr** [felixge/node-mysql#1244]
When i use siege with 100 connections, im getting the above error. Below is the sample code.

Code:
```js
var pool = mysql.createPool({
            host: 'localhost',
            user: 'xxx',
            password: 'xxxxx',
            connectionLimit: 100,
            database:'xxxx'
        });
        pool.getConnection(function (error, connection) {
            if (error) {
                throw err;
            }
            connection.query('select * from products;', function (err, rows, fields) {
                connection.release();
                if (err) {
                    throw err;
                }
                if (rows && rows[0] != undefined && rows[0].length > 0) {
                    res.send({ "status": "success", "records": rows[0] });
                }
                else {
                    res.send({ "status": "error", "ecode": "e1", "emsg": "NO_DATA" });
                }
            });
        });
```

The above error im getting at `Handshake.sequence._packetTOError`.

Is it required to configure anything on mysql. Could you please help on this

**Comment by dougwilson** [comment]
That error is coming from your MySQL server. Please refer to their documentation https://dev.mysql.com/doc/refman/5.5/en/too-many-connections.html regarding the error. If you feel like there is a bug in this library, we'd be happy to help if you can explain what the bug is :)

**Comment by dineshkumarreddyr** [comment]
Thanks for your quick reply. Understood, that i need to increase max_connections in mysql and also it dependent on RAM as well..
