### ISSUE TITLE
Knowing when results are back? question

### ISSUE THREAD

**Issue by bmcgonag** [felixge/node-mysql#1245]
I'm writing a socket.io message system, and I need to have a way to know when the results are back so I can emit the message with results.  

I just seem to be missing something.  

I do something like 

```javascript
if (err) { .... }
else if (results) { emit.info(results) }
```
but the results are null, so I'm guessing they haven't returned yet. 

Am I off?  What am I missing?

**Comment by dougwilson** [comment]
With such a tiny bit of code, it's not possible to answer. Can you show a bit more code? Perhaps how this library is being used?

**Comment by bmcgonag** [comment]
No worries, I'm an idiot.  I was trying to do

    results.message

instead of
 
    results[0].message

and thus my issue is resolved.  I see now that results is the callback, and it won't move into the sql return function until there is either an error, or there are results to be used.  

Sorry for the trouble.
