### ISSUE TITLE
Strange Json error format

### ISSUE THREAD

**Issue by lucaskenda** [felixge/node-mysql#1247]
Hi,

I need to output the error from a failed connection:
"Error: getaddrinfo ENOTFOUND 127.0.0.1a"

The code is quite simple:
```js
connection.query('SELECT 1', function(err, rows) {
      if(err){
        console.log(err);
    });
```
But the format of the response is a bad formatted json:
```
{ [Error: getaddrinfo ENOTFOUND 127.0.0.1a]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '127.0.0.1a',
  fatal: true }
```
if this is not an error, how can I get only the parte between the brackets?

Thanks,
Lucas

**Comment by dougwilson** [comment]
Hi @lucaskenda ! This is just how Node.js code's `console.log` function works. For example:
```
$ node -e 'err = new Error("oops"); err.code = "EOOPS"; console.log(err)'
{ [Error: oops] code: 'EOOPS' }
```

You'll probably want to open a question on Node.js help forums for what the best way to turn a JavaScript `Error` object into JSON is.

**Comment by lucaskenda** [comment]
Thanks for the fast response!
