### ISSUE TITLE
Syntax help for Bulk insert with ON DUPLICATE

### ISSUE THREAD

**Issue by Laro88** [felixge/node-mysql#1248]
I am having trouble with a bulk insert with a conditional update.
Table looks like this:
```CREATE TABLE `status` (
  `id` int(11) NOT NULL,
  `keyname` varchar(100) NOT NULL,
  `val` varchar(100) NOT NULL,
  PRIMARY KEY (`id`,`keyname`)
)```
I have been trying to put qStatus into an extra array ([qStatus] instead of qStatus) and what not, but I keep getting errors. The commented SQL statement Iin the code is fine, so I am suspecting that there is something in the parameter handling that I break by accident.
```
qStatus = [];
qStatus.push([33, 'a', 'a1'])
qStatus.push([33, 'a', 'a2'])
qStatus.push([33, 'b', 'a3'])
//this works in mysql workbench INSERT INTO status(id, keyname, val) VALUES(3, "ut", "a4"), (3, "ut", "a5") ON DUPLICATE KEY UPDATE val = VALUES(val);
var s = 'INSERT INTO status(id, keyname, val) VALUES(?) ON DUPLICATE KEY UPDATE val = VALUES(val)';

dbioCore.loggingpool.query(s, qStatus, function (err, res) {
  if (err) {
    logger.error("Failure bulk inserting status data" + err);
  }

qStatus = []; //clear queue
```
Can anyone tell me what the correct use of the ? mapping should be. I have tried to insert the val parameter twice and use 4 x ?, however I have not been successful yet.
I miss something like indexed variables such as ?[0]..?[n] - then the values could be reused in complex queries.

**Comment by Firnis** [comment]
As suggested in https://github.com/felixge/node-mysql/issues/1189#issuecomment-133451494 it should be:
```
...
dbioCore.loggingpool.query(s, [qStatus], function (err, res) {
...
```

**Comment by dougwilson** [comment]
You also need to remove the parentheses around the question mark:

    dbioCore.loggingpool.query('INSERT INTO status(id, keyname, val) VALUES ? ON DUPLICATE KEY UPDATE val = VALUES(val)', [qStatus], function (err, res) {

**Comment by Laro88** [comment]
Thank you - working perfectly  - the ```VALUES(?)``` should be ```VALUES ?```

I completely overlooked the paranthesis after VALUES:
BAD: ```INSERT INTO status(id, keyname, val) VALUES((3, "ut", "a4"), (3, "ut", "a5")) ON DUPLICATE KEY UPDATE val = VALUES(val);```
OK: ```INSERT INTO status(id, keyname, val) VALUES (3, "ut", "a4"), (3, "ut", "a5") ON DUPLICATE KEY UPDATE val = VALUES(val);```
