### ISSUE TITLE
Connection url

### ISSUE THREAD

**Issue by felixfbecker** [felixge/node-mysql#1250]
I don't know if this is already supported, at least it is not documented:

- Is connecting with a url-string in the form of `mysql://user@host:3306/database?multipleStatements=true` supported?
- If yes, does this also work with pools
  - in general
  - for pool specific options like `connectionLimit`?

If yes, these should be documented.
If not, this is a really important feature for universially configuring apps with env variables. See:

 - http://12factor.net/backing-services
 - http://12factor.net/config

Hope someone can answer this.
Cheers

**Comment by felixfbecker** [comment]
Ok just found the answer to the first question in the docs. No idea how I overread that.

**Comment by dougwilson** [comment]
Hi @felixfbecker , it sure does! Anything in the `options` can be set in the query part of the string, for example, `mysql.createPool('mysql://user@host:3306/database?multipleStatements=true&connectionLimit=2')` should work just fine.

**Comment by felixfbecker** [comment]
Thanks!
