### ISSUE TITLE
Error: Handshake inactivity timeout

### ISSUE THREAD

**Issue by johnymonster** [felixge/node-mysql#1252]
I was trying to use node version v4.2 and the plugin does not work, I get the error above.  Is this already known?

**Comment by dougwilson** [comment]
This is a bug in Node.js 4.2.0. It is fixed in 4.2.1, if you want to upgrade to get the fix :)

**Comment by huangyunbo** [comment]
I use version v4.2.1, It often Unhandled rejection Error: Handshake inactivity timeout.
