### ISSUE TITLE
Add .eslintrc

### ISSUE THREAD

**Issue by felixfbecker** [felixge/node-mysql#1254]
It is currently quite hard to see which styling guide this code follows or to get editor help for it.
I propose to add a .eslintrc file which contains the rules of code style this project currently follows. This could be integrated with travis as well.

**Comment by dougwilson** [comment]
I've never used eslint, personally. If you can cme up with a set of rules that match this library, I can probably accept :)

**Comment by felixfbecker** [comment]
Looked into the code a bit more and there are many inconsistencies that would need to be resolved. Some examples I found:
 - errors in indentation (indentation of 3 spaces for example when it should be 2)
 - `function ()` vs. function()` inconsistent
 - single quotes vs. double quotes
 - redeclaration of variables (a lot - this can lead to nasty bugs)
 - spaces between operators
 - non-strict comparison (== vs. ===)
 - statements inside curly braces on next line inconsistent
 - trailing commas inconsistent
 I can make a PR if I know what your opinion is about these :)

**Comment by dougwilson** [comment]
For now, a lint file that requires no code changes would be best, then we can start working on determining any other rules on a case-by-case basis. The style of this module is the same as the original author, and so the resolutions would be whatever that is. I would bet some of the conflicts are from accepting PRs, which may not have complied with the author's style.

**Comment by felixfbecker** [comment]
Okay, gonna run some `git blame`s to find out when I find the time.
