### ISSUE TITLE
PoolNamespace.query() method does not exists

### ISSUE THREAD

**Issue by euglv** [felixge/node-mysql#1256]
Hello,
[documentation](https://github.com/felixge/node-mysql#performing-queries) states:
># Performing queries
> 
>The most basic way to perform a query is to call the `.query()` method on an object (like on a `Connection`, `Pool`, `PoolNamespace` or other similar objects).

`PoolNamespace`, as stated [here](https://github.com/felixge/node-mysql/issues/1161#issuecomment-130169375), is returned by `poolCluster.of()` method.

```javascript
var mysql = require('mysql');
var poolCluster = mysql.createPoolCluster({
	restoreNodeTimeout: 1,
});
poolCluster.add(config.db);

poolCluster.of('*').query(sql, callback);
```
But the last line of code produces error:
`TypeError: poolCluster.of(...).query is not a function`

**Comment by dougwilson** [comment]
Oops, I'm so sorry! Looks like the document is wrong, as `PoolNamespace` does not have a `.query` method. I'll update the documentation (unless you make a PR first to do so) and to get a `.query` method on there, a PR is certainly welcome :)
