### ISSUE TITLE
Edit data before callback

### ISSUE THREAD

**Issue by yehudahkay** [felixge/node-mysql#1258]
Hi,

Is there a way for me to add a global function which will edit the rows array before it is passed to my individual callback for the query?

Thanks for the great package!

**Comment by dougwilson** [comment]
There are really only three options:

1. Subclass the connections here and wrap the `.query` method to perform your overrides.
2. Create a new class in our own code and use this module has an internal property an expose our own methods (which can internally cal `.query` here, perform the transforms, and then provide that to the callers of your class.
3. Try to fit in whatever you're looking to do in the built-in `typeCast` option (https://github.com/felixge/node-mysql#type-casting)
