### ISSUE TITLE
datetime stamp should be receive in 24 hour format

### ISSUE THREAD

**Issue by sapkal-manish** [felixge/node-mysql#1260]
I have hosted my database on AWS (Singapore Region) where timezone set UTC. One of my table has timestamp datatype for a column,  and it is hold value like `'2010-08-02 11:53:39.000000'`.
When I run this query in workbench 
`select CONVERT_TZ('2015-10-28 08:02:27.062120','+00:00','+05:30')` ist
its return me `'2015-10-28 13:32:27.062120'` which is perfect. 
But when I receive data using your drive in javascript, its shows me `"2015-10-28T02:32:27.062Z"`, which is wrong (As per my opinion), my expected value should be `"2015-10-28T01:32:27.062Z"`, which is one hour less. and does it have any option to receive date time in 24 hours format?

EDIT:
I have set `timezone = '+05:30'` and  `dateStrings = false` in my pool option.
If I have set `dateStrings = true`, so its not converting date as per timezone, which is bed.

It is very urgent and very serious problem for me. Please guide me. 

Thanks.

**Comment by dougwilson** [comment]
If it's still not working if you have done `mysql.createConnection({ ... , timezone: '+00:00' })` to match that your server is in UTC, I'm not sure what else to do, as there isn't really enough information here for me to determine.

**Comment by sapkal-manish** [comment]
I want data as per my local timezone, with is +5:30 (IST, Indian Time). So, I must have to set mysql.createConnection({ ... , timezone: '+05:00' }) in driver. I am ready to set this. but when result comes in javascript, It should be in 24hour format instead in 12hour format.
