### ISSUE TITLE
Does pool handle connections gap filling in case of an err.fatal occurs?

### ISSUE THREAD

**Issue by cusspvz** [felixge/node-mysql#1261]
I've been experiencing some fatal errors and I've seen that I will have to handle with this manually.
My question is, does Pool handles connection.reconnect as it is a higher level structure?

**Comment by dougwilson** [comment]
it sure does: https://github.com/felixge/node-mysql#server-disconnects

**Comment by cusspvz** [comment]
Thanks for the fast response! :smile: 
I saw that on README, but since it is only referring `PROTOCOL_CONNECTION_LOST` I don't had sure if it covers all `err.fatal` cases since itdoesn't clarify: `E_TIMEOUT`, `PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR`, and so on.

So I guess it handles all closed events deriving from `err.fatal`, right?

**Comment by dougwilson** [comment]
Gotcha. Yes, the way the pool works is that on a fatal error, the connection is removed from the pool, so when you eventually `.release()` that connection back to the pool, the connection is just destroyed instead of returned.

**Comment by cusspvz** [comment]
Nice! Don't know if I already said this but, you got here an awesome work! Congrats!

Thank you once again.
