### ISSUE TITLE
64 bit number

### ISSUE THREAD

**Issue by Turkk** [felixge/node-mysql#1262]
When I retrieve the 64 bit steam community id from the database, the last 2 numbers change for some odd reason:

inside database: 76561198045763615
retrieved from database: 76561198045763620

**Comment by dougwilson** [comment]
This is a property of JavaScript itself. For example:
```
$ node -pe '76561198045763615'
76561198045763620
```

Depending on your use-case, there are two main options you can use (https://github.com/felixge/node-mysql#connection-options): `supportBigNumbers` and `bigNumberStrings`
