### ISSUE TITLE
passing parameters for IN()

### ISSUE THREAD

**Issue by giulianozorzi** [felixge/node-mysql#1263]
Hi,
I'd like to sena a list of values to the mysql server but I can't find how to do it (if possible at all).

SQL: `select * from peoples where age in(?);`

I would like to pass a parameter containing ie: 20,21,22 so the query that is actually executed is `
select * from peoples where age in(20,21,22);`
Actually I get `
select * from peoples where age in('20,21,22');`

My code is like:
```js
var params= [ '20,21,22' ]; // I know it's wrong, but I have no ideas...
connection.query(sql, params, function(err, results) {
```
Is it possible to do so ?

thanks

giuliano

**Comment by MalyshevDmitry** [comment]
:+1: Interesting too.

**Comment by dougwilson** [comment]
Hi! From https://github.com/felixge/node-mysql#escaping-query-values , the pattern would be the following:
```js
var sql = 'SELECT * FROM peoples WHERE age IN (?);'
var ages = [20, 21, 22];
var params = [ages];
connection.query(sql, params, function(err, results) {
```
