### ISSUE TITLE
regexp escaping

### ISSUE THREAD

**Issue by giulianozorzi** [felixge/node-mysql#1264]
Hi, sorry for the new message :)

I'm trying to pass a regexp via a parameter, but it's escaped in a way I can't get it correctly to the server

my regexp is `(.*)@\.\d.\d$`
`console.log(mysql.escape('^(.*)@\.\d.\d$'));` -> `'^(.*)@.d.d$'`
`console.log(mysql.escape('^(.*)@\\.\\d.\\d$'));` -> `'^(.*)@\\.\\d.\\d$'`

SQL is something like `select * from users where username regex (?)`

is there a way to skip escaping these `\` ? the regexp is not user submitted so I can safely escape it by myself

thasnks

giuliano

**Comment by dougwilson** [comment]
You'll want to use the following:
```js
conn.query('SELECT * FROM users WHERE username REGEX ?', ['^(.*)@\\.[0-9].[0-9]$'], function (err, results) {
```

That will result in the equivalent of `/^(.*)@\.\d.\d$/.test(username)` in JavaScript. In MySQL, there is no such shortcut as `/\d/`, AFAIK
