### ISSUE TITLE
Truncation of value with multi-byte characters and union queries

### ISSUE THREAD

**Issue by matthew-dean-hp** [felixge/node-mysql#1269]
I realise this might just be an issue with 4 byte characters and this library but the resultant behaviour is very odd.

If I run a query that inserts into a table a utf8 4 byte character, and that insert uses a union operation, the value inserted is truncated just before the 4 byte character. This also happens if I just do an isolated select with a union, for example:

```javascript
var mysql = require('mysql')

var query = 'SELECT \'{\\"value\\":\\"' + decodeURIComponent('%F0%9F%98%89') + '\\",\\"type\\":\\"string\\"}\' AS value, 0 AS `order`'
var badquery = query + ' UNION ALL ' + query

var connection = mysql.createConnection({
  host     : 'my-database',
  user     : 'user',
  password : 'password',
  database : 'database',
  // charset  : 'ASCII_BIN'
});

connection.connect();

connection.query(query, function(err, rows, fields) {
  if (err) throw err;
  console.log(rows)
  connection.query(badquery, function(err, rows, fields) {
    if (err) throw err;
    console.log(rows)
    connection.end();
  }) 
});
```
will return:
```javascript
[ { value: '{"value":"😉","type":"string"}', order: 0 } ]
[ { value: '{"value":"', order: 0 },
  { value: '{"value":"', order: 0 } ]
```
Changing the connection encoding to ascii strangely fixes the issue. I'm using version 2.9.0. Any ideas?

**Comment by dougwilson** [comment]
MySQL can only store 4 byte UTF-8 sequences in tables with the charset set to utf8mb4. As long as all your columns in your database are set to utf8mb4, then the only thing you need to do in addition is set `charset: 'UTF8MB4_GENERAL_CI'` in your connection options to this module.

**Comment by matthew-dean-hp** [comment]
Yep, that works a treat. I swear I had started with that but it works just fine.
