### ISSUE TITLE
How to deal with implicit transaction rollback after ER_LOCK_WAIT_TIMEOUT?

### ISSUE THREAD

**Issue by emmettnicholas** [felixge/node-mysql#1270]
I'd appreciate guidance, patterns, or best practices to deal with implicit rollbacks caused by lock wait timeouts. Here's a pseudo-coded, simplified version of our logic:

```javascript
// 1. beginTransaction...

async.parallel({
    function(next) {
        // 2a. INSERT INTO foo
    },
    function(next) {
        // 2b. INSERT INTO bar
    }
}, function(err) {
    if (err) {
        // rollbackTransaction...
        return;
    }

    // 3. commitTransaction...
});
```

The problem is: step 2a results in ER_LOCK_WAIT_TIMEOUT and implicitly rolls back the transaction. However, 2b has already been enqueued on the connection, so it actually gets committed (now outside of a transaction).

Basically we either need to insert into both foo and bar (success), or neither (failure). But in the event of a lock wait timeout, it's inserting into one but not the other.

p.s. I came across https://github.com/felixge/node-mysql/issues/410, which references https://github.com/HBYoon/node-mysql-transaction -- is that the recommended way forward?

**Comment by dougwilson** [comment]
MySQL is a sequential protocol, so running async.parallel does not have any benefit, and in fact, just works against you. Changing it to async.series should be all you need to do.

**Comment by emmettnicholas** [comment]
@dougwilson Thanks, that occurred to me. If I make "parallel" queries on the same connection, will node-msyql enqueue queries on its end, or will it immediately send the queries to the database server, which would enqueue on its end? I suppose I was imagining that this would save time by parallelizing webServer<-->dbServer communication latency, but my understanding of this stuff is not at all complete.

**Comment by sidorares** [comment]
packets enqueued on client side, otherwise server immediately disconnects on any duplex write attempt. It's always half duplex command packet -> set of response packets sequence

**Comment by dougwilson** [comment]
The MySQL protocol is serial, so we cannot send a new query until the response from the previous query has been received. As a convience, we will simply queue up your second query until the first one is done instead of throwing an error.

**Comment by emmettnicholas** [comment]
Thanks a lot. We get a lot of benefit (i.e. code expressiveness) by using `async.parallel`, `async.auto`, etc., but it looks like we can safely proceed by abstracting away node-mysql in a module which performs queries in series.
