### ISSUE TITLE
How does it work with SSH?

### ISSUE THREAD

**Issue by LanceCong** [felixge/node-mysql#1271]
I want to connect several mysql on several CentOS Server.
But all of their mysql counld only be connected with SSH.I can't connect them by IP with a remote way.
Sorry for my poor English.

**Comment by sidorares** [comment]
are you talking about ssl, not ssh? 

https://dev.mysql.com/doc/refman/5.7/en/using-ssl-connections.html
https://github.com/felixge/node-mysql#ssl-options

**Comment by LanceCong** [comment]
I mean how to connect the Mysql on the remote server which not allow the remote connection.So if I want to use it,I should connect it by the SSH way.
But I finally fix this.I find another remote Mysql. :)
You know what I mean now?Thx

**Comment by tfzxyinhao** [comment]
i think you may said use ssh tunel to connect mysql server,
it was impossble

**Comment by sidorares** [comment]
looks like it's a generic mysql/ssh question, not related directly to this driver

**Comment by LanceCong** [comment]
Thank you.
It was possible but I should use another moduel like "ssh2".It's right this question not related directly to this driver.

**Comment by sidorares** [comment]
@LanceCong see #1110 for custom stream support ( e.i using ssh2 tunneled connection stream instead of direct tcp )

**Comment by farzer** [comment]
can you show any example? @sidorares

**Comment by sidorares** [comment]
you mean for api proposed in pr #1110 ?

**Comment by farzer** [comment]
using mysql via tunnel ssh by using `stream` options

**Comment by farzer** [comment]
but it seems that `stream` options is no longer available

**Comment by farzer** [comment]
but it seems that `stream` options is no longer available from the Doc

**Comment by sidorares** [comment]
this is not in master yet, but if lands as is the usage would be similar to following code (example adopted from https://stackoverflow.com/questions/30658906/trouble-connecting-to-mysql-via-ssh/30669454#30669454 ): 

```js

var SSH2Client= require('ssh2').Client;
var sshConf = {
  host: 'ourCloudServerName.net',
  port: 22,
  username: 'myusername',
  password: 'mypassword',
};
var sqlConf = {
  user: 'root',
  password: 'rootPassword',
  database: 'SomeDatabaseName',
  timeout: 100000
};

var ssh = new SSH2Client();
ssh.on('ready', function() {
  ssh.forwardOut(
    // source IP the connection would have came from. this can be anything since we
    // are connecting in-process
    '127.0.0.1',
    // source port. again this can be randomized and technically should be unique
    24000,
    // destination IP on the remote server
    '127.0.0.1',
    // destination port at the destination IP
    3306,
    function(err, stream) {
      // you will probably want to handle this better,
      // in case the tunnel couldn't be created due to server restrictions
      if (err) throw err;

      // if you use `sqlConf` elsewhere, be aware that the following will
      // mutate that object by adding the stream object for simplification purposes
      sqlConf.stream = stream => stream;
      var db = mysql.createConnection(sqlConf);

      // now use `db` to make your queries
    }
  );
});
ssh.connect(sshConf);

```

**Comment by sidorares** [comment]
> but it seems that stream options is no longer available from the Doc

this is just proposed change, not merged to master

**Comment by farzer** [comment]
thanks a lot
