### ISSUE TITLE
Callback doesn't fire for an Insert query

### ISSUE THREAD

**Issue by atif089** [felixge/node-mysql#1274]
Below is my code

     var query = "INSERT INTO partners SET ?";
     var inserts = {
        partner_userid: options.partner_userid,
        password: options.password,
        email: options.email,
        phone_number: options.phone_number,
        registered_since : "FROM_UNIXTIME(" + (new Date()).getTime() + ")"
     };
     query = conn.format(query, inserts);
    
     conn.query(query, function(err, results) {
        console.log('aaaaaaaaaaaaaaaaaa');
        console.log(arguments);
        if (err) return cb(appConfig.errors._2010);
        cb(null, results.insertId);
     });

Statements in my callback statement don't seem to fire. Not even the console.log(). 

* The query works fine.
* The callbacks (console.log statements) seem to work fine for SELECT statements.
* I'm running Mocha + Istanbul Unit Tests

Here's the code for the test

    it("should create a new partner", function() {
      var options = {
                      partner_userid : "test123",
                      password : "A112s4#5^?sas",
                      email : "test123@gmail.com",
                      phone_number : "9748578452"
                    }
      
      myLib.add(options, function (err, results){
        expect(results).to.be.equal("aa");
        done();
      });

Is the call back really not firing or is it some mess up with the unit tests?

No matter what I write in my expect statement, the test is always successful. This doesn't happen to my unit tests with SELECT statements.

**Comment by atif089** [comment]
was missing "done" param in the test case. Time to sleep

**Comment by dougwilson** [comment]
Hi! Sorry I didn't get to your question before you were able to figure it out, but I'm glad you did!
