### ISSUE TITLE
insertId equals 0 with TIMESAMP primary key

### ISSUE THREAD

**Issue by lailune** [felixge/node-mysql#1275]
For example:

connection.query('INSERT INTO test SET post_id=?',[1], function(err, result) {
		console.log(result);
});

Output:

{ fieldCount: 0, 
affectedRows: 1, 
insertId: 0, 
serverStatus: 2, 
warningCount: 0, 
message: '', 
protocol41: true, 
changedRows: 0 }

**Comment by dougwilson** [comment]
Correct, this is how MySQL works; the insert id property of the response packets only works if your primary key is a positive integer.
