### ISSUE TITLE
Return all inserted ids on bulk insert

### ISSUE THREAD

**Issue by articho** [felixge/node-mysql#1284]
"Bulk" inserts using nested array only return one id. Is it possible for it to return all inserted ids?

> Nested arrays are turned into grouped lists (for bulk inserts), e.g. [['a', 'b'], ['c', 'd']] turns into ('a', 'b'), ('c', 'd')

This example inserts two rows, but returns only 1 insertId.

**Comment by dougwilson** [comment]
Unfortunately it is not possible for us to do, as this is a MySQL server limitation. The information is not provided over the MySQL protocol for us  to give to you.

**Comment by dreamcatcha** [comment]
This is the only solution I have;

    var values  = ["one", "two", "three"];
    var sql     = connection.format("INSERT INTO test (text) VALUES ?;", [_.chunk(values, 1)]);
    sql         += connection.format("SELECT id FROM test WHERE text IN (?);", [values]);

I use lodash .chunk to change values from ["one", "two", "three"] to [["one"], ["two"], ["three"]]

Works pretty easy

**Comment by jrichardsz** [comment]
According to this https://stackoverflow.com/questions/45076191/mysql-bulk-insert-in-node-js-how-to-get-all-insertids, just the first inserted id is returned.  It will be grateful if all the inserted ids in the result

**Comment by dougwilson** [comment]
https://github.com/mysqljs/mysql/issues/1284#issuecomment-157897272

> Unfortunately it is not possible for us to do, as this is a MySQL server limitation. The information is not provided over the MySQL protocol for us to give to you.
