### ISSUE TITLE
if contains word # in password ... 

### ISSUE THREAD

**Issue by daijongkim** [felixge/node-mysql#1285]
my database password contains # word 
so.. throw error in node-mysql 

please.... resove this problem..

**Comment by sidorares** [comment]
could you provide more details? '#' character should not be a problem

**Comment by dougwilson** [comment]
Hi @daijongkim , assuming you mean that you are trying to pass the MySQL URL like `mysql://myuser:my#pass@myhost`, this is actually an invalid URI, as you cannot have a `#` in the authority section, which is causing Node.js itself to be unable to parse the string. You need to properly encode special characters in the username and password. The correct encoding for my above example would be `mysql://myuser:my%23pass@myhost`

**Comment by daijongkim** [comment]
thanks. i'll try tomorrow.
