### ISSUE TITLE
Column convert string with "e" to numeric

### ISSUE THREAD

**Issue by AminaG** [felixge/node-mysql#1286]
When I have this data in a field:
29e1

It is converting it to: 290.

I didn't want it. I want it as a string: "29e1"

How to solve it?

I tried to solve it by reading the parser.js and connection.js but didn't found. I thought maybe it because you using parseFloat, but no.

**Comment by dougwilson** [comment]
Hi! Thanks for the report. I have never heard of this issue before and have no idea where to start looking based on this report. Can you provide the following information?

1. Version of Node.js
2. Version of this module
3. Complete code, DDL and steps for me to reproduce the issue

**Comment by dougwilson** [comment]
Hi @AminaG , I'm closing this issue due to a lack of response. If you can provide the above information, I'll gladly re-open and investigate!
