### ISSUE TITLE
GROUP_CONCAT () This being ignored in select ?

### ISSUE THREAD

**Issue by GutembergPraia** [felixge/node-mysql#1288]
GROUP_CONCAT () This being ignored in select this is normal ?

**Comment by dougwilson** [comment]
Hi! I use GROUP_CONCAT all the time and have never had that issue. Can you provide the version of Node.js, the version of this module, the version of MySQL, full code, DDL, and instructions on how to reproduce the issue?

**Comment by GutembergPraia** [comment]
npm version 3.4.0
node version 0.12.7
mysql version 2.9.0

  var query = 'SELECT agenda.agenda_id,agenda_dtatendimento, medical_id,user_name as medical_nome, clinic_name, clinic_address, clinic_phone,agendatipoatendimento_name,GROUP_CONCAT(specialty_name) FROM medical '
             + 'JOIN medicalspecialty ON medicalspecialty.ms_medical_id = medical.medical_id '
             + 'JOIN specialty ON specialty.specialty_id = medicalspecialty.ms_specialty_id '
             + 'JOIN agenda ON agenda.agenda_medical_id = medical.medical_id '
             + 'JOIN user ON user.user_id = medical.medical_id '
             + 'JOIN medicalclinic ON medicalclinic.mc_medical_id = medical.medical_id '
             + 'JOIN clinic ON clinic.clinic_id = medicalclinic.mc_clinic_id '
             + 'JOIN agendatipoatendimento ON agendatipoatendimento.agendatipoatendimento_id = agenda.agenda_agendatipoatendimento_id '
             + 'WHERE agenda.agenda_dtatendimento BETWEEN ? '
             + 'AND TIMESTAMP ? + INTERVAL ? day '
             + 'AND agenda.agenda_agendastatus_id = 1 '
             + 'OR ms_specialty_id = ? '
             + 'GROUP BY agenda.agenda_id'

  var dados = [agendaBusca.data,agendaBusca.data,agendaBusca.intervalo,agendaBusca.specialtys];


I'm using this way is correct ? You have an example? Thank you

**Comment by dougwilson** [comment]
I don't see anything obviously wrong there, but it still is not enough for me to determine the issue. I need the full code, DDL, and instructions so I can run it on my machine. Probably also need you to provide the data to populate my tables with as well.

**Comment by dougwilson** [comment]
Hi @GutembergPraia , I see you closed this issue earlier. Did you figure out the issue? If so, would you be wiling to post that the issue was and the fix for other people who come searching through the issue tracker with a similar problem?
