### ISSUE TITLE
Get field datatype

### ISSUE THREAD

**Issue by TheColorRed** [felixge/node-mysql#1290]
When I loop through the fields, I need to get the field type, but the type comes back as an integer. Is there any way to get the type as a string or convert the int to a string?

    connection.query('select * from interests', function(err, rows, fields) {
        for(var i = 0; i < fields.length; i++){
            console.log(fields[i].type)
        }
    });

**Comment by sidorares** [comment]
constants are defined [here](https://github.com/felixge/node-mysql/blob/master/lib/protocol/constants/types.js), you need to invert hash to get name from integer 

```js
var mysql = require('mysql');
var types = mysql.Types;

var typeNames = [];
for (var typeName in types) {
   typeNames[types[typeName]] = typeName;
}

connection.query('select * from interests', function(err, rows, fields) {
    for(var i = 0; i < fields.length; i++){
        console.log(typeNames[fields[i].type])
    }
});
```

**Comment by TheColorRed** [comment]
Perfect thanks!
