### ISSUE TITLE
How to set {multipleStatements: true} on pool connection?

### ISSUE THREAD

**Issue by mageddo** [felixge/node-mysql#1293]
In a normal conection when I am creating it I can set `{multipleStatements: true}`, how can I do it in a pool connection?

	// how do it here?
	pool.getConnection()

**Comment by dougwilson** [comment]
If you want it on all connections from the pool, you can include that option in your createPool call. If you want it only on specific connections, it is unfortunately currently impossible to do this, but there would be two solutions: use two different pools or someone will just need to implement the functionality.

**Comment by mageddo** [comment]
Hm, yes I want to use on the entire pool, is the syntax pass something like this?

	mysql.createPool({
	  multipleStatements: true
	});

**Comment by dougwilson** [comment]
Yep! Let me know if that doesn't seem yo be working, or feel free to close if it does.

**Comment by mageddo** [comment]
It Works!! Thanks
