### ISSUE TITLE
JSON Data Type

### ISSUE THREAD

**Issue by TheColorRed** [felixge/node-mysql#1295]
You're missing the new JSON data type [listed here](https://github.com/felixge/node-mysql/blob/master/lib/protocol/constants/types.js) (and maybe in other places too).

http://dev.mysql.com/doc/refman/5.7/en/json.html

**Comment by dougwilson** [comment]
Thanks for the heads-up! We're about to get all the constants from 5.7.9 added here, which will include the new JSON type added in 5.7.8.
