### ISSUE TITLE
pool acquireTimeout

### ISSUE THREAD

**Issue by guypaskar** [felixge/node-mysql#1297]
What happens when acquireTimeout triggers? does the request go back to the pool?

Is there any event of dequeue so that you can follow up that your query succeeds?

**Comment by dougwilson** [comment]
Hi @guypaskar , the `acquireTimeout` only applies to trying to acquire a connection from the pool. When the timeout occurs, what happens depends on what was available in the pool:

* If the pool had no available connections and tried to establish a new connection, then the connection must be established to the MySQL server within the timeout period. If it fails, then your callback will get an `err` object as the first argument.
* If the pool had an available connection, it will try to acquire that connection by running a PING command on it. If it does not respond within the timeout, then the connection is thrown away and it will re-try to establish a new connection and the rules above apply.

If there is a true failure, then your callback will always be called with the first argument, `err`, populated with the error.
