### ISSUE TITLE
datetime timezone to set reverse instade of actual 

### ISSUE THREAD

**Issue by sapkal-manish** [felixge/node-mysql#1298]
I have raised issue earlier. Please have a look first : https://github.com/felixge/node-mysql/issues/1260.

I have stored timestamp in my database /table hosted on Amazon RDS, where timezone sets as UTC.
Please assume following value in timestamp column:
```
2015-11-30 03:11:10.015824 
```
When I set timezone = '+00:00' in pool like this : 
```js
    pool = mysql.createPool({
        host: 'rds.clerbaufwmqz.ap-southeast-2.rds.amazonaws.com',
        user: 'user',
        password: 'pswd'
        database: 'db',
        multipleStatements : true,
        connectionLimit : 20
        dateStrings: false,
        charset :'utf8mb4',
        timezone : '+00:00'
    });
```
then I am getting result in json at client side as follows : 
```
30-11-2015 03:11:10
```
If I set timezone = '+05:30' in pool then I am getting 
29-11-2015 21:41:00  (which is wrong, as I feel)

If I set timezone = '-05:30' in pool then I am getting 
30-11-2015 08:41:00 (which is right)

But my question is, I am requesting this result from India, which has +05:30 time offset, so I think I have to set '+05:30' timezone in config in pool, but its shows wrong result. That's why I had set it '-05:30'. why???

**Comment by dougwilson** [comment]
Hi! There is not enough information to understand why your dates are working like that. Can you please provide your full code, version of Node.js, version of this module, and full instructions on exactly how I can see the same outcome as you?

**Comment by sapkal-manish** [comment]
I am residing in India, and I need all my reports in Indian Datetime (timezone +05:30) and my database has timezone (UTC). My website is hosted on localhost, which has +05:30 time offset. So, what should I have to set in timezone in node-mysql config file?

**Comment by dougwilson** [comment]
The `timezone` option in this module is for you to tell this module what timezone your MySQL server is using so we can property inflate the times coming over the wire into a JavaScript `Date` object. If your MySQL server is in UTC, then your should have `timezone: '+00:00'`. The module does not care in any way what the time zone is on the server you are running this module on, as it can not only see that information, but also that information is unnecessary for how JavaScript `Date` objects work.

If you are still really confused and just need an out, simply provide the option `dateStrings: true` and then all the returned dates and times will just be the exact string your MySQL server returned and you can parse them however you like :)

**Comment by sapkal-manish** [comment]
I have set dateStrings: false and timezone : '-05:30' in config, then I get date what I expect (perfect local date time as per IST (Indian Standard Time), but don't know how? because as you mentioned above If I set here timezone : '+00:00', then my local date shows me less by 05:30 from localtime.

**Comment by dougwilson** [comment]
Hi! There is not enough information to understand why your dates are working like that. Can you please provide your full code, version of Node.js, version of this module, and full instructions on exactly how I can see the same outcome as you?

**Comment by sapkal-manish** [comment]
Node.js : v0.12.8
mode-mysql : 2.8.0

pool = mysql.createPool({
        host: 'rds.clerbaufwmqz.ap-southeast-2.rds.amazonaws.com',
        user: 'user',
        password: 'pswd'
        database: 'db',
        multipleStatements : true,
        connectionLimit : 20
        dateStrings: false,
        charset :'utf8mb4',
        timezone : '-05:30'
    });

I have one table on Amazon RDS with timestamp(6) datatype and value has "2015-12-01 06:15:21.126911", default timezone is UTC. When I get result on client side in Javascript It shows me "2015-12-01T11:45:21.126Z". Which is perfect as per my local time zone.
But If I set timezone "+00:00", as you mentioned, then It shows me  "2015-12-01T06:15:21.126Z", which is wrong. 
Is it ok or you need more information. Due to company policy, I can't send you source code. sorry for inconvenience.

**Comment by dougwilson** [comment]
Unfortunately that us still not enough information. I need to be able to reproduce the issue, so I need enough code I can copy and paste and run to see it, I need instructions to create the necessary tables, the data to load into the tables, and the instructions on how to configure my MySQL server. Without that information, there is nothing I can say besides if you think it's a bug, please offer a PR with a fix.

**Comment by sapkal-manish** [comment]
CREATE TABLE `feedbackdet` (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `email` varchar(50) NOT NULL,
  `userid` mediumint(8) unsigned DEFAULT NULL,
  `feedback` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `insdate` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

INSERT INTO feedbackdet(email, userid, feedback)
VALUES ('aaa@aa.com', 1, "this is testing");

select * from feedbackdet
It's shows me "2015-12-01 07:41:18.663386" in "insdate" field, but when I fetch it shows me wrong.

btw, I am not much aware with Github, so I don't know what is "PR" means. I don't know weather this is bug or my mistake.  
Can you check it on TeamViewer? Is it ok for you? I am just asking. 
Thanks.

**Comment by sapkal-manish** [comment]
What happen sir? Do you need more details? I'm waiting sir. Thanks

**Comment by dougwilson** [comment]
Hi @sapkal-manish , I'm in a very different time zone from you and we were chatting at 2:30am my time, so I had to go to sleep sometime. I'll take a look again during night time in my time zone when I have time for open source things :)

**Comment by dougwilson** [comment]
In the meantime, if you see this before I'm back on, I see you are not even using the latest version of this module. Can you just try 2.9.0 to see if there is a difference in behavior? You may also want to try installing the unrelease version from GitHub as well to see (instructions at https://github.com/felixge/node-mysql#install).
