### ISSUE TITLE
Execute parallel http requests/ set multiple connections

### ISSUE THREAD

**Issue by apoorv173** [felixge/node-mysql#1301]
Hi,
In my application, there are around 10 ajax calls on page load, and if I insert console logs in the front end(before the ajax query is triggered and success) and the back end(where the SQL query is initiated and response is received), its shows the time difference as 14 sec and 3 sec in front end and back end respectively. Services previous to this take around 2 or 3 sec at both the front end and server side.
So, I think some of the queries are getting queued at the back end or I am not able to set multiple connections.
Code snippets,
First module where the pool is created

<pre>
function DataConnectionLayer() {
    var self = this;
    self.connectDB();
};
DataConnectionLayer.prototype.connectDB = function() {
    var self = this
    var pool = mysql.createPool({
        connectionLimit: 100,
        host: constants.getValue('db_host'),
        user: constants.getValue('db_user'),
        acquireTimeout: '30000',
        password: constants.getValue('db_password'),
        database: constants.getValue('db_database')
    });
    pool.getConnection(function(err, connection) {
        if (err) {
            console.log("error occured and logged ")
            console.log(new Date());
            console.log(err);
            // self.stop(err);
            // self.configureExpress(connection);
            self.connectDB();
        } else {
            self.configureExpress(connection);
        }
    });
}
DataConnectionLayer.prototype.configureExpress = function(connection) {
    var router = express.Router();
    app.use(bodyParser.urlencoded({
        extended: true
    }));
    app.use(bodyParser.json())
    console.log(application_root);
    app.use(express.static(application_root + '/public'));
    app.use('/api', router);

    var apiController = new <strong>dataController</strong>(router, connection);
    this.startServer();
}
</pre>

Second module where after routing queries are triggered,

<pre>
function dataController(router, connection) {
    var self = this;
    self.handleRoutes(router, connection);
}

dataController.prototype.handleRoutes = function(router, connection) {
    var self = this;
    router.get("/", function(req, res) {
        res.json({
            "Message": "Hello World !"
        });
    });

    router.get("/getDetails", function(req, res) {
        self._setResponseHeader(res);
        
var old_time = (new Date()).getTime();
        var query = "";

        connection.query(query, function(err, data) {
var difference = (new Date()).getTime() - old_time;
                	console.log("time taken: " + (difference/1000));
            if (err) {
            	

                self._sendErrorResponse(res);
            } else {
                
            }
        })

    });

}
</pre>

And one more problem I faced, if I write <strong>connection.release()</strong>, in the callback of the query, then , in the logs it throws an error, connection already closed.

**Comment by dougwilson** [comment]
Hi! I've seen people post this exact Express + MySQL pattern here a few times lately, so I'm assuming it must be in an article somewhere. The short answer is that pattern is completely wrong and will never work for taking advantage of pooling connections and parallel execution, I'm sorry to tell you that.
