### ISSUE TITLE
MySql Dump

### ISSUE THREAD

**Issue by ralves09** [felixge/node-mysql#1308]
A suggestion....
Why not incorporate a 'mysqldump' and 'mysqlrestore' features.

**Comment by dougwilson** [comment]
Hi! Those seem like good ideas, but doesn't fit into this library. This is just a protocol library, meant for people to use to build things like `mysqldump` or `mysqlrestore`.

**Comment by pbassut** [comment]
@dougwilson Is there any code out there that does that though? I want something as simple as dump a database to a sql file and restore an sql into a database.
The beauty of all this is that it discards the need for a binary and can be used cross-platform.

**Comment by dougwilson** [comment]
I don't have a comprehensive list of all node.js mysql modules out there and no one has come back here to tell of a module that does this functionality. So it's possible it doesn't exist and someone just needs to build it.
