### ISSUE TITLE
Question/Help Wanted: Recursive/Repeating connections in pool?

### ISSUE THREAD

**Issue by wesleygauntt** [felixge/node-mysql#1309]
Hello, 

This question has come up after a few days of testing  and having bots ping a status route which exercises connections to databases. Current function is used below as middleware for requests on a node/express server, and the pool variable is created on app initialization.

```js
var mysql = require('mysql');
var pool  = mysql.createPool({
  connectionLimit : 1000,
  host     : dbconfig.connection.host,
  user     : dbconfig.connection.user,
  password : dbconfig.connection.password,
  database : dbconfig.database,
  ssl: dbconfig.connection.ssl
});

function setupMysqlConnection(req, res, next){

  log.debug("Setting up sql connection.");
  req = req || {};

  if(!req.sqlConnectionAttempts){
    req.sqlConnectionAttempts = 1;
  }

  if(req.sqlConnectionAttempts > 25){
    errorHelpers.handleError(res, 'More than 25 sql connection attempts.');
    return;
  }

  pool.getConnection(function(err, connection) {
    if(err){
      log.warn("Error getting pool connection: ", err);
      log.info("Attempting to re-connect with SQL.");
      req.sqlConnectionAttempts += 1;
      setupMysqlConnection(req, res, next)
      return;
    }
    req.sqlConnection = connection;
    next();
  });

  pool.on('connection', function (connection) {
    log.debug('Connected with threadId: ', connection.threadId);
  });

  pool.on('enqueue', function () {
    log.info('Waiting for available connection slot');
  });

  req.on('end', function(){
    //Give some time to process outstanding async sql queries, then close connection
    if(this.sqlConnection){
      setTimeout(function(){
        var connectionId = this.sqlConnection.threadId;
        log.debug("Releasing connectionId: ", connectionId);
        this.sqlConnection.release(function(err){
          if(err)
            log.warn("Error releasing sql connection: ", err);
          else
            log.debug('Sql connection released for threadId: ' + connectionId);
        });
      }.bind(this), 5000);
    }
  });
}
```

Our connection to SQL remains a constant, and there are no signs of a failed connection or any attempts for our function to recurse upon itself. What we are seeing though in our logs, is a HUGE excess of "Connected with threadId: ". An example as shown below:
```
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.308Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.309Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.309Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.309Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.309Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.309Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.309Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.309Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.309Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.309Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.309Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.309Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.310Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.310Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.310Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.310Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.310Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.310Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.310Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.310Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.310Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.310Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.310Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.310Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.311Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.311Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.311Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.311Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.311Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.311Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.311Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.311Z"}
"Connected with threadId:  255082","time":"2015-12-16T13:40:09.311Z"}
```

This repeats many more times, and will almost always have the same threadId depending on the request. It appears to be adding incrementally. As a note, there were no errors in connecting with SQL, and the recursive call to create a connection on an error is never made.

There are a few things from the code that might point towards this behavior, and as a result here are some of my questions:

1. The `pool` variable is defined outside of the function, and has a listener inside of the function. Each time a connection is defined, why would the same thread id be printed each time? Perhaps it prints one time for each connection in the pool, though only prints a single thread id? Maybe this is a scope issue for our connection/pool definition?

2. It got the the point where the above logs were being printed so frequently, and really started to take a toll on server performance. Perhaps there are connections that never get released in the pool and causes a huge backup?

3. Even small scale examples lead to duplicate printings (of ~2-10 times) is this because of the way we are creating the pool and requesting connections?

Any and all help is appreciated, and if more information is needed I'll be happy to post.

**Comment by dougwilson** [comment]
Hi! There are a lot of questions here, but I think, perhaps they may all be answered with a single statement: you are not using Node.js EventEmitters correctly. For instance, in your example code, you keep calling `pool.on('connection', function (connection) {` for every single request. This means that after 5,000 request, you will now have 5,000 event listeners on the `connection` event on the single `pool` object. This would mean that when one new connection is made, the `Connected with threadId: #` will print 5,000 times.

You should have gotten a bunch of warnings from Node.js from your code above, telling you that you have an event emitter leak (`warning: possible EventEmitter memory leak detected.`). This would have pointed to the line of code in your middleware as the source of the leak.

To fix this leak, you need to move the listeners outside of your middleware, so they are only attached once to the pool:
![move ee](https://cloud.githubusercontent.com/assets/67512/11858742/19057c48-a432-11e5-964a-a65f1679b25f.png)

**Comment by wesleygauntt** [comment]
@dougwilson, thanks for taking the time to reply! I think that we can go ahead and mark this as closed -- already in small scale local testing the behavior is looking much better with your suggested fix. Thank you!
