### ISSUE TITLE
haproxy & node-mysql not working together

### ISSUE THREAD

**Issue by coreygeesey** [felixge/node-mysql#1313]
We're attempting to set up a redundant architecture using haproxy (we want to keep everything going through haproxy as well). We're using a pool of connections that connects to db1 (which is part of a mysql cluster), and if/when for some reason, mysql goes down on that system, haproxy redirects all requests to db2.

Now, obviously that means that all connections within the pool are now bad. My understanding of the pool is that when getConnection is called, the connection should be checked & reconnected afterwards. With haproxy in the middle, it doesn't seem to be doing that for us. At this point, there is no error being thrown for us, and when we attempt to run a query, we get an uncaught exception:

[Error: Connection lost: The server closed the connection.,     at Protocol.end (... /node_modules/mysql/lib/protocol/Protocol.js:103:13

Our code is as follows:

    // Connect to Mysql
    db = mysql.createPool({
	acquireTimeout: 4000,
        connectionLimit: 10,
        waitForConnections: true
        queueLimit: 0, // No Limit
        host: c.MYSQL_HOST,
        user: c.MYSQL_USER,
        password: c.MYSQL_PASS,
        database: c.MYSQL_DB,
        insecureAuth: true
    });

    db.on('connection', function(connection) {
        log.debug("New Connection.");
    });

    db.on('error', function(err){
        log.error('db error: ' + err.name, err.message);
    });

    db.getConnection(function(err, connection) {
                    if (err) {
                        msg = 'Failed to get connection from pool'
                        throw err;
                    }
                    connection.beginTransaction(function(err) {
                        if (err) {
                            msg = 'Failed to start db transaction';
                            throw err;
                        }
                        connection.query('Insert into `Application` (map,appkey) values (?,?) on duplicate key update map=values(map)', [dbValue, appKey], function(err, result) {
                            if (err) {
                                msg = 'Failed to load config records';
                                throw err;
                            }
                            connection.commit(function(err) {
                                if (err) {
                                    msg = 'Failed to add application to db';
                                    return db.rollback(function() {
                                        throw err;
                                    });
                                }
                                log.debug("Successfully committed application to the database")
                            });

                            connection.release();

                            log.debug('Successfully added application with appKey ['+appKey+'] to the database.');
                        });
                    });
    });

**Comment by dougwilson** [comment]
Hi! I would love to dig into the issue, but there isn't enough information for me to even begin to setup the same situation on my own computer. Without the ability to reproduce, I would probably have to lean on you to offer up the suggested fix to this module, unfortunately.

As far as you getting an uncaught exception, it's because you are throwing the error from outside a try-catch block. Don't use the `throw` keyword outside a try-catch and it won't be an uncaught exception :)

**Comment by coreygeesey** [comment]
Ah, sorry, that isn't the entire code. I picked out what I figured you'd need in the code. The actual code spans several modules, and that particular piece is in a try/catch statement.

Let me know what information you need and I can provide it.

Node v 0.10.9, node-mysql 2.9.0, running on CENTOS 6. MariaDb (I guess I should have clarified that as well) v 5.5.46.

**Comment by dougwilson** [comment]
Pretty much as much instructions & code as possible. If you can reproduce it with that code, that's fine (but when you said there is an uncaught exception among a bunch of paces where it's coded to be uncaught, it's hard to make good comments on that). For example, I only hear there is a thing call "haproxy"--I have no idea what it is, how to set it up or anything. If I need that in order to reproduce, you'll probably have to teach me how to install that on my Windows machine.

**Comment by dougwilson** [comment]
Hi @coreygeesey , any progress on providing those instructions? Without them, I will have to lean on you to offer up a pull request to address the issue.

**Comment by crh3675** [comment]
Releasing a connection before commit() might well cause that error

**Comment by dougwilson** [comment]
Hi @coreygeesey, I'm going to close this issue since I still haven't heard anything back. If you can get that information, I'll re-open the issue!
