### ISSUE TITLE
DATE_FORMAT(...) inside SELECT not working correctly with nestedTables = true?

### ISSUE THREAD

**Issue by mitomm** [felixge/node-mysql#1316]
Hi there,

I'm trying remove the seconds from a MySql "Time" field inside a SELECT query, however I cannot get it to work with "nestTables" set to "true". A simple example to reproduce the error would be the following (for simplicity reasons, I did join a second table in this example, since it doesn't make a different for the error to occur):

     var sql = 'SELECT DATE_FORMAT(startTime,\'%H:%i\') as startTime,endTime FROM MyTable'
     var options = {sql, nestTables: true};
     connection.query(options, function(err, rows) {
     ....
          console.log(rows)
     });

which logs rows that look like this (Note that the startTime is outside of the "MyTable object"):

    [ RowDataPacket {"'': { startTime: '08:00' },MyTable: { endTime: '17:00:00' } } 
     ,... ]

instead of something along those lines:

    [ RowDataPacket {MyTable: {startTime: '08:00', endTime: '17:00:00' } } 
     ,... ]

Am I missing something?

**Comment by dougwilson** [comment]
Hi! Unfortunately this is a limitation of the MySQL protocol itself. The `nestTables` feature uses the information from the fields packets the MySQL server sends back to understand what the name of the column and the table is, to construct the object. Unfortunately all calculated fields have no table information in the packets.
