### ISSUE TITLE
SELECT query only returns undefined rows

### ISSUE THREAD

**Issue by WalkingCore** [felixge/node-mysql#1318]
So here's my code:
```js
connection.query({
  sql: 'SELECT * FROM `game_table` WHERE `creatorsent` = ?',
  timeout: 40000, // 40s
  values: [0]
}, function (error, rows, fields) {
  if (error) {console.log(error);}else{
//here is code with rows[1] and rows[2]
```
and it says that `rows[1]` for example is `undefined`...I checked in phpmyadmin and the query is correct and it finds a result there.

**Comment by WalkingCore** [comment]
and if I jsut write console.log(rows) it logs all the correct rows from the database.

**Comment by dougwilson** [comment]
Hi, @WalkingCore , from your description so far, the fact that the rows show up fine in your `console.log(rows)` statement tells me the rows are returned just fine. Perhaps you just made a typo or other mistake in your code that you did not paste? Can you paste the code that is not working?

Also, I keep seeing you refer to `rows[1]` above. I'm not sure if this is the reason, but just to know, in the JavaScript language, the first element of an array is `0`, so your first row is available at `rows[0]`, and not `rows[1]`.

**Comment by dougwilson** [comment]
Hi @WalkingCore , I'm closing this issue since I didn't hear anything back from my response/question. Please feel free to reply here when you can and I can always re-open!
