### ISSUE TITLE
Question: prevent data corruption

### ISSUE THREAD

**Issue by AdriVanHoudt** [felixge/node-mysql#1319]
What is the best way to deal with this. I have found that using async + making sure data is correct is somewhat hard.
For example doing a lot of inserts into a table but only do every insert under certain conditions while any previous insert can affect the decision. Doing it async in node is no option (found out the hard way) and unique key also not. 
Just an on before insert trigger or?

**Comment by AdriVanHoudt** [comment]
So I tried and tested a trigger and this seems to work like I want. Will leave open for a bit because I am still interested to hear opinions.

**Comment by dougwilson** [comment]
Hi @AdriVanHoudt , what kind of data corruption are you experiencing? There isn't really enough detail on what you are trying to do and what exactly is not meeting expectations to really give any kind of good answer. There is a lot of literature on how to use MySQL server for all kind of different tasks. Is the question more about using MySQL itself or a question for how to implement some pattern with this library?

I'm happy to help, but just need more detail.

**Comment by AdriVanHoudt** [comment]
more of in general with the async way of node.
what I did before was run a select as a check and based on that do an insert, the problem with that is that on higher loads or with bulk insert all the checks run and give clearance for the insert and then everything inserts. Ideally it should select and insert sync/safe. The basic stuff we have now is just use unique keys which helps but does not work for more complex stuff. What I did now is add an `insert before` trigger which does seem to work and returns a signal error when the insert is not allowed. Is it a good solution to use the trigger and is it ok/good practice to signal an error and catch that error in the code, as in does generating errors in mysql have a large overhead or something.

**Comment by dougwilson** [comment]
Hi @AdriVanHoudt , you may want to do something like start a transaction with the isolation level that would best work for you. This would allow you to do a SELECT + INSERT. Part of MySQL is that if everything is in a single instance, you get full ACID across all your tables. MySQL provides many ways to get your actions, even within async Node.js, to be atomic in nature, by using locks and isolation levels within transactions.

I hope this helps point you in the right direction! Note that moving that logic into a stored procedure does not actually fix the race condition if all the statements are still within separate transactions; it will just be harder to trigger the race condition now.

**Comment by AdriVanHoudt** [comment]
thanks for the info, we ended up with adding a column to the table and adding a unique key to that, the trigger was also getting in a condition where it didn't do the expected thing.
