### ISSUE TITLE
InsertId missing from INSERT with SELECT where clause

### ISSUE THREAD

**Issue by dreamcatcha** [felixge/node-mysql#1320]
if I run the following;

    var insertQuery = "INSERT INTO comments (profile_id, post_id, comment_text, created_at) VALUES (?, ?, ?, ?);";
    var params = [userId, postId, commentText, createdAt];

I will get an insert Id, but if I do the following;

    var insertQuery = "INSERT INTO comments (profile_id, post_id, comment_text, created_at) SELECT ?, ?, ?, ? FROM dual WHERE EXISTS (SELECT post_id FROM posts WHERE post_id = ? AND status = 1);";
    var params = [userId, postId, commentText, createdAt, postId];

is there any specific reason I can remedy this with?

Cheers

**Comment by dougwilson** [comment]
Hi! This is how MySQL itself works: the protocol only contains the insert id if the last statement was only a single-row insert statement. The form INSERT INTO ... SELECT does not meet the requirement and the MySQL server never sends back the id.

**Comment by dreamcatcha** [comment]
Ok, even when the statement can only possibly insert one record, its the INSERT.... SELECT that isn't supported?

**Comment by dougwilson** [comment]
That's correct. MySQL server will not send us the insert id if the statement has the potential to insert more than one record.

**Comment by dreamcatcha** [comment]
Cheers mate ;)
