### ISSUE TITLE
RangeError when streaming a large table

### ISSUE THREAD

**Issue by refaelos** [felixge/node-mysql#1324]
I'm trying to stream a large query and do some operations on it.

```js
var connection = mysql.createConnection({
  host    : '...',
  port    : '...',
  user    : '...',
  password: '...',
  database: '...',
  timezone: '+0000'
});
var retrieveQuery = 'SELECT * FROM table;';
connection.query(retrieveQuery)
  .on('error', function(err) {
    // Handle error, an 'end' event will be emitted after this as well
    clbk(err);
  })
  .on('fields', function(fields) {
    // the field packets for the rows to follow
  })
  .on('result', function(row) {
    //...
  })
  .on('end', function() {
    // all rows have been received
  });
```

After it fetches to around 2M rows, I'm getting this error:
```
buffer.js:71
    throw new RangeError('Attempt to allocate Buffer larger than maximum ' +
          ^
RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes
    at new Buffer (buffer.js:71:11)
    at Parser.append (/home/ubuntu/soomla-scripts/node_modules/mysql/lib/protocol/Parser.js:111:14)
    at Parser.write (/home/ubuntu/soomla-scripts/node_modules/mysql/lib/protocol/Parser.js:25:8)
    at Protocol.write (/home/ubuntu/soomla-scripts/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/ubuntu/soomla-scripts/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at Socket.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)
    at _stream_readable.js:717:7
    at process._tickCallback (node.js:355:11)
```

It happens around the same amount of rows fetched every time I run it.

Any ideas?

**Comment by crh3675** [comment]
How large is the table? Perhaps TCP buffer size limitations?

**Comment by refaelos** [comment]
Are you saying the the issue is on the DB ?

I'm used to stream data this way on large tables and it used to work perfectly. Maybe this specific table is bigger. What I don't understand is why the data is even accumulated in memory and not streamed line by line?

**Comment by crh3675** [comment]
If you are using INNODB tables that have the buffer pool set too high, it could be MySQL trying to allocate memory for a large dataset beyond the buffer pool size. Can you reduce the MySQL innodb-buffer-pool?

**Comment by refaelos** [comment]
It didn't help. We had to do smaller queries.

**Comment by dougwilson** [comment]
Hi @refaelos , this seems like a real issue with this module. I'm going to re-open this so I don't forget to investigate.

**Comment by refaelos** [comment]
Ok thanks.

When we do smaller queries it doesn't happen so either the DB can't handle larger queries or the module doesn't handle them correctly.

**Comment by dougwilson** [comment]
Hi @refaelos , my suspicion is that we are, at some point, trying to create a Node.js `Buffer` object that is too large. If this is the case, we should be able to keep the buffers separate and then change all the code to operate on a virtual buffer that is a view across multiple underlying buffers.

**Comment by zeluis9** [comment]
Just my 2 cents here.. What is missing is a check if the write on the stream is successful. If it's not, it has to wait until `drain` was completed.
Pseudo-code:
```javascript
let success = myStream.write(myObject);
if(!success) {
    return myStream.once('drain', function () {
          return iterateThroughNext();
        });
}
iterateThroughNext();
```
Sorry if I misunderstood something here.

**Comment by dougwilson** [comment]
Hi @zeluis9, can you point to what part of the code you are referring to?

**Comment by zeluis9** [comment]
@dougwilson [https://github.com/felixge/node-mysql/blob/master/lib/protocol/sequences/Query.js](Query class)

**Comment by zeluis9** [comment]
Replace [line 206 and following](https://github.com/felixge/node-mysql/blob/master/lib/protocol/sequences/Query.js#L206) with something like this:
```javascript
this.on('result',function(row,i) {
    if (!stream.push(row)) {
      self._connection.pause();
      return this.once('drain', function(){
        stream.emit('result',row,i);  // replicate old emitter
      });
    }
    stream.emit('result',row,i);  // replicate old emitter
  });
```

**Comment by dougwilson** [comment]
Thanks, @zeluis9, but it is not clear how that will specifically fix the problem outlined in the original post, but what you are highlighting may be an unrelated bug to this. Would you be willing to create a pull request to fix it? Please include a test that files without the change and passes with the change.

**Comment by zeluis9** [comment]
I will make it asap @dougwilson :)

Às 18:14 de 26-02-2016, Douglas Christopher Wilson escreveu:
