### ISSUE TITLE
GROUP_CONCAT with "nestTables" option created empty table strings

### ISSUE THREAD

**Issue by bartonsprings** [felixge/node-mysql#1325]
I am using the "nestTables" option in my sql so that formatting the results in JSON format is much simpler and faster. But when I use the GROUP_CONCAT then the results for that GROUP_CONCAT is put in a separate empty table. Is there a way to specify the table name under which it should go?

Current example output and you can see the empty table created by node-mysql:
{
      "Table1": {
        "Field1": "3d1vx6074o",
        "Field2": "3d1vx6074o",
        "Field3": "or625607jl",
      },
      "": {
        "ConcatFields": "1,1"
      },
          ..........

Thanks again for a great library!

**Comment by bartonsprings** [comment]
I saw a duplicate question by another person. Now I understand that this is not a node-mysql issue. Is there any way to force a table name in Mysql itself for the Concat result so that node-mysql does not pick up empty table names?

Thanks

**Comment by dougwilson** [comment]
Hi! Unfortunately the MySQL protocol does not provide any way to influence the table names coming back in the packets.

If you are running up against this limitation, the only good solution is to not use the nestTables feature and return all your column names in a way that you can transform them in some helper code you write.

For example, if you return all columns in the format "table.column", then you can write a helper that will split on the dot and restructure the object in a generic way.

I hope this helps :)
