### ISSUE TITLE
Why select result return an array of RowDataPacket?

### ISSUE THREAD

**Issue by vthai** [felixge/node-mysql#1330]
I am wondering why the query result for a SQL SELECT return something like this:
```
[ RowDataPacket {
        id: 19,
        username: 'admin',
        status: 1,
        role: 2,
        phone: '123456789',
        first_name: 'admin',
        last_name: 'admin' },
      RowDataPacket {
        id: 23,
        username: 'abhjj',
        status: 1,
        role: 2,
        phone: '123456789',
        first_name: 'admin',
        last_name: 'admin' },
      RowDataPacket {
        id: 24,
        username: 'abheee',
        status: 1,
        role: 2,
        phone: '123456789',
        first_name: 'admin',
        last_name: 'admin' } ] 
```

Shouldn't it just return something a "pure" JSON array like this:
```
[{"id":19,"username":"admin","status":1,"role":2,"phone":"123456789","first_name":"admin","last_name":"admin"},{"id":23,"username":"abhjj","status":1,"role":2,"phone":"123456789","first_name":"admin","last_name":"admin"},{"id":24,"username":"abheee","status":1,"role":2,"phone":"123456789","first_name":"admin","last_name":"admin"}]
```

Maybe I am new to Javascript but the one returned by node-mysql doesn't even qualified as JSON object? no colon after RowDataPacket?

**Comment by dougwilson** [comment]
Hi @vthai ! We return an array of `RowDataPacket` objects because this is a low-level driver library. But regardless, the output you provided above is not JSON because you didn't use a JSON serializer to display it. It looks like you probably used `console.dir` or `console.log`, which Node.js uses a different formatting.

Try using this: `console.log(JSON.stringify(result))`

**Comment by sidorares** [comment]
It might actually help with performance as well. Because all rows are instances of the same RowDataPacket class, they all share same 'hidden class' - see for example http://s3.mrale.ph/nodecamp.eu/#41 for explanation

**Comment by Deepavathi** [comment]
Im getting results like this on using console.log(JSON.stringify(result)). How to read StatusFlag and Statusmessage from this.

[
	[{
		"StatusFlag": 0,
		"StatusMessage": "Dot User does not exists. Please register"
	}], {
		"fieldCount": 0,
		"affectedRows": 0,
		"insertId": 0,
		"serverStatus": 34,
		"warningCount": 0,
		"message": "",
		"protocol41": true,
		"changedRows": 0
	}
]

**Comment by sugandanrg** [comment]
dougwilson.. Is there any way to get nested JSON outputs from a certain SELECT statement?

**Comment by ZeroHackeR** [comment]
Here's how to get rid of "RowDataPacket" and return a JS object:

`JSON.parse(JSON.stringify(result))`
