### ISSUE TITLE
Using procedures/functions on the output of a query does not work

### ISSUE THREAD

**Issue by grumpyoldman-io** [felixge/node-mysql#1341]
I have functions in my mysql to convert UUID to binary 16 and back again. These work.

In Mysql when I execute the query:
`SELECT UuidFromBin(uuid) FROM table`

I get the correct output:
`f37b3741-cb57-11e5-bbec-650c817ca5da`

**But**

when I try the same query in node-mysql:
`SELECT UuidFromBin(uuid) FROM table`

I get:
`//UuidFromBin(uuid): <Buffer 66 33 37 62 33 37 34 31 2d 63 62 35 37 2d 31 31 65 35 2d 62 62 65 63 2d 36 35 30 63 38 31 37 63 61 35 64 61>`

*edit:*
the insert function does work from node-mysql:
`INSERT INTO table (uuid) VALUES (UuidToBin('f37b3741-cb57-11e5-bbec-650c817ca5da'))`

I suspect the function is stripped from the fields when parsing/sending the `SELECT` query. Or is it something I am doing wrong?

**Comment by sidorares** [comment]
make sure your charset is not binary, or just convert result ( which is node Buffer ) to string with `.toStringg()`

see code here - https://github.com/felixge/node-mysql/blob/13091825e11096748b9273c5b17527c338fec764/lib/protocol/packets/RowDataPacket.js#L113-L116

**Comment by grumpyoldman-io** [comment]
Ah the `.toString()` worked, It was indeed the case that the results were returned as binary 32, I didnt notice because all my direct mysql output was formatted in my IDE. I changed it to give the output in varchar and now it works even without the `.toString()`.
