### ISSUE TITLE
Field warningCount not returned in SELECT commands

### ISSUE THREAD

**Issue by edrabc** [felixge/node-mysql#1343]
For insert, update or delete operations the `warningCount` field is returned inside the result object. Is there a way to get the same `warningCount` for SELECT commands? I guess the `rows` object would not be the best place, but maybe `fields` object might include that information.

I see that the value is correctly received and parsed inside EofPacket and OkPackets but never gets propagated to the response objects. Is there a reason for that?

Thanks!

**Comment by sidorares** [comment]
no, only if there is zero fields in response ( usually insert command, variable assignment or stored procedure call ) OK packet with `warningCount ` is returned
![com_query response diagram](http://dev.mysql.com/doc/internals/en/images/graphviz-3ab2ba81081a7f3cc556d11fd09f50341bba6f15.png)

see the diagram, if you have rows the response is fields + eof + rows + eof, if not it's zero field count + [ok packet](http://dev.mysql.com/doc/internals/en/packet-OK_Packet.html)

**Comment by edrabc** [comment]
Ok. Thanks for the details!
