### ISSUE TITLE
Fallback when mysql goes down

### ISSUE THREAD

**Issue by astutesoftware** [felixge/node-mysql#1344]
Has anyone figured out a logic that takes care of operations when MYSQL goes down.
Ideally if mysql is not available and we have data, we would write to a log file and then when mysql is available we would push things from the log file back to the database.
What would be the right way to do it?
If we write to a log file with all the queries and when mysql connection is restored - how do we remove the entries from the log file which got successfully fired?

**Comment by dougwilson** [comment]
Hi @astutesoftware, that question is probably too broad for the issue tracker of this module. It is definitely something you could implement using this module for the underlying connection, yes, but going into the detail of a management implementation is just beyond the scope of here, I'm sorry.

This module is just meant to be a low-level driver module, simply providing connections out when asked and shuttling the data over the protocol.

**Comment by astutesoftware** [comment]
understood. meanwhile i did come up with a solution. will leave it as a note on this thread for anyone with similar needs.

On non-availability of mysql server we write the SQL statements to a taffydb persistent store.
On restoration of connectivity we push all the SQL statements in batches of X number of queries back to the mysql. Batching several queries is recommended over several individual queries fired one by one.

http://www.taffydb.com/
