### ISSUE TITLE
Mysql version supported by Node

### ISSUE THREAD

**Issue by Tibicenas** [felixge/node-mysql#1347]
hi,
maybe is a silly question but, where can i see what versions of mysql are supported by each Node version? 
Thanks in advance

**Comment by sidorares** [comment]
all node versions starting from 0.6 are supported

With mysql versions: core protocol is identical for all mysql versions back to really old ones, as far as I know everything exposed by this library API works with any mysql version

**Comment by Tibicenas** [comment]
So if i use a node version > 0.6 and use this package, i don't have to worry about mysql version because all will be supported ?

Thanks by your fast replay :)

**Comment by sidorares** [comment]
yes, you don't have to worry :)
