### ISSUE TITLE
can't access results from method call

### ISSUE THREAD

**Issue by DannyCork** [felixge/node-mysql#1348]
I have a simple function which works:

```js
var x = test();
console.log (x);

function test()
{
return (6);
}
```

However I can't get a value back from 

```js
var x = test();
console.log (x);

function test() {
 connection.query(sql, function(err, results) {
    if (err) throw err;
    console.log(results);
    connection.end();
    return (results);
  });
```

The line     console.log(results); contains a value retrieved from the db call. However after this line results if undefined. Does connection.end() kill results() ?

Any ideas what I'm doing wrong here ?
Thanks in advance :)

**Comment by sidorares** [comment]
why are you returning results with `return (results)`? They are not used by callee. Your handler function as called from here - https://github.com/felixge/node-mysql/blob/13091825e11096748b9273c5b17527c338fec764/lib/protocol/sequences/Sequence.js#L96
As you can see result is discarded

**Comment by dougwilson** [comment]
Yea, this is a simple misunderstanding, new to Node.js, callbacks, and event loops. The issue with your code @DannyCork, is that your `function test() {` does not actually return any value; the `return (results);` is the return for an anonymous function that is called later.

You'll need to re-write your example using callbacks all the way through:
```js
test(function (x) {
  console.log(x);
});

function test(callback) {
 connection.query(sql, function(err, results) {
    if (err) throw err;
    console.log(results);
    connection.end();
    callback(results);
  });
}
```

**Comment by DannyCork** [comment]
Thanks for the great example!
