### ISSUE TITLE
New connection never closes

### ISSUE THREAD

**Issue by xerardoo** [felixge/node-mysql#1351]
Hi, when I close a connection is actually never closes , so I can see in the status.

[`Status MariaDB`](http://i.stack.imgur.com/V65Hc.png)

    router.get('/test', function (req, res, next) {

        var conn = mysql.createConnection(config);

        //conn.connect();

        conn.query('select  * from invoices ', function (err, result) {

           if (err) {
                throw err;
            }

            res.status(200).json({result: result});
            conn.end();// || conn.destroy();
        });
         //  conn.end(); || conn.destroy();
    });

**Comment by dougwilson** [comment]
Hi @xerardoo, if you are referring to the value of the `Connections` variable in your screenshot, then I think you misunderstand what that variable means. You can find the documentation in the MySQL manual (https://dev.mysql.com/doc/refman/5.5/en/server-status-variables.html#statvar_Connections):

>  The number of connection attempts (successful or not) to the MySQL server. 

This means that variable only ever goes up, it never goes down. It's just a value that increments every time there is a connection attempt. The value does not decrease when a connection ends.
