### ISSUE TITLE
Wrong type detection

### ISSUE THREAD

**Issue by olessavluk** [felixge/node-mysql#1352]
When I calculating some values "on the fly" they are getting type `LONGLONG` and represented as strings in javascript. Which is wrong sometimes, for example `FALSE` represented as `"0"` which is truthy value in javascript. 

Here is es6 code example to reproduce this issue

```javascript
import mysql from 'mysql';

const pool = mysql.createPool({
  host: process.env.MYSQL_HOST,
  port: process.env.MYSQL_PORT,
  user: process.env.MYSQL_USER,
  password: process.env.MYSQL_PASSWORD,
  supportBigNumbers: true,
  bigNumberStrings: true,
  charset: 'UTF8MB4',
});

pool.query({
  sql: 'SELECT 0 AS zero, TRUE AS ok, 42 AS number, "text" as str, 3.13 AS floating',
  typeCast: (field, next) => {
    console.log(`"${field.name}" - ${field.type}`);
    return next();
  },
}, (err, res) => {
  console.log(res);
});
```
Which outputs following:
```
"zero" - LONGLONG
"ok" - LONGLONG
"number" - LONGLONG
"str" - VAR_STRING
"floating" - NEWDECIMAL
[ RowDataPacket { zero: '0', ok: '1', number: '42', str: 'text', floating: '3.13' } ]
```
But when I'm checking types in MySQL they are different:
```sql
mysql> CREATE TEMPORARY TABLE temp
    -> SELECT 0 AS zero, TRUE AS ok, 42 AS number, "text" as str, 3.13 AS floating;
Query OK, 1 row affected (0.00 sec)
Records: 1  Duplicates: 0  Warnings: 0

mysql> DESCRIBE temp;
+----------+--------------+------+-----+---------+-------+
| Field    | Type         | Null | Key | Default | Extra |
+----------+--------------+------+-----+---------+-------+
| zero     | int(1)       | NO   |     | 0       |       |
| ok       | int(1)       | NO   |     | 0       |       |
| number   | int(2)       | NO   |     | 0       |       |
| str      | varchar(4)   | NO   |     |         |       |
| floating | decimal(3,2) | NO   |     | 0.00    |       |
+----------+--------------+------+-----+---------+-------+
5 rows in set (0.00 sec)

mysql> 
```

So why do types are different inside MySQL and node-mysql?

**Comment by dougwilson** [comment]
Hi @olessavluk, if you do a packet capture, you'll find that the type information is not detected by this module--it's actually part of the MySQL protocol and your MySQL server is saying that the type of that column is a LONGLONG, so that's how this module treats it.

**Comment by olessavluk** [comment]
Thank you @dougwilson !
This is really strange MySQL behaviour. Now I understand why `bigNumberStrings` set to `false` by default, because it can break things.

**Comment by dougwilson** [comment]
Yea, I don't quite understand how MySQL determines the types when not coming directly from a column, but in general it seems to just choose the largest possible type.
