### ISSUE TITLE
upload mysql dump into new remote database

### ISSUE THREAD

**Issue by prashanthmadi** [felixge/node-mysql#1355]
I have a mysql dump in my local workspace, Can i export this to new remote database using this module ?

**Comment by dougwilson** [comment]
Hi @prashanthmadi, this module is simply a low-level driver. What this means is that if you have a file that has a bunch of SQL in it, you will need to do the same thing the `msyql` command line does: parse the SQL in the file and use the underlying driver (this module in the JavaScript case) to make each one of those queries to the database.

I hope that helps! This is simply a low-level MySQL driver for Node.js, similar to if you directly used `libmysql` vs a featured program built on top of it.
