### ISSUE TITLE
slowness in execution stored procedure

### ISSUE THREAD

**Issue by abarmawi** [felixge/node-mysql#1356]
Hi,

i'm facing an issue with one of my stored procedure, check this for details :

i have stored procedure that takes 1 second to be executed.
i use Apache JMeter to do load test.
when i use JMeter to do 1 request, the sample time is ~1 sec.
when i use JMeter to do 4 request, the sample time is ~1.5 sec.
when i use JMeter to do 4 request, the sample time is ~4 sec.

and so on, if u increased the number of requests, the sample time will be increased as well!!!!

below is the code i use : 
```

var mysql = require("mysql");

// First you need to create a connection to the db
var pool = mysql.createPool({
    connectionLimit: 30,
    host: "server if",
    user: "db username",
    password: "pass",
    database: "dbname"
});

router.get('/customer', function (req, res, next) {
    pool.getConnection(function (err, connection) {
        // Use the connection 
        connection.query("CALL get_customers1();", function (err, rows) {
            if (err) throw err;
            res.render('index', { title: '' });
            console.log('Data received from Db:\n');
            console.log(rows);

            connection.release();
        });
    });
});

```

any help?

i have tried to change the "connectionLimit" with no luck.
and tried also to remove "connection.release();" with no luck also.

**Comment by sidorares** [comment]
hi @abarmawi could you print connection Id for connection you get from pool?

```js
 pool.getConnection(function (err, connection) {
    console.log(connection.threadId);
    //....
 });
```

expected behaviour is that two requests run in parallel in two separate connections when you do http get /customer and http get /customer again

**Comment by abarmawi** [comment]
Hi @sidorares ,

the log gave me different ids each time as below :

8837
8838
8839
8841
8840
8842
8843
8845
8846
8844

**Comment by sidorares** [comment]
what time do you get when log from inside script?

```js
router.get('/customer', function (req, res, next) {
    var start = +new Date();
    pool.getConnection(function (err, connection) {
        // Use the connection
        console.log('Pool get time: ' + ( new Date() - start)); 
        connection.query("CALL get_customers1();", function (err, rows) {
            if (err) throw err;
            console.log('Pool get + query: ' + ( new Date() - start)); 
            res.render('index', { title: '' });
            console.log('Data received from Db:\n');
            console.log(rows);
            connection.release();
        });
    });
});
```

**Comment by abarmawi** [comment]
@sidorares 

check this log  plz.

Pool get time: 53
Pool get time: 53
Pool get time: 56
Pool get time: 54
Pool get time: 49
Pool get time: 50
Pool get time: 50
Pool get time: 50
Pool get time: 52
Pool get time: 52
Pool get time: 52
Pool get time: 52
Pool get time: 51
Pool get time: 53

Pool get + query: 9561
Pool get + query: 12737
Pool get + query: 13133
Pool get + query: 13248
Pool get + query: 13354
Pool get + query: 13385
Pool get + query: 13643
Pool get + query: 13715
Pool get + query: 13749
Pool get + query: 13761
Pool get + query: 13824
Pool get + query: 13863
Pool get + query: 13886
Pool get + query: 13906
Pool get + query: 13958
Pool get + query: 13957
Pool get + query: 13972
Pool get + query: 14003
Pool get + query: 14021
Pool get + query: 14038
Pool get + query: 14053
Pool get + query: 14096
Pool get + query: 14092
Pool get + query: 14112
Pool get + query: 14155
Pool get + query: 14166
Pool get + query: 14195
Pool get + query: 14204
Pool get + query: 14228
Pool get + query: 14240

**Comment by sidorares** [comment]
looks like it's just slow query. Try to profile server side first:

http://dev.mysql.com/doc/refman/5.6/en/performance-schema-query-profiling.html
https://www.digitalocean.com/community/tutorials/how-to-use-mysql-query-profiling

**Comment by abarmawi** [comment]
i will check and get back with the results

**Comment by dougwilson** [comment]
@abarmawi, any update?

**Comment by abarmawi** [comment]
it's juts a slow query from my side, i managed to optimize it, and everything working fine now,

thanks.
