### ISSUE TITLE
handling null in typecast function

### ISSUE THREAD

**Issue by diginfo** [felixge/node-mysql#1362]
I am trying to convert BLOBS to strings and NULL to '' (empty tring) but it looks like NULL kills the function.

How can I typecast NULL as '' and also prevent the BLOB typecast from crashing when it meets a NULL value ?

    con.typeCast = function (field, next) {
      if(!field.length) return(field.string() = '');
      else if (field.length && field.type.indexOf('BLOB') !== -1) return field.string().toString('utf-8');
      return next();
    }

    TypeError: Cannot read property 'toString' of null

**Comment by dougwilson** [comment]
Hi @diginfo, in your type cast function, you can remove the `.toString('utf-8')`, as that doesn't do anything even when not `null`, but keeping it would make it more complex to handle the `null` case. Example:
```js
con.typeCast = function (field, next) {
  if(!field.length) return(field.string() = '');
  else if (field.length && field.type.indexOf('BLOB') !== -1) return field.string().;
  return next();
}
```

**Comment by diginfo** [comment]
Thanks, can I assume that the training "." is a typo ??

    return field.string().;

**Comment by dougwilson** [comment]
Yes, a typo, sorry.

**Comment by diginfo** [comment]
Sorry to re-open this, but the null values are not being returned as empty strings ??

**Comment by dougwilson** [comment]
Oh, sorry, didn't notice that part of your question. Here you go:
```js
con.typeCast = function (field, next) {
  if(!field.length) return(field.string() = '');
  else if (field.length && field.type.indexOf('BLOB') !== -1) return field.string() || '';
  return next();
}
```

**Comment by diginfo** [comment]
Oops, I should have been more specific, it is the NON BLOB values that are not returining as empty strings:

    if(!field.length) return(field.string() = '');

**Comment by dougwilson** [comment]
Hi @diginfo, that was just a copy from your original code. I don't understand what you are actually trying to do on that line, sorry.

**Comment by diginfo** [comment]
OK, when any value is returned null, I want to return an empty string instead.

**Comment by dougwilson** [comment]
```js
con.typeCast = function (field, next) {
  var value = next();
  return value === null ? '' : value;
}
```

**Comment by diginfo** [comment]
Thanks very much that works :-)

**Comment by diginfo** [comment]
That eliminates the need for me to loop through all of the rows > columns and replace each occurence.

**Comment by dougwilson** [comment]
Awesome :) That's one of the reasons we provide a way to get code into that process :)

**Comment by diginfo** [comment]
Is it possible to achieve something similar when INSERTING OR UPDATING  so the typecast would replace any empty strings with NULL ?? - right now I have to parse the SQL statement and replace all occurrences of '' with NULL

**Comment by sidorares** [comment]
@diginfo this module does not perform any sql parsing, if you get query which is already built for you from somewhere outside you'll need to do replacement manually.

**Comment by diginfo** [comment]
so typecast is only effective on SELECT and not on UPDATE or INSERT ?

**Comment by sidorares** [comment]
typecasts are performed on records you receive, not on the data you submit
