### ISSUE TITLE
Timezone 'utc' not formatting datetime correctly.

### ISSUE THREAD

**Issue by andrewmunro** [felixge/node-mysql#1365]
```js
            this._pool = this.mysql.createPool({
                maxConnections: this.config.maxConnections || 10,
                host:     this.config.host,
                user:     this.config.username,
                password: this.config.password,
                database: this.config.database,
                timezone: 'utc'
            });
```

I have this setup to create my connections, however when I query, timestamps are always returned in my local timezone (GMT). This causes issues with test assertions failing in my integration tests when running them on a local dev machine. Any idea why this wouldnt work?

**Comment by dougwilson** [comment]
Hm, not sure, though I'm pretty sure the `timezone` option can't be the string `"utz"`, only `"+0000"` or `"Z"`. Do either of those change the behavior for you?

**Comment by andrewmunro** [comment]
I had a look at https://github.com/felixge/node-mysql/blob/master/test/integration/connection/test-timezones.js which made me try 'Z', but it still outputs 'GMT' :(

I only saw a change in formatting when it was a non-utc timezone (e.g 'est').

I've worked round it at the moment by ensuring my server process is run with UTC enforced as the timezone, but I thought it was still worth raising as an issue.

**Comment by dougwilson** [comment]
Wait, are you referring to how JavaScript turns a `Date` object into a string? For example, if you run the following, does it display the current time in the same format you are seeing?
```
$ node -pe 'new Date()'
```

If so, this is just an issue for how you are turning the JavaScript `Date` objects into strings, and you may want to take a look at a library like `moment` to get better stringification than javaScript provides you.

**Comment by andrewmunro** [comment]
I see, I was under the impression that UTC was a valid timezone in JS's date object, but having looked at MSDN it isn't. I was hoping I wouldn't have to reformat my output.
