### ISSUE TITLE
[HELP] How to do “for each” for 1,000,000 rows using node-mysql?

### ISSUE THREAD

**Issue by AminaG** [felixge/node-mysql#1370]
http://stackoverflow.com/questions/36015279/how-to-do-for-each-for-1-000-000-rows-using-node-mysql

I'm using NodeJS. I want to do something to 1,000,000 rows without loading all the rows into the memory.

Before, when I used ASP Classic I did:

    do while not rec.eof
       //do something
       rec.movenext
    loop

In node-mysql I didn't found anything that similar to cursor. only

    connection.query('select * from bigdata',function(err,rows))

The problem is, that I don't want to loads all the rows at one time.

**Comment by rm3nchaca** [comment]
you can use LIMIT and implement some pagination or if it's possible, filter the rows with WHERE, for example:

select * from bigdata where field='something' limit 1, 1000

**Comment by AminaG** [comment]
Thanks. I hoped maybe there is something built-in in the module.

**Comment by ZJONSSON** [comment]
You can use streams to process large large datasets without blowing up memory.  Here is an example with transform stream:

```js
connection.query('select * from bigdata')
  .stream()
  .pipe(stream.Transform({
    transform: function(data,encoding,callback) {
      // do something with data...
      callback()
    }
   })
   .on('finish',function() { console.log('done');})
```

**Comment by AminaG** [comment]
The data in this example will contain an array or rows, or object? I want it to contain an object or 1 row.
You didn't set the highWaterMark. What is the default value? I need it to be '1'

Thanks.

**Comment by ZJONSSON** [comment]
Clarified a little the answer above.    In transform stream you will only handle one record at a time (and call `callback` when you are done).  The highWaterMark defines how large the internal buffer of the stream (i.e. how many records) can become before pausing (until the buffer has been reduced through processing the records).

Each record coming into the transform will be an object representing a single row.   For this reason the transform (and any other stream processing the data) needs to be defined with option: `objectMode: true`

**Comment by ZJONSSON** [comment]
Closing - please reopen if any further issues

**Comment by AminaG** [comment]
Not working for me. Only the finish called
Node Version: v5.6.0

```
connection.query('select id  from stats  limit 100')
        	.stream()
        	.pipe(stream.Transform({
    		        objectMode:true,
        		transform:function(data,encoding,callback){
                                //This never be called
        			res.write(util.inspect(data))
        			callback()
        		}        	
        	}))
        	.on('finish',function(){console.log('done');res.end()})
```

**Comment by AminaG** [comment]
Now it's working. I have used by mistake `node-mysql` insted of `mysql` module.
Thanks.

**Comment by AminaG** [comment]
It's not working in pool.

```
var conn=mysql.createPool(data)
    conn
		.query('select * from stats limit 100')
		.stream()
		.pipe(require('stream').Transform({
			objectMode:true,
			transform:function(object,encoding,callback){
				console.log(object)
				callback()
			}
		}))
		conn.end()
```

**Comment by ZJONSSON** [comment]
At first glance it seems you are closing the connection immediately.  Wrapping it inside the finish event, -handler i.e. `.on('finish',() => conn.end())` might be the fix

**Comment by AminaG** [comment]
You right. you can close it again. Thanks again

**Comment by iSuperMan** [comment]
Hi! I have some problem like @AminaG, but i don't want to receive a single object/row in each transform callback. Instead of i want to receive a small array of certain size which contains objects/rows . Is it possible ?

```javascript
var stream = require('stream');

connection.query('select * from bigdata')
  .stream()
  .pipe(stream.Transform({
    objectMode: true,
    transform: function(rows,encoding,callback) {
      rows.forEach(row => { /* do something with each row */ })
      callback()
    }
   })
   .on('finish',() => connection.end() )
```

**Comment by dougwilson** [comment]
Hi @iSuperMan Streams are defined by Node.js code, and object mode streams will only ever give your transform function one object at a time. Since the objects are a row, you only get one row at a time. If you want to get multiple at once, you may need to ask how to do this, but it's a general Node.js stream question, not really anything to do with this module.

**Comment by charutiwari04** [comment]
Hi All, In the above code examples, What is callback? Do I need to create any function for callback? Please clarify

**Comment by taylorgoolsby** [comment]
Hi everyone. I was wondering how streaming affects concurrency. If I start a `SELECT` on a large set, what happens if the table is updated during streaming?
