### ISSUE TITLE
Error : Cannot enqueue Handshake after already enqueuing a Handshake.

### ISSUE THREAD

**Issue by nirmalgoswami** [felixge/node-mysql#1372]
i know this issue was opened many times but every time solution over internet is remove `.connect()` & `. end() `and using `.release`

Any one please explain again for the year 2016 why this issue comes during using this module in node.js. what is problem with using `.connect()` and `.end()` ?

**Comment by nirmalgoswami** [comment]
my code

```
var mysql      = require('mysql');

var connection = mysql.createConnection({
    host     : 'hostname',
    user     : 'user',
    password : 'password',
    database : 'dbname',
    dateStrings :true
});

connection.connect(function(err) {
            if (err) {
                //error code
            }

            //success
        });
```

if we cant use `.connect` then how can we handle db connection error

**Comment by dougwilson** [comment]
There is no reason you cannot use connect and the code you provided runs fine for me without error on the current version of this module.
