### ISSUE TITLE
When do streams finish streaming?

### ISSUE THREAD

**Issue by marti-1** [felixge/node-mysql#1377]
If I stream a select of all records from a table which is constantly updated, will the new records (created after streaming has started) get streamed as well?

**Comment by dougwilson** [comment]
It depends on your transaction isolation. By default no, because InnoDB will basically take a snapshot of the table when the SELECT starts and you will receive all records as they were the moment the SELECT began.

**Comment by marti-1** [comment]
My question was answered. Thanks.
