### ISSUE TITLE
Add support for restoring database dumps

### ISSUE THREAD

**Issue by m2u-germany** [felixge/node-mysql#1379]
Hi,

as far as I can see there is currently no option to import an SQL database dump. Something similar like mysql.exe can do with

`mysql --host=hostname --user=username --password=password < "path\to\dump.sql"`

would be great. Is it possible to implement this functionality or do you consider it out of the scope of this module? Or maybe it is already there and I just missed something… Of course being able to dump database data would be great, too.
I know about other modules like mysql-tools but they don’t really work smoothly, e. g. because they rely on mysql.exe in path environment.

Otherwise awesome module, thanks for all your efforts!

**Comment by dougwilson** [comment]
Hi! Yes, that is out of scope for this module. This module is just the driver. You can absolutely create something like that on top of this module,though you likely need to implement a SQL parser so you can understand all the queries in the dump, like like the commas line does.

**Comment by m2u-germany** [comment]
Ok that makes sense. Maybe I’ll try to implement something on top like you suggested. Thanks anyways!

**Comment by dougwilson** [comment]
No problem! I also just re-read my response and wanted to also add that if there was a pull request implementing this made here, it would most likely get accepted, so that could also be useful if you wanted to make it, but didn't want to own a module for it :)

**Comment by sidorares** [comment]
@m2u-germany  https://github.com/webcaetano/mysqldump

**Comment by sidorares** [comment]
cc @prashanthmadi  #1355

@ralves09  #1308
