### ISSUE TITLE
Implementing with Kraken configuration files

### ISSUE THREAD

**Issue by betweenbrain** [felixge/node-mysql#1380]
Hello,

First of all, thank you for this awesome module. While I am new to Node.js, coming from the PHP world, this module has really been a pleasure to work with.

I am attempting to use it with [Kraken](http://krakenjs.com/) and specifically am having issues passing configuration data to `createPool` in such a way that I can continue using the database connection as an exported module.

Currently, my exported db module looks like:

```
var mysql = require('mysql');

var db = mysql.createPool({
    connectionLimit: 10,
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'test'
});

// Test the connection
db.getConnection(function (err, connection) {
    if (err) {
        console.error('error connecting: ' + err.stack);
    }

    console.log('connected as id ', connection.threadId);

    connection.release();
});

module.exports = db;
```

This works fine as I can reuse the connection elsewhere. I'd like to leverage use of Kraken's config file such as they do at https://github.com/krakenjs/kraken-example-with-shoppingcart/blob/master/lib/database.js. I've been trying to implement this, but come across issues such as `mysql.getConnection is not a function`. My attempt was as follows.

```
var mysql = require('mysql');

var db = function () {
    return {
        config: function (conf) {

            var db = mysql.createPool({
                connectionLimit: 10,
                host: conf.host,
                user: 'root',
                password: '',
                database: 'test'
            });

            // Test the connection
            db.getConnection(function (err, connection) {
                if (err) {
                    console.error('error connecting: ' + err.stack);
                }

                console.log('connected as id ', connection.threadId);

                connection.release();
            });
        }
    };
};

module.exports = db();
```

Is there a way to configure the MySQL connection via a function? Any suggestions?

**Comment by kai-koch** [comment]
That is not how this works, I don't know exactly, how it works with mongoDB from the example, but all your code does is exporting a function "conf", that takes a config-literal, opens an encapsulated pool connection in local ```var db```, test it and exits.
When the callback function is executed and is done the local ```var db``` will be garbage collected since it is not accessible any longer.

I guess you code looks something like this:
```javascript
// main app-file
[...]
var mysql = require('lib/database.js');
[...]
```
The only method on ```mysql``` there is ```conf```, which does nothing but locally connecting and testing.

What you want to do is something like this:

In "database.js":
```javascript
'use strict';
var daPool = require('mysql');
function conf(conf) {
    return daPool.createPool({
        connectionLimit: conf.connectionLimit,
        host: conf.host,
        user: conf.user,
        password: conf.password,
        database: conf.database
    });
};
module.exports = conf;
```

in the part of your app where you load the modules:
```javascript
// [...] other modules loaded before
var mysql = require('lib/database.js');
var pool = mysql.conf(dbConfigurationLiteral);

/* Test the connection. The execution of the test is asynchronous!!
   So it will execute later, when the app is running */
pool.getConnection(function testCallback(err, connection) {
    if (err) {
        console.error('error connecting: ' + err.stack);
    }
    console.log('connected as id ', connection.threadId);
    connection.release();
});
// [...] more modules loaded and app magic happens

// App starts listens to http-rquests.
// Now you might get a console message from ```testCallback```
```
 Please close the issue, if this does answer your question.

**Comment by betweenbrain** [comment]
@kai-koch thanks for the response. My apologies for the delay in responding, I will take a further look at this as soon as I can.

**Comment by dougwilson** [comment]
Hi @betweenbrain, I'm going to close this issue unless you think there is an issue with this module itself. The discussion is welcome to continue, and all parties will receive email alerts of new comments :)
