### ISSUE TITLE
is it possible to disable 'fields' population?

### ISSUE THREAD

**Issue by kfirufk** [felixge/node-mysql#1385]
Hello.

I have a big production application that uses this wonderful module.

I have some memory leaks in my application and i'm trying to investigate the issue.

for now i create core dumps with gcore and analyze them with mdb_v8.

what I noticed from the result is that after a couple of days of having the application running i have around 148k of the 'fields' result objects.

example:
(replaced actual values with #####)
```
{
    "catalog": "def",
    "db": "######",
    "table": "#######",
    "orgTable": "#######",
    "name": "#######",
    "orgName": "######",
    "charsetNr": 63,
    "length": 10,
    "type": 3,
    "flags": 4129,
    "decimals": 0,
    "default": undefined,
    "zeroFill": false,
    "protocol41": true,
}
```
so i have more then 148k of the 'fields' return object.

i never use the fields object in my code. more then that, all my queries end with an anonymous function with (err,rows) parameters. i never needed to use the 3rd parameter which is 'fields'.

is there a way to disable the population of the 'fields' object ?

**Comment by sidorares** [comment]
is that 148kb of memory or 148 thousands columns in your result?

**Comment by kfirufk** [comment]
148k instances of objects with same amount and names of properties.

**Comment by sidorares** [comment]
so it's actually 148k rows, right? And you are worried that saving each row as proper object is not very efficient? Can you try to actually measure memory before / after receiving all data? Also, you might want to avoid storing all rows at all by not having query callback and listen to individual rows events

**Comment by dougwilson** [comment]
Hi @kfirufk I took a look into this but am not seeing a memory leak anywhere. Is is possible to provide answers to any of @sidorares's questions? Perhaps provide the following information as well?

1. Version of Node.js
2. Version of this module 
3. Complete code that reproduces the issue. It needs to be a single file and I will copy paste it and run it. Please do not use any other modules besides this one and Node.js core modules, unless you are trying to demonstrate this module not working with another.
4. Complete steps to run that script, how to reproduce the issue, and how to know I am reproducing it.

**Comment by kfirufk** [comment]
Hi.
these are the details i can provide:

nodejs version 5.9.1
mysql module version 2.10.2

i'm in a process of reinstalling the operation system and upgrading nodejs version to 6. 
it will take some time... but as soon as i get this upgrade completed i will try to use gcore again after a few days and see the results. if mdb_v8 will report that there are so many fields objects again, i will try to reproduce it with minimal code and i'll update this issue.

thanks

**Comment by dougwilson** [comment]
Hi @kfirufk, since I haven't heard back in over a month, I'm going to close the issue, but if you can prove some more information, like how to reproduce, I would be happy to re-open this issue!

**Comment by Santhoshas** [comment]
Did u resolve this issue ?

**Comment by kfirufk** [comment]
Nodejs evolved greatly since then. We divided our project to several processes so it will be easier to restart the services. Since I haven’t tested this issue since then, I can’t be sure that our memory leaks are still related to this issue or if this issue still exists.
