### ISSUE TITLE
How to escape LIKE statement?

### ISSUE THREAD

**Issue by overflowz** [felixge/node-mysql#1386]
Hello, I'm trying to escape query which uses LIKE statement. Query itself is dynamic, so I need a way to escape it somehow.

example pseudocode:
```
var sql = "SELECT * FROM USERS";
var where = "WHERE 1 = 1 ";
if(argument != null) {
    where += "AND someField LIKE '%" + argument + "%'";
}
```

In this case, argument is left unescaped. if I do escape it, then I would result '%'argument'%' which is syntax error.

Any thoughts?

**Comment by umutm** [comment]
Although not yet tried, this must work:
`"SELECT * FROM dbTable WHERE dbColumn LIKE " + connection.escape('%' + keyword + '%')`

**Comment by PHPTrude** [comment]
var selectQuery = 'SELECT * FROM a WHERE name LIKE ? '
var params = ['%'+searchString+'%'];
connection.query( selectQuery, params, function (err, result) {
    ...
}

**Comment by omkelderman** [comment]
to expand on that (disclaimer, didnt test this!)

```javascript
var oarams = []
var sql = "SELECT * FROM USERS";
var where = "WHERE 1 = 1 ";
if(argument != null) {
    where += "AND someField LIKE ?";
    params.push('%'+argument+'%')
}

connection.query(sql, params, function(err, result) { ... });
```

**Comment by dougwilson** [comment]
Hi @overflowz, I hope the above answers have been helpful! Please feel free to leave a comment if you're still looking for help :)
