### ISSUE TITLE
Fatal error when adding to stack trace

### ISSUE THREAD

**Issue by adam-clarey** [felixge/node-mysql#1387]
On line 67 of `/mysql/lib/protocol/sequesnces/Sequences.js`
```
this._callSite.stack
```
is an array, but it is being acted upon as if it is a string and as such it's crashing my site when this lisne is hit.

What is supposed to be happening here? Should it be an array or string?

**Comment by sidorares** [comment]
Are you sure it's array?

```
> var e = new Error()
undefined
> e.stack
'Error\n    at repl:1:9\n    at REPLServer.defaultEval (repl.js:269:27)\n    at bound (domain.js:287:14)\n    at REPLServer.runBound [as eval] (domain.js:300:12)\n    at REPLServer.<anonymous> (repl.js:439:12)\n    at emitOne (events.js:95:20)\n    at REPLServer.emit (events.js:182:7)\n    at REPLServer.Interface._onLine (readline.js:211:10)\n    at REPLServer.Interface._line (readline.js:550:8)\n    at REPLServer.Interface._ttyWrite (readline.js:827:14)'
>
```

Possible reason could be that error somewhere in your code is not instance of `Error` object

**Comment by dougwilson** [comment]
Well, the contents of `_callSite` is actually only set from this library itself (so it doesn't contain user-thrown objects). It is just the result of `new Error()` on the runtime.

@adam-clarey are you running this module in something other than Node.js? If not, then there is likely something really wrong with your environment.

If you think there is an issue with this module, then I'll need the following:

1. Version of Node.js
2. Version of this module 
3. Complete code that reproduces the issue. It needs to be a single file and I will copy paste it and run it. Please do not use any other modules besides this one and Node.js core modules, unless you are trying to demonstrate this module not working with another.
4. Complete steps to run that script, how to reproduce the issue, and how to know I am reproducing it.

**Comment by adam-clarey** [comment]
Providing such a test case will be almost impossible as the mysql module is being used as an extension to an IrisJS system we are building. I can try and reduce it to a single script but that will mean its not an accurate test case.

node version 5.0.0

**Comment by dougwilson** [comment]
Hi @adam-clarey, even using node.js 5.0.0, I'm not seeing this issue, as `_callSite` continues to be an object that has a `.stack` property that is a string (just as what V8 is designed to do). I would like to address this issue, but would like to understand more in order to. If you cannot provide the requested information, perhaps another possible route to resolution would be if you provided a pull request that fixes the issue (please include a test)?

**Comment by dougwilson** [comment]
Looking into this, it seems most likely that something in your app is altering `Error.prepareStackTrace` and not setting it back to normal. I'm going to add a work-around to ignore stack under that condition.
