### ISSUE TITLE
mysql.createPoolCluster problems

### ISSUE THREAD

**Issue by happilymarrieddad** [felixge/node-mysql#1389]
Hi, I have several servers connected to the pool cluster and I was wondering what the proper configuration would be if I wanted the cluster to always attempt to connect to a mysql server after disconnect with some delay. The delay is obviously the restoreNodeTimeout option but the removeNodeErrorCount doesn't have a way to always allow for a disconnect. 0 = no reconnect and any integer that's passed in is the number of times it will try. I wanted unlimited retrys. Thanks!

**Comment by dougwilson** [comment]
Hi @happilymarrieddad, I think I understand your question for the most part. Does `removeNodeErrorCount: 1` do what you're looking for? If not, I think I need to better understand your question.

**Comment by happilymarrieddad** [comment]
Umm no because then it will be removed after one error. I want it to never be removed. Thanks!

**Comment by dougwilson** [comment]
I'm sorry, but I have no idea what you ate trying to do, so I have no way to help you. Your comment there seems to me to conflict with your initial post.

Can you explain what you are trying to accomplish, exactly?

**Comment by happilymarrieddad** [comment]
I want to have a series of database connections and I Don't want them to ever be removed from the cluster. I want the module to check for connections and when one is down then reconnect. The problem I'm encountering is after a week or so after a node has had some disconnects it completely removes the node and the only way to get the system to attempt a reconnect is to restart the server process. I hope that makes more sense =)

**Comment by dougwilson** [comment]
I think it does and what you are describing is the default behavior of the cluster. I can think of two solutions:

1. Set  restoreNodeTimeout  to a non-zero value, even 1 would work.
2. Set  removeNodeErrorCount  to  Infinity

**Comment by happilymarrieddad** [comment]
how do I set removeNodeErrorCount to infinity?

**Comment by dougwilson** [comment]
It's a part of JavaScript:

    removeNodeErrorCount: Infinity
