### ISSUE TITLE
I got `affectedRows = 2` when using `insert ... on duplicate key update ...` statement.

### ISSUE THREAD

**Issue by luochen1990** [felixge/node-mysql#1391]
when I execute the `insert ... on duplicate key update ...` sql the first time, I got a response message like

>  OkPacket {
  fieldCount: 0,
  affectedRows: 1,
  insertId: 551,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  protocol41: true,
  changedRows: 0 }

but when I execute a similer statement the second time, I got

> OkPacket {
  fieldCount: 0,
  affectedRows: 2,
  insertId: 551,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  protocol41: true,
  changedRows: 0 }

I found that the `insertId` is the same, but the second time I execute it, the affectedRows becomes 2, I wonder if this is expected.

**Comment by dougwilson** [comment]
Hi @luochen1990, this module simply passes through the number from the underlying protocol. MySQL is definitely full of quirks and this is simply how MySQL functions. You can find a great explanation (that doesn't even use Node.js) here: http://stackoverflow.com/questions/3747314/why-are-2-rows-affected-in-my-insert-on-duplicate-key-update
