### ISSUE TITLE
cannot read property when using if statement

### ISSUE THREAD

**Issue by ezekel** [felixge/node-mysql#1394]
Hi,  

  I have problem when using if statement, it will throw error ,"cannot read property created_at" , my sql works fine if i will not use the if statement, I want to achieve that if no match to other table the created_at will not display null instead empty or no text,that's why I have this  ' ' in the sql.

  ```
var options = {
      sql: " select usr.col1, usr.col2,IF(dl.created_at IS NULL,' ',dl.created_at)   as created_at from user_table as usr left join product as dl
     etc ...
   "
}

```

Thank you in advance.

**Comment by dougwilson** [comment]
Hi @ezekel, that is weird. I was going to take a look into this, but it looks like your code above is not even complete enough to be valid JavaScript. Would it be possible to provide the following information?

1. What version of Node.js are you using?
2. What version of this module are you using?
3. What version of MySQL server are you connecting to?
4. A more complete example that I cat at least mostly copy-and-paste into a file and run?

**Comment by dougwilson** [comment]
Hi @ezekel, since I have not heard back in over a month, I'm going to close this issue. If you can provide the above details, I'd be happy to re-open!
