### ISSUE TITLE
How to close pool and release all the connection in pool?

### ISSUE THREAD

**Issue by AminaG** [felixge/node-mysql#1395]
Is it possible?
If not, where should I add this functionality in the source ccode?

**Comment by sidorares** [comment]
"Releasing" only has meaning in the context of a pool. If you don't need a pool and you want to gracefully close all connections belonging to that pool, just use `pool.end()`

https://github.com/felixge/node-mysql/blob/1720920f7afc660d37430c35c7128b20f77735e3/lib/Pool.js#L152-L182

**Comment by AminaG** [comment]
I use a pool, and then the app decide to close the pool.
For example:

```
var pool=db.createPool({})
for(var i=1;i<100;i++)
pool.query()

// Now I want to close all the connection of the pool
```

**Comment by dougwilson** [comment]
Hi @AminaG, in your example, since you are simply using `pool.query` for every operation, just calling `pool.end` would close them all. Extending your example:
```js
var pool=db.createPool({})
for(var i=1;i<100;i++)
pool.query()

// Now I want to close all the connection of the pool
pool.end()
```

**Comment by pwnsdx** [comment]
Hello,

Is it possible to wait that all waiting queries are completed before closing the pool please?

Regards,
S

**Comment by pwnsdx** [comment]
Ended up with:

```
		_shouldWeStopChild() {
			return new Promise((resolve, reject) => {
				setInterval(() => {
					// Ensure all queries has been executed before exiting the script
					let connectionQueue = this.Database.getCurrentConnection()._connectionQueue.length;
					if(connectionQueue == 0) {
						clearInterval(this.shouldWeStopChild);
						debug('All queries has been completed.');
						resolve();
					} else {
						debug('There are ' + connectionQueue + ' queries left');
					}
				}, 50);
			});
		}
```
