### ISSUE TITLE
missing ER_DUP_ENTRY error message

### ISSUE THREAD

**Issue by ssteffl** [felixge/node-mysql#1397]
I am having issues getting the error message from an ER_DUP_ENTRY error. So I have no idea which field is getting the dup_entry conflict. I am running node mysql 2.10.2 on node version v5.10.1 with mysql version 5.7.10 Win64 edition. on windows 8.1 64 bit. 

What i am trying to do is insert around 10k items into a table. I get the same issue whether i use 1 transaction or 10k transactions. I set a debugger in lib/protocol/Protocol.js line 268 and logged the ErrorPacket and got

    debug> repl
    Press Ctrl + C to leave debug repl
    > packet
    { fieldCount: 255,
      errno: 1062,
      sqlStateMarker: '#',
      sqlState: '23000',
      message: '' }
    >

as you can see the message has nothing in it. judging from the [mysql documentation](http://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html#error_er_dup_entry), the `message` field should contains something like:

    Duplicate entry '%s' for key %d

any ideas on how to debug this further? Im using sequelize on top of node-mysql but this appears to be an issue at a level below sequelize.

**Comment by dougwilson** [comment]
Would it be possible to provide a network packet capture of the error packet?

**Comment by ssteffl** [comment]
ill see if i can manage that.

**Comment by dougwilson** [comment]
Thanks @ssteffl! If anyone else in the future stumbles across this issue, please see what you can find out or even if you know of a fix for the issue :)
