### ISSUE TITLE
Is pool.query creating a new connection instead of picking from pool?

### ISSUE THREAD

**Issue by sfabriece** [felixge/node-mysql#1399]
line 184 of pool.js

for some reason the link doesn't seem to work for me.

**Comment by AdriVanHoudt** [comment]
does https://github.com/felixge/node-mysql/blob/master/lib/Pool.js#L184 work?

**Comment by dougwilson** [comment]
Hi @sfabriece, `pool.query` picks a connection from the pool. You can see this happening on line 196 (https://github.com/felixge/node-mysql/blob/master/lib/Pool.js#L196). I hope that helps!
