### ISSUE TITLE
Connection.end() Usage

### ISSUE THREAD

**Issue by harish-hsirah** [felixge/node-mysql#1400]
Can something go wrong in the production system if I do not use connection.end() anywhere in my code?

**Comment by go4cas** [comment]
@harish-hsirah, I have actually tested this quite a bit in my app's production setup. What will basically happen if you close / shutdown you application, while the pool is still open, is the following:
- The pool connections (depending on the number of open connections at the time of shutdown) will still be open on your database engine - you can easily check this by doing a `show processlist;` from your MySQL client.
- These connections will remain open on MySQL until the MySQL connection timeout expires - this is a configuration option on your database engine (if I remember correctly the default is 8 hours)

So, to answer the "_can something go wrong?_" bit: that will depend on how many other apps are using the same DB instance. So, if your application consumes the majority of MySQL connections available, and you shutdown without `connection.end()`, these connections will not be available for other applications to consume.

**Comment by dougwilson** [comment]
If you are using the pool, you wouldn't use connection.end() anywhere (sorry, you didn't say if you were using it or not, so just wanted to note that).

If you are using ~mysql.createConnection~ but not calling ~.end()~ anywhere, then yes, you will have problems unless the Node.js process is being terminated (not typical in Node.js programs). @go4cas has a pretty good explanation :)
