### ISSUE TITLE
Get empty result in queries

### ISSUE THREAD

**Issue by flpms** [felixge/node-mysql#1406]
When I do queries like `SELECT` or `INSERT`, some strange things happens. In this question at Stackoverflow, [you can see the first problem. (I follow the suggest in the answer, with no effect)](http://stackoverflow.com/questions/36973751/mysql-in-nodejs-is-not-working-for-multiple-statements-in-insert-into)

And the other problem is when I select with Inner Join, loggin the query and using MySQL at CLI, I get results, but with node-mysql I get a empty array. It's a bug or some wrong I'm do wrong, you can find the code in link.

**Comment by kai-koch** [comment]
Please read the node-mysql documentation

> **section connection options**
> 
> ```multipleStatements```: Allow multiple mysql statements per query. Be careful with this, it could increase the scope of SQL injection attacks. (Default: false)
> 

closed. not an node-mysql issue
