### ISSUE TITLE
Is multiple statement queries supported?

### ISSUE THREAD

**Issue by joserodolfofreitas** [felixge/node-mysql#1409]
Executing multiple query statements within the same string can delegate the transaction management to mysql itself, which also has a smaller overhead since we don't need to create a transaction session within node.js server.

Is multiple statement queries (like the following one) supported? 

`INSERT INTO parent_table (id, field1, field2, field3) VALUES (1,2,3,4); INSERT INTO child_table (id, parentid, field1, field2) VALUES (1,1,2,3);`

Right now I'm getting a parser error, but the output SQL can be  executed if I go directly to mysql terminal.
  ```
code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000'
```

**Comment by dougwilson** [comment]
Hi! Does it not work if you set to enable multiple statements in the connection options? Can you share what connection options you are using to create the connect? Perhaps you have a typo in the property to enable it?

**Comment by joserodolfofreitas** [comment]
Hi, doug!
My bad, I completely forgot that config parameter.
Thanks!

**Comment by dougwilson** [comment]
Hi @joserodolfofreitas, ah, gotcha :) Glad to hear it's working for you now :)!
