### ISSUE TITLE
connect mysql binlog error

### ISSUE THREAD

**Issue by kittencup** [felixge/node-mysql#1412]
index-0 (err):     at Object.exports._errnoException (util.js:870:11)
index-0 (err):     at exports._exceptionWithHostPort (util.js:893:20)
index-0 (err):     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
index-0 (err):     --------------------
index-0 (err):     at Protocol._enqueue (/opt/bmqb_account_stat/node_modules/mysql/lib/protocol/Protocol.js:141:48)
index-0 (err):     at Protocol.handshake (/opt/bmqb_account_stat/node_modules/mysql/lib/protocol/Protocol.js:52:41)
index-0 (err):     at Connection.connect (/opt/bmqb_account_stat/node_modules/mysql/lib/Connection.js:123:18)
index-0 (err):     at new ZongJi (/opt/bmqb_account_stat/node_modules/zongji/index.js:18:23)
index-0 (err):     at Object.<anonymous> (/opt/bmqb_account_stat/src/commands/mysql.js:9:22)
index-0 (err):     at [object Generator].next (native)
index-0 (err):     at step (/opt/bmqb_account_stat/src/commands/mysql.js:3:1)
index-0 (err):     at /opt/bmqb_account_stat/src/commands/mysql.js:3:1
index-0 (err):     at Object.<anonymous> (/opt/bmqb_account_stat/src/commands/mysql.js:3:1)
index-0 (err):     at Object.handler (/opt/bmqb_account_stat/src/commands/mysql.js:7:5)
index-0 (err):     at /opt/bmqb_account_stat/src/index.js:18:31
index-0 (err):     at [object Generator].next (native)
index-0 (err):     at step (/opt/bmqb_account_stat/src/index.js:1:1)
index-0 (err):     at /opt/bmqb_account_stat/src/index.js:1:1
index-0 (err):     at /opt/bmqb_account_stat/src/index.js:1:1
index-0 (err):     at Object.<anonymous> (/opt/bmqb_account_stat/src/index.js:16:1)

**Comment by dougwilson** [comment]
Hi @kittencup, the paste above is missing what the actual error is. Can you post the error message, some information about what the issue is, the version of this module, and perhaps the code that is having the problem?

**Comment by dougwilson** [comment]
Hi @kittencup, I'm going to close this issue since I haven't heard back in 19 days. If you can provide the information, I'd be happy to re-open the issue!
