### ISSUE TITLE
Problem connection port /!\

### ISSUE THREAD

**Issue by GregdTd** [felixge/node-mysql#1414]
Hey everyone, 

I got a problem ! I have a specific URL for my database which look like : 
https://example:myport/mypath

So when I do not specify a port, it try to connect to: 
https://example:myport/mypath:3306      
And it doesn't work .... My port is not 3306, and as you see it is specified before my path !!

I would like to disable the default port configuration .... Or have a "path" option in the configuration... 

Someone got an idea ? 
Thanks for your replies !

**Comment by dougwilson** [comment]
MySQL cannot connect over HTTP, as it does not use the HTTP protocol. Can you provide more information on what you are trying to do? Perhaps even code so we can understand?

**Comment by GregdTd** [comment]
Hey @dougwilson , 
Thanks for your quick reply. 
I'm going on something else so finally don't need an answer. 

In any case, thank you !
