### ISSUE TITLE
Compatibility with AWS Aurora DB

### ISSUE THREAD

**Issue by hamsuu** [felixge/node-mysql#1417]
Hello :) I had a problem with get insertId when using aurora db, ( mysql 5.6.10 is fine ) 
Is there any document that describes a compatibility with amazon aurora db ? 
Regards -

**Comment by dougwilson** [comment]
Hi @hamsuu, I never actually heard of that DB before. I am looking at their site http://aws.amazon.com/rds/aurora/faqs/ and see the following:

> The Amazon Aurora database engine is designed to be wire-compatible with MySQL 5.6 using the InnoDB storage engine.

This would seem to imply that if there is a difference between your 5.6.10 and Aurora, there is some issue with the way Aurora is doping something (or perhaps just not providing the insert ID field in the packet). I don't have access to an Aurora DB to try it out, though.

Would it be possible for you to do a packet capture between your Node.js application and the database? If not, you can try applying commit 8eda6158b98c06f0a7ab68d9669530c951f009ec to the `mysql` source you are using, and add `debug: true` to your connection options and pasting the output to STDOUT here.

**Comment by hamsuu** [comment]
Problem seems to be at auto increment options.
Thanks for your consideration :+1:
