### ISSUE TITLE
Prepared statements - present or not?

### ISSUE THREAD

**Issue by agauniyal** [felixge/node-mysql#1418]
Todo section lists - 'Prepared statements' as first item and this stackoverflow [thread](http://stackoverflow.com/questions/5818312/mysql-with-node-js) mentions otherwise.

**Comment by dougwilson** [comment]
Ok, not sure what the SO is about, but this module does not support prepared statements, still.

**Comment by dougwilson** [comment]
Issues #274 and #616 are two open issues tracking this. If you can help, please feel free to contribute adding prepared statements to this module :star2: !
