### ISSUE TITLE
Space character intrusion in field name if mathematical expression.

### ISSUE THREAD

**Issue by Salketer** [felixge/node-mysql#1419]
Hello there,

I have stumbled on something that got me for quite some time... When using a math expression in a statement without alias, if it is the last field before the keyword "FROM", a space is added at the end of its name. Here's an example:

```
mysql.query("SELECT REVENUE_PERIOD,MARGIN_VALUE/REVENUE_PERIOD FROM cube WHERE month=201504;",function(err, rows, fields) 
[ RowDataPacket {
    REVENUE_PERIOD: 522565071.88,
    'MARGIN_VALUE/REVENUE_PERIOD ': 0.006249748 } ]

FieldPacket {
    catalog: 'def',
    db: '',
    table: '',
    orgTable: '',
    name: 'MARGIN_VALUE/REVENUE_PERIOD ',
    orgName: '',
    charsetNr: 63,
    length: 33,
    type: 246,
    flags: 128,
    decimals: 9,
    default: undefined,
    zeroFill: false,
    protocol41: true }
```

This behavior can also be observed if we put a space before the comma in the field list like this query:

`SELECT MARGIN_VALUE/REVENUE_PERIOD ,REVENUE_PERIOD FROM cube WHERE month=201504;`

I have not tested a full range of possibilities but it seems that surrounding the fields in parenthesis gets rid of the space... As my queries are built on-the-fly, by the users, I found the easiest way to dodge the problem without modifying all my code is to join the fields with a simply comma, no spaces, and add the field "1" at the end just to be sure.

Version 2.10.2

Thanks

**Comment by dougwilson** [comment]
Hi @Salketer, the SQL is being parsed by your MySQL server, and your MySQL server is sending back to us field packets with the field names. We simply use whatever the field name the MySQL server is reporting back to us. Perhaps this is a bug in the MySQL server you are using.

**Comment by Salketer** [comment]
Thank you, I will have a look with them. Just so it is there if needed, my
MySQL version is 5.7.12

2016-06-01 1:40 GMT+02:00 Douglas Wilson <notifications@github.com>:
