### ISSUE TITLE
isoString dates

### ISSUE THREAD

**Issue by yusijs** [felixge/node-mysql#1423]
I'm having the same issues as outlined in https://github.com/felixge/node-mysql/issues/758, where I get the datetime returned as an isostring: 2016-05-20T14:18:35.000Z

However, I'm not doing anything with the results, my code:
```
query("select * from jobs where job_no = ?", [jobId], function (err, rows, fields) {
    console.log(rows);
    if (err) {
      res.status(500).send(err);
    }
    else if (rows.length != 1) {
      res.status(500).send("No rows, invalid job");
    }
    else {
      res.send(rows);
    }
  })
```

The field in question:
`order_time datetime NOT NULL,`

Any clues?

**Comment by dougwilson** [comment]
It looks like whatever that `res.send` is you are using is doing the transformation. I'm sure there is probably some way you can configure that, or another option is to just keep the strings from MySQL using `dateStrings: true` in your connection/pool configuration (https://github.com/felixge/node-mysql#connection-options) which will keep this module from inflating the string into a JavaScript `Date` object.

I traced it down to core JavaScript will do this when you run `rows` through `JSON.stringify` (it converts any `Date` object into the ISO format of the underlying date). Using `dateStrings: true` seems to be a simple way to just avoid the issue, if you need to use `JSON.stringify`.

I hope that helps!

**Comment by yusijs** [comment]
I don't think that's it, as it happens before I even do a res.send. just logging rows to the console mangles it. Json.stringify does nothing to help either.

**Comment by dougwilson** [comment]
`console.log(rows);` will mangle `Date` objects as well, just as Node.js documents. If you want the date to be a specific string, you have to format it yourself, otherwise someone else is going to choose how to represent a `Date` object as a string.

If you want it just as-is from the MySQL server, you can set the `dateStrings: true` in your connection/pool configuration (https://github.com/felixge/node-mysql#connection-options) which will keep this module from inflating the string into a JavaScript `Date` object.

**Comment by yusijs** [comment]
So just so i understand correctly: there is no way to return a "regular" javascript date object from node-mysql? I testes with json.stringify as well with the same results. I realize I can just grab the strings as is, but I generally prefer working with regular date objects as much as possible, to keep as much of my code as possible similar if that makes sense?

**Comment by dougwilson** [comment]
> there is no way to return a "regular" javascript date object from node-mysql?

I'm not sure what you mean, a "regular javascript date object". Are you not getting a `Date` object? Can you try doing `instanceof Date` on the column to check if it is there? I used your example, and it works just fine for me:
query("select * from jobs where job_no = ?", [jobId], function (err, rows, fields) {
    console.log(rows[0].order_time instanceof Date);
    // I see true logged to the console, indicating it is a Date object
  })
```

> I realize I can just grab the strings as is, but I generally prefer working with regular date objects as much as possible, to keep as much of my code as possible similar if that makes sense?

Sure, but frankly, I have no idea what you want. Your initial post just asked about why you are getting the ISO format when using `res.send`, which I explained. You never actually explained what you are seeing in the `console.log` vs what you are expecting to see, so I cannot comment on there. Perhaps you can explain further. I'll re-open this issue only if you can provide all the following information so we can be sure we are on the exact same page and are not talking in circles:

1. What version of Node.js are you using?
2. What version of this module are you using?
3. Complete SQL to create the necessary table to use in a query.
4. Complete SQL to insert the necessary rows into that that to select on.
5. Provide complete code that reproduces the issue. It must be self-contained such that I can copy and paste the code into a file and run it to reproduce the issue. Please use as few other modules besides this one as possible in order to reproduce the issue, as the more there are, the harder it is going to be to diagnose.
6. Provide the exact steps needed to reproduce the issue. Explain what we will see when we hit the issue and what we should see if the issue wasn't there.

**Comment by dougwilson** [comment]
And for posterity, here is what it looks like when I run a JavaScript Date object though `console.log` and `JSON.stringify` on Node.js. If you are seeing the same formats output, then that just re-inforces that yes, this module is returning a `Date` object, just you don't like the way that `console.log` or `JSON.stringify` feels like formatting the object:
```
$ node -e 'console.log(new Date())'
Sun May 22 2016 15:17:02 GMT-0400 (Eastern Daylight Time)

$ node -pe 'JSON.stringify(new Date())'
"2016-05-22T19:17:19.567Z"
```

**Comment by yusijs** [comment]
You're exactly right - I'm just not a huge fan of how it gets printed. I though the node-mysql module would convert everything to a Date object (e.g New Date(rows[0].date_column)) and return that, but instead I get the dirty isoString. 

Don't get me wrong, I can work with it - I'm just not a huge fan of it. The reason I'm adamant on trying to keep everything consistent is that the backend (from an older system I'm trying to bring up to speed) is messy. Dates, datetimes and timestamps all over. 

What I want to see is the new Date() object, and not the stringified date object. :)

I guess this isn't really an issue with the module itself though, so can just leave this closed I reckon.

**Comment by dougwilson** [comment]
> I though the node-mysql module would convert everything to a Date object (e.g New Date(rows[0].date_column)) and return that

It does, and we are returning a Date object. You can see that using the instanceof check I showed above. If you are not seeing that, then I think we are seeing different things. I need to to provide all the information in my comment above to be able to help you further, as clearly we are seeing different thing: I see this module retuning new Date(rows[0].date_column) and you're not. I would like yo he to the bottom of this, but I need complete information, so please provide everything I have asked for.

**Comment by yusijs** [comment]
Alright - I'll update the thread once the kids are asleep this evening.

Den tir. 24. mai 2016, 15:04 skrev Douglas Wilson <notifications@github.com

**Comment by yusijs** [comment]
1:
> $ node -v
> v6.0.0
> 

2:
> "mysql": "^2.10.2"

3/4:
```
-- MySQL dump 10.13  Distrib 5.5.49, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: orders
-- ------------------------------------------------------
-- Server version       5.5.49-0+deb8u1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `jobs`
--

DROP TABLE IF EXISTS `jobs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `jobs` (
  `job_no` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `create_time` datetime NOT NULL COMMENT 'Timestamp of this record',
  `order_time` datetime NOT NULL,
  `client_id` varchar(11) NOT NULL COMMENT 'Customer id from visma',
  `client_name` varchar(100) NOT NULL COMMENT 'Please populate with a copy of the name belonging to client_id. For backup purposes.',
  `data_owner_id` varchar(11) DEFAULT NULL,
  `priority` enum('Normal','Urgent','Project') DEFAULT NULL,
  `drn_no` varchar(10) DEFAULT NULL,
  `se_no` varchar(10) DEFAULT NULL COMMENT 'Sales Enquery. Not standard price list.',
  `description` varchar(100) DEFAULT NULL,
  `order_value` double DEFAULT NULL COMMENT 'Order value',
  `current_department` enum('Customer Service','Archive','Archive-Oslo','Data Entry','Tape','DMS','Finance','Supervisor','IT') NOT NULL DEFAULT 'Customer Service',
  `order_handler` varchar(50) DEFAULT NULL,
  `unused_archive_handler` varchar(50) DEFAULT NULL,
  `unused_prod_handler` varchar(50) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `deadline` datetime DEFAULT NULL,
  `complete_date` date DEFAULT NULL,
  `client_contact` varchar(50) DEFAULT NULL,
  `client_contact_email` varchar(255) DEFAULT NULL,
  `client_ref` varchar(50) DEFAULT NULL,
  `cost_code` varchar(50) DEFAULT NULL,
  `percent_complete` tinyint(4) unsigned DEFAULT NULL,
  `delivery_time` datetime DEFAULT NULL,
  `qc_performed_order_handling` tinyint(1) NOT NULL DEFAULT '0',
  `qc_performed_production` tinyint(1) NOT NULL DEFAULT '0',
  `non_conformity` tinyint(1) NOT NULL DEFAULT '0',
  `customer_complaint` tinyint(1) NOT NULL DEFAULT '0',
  `job_status` enum('New','Active','On Hold','For Approval','Complete','Invoice Exported','Invoice Complete','VOID') NOT NULL DEFAULT 'New',
  `order_via` varchar(50) NOT NULL,
  `order_via_details` varchar(50) DEFAULT NULL,
  `order_type` enum('Backup Rotation','Consultancy','Data Entry','Destruction','Inquiry','Other','Permanent Out','Photocopying','Pickup','Retrieval','Scanning','Supplies','Tape Transcription','Refile') NOT NULL DEFAULT 'Other',
  `details` text,
  `ship_to` text,
  `authorized_by` varchar(50) DEFAULT NULL,
  `package_type` varchar(25) NOT NULL DEFAULT 'n/a',
  `no_of_packages` int(11) NOT NULL DEFAULT '0',
  `no_of_items` int(11) NOT NULL DEFAULT '0',
  `confirmation_sent` datetime DEFAULT NULL,
  `update_sent` datetime DEFAULT NULL,
  `salt` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`job_no`),
  KEY `job_status` (`job_status`),
  KEY `order_type` (`order_type`),
  KEY `client_id` (`client_id`),
  KEY `se_no` (`se_no`),
  KEY `drn_no` (`drn_no`),
  KEY `data_owner_id` (`data_owner_id`),
  KEY `order_handler` (`order_handler`),
  KEY `archive_handler` (`unused_archive_handler`),
  KEY `prod_handler` (`unused_prod_handler`),
  KEY `authorized_by` (`authorized_by`)
) ENGINE=InnoDB AUTO_INCREMENT=25439 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `jobs`
--

LOCK TABLES `jobs` WRITE;
/*!40000 ALTER TABLE `jobs` DISABLE KEYS */;
INSERT INTO `jobs` VALUES (25422,'2016-05-20 16:18:35','2016-05-20 16:18:35','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25423,'2016-05-20 16:24:47','2016-05-20 16:24:47','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25424,'2016-05-20 16:24:49','2016-05-20 16:24:49','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25425,'2016-05-20 16:25:09','2016-05-20 16:25:09','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25426,'2016-05-20 16:25:20','2016-05-20 16:25:20','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25427,'2016-05-20 16:25:41','2016-05-20 16:25:41','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25428,'2016-05-20 16:26:18','2016-05-20 16:26:18','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25429,'2016-05-20 16:26:32','2016-05-20 16:26:32','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25430,'2016-05-20 16:26:55','2016-05-20 16:26:55','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25431,'2016-05-20 16:27:33','2016-05-20 16:27:33','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25432,'2016-05-20 16:27:40','2016-05-20 16:27:40','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25433,'2016-05-20 16:27:58','2016-05-20 16:27:58','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25434,'2016-05-20 16:29:11','2016-05-20 16:29:11','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25435,'2016-05-20 16:29:13','2016-05-20 16:29:13','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25436,'2016-05-20 16:29:28','2016-05-20 16:29:28','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25437,'2016-05-20 16:29:42','2016-05-20 16:29:42','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL),(25438,'2016-05-20 16:29:59','2016-05-20 16:29:59','10051','','','Normal',NULL,NULL,'descriptionthingamajig',NULL,'Customer Service',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,0,0,'New','mail',NULL,'Consultancy',NULL,NULL,NULL,'Goods In',0,0,NULL,NULL,NULL);
/*!40000 ALTER TABLE `jobs` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2016-05-24 18:51:58

```

5:
```
connection.query("select * from jobs where job_no = ?", [jobId], function (err, rows, fields) {
  console.log(rows); /* this should give us a new Date() object, as it's not been stringified. However, I get an isostring here as well. */
  if (err) {
    console.log(err);
  }
  else if (rows.length != 1) {
    console.log("No rows, invalid job");
  }
  else {
    console.log(JSON.stringify(rows)) // this should give us isostring, cuz stringified
  }
})
```

6. Expected result: order_time should equal a new Date(order_time) object.
Actual result Im seeing: order_time equals a isostring representation of a date object. 


-----
Is this thorough enough, or do you need anything else?

**Comment by dougwilson** [comment]
> Is this thorough enough, or do you need anything else?

I need complete code that reproduces the issue. It must be self-contained such that I can copy and paste the code into a file and run it to reproduce the issue. Please use as few other modules besides this one as possible in order to reproduce the issue, as the more there are, the harder it is going to be to diagnose.

Just using your code you gave me, I literally am still getting a Date object, so there is something else going on. Remember, console.log had to print to the string, so it had to turn a Date object into some kind of string. Can you also provide the exact text you are seeing on the console.log call and the exact text you would expect to see?

**Comment by dougwilson** [comment]
Also, I asked if you could do " instanceof Date " checks on the columns you are expecting to be a Date object, to verify they are a date object coming from this module, before you print them. Have you done that? Please be sure to include what  instanceof Date  checks you have done in the new code sample you provide.

**Comment by yusijs** [comment]
I used n now to change node version to 4.4.4, and it logged out a date object:
`console.info(rows[0].order_time);`

> Fri May 20 2016 16:18:35 GMT+0200 (CEST)

Running instanceof on rows[0].order_time returned a date object on both node 4.4.4 and 6.2.0. I'm guessing that node v.6+ is stringifying the object before logging it out? I don't know what else it could be tbh, since it's a date object until it's printed on screen. 

That or something wonky is going on on my server.

**Comment by dougwilson** [comment]
> I'm guessing that node v.6+ is stringifying the object before logging it out? I don't know what else it could be tbh, since it's a date object until it's printed on screen. 

Probably. Did you ever try the commands in https://github.com/felixge/node-mysql/issues/1423#issuecomment-220850460 ? Those would show you how, for example, Node.js displays a `Date` object using `console.log`. Since the console is just text characters, it has to turn the object into a string somehow to get characters to print. The format "Fri May 20 2016 16:18:35 GMT+0200 (CEST)" would be the format that `console.log` uses in your time zone; the format is simply the result of the `Date.prototype.toString` method, I believe.

**Comment by dougwilson** [comment]
It's also common I've seen libraries overload the `console.*` methods to provide enhanced or redirected logs. If that is the case, you may be seeing it is any other format. The `instanceof` check is how you can know if you are actually getting a `Date` object back or not, which is the most the module can control. You can also try doing something like adding `console.info(new Date())` to your server code to see how your `console.log` is formatting the date and compare to see if it's in the same format.

**Comment by yusijs** [comment]
> Did you ever try the commands in #1423 (comment)

```
$ node -e 'console.log(new Date())'
2016-05-24T18:12:44.984Z
```

So yeah, deffo a node v.6 issue. .info and .error all give the same result.

**Comment by dougwilson** [comment]
Ah, ha! And I just creeped around in the Node.js source and here is the commit that changed the format for `Date` objects in the console output: https://github.com/nodejs/node/commit/93d6b5fb68eae8b0912579980e17ebf0723ab2cc

**Comment by yusijs** [comment]
That's just silly imo. Ah well. Guess it's just more work on the frontend! Thanks for looking into it! :+1:
