### ISSUE TITLE
connection enqueued causing non responsiveness  

### ISSUE THREAD

**Issue by NasserAlmanji** [felixge/node-mysql#1425]
Hi,

In an express route, I fetch data from the database, using this configuration options
```js
var config = {
		  host     : '192.168.20.100',
		  user     : 'root',
		  password : '',
		  database : 'users',
		  queueLimit: 100,
		  debug: true
		};
```

Sometimes, 
I get this logged out 'Waiting for available connection slot' and any subsequent processes don't get serviced in that route (the client doesn't get a response).

The code that logs the above message
```js
pool.on('enqueue', function () {
  console.log('Waiting for available connection slot');
});
```

So it seems that database connection is stuck and further requests get waiting (making no response to clients). Usually I see this error 502 Bad Gateway.

Kind regards,
Nasser

**Comment by dougwilson** [comment]
Hi! This always happens when you have somewhere in your code where you forgot to put a .release() call in every single code path after a .getConnection() call.

I hope this helps you track it down!

If you need help tracking it down, please share your entire code base, or at lease enough of it that we can run without adding code ourselves (i.e. you cannot just provide snippets) that reproduces the issue.

**Comment by pioneer32** [comment]
I faced the same trouble.
The situation:
MySQL is being slow. Consequently, the number of simultaneous connection grow up and reach connectionLimit.
Then, if I invoke getConnection with passing a callback there, the callback will never be called (moreover, it's not enqueued). So, I'm a bit confused, as the default value of queueLimit is 0 and an Error 'No connections available.' is expected. 
I also tried to set waitForConnections to false and it began working well, as it stops to enqueue requests for connection.

I have an idea how to fix it: We have to add a validation for this case before invoking _enqueueCallback.

Should I send a pool request?

**Comment by NasserAlmanji** [comment]
@dougwilson The issue still even resurfaces from time to time, I removed the release condition.
I reloaded the Node.js program and shortly after it, it appeared. 

```js
SQLStore.prototype.execute = function(pool, query, info, release, callback) {

	var self = this;

	if((_.isFunction(release)) && (callback === undefined)) {
		callback = release;
		//release = true;
	}
	else if(typeof callback === "undefined") {
		callback = function() {};
	}

	pool.getConnection(function(err, connection) {
		if(err) {
			if(connection) {
				connection.release();
			}
			self.emit("error", err);
			callback(err);
			return;
		}

		// self.queryFormat(connection);
		connection.query(query, info, function(query_error, result) {
			//if(release) {
				connection.release();
			//}

			if(query_error) {
				self.emit("error", query_error);
			}
			callback(query_error, result);//, connection);
		});
	});
};
```
Thank you in advance
