### ISSUE TITLE
LIKE query where string contains ", escaping breaks query

### ISSUE THREAD

**Issue by Laro88** [felixge/node-mysql#1433]
I have a table with some json inside, and I would like to use the LIKE query to run some matches (instead of loading all into node.js, parse the json, and then run comparisons.

Data in column: ```'{"app":"utapp","subapp":1, "partid":-54}'```

For some reason the escaping seems to break when using ? and parameters or creating the string and using mysql.escape

The OK query is:
```SELECT * FROM json WHERE jsongroup='ut' AND specifier LIKE '%"partid":-54%' ORDER BY jsonid DESC;```

Since I am matching a string that contains " inside, then the LIKE query fails due to escaping the added ```"``` into ```\"```

Any way to make this LIKE query work? Have I missed something obvious :-)

**Comment by Laro88** [comment]
The resulting query seems "double escaped" like this
```"SELECT * FROM json WHERE jsongroup='diagram'  AND specifier LIKE '\'\\\"partid\\\":-54\'' ORDER BY jsonid DESC"```

**Comment by dougwilson** [comment]
If you are using the ?, you do not use mysql.escape. If you do, of course it will be double-escaped, as ? replacement does the escaping.

If you are not sure what I mean, please provide your code and I can help you adjust it.

**Comment by dougwilson** [comment]
Hi @Laro88, I'm going to close since I haven't heard back. If you can provide your code, I'd be happy to help. I was able to run the query fine using the following code:
```js
connection.query('
 SELECT * FROM json WHERE jsongroup='ut' AND specifier LIKE ? ORDER BY jsonid DESC;', ['%"partid":-54%']);
```

**Comment by sanjay-nag** [comment]
Hi @Laro88, I'm facing the same issue as well. Here's my code

let sqlQuery = `SELECT *
			FROM canvas.Courses
			WHERE courseterm=${mysql.escape(request.body.courseTerm)} AND ((coursedept=%${mysql.escape(request.body.courseDepartment)}% AND courseid ${mysql.escape(request.body.prefix)} ${mysql.escape(request.body.courseId)}) OR (coursename LIKE %${mysql.escape(request.body.courseName)}%));`;

which translates to 

`SELECT *
                        FROM canvas.Courses
                        WHERE courseterm='Spring' AND ((coursedept=%'CMPE'% AND courseid '>' '220') OR (coursename LIKE %'dfg'%));`

Please help me. Thanks in advance
