### ISSUE TITLE
How to insert "\n" by sql?

### ISSUE THREAD

**Issue by qiangzi109901** [felixge/node-mysql#1435]
when I use query(sql),I can't insert data with '\n'

sql just like this：

```
sql = "insert into message(title,content) value('test','\\nhello')"
```

when execute this sql ,the content is not contain "\n"

**Comment by kai-koch** [comment]
[linefeed] = \x0a

The datacell will contain a ```[linefeed]hello```.
Depending on what you use to display the result the [linefeed] will not be shown. (e.g. some kind of html-db-interface may not render the [linefeed] as new line, but it would be there if you look in the source-code of the html-page.)

JavaScript escape the the Backslash, so SQL writes ```[linefeed]hello``` into the datacell. 
If you really want to write ```[backslash]nhello``` to the database this way use 4 Backslashes:
```Javascript
sql = "insert into message(title,content) value('test','\\\\nhello')";
```
JavaScript escapes the character sequence to ```"[backslash][backslash]nhello"``` and sends it to MySQL. MySql then escapes a second time and writes ```"[backslash]nhello"```

If your input originates from a HTML-textarea, you need to check, if the textarea uses "virtual" breaks or not. (Also, you might need to test, if different browsers send linefeeds the same way.)

Please also read this paragraph in the node-mysql documentation, especially if you want to store input from unsafe sources like user input:
[Escaping query values](https://github.com/felixge/node-mysql#escaping-query-values) 

Closed, not an Node-MySQL issue.
