### ISSUE TITLE
Piping results with Streams2: TypeError: dest.on is not a function

### ISSUE THREAD

**Issue by wzup** [felixge/node-mysql#1440]
How does piping results with streams work? I get error:

> TypeError: dest.on is not a function

My goal is to execute several queries:

```
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE user_account;
TRUNCATE TABLE user_profile;
TRUNCATE TABLE user_account_status;
SET FOREIGN_KEY_CHECKS = 1;
```

Here is my operation:

```
        pool.query('SET FOREIGN_KEY_CHECKS = 0').stream({highWaterMark: 5})
            .pipe('TRUNCATE TABLE user_account', function(err, res, flds) {
                console.error('[err] :', err);
                console.log('[res] :', res);
                console.log('[flds] :', flds);
                done();
            })
```

And error thrown:

```
  Message:
    TypeError: dest.on is not a function
  Stack:
    TypeError: dest.on is not a function
        at Readable.pipe (C:\Users\user\sbox\node\app\node_modules\mysql\node_modules\readable-stream\lib\_stream_readable.js:527:8)
        at Object.<anonymous> (C:\Users\user\sbox\node\app\spec\mySpec.js:69:14)
```

How to do it?

**Comment by dougwilson** [comment]
Hi @wzup, it looks like there is a general misunderstanding on what streams2 is in Node.js, as your `.pipe()` call does not make any sense. You can lean more about streams2 probably in other sources. For how to use `.pipe()`, you can also refer to the Node.js documentation on this method: https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options
