### ISSUE TITLE
Failed to find mysql server

### ISSUE THREAD

**Issue by mendrik** [felixge/node-mysql#828]
Hi,
I'm using sequelize with the latest node-mysql module with pm2 cluster. And everything works just dandy, however once in a while mysql.createConnection fails with "Failed to find mysql server". Any ideas what could be the reason for this?

**Comment by renatoargh** [comment]
+1

Any update on this?

I am still getting this error. After reading this thread I have just replaced host info that was `db.example.com` with fixed IP address (which I know is a bad practice). Will monitor and see if this error goes away.

**Comment by dougwilson** [comment]
Hi @renatoargh , no there is no update, as my questions above went unanswered. Can you provide some insight?

**Comment by dougwilson** [comment]
As there has still not been any response to my inquiries, I'm going to close this issue for inactivity. I'll be happy to reopen the issue with more information.
