### ISSUE TITLE
INSERT query speed and transactions

### ISSUE THREAD

**Issue by rogierschouten** [felixge/node-mysql#916]
Hi guys,

I tested the number of INSERT queries I could run per second as compared with other databases and drivers. Surprisingly, all MySQL implementations for Node.JS I could find are a factor 10 slower than e.g. drivers for MS SQL, but also they are a factor 10 slower than other (non-Node, e.g. VBA) implementations of MySQL drivers. 
Therefore, the problem is neither inherently Node and it also isn't inherent to MySQL. 

I also noticed that when run inside a transaction, the INSERT queries become as fast as all others.  

Are there any ideas as to why all Node.JS drivers for MySQL could be so slow compared to others, and then fast inside a transaction?

Kind regards,
Rogier

**Comment by dougwilson** [comment]
If anyone can diagnose the speed issues they are experiencing specifically and offer up PRs, that would be the best course of action :)
