### ISSUE TITLE
SSL3_GET_RECORD:wrong version number when using X.509 v3 with intermediate CA

### ISSUE THREAD

**Issue by MichalStaruch** [felixge/node-mysql#917]
Using X.509 v3 certificates with intermediate CA in MySQL result in errors like this:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: 140178143799072:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:../deps/openssl/openssl/ssl/s3_pkt.c:338:

    at SlabBuffer.use (tls.js:234:18)
    at CleartextStream.read [as _read] (tls.js:454:29)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.write [as _write] (tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at EncryptedStream.Writable.write (_stream_writable.js:182:11)
    at Socket.<anonymous> (/vagrant-shared/redis-feeder/node_modules/mysql/lib/Connection.js:311:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
```
MySQL 5.6.19, Debian 7.6 amd64.
Here's archive with test certificates: https://www.dropbox.com/s/bydkkv21pt9kqvl/fake-certs.zip?dl=1
Certificates were generated with xca, using CA, HTTPS_server and HTTPS_client templates appropriately.

SSL options for node-mysql are created as below:
```js
{
    ca: [
        fs.readFileSync("fake-ca.crt"),
        fs.readFileSync("fake-ca-it.crt")
    ],
    cert: fs.readFileSync("fake-client.crt"),
    key: fs.readFileSync("fake-client.pem")
};
```
In /etc/mysql/my.cnf following lines are present:
```
ssl-ca=/etc/mysql/fake-ca-it.crt
ssl-cert=/etc/mysql/fake-server.crt
ssl-key=/etc/mysql/fake-server.pem
```
User has privileges as below:
```sql
GRANT ALL PRIVILEGES ON fakedb.* to 'fake'@'%' IDENTIFIED BY 'fake' REQUIRE ISSUER '/CN=fake-ca-it' AND SUBJECT '/CN=fake-client' WITH GRANT OPTION;
```
CA certificates were added to "/usr/share/ca-certificates/fake" and activated via "sudo dpkg-reconfigure ca-certificates" command.

The same certificates work fine with MySQL Workbench, using fake-ca-it.crt as CA, fake-client.crt as CERT, and fake-client.pem as KEY.

No problems with establishing connection via OpenSSL tools, too - that is
```sh
openssl s_server -accept 1234 -CAfile fake-ca-it.crt -cert fake-server.crt -key fake-server.pem -verify 2
```
and
```sh
openssl s_client -port 1234 -CAfile fake-ca-it.crt -cert fake-client.crt -key fake-client.pem
```
results in
```
    Verify return code: 0 (ok)
```

**Comment by MichalStaruch** [comment]
@dougwilson Any chance for implementing `SSL_VERIFY_SERVER_CERT` this year?

**Comment by dougwilson** [comment]
Hi, sorry this had stalled out for so long. We do currently support SSL with the most recent version, and by default we validate certificates (i.e. the functionality that the `SSL_VERIFY_SERVER_CERT` flag does on the standard C client). Because we use Node.js SSL, you are unfortunately still constrained by it's limitations, like that it cannot use any certificates in your system store, only what is built-in to Node.js itself or what you provide (and it has to be in the format Node.js requires).

In addition, we just fixed the fact that the original exception was not being caught in our SSL routines.

**Comment by MichalStaruch** [comment]
@dougwilson Thanks for the info. :+1:
