### ISSUE TITLE
Using pool.query to run a long than 10 minutes disconnects

### ISSUE THREAD

**Issue by domrein** [felixge/node-mysql#942]
When using pool.query to run a query that lasts longer than 10 minutes this error is always received:
```
Error: Connection lost: The server closed the connection.
```
This issue does not happen if I use `pool.getConnection` and then `connection.query` to run the same query. The issue can be reproduced just by running `pool.query("SELECT SLEEP(60*15)")`

**Comment by dougwilson** [comment]
Hi @domrein , I'm sorry the question got lost :( Are you still experiencing this? I was not able to reproduce this issue.

**Comment by domrein** [comment]
I'm unable to reproduce this any longer either. It must have been fixed since I posted this. Thanks for checking out the issue!

**Comment by dougwilson** [comment]
Thanks for the confirmation, @domrein , that's also what I figured: I may have fixed this but forgot this ticket was associated so let it linger on :) Please always feel free to open new issues whenever you ahev a problem!
