### ISSUE TITLE
connections slow

### ISSUE THREAD

**Issue by gotmikhail** [felixge/node-mysql#944]
Sorry if this is such a vague question, but we're currently having issues w/ connections taking a few seconds (or more) to be established.

We're working with Google's Cloud SQL. I know they have an option where the system goes to sleep after inactivity, but we have that option off (so the system is up 24/7).

This doesn't happen all the time, to be honest, I would say that it's the system waking up, but I'm actually working w/ Google right now on this issue and, just as any vendor would, they insist that the system is not going to sleep.

So, I was wondering if there's anything w/ the pool connections that "go to sleep", or if people know of a mysql option, or ...

**Comment by dougwilson** [comment]
Hi @gotmikhail , I''m really sorry your issue seems to have fallen through the cracks. Do you still need help on this?

**Comment by thomaaam** [comment]
We are experiencing the same issue with Microsoft Azure. If our application has not received any requests for a while, MySQL queries suddenly takes 10-60 seconds to go through and finish. The "funny" part is that we used the exact same configuration with Amazon EC2, where it worked every time. We are also working with Microsoft as we speak to solve this issue, and even they claim their system is not going to sleep after a period of inactivity. 

I Actually made the discovery of a quick fix, where the idea was to keep the MySQL connections busy with queries being made every three seconds to every database in use. This solved the issue, but is not a clean fix. We are desperate to get to the bottom of this.

**Comment by sidorares** [comment]
@thomaaam are you using IP address or host name to connect? ( maybe it's DNS lookup issue sometimes? )

**Comment by thomaaam** [comment]
Have tried connecting using both IP address and host name, and sadly it does not eliminate the problem, but thanks anyway!

**Comment by thomaaam** [comment]
Our problem was with the Azure Load Balancer dropping idle connections on timeout. Our database connections are at the time being external and thus do not reside within the Azure boundaries, therefore making connections painfully slow after periods of inactivity.

**Comment by dougwilson** [comment]
Ah, makes sense. If there is not a way to adjust your Azure Load Balancer timeout settings, you can always queue up periodic `conn.ping()` commands to keep the connections busy :)!
