### ISSUE TITLE
ETIMEDOUT and lack of callbacks with remote MySQL server

### ISSUE THREAD

**Issue by EvilTrev** [felixge/node-mysql#952]
This issue affects both `node-mysql`, and `node-mysql2`. It is a hole in the pool API that can allow a potential edge case to totally destroy your server. Here is a rough breakdown of the problem and my workaround...

1. Using remote MySQL server, a machine where your Node is not running.
2. Use a connection pool to connect, say 20 connections.
3. Issue a query every 5 - 10 seconds or something from a browser or several, doesn't really matter.
4. Wait a duration of time roughly equal to your MySQL connection timeout (mine was 90 minutes).
5. IF a query is in flight, and you are waiting on a callback whilst or after `ETIMEDOUT` error occurs on a connection... the query never seems to time out, or the callback you are expecting is never fired. Often, if not always, on my setup.
6. By placing a suicide timer alongside the query, and invoking the callback yourself with an error after killing the connection end/destroy will prevent deadlock... 
7. Without the suicide timer, more deadlocks occur and eventually your node server will stop serving anything at all. If you reverse-proxy, you will see 503 errors.

General observation:

ConnectionPool doesn't seem to correctly handle `connection.on("error",function(){});` and "end" events, or they escape/abort the query callback somehow so it is never fired. The particular error that messes everything up is:
```
{ [Error: read ETIMEDOUT]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'read',
  fatal: true }
```
And whilst it's seen at the global connection.on handlers, it doesn't get returned by the query.

Hope this helps someone, somewhere approach this problem. I'll dig into the code sometime to see if I can help... but I've lost a lot of ground to chasing this down and need to play catchup first.

**Comment by dougwilson** [comment]
Closing due to lack of response. Please feel free to post back with answers to the questions and I can always reopen :)

**Comment by rizvanhaider** [comment]
Having the same issue with node 4.4.0

**Comment by winterlightning** [comment]
have the same issue

**Comment by dougwilson** [comment]
Please, if no one is going to actually provide any information that I requested above, nothing is going to change, so there is no point in commenting at all. I'm going to lock the issue since no one actually providing any information to help and is just creating noise.
