### ISSUE TITLE
why query does not fire in serial

### ISSUE THREAD

**Issue by sapkal-manish** [felixge/node-mysql#967]
I have created one app using node js. In this app, I am giving some points to my user on every login for a each single day. means If user is doing login in my app on 28-12-2014, I have to give 1 point for login for 1st time. If this user is login thereafter on same day, I am not giving point (because he/she has already credited fot it). It is working vary well for most of the users who is login, but in a such case it is showing me strange output. first of all I am going to explain my stored procedure.

First stored procedure
```sql
CREATE PROCEDURE sp_Login(
   IN  cUserName VARCHAR(50),
   IN  cPassword VARCHAR(20),
)
BEGIN
   DECLARE dLoginTime DATETIME DEFAULT NULL;
   DECLARE nUserID INT DEFAULT NULL;
   DECLARE nLoginID INT DEFAULT NULL;

   SET dLoginTime = NOW();
   IF EXISTS(SELECT 1 FROM Users WHERE UserName = cUserName AND Password = cPassword) THEN

      SELECT UserID = nUserID FROM Users WHERE UserName = cUserName AND Password = cPassword;
      IF (nUserID > 0) THEN  //If userid from 
         //Insert record in login table with current datetime
         SET nLoginID = LAST_INSERT_ID();

         //Then I am checking for points, in another stored procedure.
	 CALL sp_Points(nUserID, nLoginID);
         
	 SELECT nLoginID AS LoginID, "Success" AS Result;
      END IF;
   ELSE
      SELECT -1 AS LoginID, "Failed" AS Result;
   END IF
END
```

Second stored procedure
```sql
CREATE PROCEDURE sp_Points(
   IN  nUserID  INT
   IN  nLoginID INT
)
BEGIN
   DECLARE dLoginTime DATETIME DEFAULT NULL;
   SET dLoginTime = CURDATE(); //here I am using CURDATE(), because In my points table, LastCreditDate field has Date Datatype.
   IF NOT EXISTS(SELECT 1 FROM Points WHERE UserID = nUserID AND LastCreditDate >= dLoginTime) THEN
	//Insert in point table.
        INSERT Points (userid, points, loginid, creditdate )
        VALUES (nUserID, 1, nLoginID, dLoginTime);  
   END IF
END
```
If one situation I am assuming, One user has open my app in 2 tabs, and trying to login from both tabs, entereing valid username and password. what happens in my server (node) what I guess.

Tab-1 :

Request comes on router.

Get new mysql connection from pool, and execute statement `Call sp_Login("jhon", "his password");`

Tab-2 :

Request comes on router from 2nd tab.
Get another new mysql connection from pool, and execute statement `Call sp_Login("jhon", "his password");`

In this case my login table shows me records like this.

Login

| loginid | userid |  logintime |
|-----|-----|-----|
| 1       | 1       | 2014-12-28 10:10:10 |
| 2       | 1       | 2014-12-28 10:11:11 |

Points	

| pointid | userid | points | loginid | creditdate |
|-----|-----|-----|-----|-----|
| 1      | 1      | 1      | 2      |  2014-12-28 10:11:30 |
| 2      | 1      | 1      | 1      |  2014-12-28 10:11:30 |

Here my first query for inserting data in "Points" is stuck, and Inserted after 2nd login is happend, (why I don't know, may be some row/table locking or deadlock situation occured), I have created index for "userid, creditdate" field in "Points" table, still this will showing "creditdate" time late by 20-30 seconds as per "logintime" from my "Login" table. (almost in every case)
 

My "Points" table should be having as follows"

| pointid | userid | points | loginid | creditdate |
|-----|-----|-----|-----|-----|
| 1      | 1      | 1      | 1       | 2014-12-28 10:11:11  (same time of login or may be with some minimum late time) |

This is very serious problem for me, and didn't getting any clue for this. Is there any setting in mysql to set priority (I know 'priority' option in query, but I have not set anywhere in my code), I don't understand, why it is not working synchronously (means command placed queue and execute one by one).

**Comment by dougwilson** [comment]
Hi!

So this problem occurs in all languages and runtimes. You'd have the same problem in PHP, Python, Java, C#, etc., so it's not specific to JavaScript, Node.js, or this library. The root issue is in your stored procedure and your table layout.

Basic answer: `creditdate` should be changed to a `DATE` column type and you need to add a `UNIQUE INDEX` to `userid, creditdate`, so a given user id cannot get entries in that row more than one time per day. The "locking" mechanism for this in MySQL is the `UNIQUE INDEX`.

**Comment by sapkal-manish** [comment]
@dougwilson, In my table structure/database design, I have not allow to create "UNIQUE INDEX". My question is, why my 1st query complited after 2nd query is complited (about 20-30 second later)?

**Comment by sapkal-manish** [comment]
@dougwilson, I have another doubt regarding pool. If I release connection using "connection.release()", should session in mysql is closed or remain same for another user who is open it using "pool.getConnection()"? If it is remain same, then all the variables declared with "@" (globle) will see to another user. (In this case user means, my application user, not mysql user)

**Comment by dougwilson** [comment]
> My question is, why my 1st query complited after 2nd query is complited (about 20-30 second later)?

I really cannot answer this unless you send me enough code that I can run against a MySQL server that reproduces the issue.

> If I release connection using "connection.release()", should session in mysql is closed or remain same for another user who is open it using "pool.getConnection()"?

It always remains the same. You should `connection.destroy()` if you don't want it to remain the same--the choice is yours. If you want to reset the session between each `getConnection()` then you'll just make lots of new connections to the database. In very new versions of MySQL (5.6+) there is a way around this which we plan to support but do not yet (though this won't help you if you're using an older MySQL).

> If it is remain same, then all the variables declared with "@" (globle) will see to another user. (In this case user means, my application user, not mysql user). 

Correct, if you are using `SET` queries. You'll want to either clear those before calling `release()` or call `destroy()` instead (you can always just always clear them after the `getConnection()` as well).

> How Do I format questions while raising issue in github issue section? I think my above main question is well formated (so easily readable) by some other person, not by me. 

Yes, I usually reformat stuff for people, because I don't expect users to know all the intricacies of using GitHub just to ask for help :) GitHub's help page for formatting is here: https://guides.github.com/features/mastering-markdown/
