### ISSUE TITLE
connection pooling for single user in asynchronous environment 

### ISSUE THREAD

**Issue by sapkal-manish** [felixge/node-mysql#970]
I have created one web application on node js using express. I am using mysql database as data storage. I have created on custom `dbutil.js` file, which is doing all the database related jobs. Here I   am using connection pool as follows.
```js
pool = mysql.createPool({
    host: 'connection',
    user: 'user',
    password: 'password',
    database: 'databasename',
    multipleStatements : true,
    debug: false, //['ComQueryPacket', 'RowDataPacket']
    connectionLimit : 20, /*The maximum number of connections to create at once. (Default: 10)*/
    //queueLimit : 0,
    //waitForConnections : false
});

pool.on("connection", function(connection) {
    // console.log('multipleStatements ' + pool.config.connectionConfig.multipleStatements);
    // nodeUtil.errorLog('mySql-pool: new connection opened.', null, 'mysql_util.js', 'pool.onConnection');
});

pool.on('enqueue', function () {
    console.log('Waiting for available connection slot');
});

module.exports.execute = function(query, callback) {
   pool.getConnection(function(err, connection) {
      if (err) { return callback(err, null); }
      else if (connection) {
          connection.query(query, function(err, rows, fields) {
              connection.release(); //send back to pool
              if (err) { return callback(err, null); }
              return callback(null, rows);
          })
      }
      else { return callback("No connection available in the pool", null); }
   });
})
```
First of all, please guide me If I am doing any wrong and correct me. 

Now my question is, If one user is doing login from my web application and send his credential using ajax to my server, I have write a code in my app.js in 'login' route. Then I am preparing query for login and call "dbutil" modules "execute" method. It is working ok. But in a heavy load/traffic, may be user get slow response from mysql, and user press "login" button again from webpage, new connection will be fetch from pool for same user and same request. Means at this time on my database server, this user has 2 request for login, How can I handle this situation. Please suggest me for "transaction"  (e.g. commit, rollback) or row locking mechanizem if necessary, It is very critical problem, and harming my database as well as server/application too, so please try to give solution as early as possible. may be following error also come in this regards : http://stackoverflow.com/questions/27719579/cant-create-a-new-thread-errno-12

and this is also linked with #967.

**Comment by dougwilson** [comment]
> may be user get slow response from mysql, and user press "login" button again from webpage

You probably don't want the user to even be tempted to do this; disable the button, show a loading screen, etc. This doesn't address your root question, but you should at least prevent the user from double-clicking your button in your client-side code.

> new connection will be fetch from pool for same user and same request. Means at this time on my database server, this user has 2 request for login

Correct. This problem occurs in all languages and runtimes. You'd have the same problem in PHP, Python, Java, C#, etc., so it's not specific to JavaScript, Node.js, or this library.

> How can I handle this situation

There is no MySQL queries in here or anything to help. Like I said, this is a very basic problem that is not specific to this library or even Node.js. The answer is based on your MySQL query itself.

**Comment by sapkal-manish** [comment]
thanks @dougwilson for replying. If I made TRANSACTION ISOLATION LEVEL in both session. Is it possible to prevent about situation? Means If my user tryes first time, that row is locked untill it is commit/rollback, meanwhile 2nd request comes to mysql for the same record, data cannot be fatched/seen in 2nd transaction (because It is locked by 1st transaction). Is it possible? If so, can you please provide me any example? thanks.

**Comment by dougwilson** [comment]
I'm not sure. Unfortunately I'm not a MySQL expert :( Perhaps someone else might see this open question on GitHub and chime in with an answer, otherwise I don't have an answer for you. You can also try asking on somewhere like stackoverflow.com if you're not sure as well.

**Comment by sapkal-manish** [comment]
@dougwilson, If my long query is running, in this situation, can another user able to get same connection from pool (which is not release yet (using connection.release())? I mean to say, same connection will be get (using  pool.getConnection() ) if task is running on connection.

**Comment by dougwilson** [comment]
No, `getConnection()` only gives out "free" connections or new ones--as long as you did not call `.release()` on the connection incorrectly, then that won't happen.

**Comment by sapkal-manish** [comment]
@dougwilson, thanks for reply. Now when will it disconnected from pool? let say there is no connection in pool, and one user required it, so, pool creates new connections as per  "connectionLimit", right? let say, I have set only 1. so, one new connection is created. and after successful, I am releasing it to pool. now it is back to pool. My question is when this connection is destroyed/disconnected from pool? any property to set this?

**Comment by dougwilson** [comment]
> My question is when this connection is destroyed/disconnected from pool? any property to set this?

It'll never be destroyed or disconnected unless there is a network error, the MySQL closes the connection or you close it yourself. You can close it yourself by calling `connection.destroy()` instead of `connection.release()`.
