### ISSUE TITLE
How can I get process id from connection?

### ISSUE THREAD

**Issue by sapkal-manish** [felixge/node-mysql#971]
How can I get process id from connection? Is there any property for the same? I want to identify each connection uniquely, so I can track which connection/session used by my application user. thanks

**Comment by sidorares** [comment]
there is `threadId` property of connection:
```js
var conn = mysql.createConnection({
  user: 'root',
  password:'12345'
});
conn.query('select 1+1', function() {
  console.log(conn.threadId);
});
```

**Comment by dougwilson** [comment]
@sidorares this doesn't need the "docs" tag, since it's already in the documentation at https://github.com/felixge/node-mysql#getting-the-connection-id :)

**Comment by sidorares** [comment]
oops, I assumed @sapkal-manish looked at readme first :)
