### ISSUE TITLE
Can't We Post SP directly ?!

### ISSUE THREAD

**Issue by weezyboyaxy** [felixge/node-mysql#972]
hmm....i should say thanx @alexcroox :+1:  for rising the question   &  @dougwilson :+1:  for giving the proper solution !

And My Question is can we use SP name directly instead of query !

EX : `var sql = 'usp_InsertLinkedInConnections_linkedin_Insert(?)';`  [ im not able to use like this !]

i was able to execute my program with this syntax !

--> `var sql = 'INSERT INTO linkedin(LinkedInID, FirstName, LastName, UserID) VALUES ? ';`

Can any1 help me with this issue :) plzz......

**Comment by dougwilson** [comment]
You need to use proper MySQL syntax to call a stored procedure, namely you need to write `CALL`:
```js
conn.query('CALL usp_InsertLinkedInConnections_linkedin_Insert(?)', ['value'])
```
