### ISSUE TITLE
need help on how to troubleshoot pool

### ISSUE THREAD

**Issue by kelchy** [felixge/node-mysql#973]
this is how i used node-mysql
```js
var mysql = require('mysql');
var connectionpool = mysql.createPool({
        host     : '127.0.0.1',
        user     : 'dbuser',
        password : 'dbuser123',
        database : 'db',
        connectionLimit : 30
});

db.getConnection(function(err, connection) { if ( !err ) {
                var q = "SELECT 1";
                connection.query(q, function(err, rows) { if ( !err ) {
                        for ( var i=0; i<rows.length; i++ ) {
                                ... process ...
                        }
                }
                connection.release();
                });
        }});
```
everything works ok, except that after a few hours or days, my express-based app returns no data 
and i have to restart the whole app, then it will work perfect again for hours, sometimes days.

i suspect it has something to do with connections. any ideas on how to isolate this?

**Comment by dougwilson** [comment]
It sounds like you may be leaking connections somewhere. This would happen if somewhere in your code base you are `.getConnection` and then there is no matching `.release` down every code path after that--I assume that's not the sole mysql call in your whole project, correct?

**Comment by kelchy** [comment]
yes, i got tons of calls and that's the first thing i checked when i got this behavior.
all `<.getConnection>` are matched with `<a .release>`

other than this, what other things should i look out for or how do i find the root cause?

**Comment by dougwilson** [comment]
That's the only cause that I am aware of, unfortunately. If you're not already, you can double-check that you're also using the most recent version of this library in case it's a bug as well.

You can also add this to your code: `connectionpool.on('queue', function(){console.log('conn queued')})` and see if when your code is "stuck" that those messages are still being printed, which would at least isolated that it is an issue where not all connections are getting released back to the pool.

**Comment by kelchy** [comment]
good idea, thanks doug. 
will try this

**Comment by kelchy** [comment]
i tried `connectionpool.on('enqueue', function(){console.log('conn queued')})`

whenever i get the lockup, i would see logs bombing out this message.
is it because connections were queued but never goes through?
so this really means i got some kind of connection leak?

**Comment by dougwilson** [comment]
>  is it because connections were queued but never goes through?

it means that all your calls to `getConnection` are queued, waiting, because there are currently `connectionLimit` connections (probably 30, looking at your code above).

>  so this really means i got some kind of connection leak?

Most likely. If you are comfortable modifying the installed source in your `node_modules` temporarily for debugging, the do this:

1. Open your local to https://github.com/felixge/node-mysql/blob/v2.5.4/lib/Pool.js#L23 and add this code: `cb = function(){cb.apply(this, arguments)};cb.trace=new Error('getConnection');`
2. Open your local to https://github.com/felixge/node-mysql/blob/v2.5.4/lib/Pool.js#L93 and add this code: `cb.trace&&console.error(cb.trace.stack)`

Now run your app again. Once it starts hanging, you know that at the minimum, the last trace you got leaked, as in it'll point to a call to `getConnection` that ran through a code path without a corresponding `release` call. Once you fix that, repeat again until you cannot get your app to hang any longer.

**Comment by kelchy** [comment]
thanks doug. this will be very helpful

**Comment by kelchy** [comment]
Hi Doug,

been trying to chase after this issue for quite some time now.
I can now verify that during the times that it is failing, i can get past `.getConnection` but i cannot do a `.query`
it just stays there doing nothing, no error as well. the client will just say socket error connection timeout
does this mean i am not having a connection leak but another issue altogether? because i can get a  connection from the pool, the query just won't go through. Is there any other reason for such behavior?

and another curious thing is, i can now predict when it will fail, around 1 hour from start time. I have monit installed monitoring http on port 80, after 1 hour of running, monit will email me saying node failed http test. and it will restart. after 1 hour, monit will email me again, and so on and so forth.

**Comment by dougwilson** [comment]
Can you post the exact version of this module you are using?

**Comment by kelchy** [comment]
nodejs-mysql 2.5.2

**Comment by kelchy** [comment]
crap. sorry the `.getConnection` also failed

**Comment by kelchy** [comment]
now trying 2.5.4
let's wait for the next hour :)

**Comment by kelchy** [comment]
still failed.

by the way, if i do the logging suggestion you mentioned, i get this

RangeError: Maximum call stack size exceeded

and everything stop working

**Comment by dougwilson** [comment]
Oops. Here are the corrected instructions:

1. Open your local to https://github.com/felixge/node-mysql/blob/v2.5.4/lib/Pool.js#L23 and add this code: `var cb1=cb;cb = function(){cb1.apply(this, arguments)};cb.trace=new Error('getConnection');`
2. Open your local to https://github.com/felixge/node-mysql/blob/v2.5.4/lib/Pool.js#L93 and add this code: `cb.trace&&console.error(cb.trace.stack)`

**Comment by kelchy** [comment]
ok done that. right now i don't see anything on the logs.
time to wait for an hour

**Comment by kelchy** [comment]
happened again after 1 hour. but all is silent.
no entries on logs

**Comment by kelchy** [comment]
This is what i saw after the hour. connection was opened and released.
but the next `.getConnection` just got stuck.

Error: getConnection
    at Pool.getConnection (/home/nodeuser/node_modules/mysql/lib/Pool.js:23:65)
    at Pool.releaseConnection (/home/nodeuser/node_modules/mysql/lib/Pool.js:135:10)
    at PoolConnection.release (/home/nodeuser/node_modules/mysql/lib/PoolConnection.js:33:15)
    at Query._callback (/home/nodeuser/contacts.js:80:17)
    at Query.Sequence.end (/home/nodeuser/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/home/nodeuser/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/home/nodeuser/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/home/nodeuser/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/home/nodeuser/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/home/nodeuser/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/nodeuser/node_modules/mysql/lib/Connection.js:82:28)


I also noticed that i get a lot of this below but seldom or none of the one above except this instance before it got stuck.

Error: getConnection
    at Pool.getConnection (/home/nodeuser/node_modules/mysql/lib/Pool.js:23:65)
    at Object.exports.getConnection (/home/nodeuser/db_handler.js:12:17)
    at /home/nodeuser/contacts.js:76:7
    at IncomingForm.<anonymous> (/home/nodeuser/node_modules/formidable/lib/incoming_form.js:104:9)
    at IncomingForm.EventEmitter.emit (events.js:92:17)
    at IncomingForm._maybeEnd (/home/nodeuser/node_modules/formidable/lib/incoming_form.js:551:8)
    at JSONParser.parser.onEnd (/home/nodeuser/node_modules/formidable/lib/incoming_form.js:524:10)
    at JSONParser.end (/home/nodeuser/node_modules/formidable/lib/json_parser.js:34:8)
    at IncomingMessage.<anonymous> (/home/nodeuser/node_modules/formidable/lib/incoming_form.js:129:30)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)



what i don't understand is, it seems like the 2nd snippet above is the release part. I put a log entry everytime I call `connection.release()` but I don't see a corresponding stack dump for the times I call `connection.release()` why is that? any more ideas?

**Comment by dougwilson** [comment]
From what you posted, it sounds like what I suspected: for all the times you call `getConnection`, your code then has some code path that doesn't call `.release()` _in every single case_. Perhaps you can post your `contacts.js` file?

**Comment by kelchy** [comment]
i checked my error logs this morning, i was looking for this entry `at PoolConnection.release (/home/nodeuser/node_modules/mysql/lib/PoolConnection.js:33:15)`
there is no indication of release, but my out logs show that all connections are released (c.log() = console.log )


this is a snippet from contacts.js
`db.getConnection` is on line 76

                        db.getConnection(function(err, connection) { if ( !err ) {
                                c.log(req.ip,'api/2/contacts/status/get/ Connection Opened');
                                var q = "SELECT number num, app_status, longtitude, latitude, accuracy, UNIX_TIMESTAMP(app_lastseen) lastseen, IF(app_lastseen < DATE_SUB(NOW(),INTERVAL 6 minute),'false','true') online FROM customers WHERE CONCAT('+',number) IN (" + str + ")";
                                connection.query(q, function(err, rows) {
                                        connection.release();
                                        c.log(req.ip,'api/2/contacts/status/get/ Connection Released');
                                        if ( !err ) {
                                                str = '{"circle_users_stats":[';
                                                for ( var i=0; i<rows.length; i++ ) {
                                                        str += '{"ph":"+' + rows[i].num + '","st":' + rows[i].app_status + ',"lng":' + rows[i].longtitude + ',"lat":' + rows[i].latitude + ',"acc":' + rows[i].accuracy + ',"ls":' + rows[i].lastseen + ',"on":' + rows[i].online + '},';
                                                }
                                                str = str.slice(0,-1) + ']}';
                                                res.send(str);
                                        } else res.status(500).json({"code":c.SERVER_DATABASE_ERROR,"details":"db error","description":"DB Error"});
                                });
                        } else res.status(500).json({"code":c.SERVER_DATABASE_ERROR,"details":"db error","description":"DB Error"}) });

**Comment by kelchy** [comment]
it's also noteworthy that i have 2 nodejs apps using this mysql module, the other one is already running for days with no problems.

memory usage of app during startup uses 40mb, before locking up, 90mb. possible memory leak?

**Comment by kelchy** [comment]
FYI, fixed this issue.
did a complete rewrite.

**Comment by dougwilson** [comment]
Gotcha. So it sounds like there most likely was a connection leak, where `.release()` was not called in all possible code paths from the `.getConnection()`.
