### ISSUE TITLE
table names are automatically lowercased

### ISSUE THREAD

**Issue by 5outh** [felixge/node-mysql#976]
I am trying to do the following:

```js
var connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    database: 'somedb'
});

connection.connect();

connection.query('SELECT * FROM dbTable', function (err, rows, fields) {
    if (err) throw err;
    connection.end();
});
```

(using appropriate renamings) I have the database `somedb` with a table `somedb.dbTable` that I want to connect to, but get the error:

```
Error: ER_NO_SUCH_TABLE: Table 'somedb.dbtable' doesn't exist
```

because `dbTable` is case sensitive.

**Comment by dougwilson** [comment]
This is, unfortunately, being done by your MySQL server, as this module doesn't even touch the SQL and only hands it s-is to the MySQL server. Do you get the same behavior with the mysql(1) command line?

**Comment by dougwilson** [comment]
Another thing you can try is to test out any other MySQL modules on npm and see if they also have this behavior.

**Comment by 5outh** [comment]
@dougwilson I had a hunch :\

I can ssh into the mysql server and it works as expected, I'll have to check with our sysadmin about it. Thanks for your help!

**Comment by dougwilson** [comment]
Alright. Well, let me know if you have any other questions, etc. :)
