### ISSUE TITLE
rows as array of values without column with value object

### ISSUE THREAD

**Issue by abarik1981** [felixge/node-mysql#981]
Is there a flag that can be set to allow the output for the following to be as

```javascript
connection.query('SELECT 1 + 1 AS solution', function(err, rows, fields) {
  if (err) throw err;

  console.log('The solution is: ', rows[0].solution);
});

// output as: rows = [[2]] instead of row = [{solution: 2}]
```

Thanks,
Amit

**Comment by dougwilson** [comment]
No, but #770 is the open feature request to implement this. If you can, please feel free to contribute an implementation :)!

**Comment by sidorares** [comment]
@abarik1981 if you decide to implement it - would be good if its compatible with node-mysql2 ( https://github.com/sidorares/node-mysql2#receiving-rows-as-array-of-columns-instead-of-hash-with-column-name-as-key )

**Comment by dougwilson** [comment]
Ooo, I didn't know mysql2 has this :) I guess that means another answer is to try out mysql2 module :)

**Comment by sidorares** [comment]
I doubt that array feature is that important to make a switch but if you really focus on speed than yes, worth trying :)
