### ISSUE TITLE
retrieve id on duplicate with one query

### ISSUE THREAD

**Issue by ktiniatros** [felixge/node-mysql#986]
Hi,

I'm executing the following query:

    insert into users (username, password) values("username","password") on duplicate key update password=values(password)

The table users has two fields, id (unique key auto incremented), username (unique text) and password

When this query is first executed I get back the inserted row id. But when the username already exists and so I just update the duplicate, I do not get back the id of that record. Is there any way to learn the id without having to execute one more query ??

**Comment by dougwilson** [comment]
I believe you cannot avoid the second query. You can see the MySQL documentation at https://dev.mysql.com/doc/refman/5.6/en/insert-on-duplicate.html for more information.
