### ISSUE TITLE
Escaping object goes through prototype chain, not the actual object

### ISSUE THREAD

**Issue by aronduby** [felixge/node-mysql#989]
Not 100% sure I described it right, but it boils down to not using the `hasOwnProperty()` function when getting the property/values. I wouldn't call this a bug, more something that could use some clarification in the documentation. 

Here's how I stumbled upon this:
```sql
CREATE TABLE `machine` (
  `machine_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `abbv` varchar(20) NOT NULL,
  `image` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `note` text,
  `active` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`machine_id`),
  UNIQUE KEY `abbv` (`abbv`)
)
```

```javascript
var pool = mysql.createPool({
    // connection settings
});

function Machine(opts){
    // loop through opts and set the parameters
}
Machine.prototype.machine_id = null;
// all the fields above
Machine.prototype.other_field = null; // not in the database

Machine.prototype.save = function(){
    var self = this;
    pool.getConnection(function(err, db){
        db.query("INSERT INTO machine SET ? ON DUPLICATE KEY UPDATE ?", [self, self]);
        // ^ unknown field error for other_field
    });
};

var mac = new Machine({ machine_id:1});
mac.save();
```

It took me a bit when that error was coming up because the debugger doesn't include `other_field` when inspecting the object. Might be worth noting that in the docs.

Also, feel free to just tell me I'm a prototypical inheritance newb (which I am) and write this off

**Comment by dougwilson** [comment]
So, hm. I may have long ago said yes, let's use `hasOwnProperty`, but these days, it's turning into a big anti-pattern, especially as ES6 is coming into the fold :) Plus I'm sure people are relying on the current behavior.

I do think we can definitely expand on the current documentation:

> Objects are turned into key = 'val' pairs. Nested objects are cast to strings.

How does the following sound?

> Objects are turned into key = 'val' pairs for each enumerable property on the object. If the property's value is a function, it is skipped; if the property's value is an object, `toString()` is called on it and the returned value is used.

Otherwise, in general, you may always want to just add some kind of method to your object that lets you get just the persisted properties. Something like the following?
```js
function Machine(opts){
    // P.S. this isn't the best pattern, because it affects the v8 hidden class
    // and may override things on the prototype, etc :)
    for (var prop in opts){
        this[prop] = opts[prop];
    }
}
Machine.prototype.machine_id = null;
// all the fields above
Machine.prototype.other_field = null; // not in the database

Machine.prototype.save = function(){
    var data = this.toMySQL();
    pool.getConnection(function(err, db){
        db.query("INSERT INTO machine SET ? ON DUPLICATE KEY UPDATE ?", [data, data]);
        // ^ unknown field error for other_field
    });
};

Machine.prototype.toMySQL = function(){
    // there are libraries like "underscore" that would simplify this
    return {
      machine_id: this.machine_id,
      other_field: this.other_field
    };
};
```

**Comment by aronduby** [comment]
I think your wording is spot on, thanks for the awesome package

**Comment by dougwilson** [comment]
No problem. I appreciate the confirmation on the wording very much!
