### ISSUE TITLE
error query method

### ISSUE THREAD

**Issue by fixy0909** [felixge/node-mysql#990]
Hello, how i can fix this error?

`TypeError: Cannot call method 'query' of undefined`

this error appear when i call `connection.query(...)` after connect socket.

Can u help me?

thanks.

**Comment by dougwilson** [comment]
That error is purely an error with your code. I would need you to paste in all your code in order to assist. It boils down to the variable `connection` is set to `undefiend` when you tried to call a method on it.

**Comment by fixy0909** [comment]
ok, ii have this pool get connection code



pool.getConnection(function (err, connection)
		{
			 async.parallel([
				function(callback)
				{
					connection.query2('SELECT user_id,username FROM users where user_id=' + data.user_id + '', function (error1, userdata)
					{
						 if (error1) return callback(error1);
						 callback(null, userdata);
						 
					});
				},
				function (callback)
				{
					if(data.user_id)
					connection.query('SELECT user_id,username FROM users', function (error3, memdata)
					{
						if (error3) return callback(error3);
						callback(null, memdata);
						connection.release();
					});
					else
						callback(null,null);
				},
				function(callback)
				{
					if(data.user_id)
					connection.query('SELECT comment_id,comment,users.user_id,username,comments.added FROM comments INNER JOIN users ON comments.user_id=users.user_id',function(error4,converdata){
						if (error4) return callback(error4);
						callback(null, converdata);
						connection.release();
					});
					else
						callback(null,null);
				}
			 ], function (err, results)
				{
					if(err) throw err;
					socket.emit('chatdata',
					{
						memdata:results[1],
						converdata:results[2],
					});
					socket.broadcast.to('room'+ data.room_id +'').emit('newuser', {userdata:results[0]});
					connection.release();
				});
		});

**Comment by dougwilson** [comment]
`connection` will be `undefined` if `err` is set; you need to actually check for `err` at the top ofyour function similar to the standard callback style.

**Comment by fixy0909** [comment]
maybe error is in async module no?

**Comment by dougwilson** [comment]
idk, but at the top, you have
```js
pool.getConnection(function (err, connection)
        {
```

but it needs to be
```js
pool.getConnection(function (err, connection)
        {
               if (err) throw err;
```

to handle the errors.

**Comment by fixy0909** [comment]
i put this line u say, and now say this

Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
    --------------------
    at Protocol._enqueue (/Users/ivo_fernandes_9/Sites/socketcode/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/Users/ivo_fernandes_9/Sites/socketcode/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/Users/ivo_fernandes_9/Sites/socketcode/node_modules/mysql/lib/Connection.js:109:18)
    at Pool.getConnection (/Users/ivo_fernandes_9/Sites/socketcode/node_modules/mysql/lib/Pool.js:45:23)
    at Socket.<anonymous> (/Users/ivo_fernandes_9/Sites/socketcode/chatserver.js:11:8)
    at Socket.emit [as $emit] (events.js:95:17)
    at SocketNamespace.handlePacket (/Users/ivo_fernandes_9/Sites/socketcode/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/Users/ivo_fernandes_9/Sites/socketcode/node_modules/socket.io/lib/manager.js:488:38)
    at WebSocket.Transport.onMessage (/Users/ivo_fernandes_9/Sites/socketcode/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/Users/ivo_fernandes_9/Sites/socketcode/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)

**Comment by fixy0909** [comment]
realy i don't know how to fix this bug

**Comment by dougwilson** [comment]
Ok, cool, so that's why you had the `undefined` error. Your issue comes down to your machine cannot connect to the remote MySQL server based on your settings. Unfortunately I cannot really assist with this unless I have access to your machines.

**Comment by fixy0909** [comment]
oh ok, thank you really had not thought about. I'll see what I can see in this matter. thank you.

**Comment by fixy0909** [comment]
dougwilson, i have this line in my code maybe because him error in query 

var pool  = mysql.createPool({


i try  replace "createPool" for "createConnection" and don't error in query. 

i don't try yet this code in one machine because this code is in my local computer.

**Comment by dougwilson** [comment]
I'm sorry, I'm not sure I understand the question :(

**Comment by fixy0909** [comment]
not a question, i try replace where i have "mysql.createPool" for "mysql.createConnecion" and the error "query" doesn't apear.
