### ISSUE TITLE
Correct way to check for a certain error

### ISSUE THREAD

**Issue by adrianblynch** [felixge/node-mysql#992]
This might be more a question for MySQL devs and DBAs but...

I want to look for duplicate entry errors in my Node code and act on them. Is it right to look at `err.code` or should I be doing something else?

Or put another way, how solid is the string `ER_DUP_ENTRY`?

**Comment by dougwilson** [comment]
We are setting the `code` on the error objects in this library. We just translate the error number that comes from the MySQL server to the error's constant name from MySQL source code. You can view the list of all the error codes we give here: https://github.com/felixge/node-mysql/blob/master/lib/protocol/constants/errors.js

> Or put another way, how solid is the string ER_DUP_ENTRY?

If you get `ER_DUP_ENTRY`, it always means the MySQL sent back error code 1062. If the question is more along the lines of "under what exact conditions the MySQL server gives error code 1062 and and is that the only error code for duplicate entries", then unfortunately I do not know for sure.

**Comment by adrianblynch** [comment]
Perfect, that's more than good enough.

**Comment by dougwilson** [comment]
:beers:
