### ISSUE TITLE
How to pass datetime in mysql stored procedure?

### ISSUE THREAD

**Issue by sapkal-manish** [felixge/node-mysql#994]
I have several stored procedures in mysql with `timestamp(6)` parameters, and want to pass it from my node module (eg. app.js). my variable for date shows me `'Sat Feb 14 2015 14:39:28 GMT+0530 (IST)'` in console and when my query (eg. `CALL usp_xyz('Sat Feb 14 2015 14:39:28 GMT+0530 (IST)'`)
fires on mysql, it shows me error `ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value`. How to solve this. should I have to reformat it as per mysql datetime format like `'YYYY-MM-DD hh:mm:ss'`

EDIT: right now I am doing as follows:
```js
new Date().toISOString().replace("T",' ').replace("Z",'')
```
Is it ok? this is not giving me microseconds, so it is not much accurate for me. thanks

**Comment by dougwilson** [comment]
You should be using the "?" placeholders or the escape functions from this library to format (they are on the readme).

**Comment by dougwilson** [comment]
What you want to do is make sure you set the `timeZone` setting for this library to match what the server is configured for, then simply do the following:

```js
var date = new Date()
conn.query('CALL usp_xyz(?)', [date])
```

and this library will convert it to the correct time zone and to to correct MySQL-formatted datetime for you (including milliseconds).

**Comment by sapkal-manish** [comment]
I have written my code as follows:
var query = "call some_storedProcedure(?,?,?,?)
var param = [new Date(), 'string', 12562, true]
var queryObj = connection.query({ 'sql' : query, 'timeout': timeout}, function(err, rows, fields) {
     connection.release(); //send back to pool
     if (err) {
         // log error
     }
     console.log(rows);
})

I don't know How to pass  param (eg. parameter value) in connection.query options? I can't find any detailed document for the same, If any let me send link.
Thanks

**Comment by dougwilson** [comment]
Do
```js
var queryObj = connection.query({ 'sql' : query, 'timeout': timeout}, param, function(err, rows, fields) {
```
