### ISSUE TITLE
How to adjust the query result format?

### ISSUE THREAD

**Issue by zacard-orc** [felixge/node-mysql#995]
Normally,the query result is the format below :
```js
[
    {
        "ddtime": "20150215 12:21:56",
        "url": "ct.ctrip.com",
        "succ": 9,
        "fail": 0,
        "succ_r": 100
    },
    {
        "ddtime": "20150215 12:21:56",
        "url": "download.hhtravel.com",
        "succ": 288,
        "fail": 9,
        "succ_r": 96.97
    },
```
Could you tell me ,how to set the config parameters to adjust the format to this style by 'node-mysql' module
```js
{
  "data": [
    [
      "Tiger Nixon",
      "System Architect",
      "Edinburgh",
      "5421",
      "2011/04/25",
      "$320,800"
    ],
    [
      "Garrett Winters",
      "Accountant",
      "Tokyo",
      "8422",
      "2011/07/25",
      "$170,750"
    ],
```
so i can reduce the  jquery convert job on the front end.
Tks

**Comment by sidorares** [comment]
no, right now you have to convert rows (as array of objects where key is field name) into array manually
see #770 #981 #658

**Comment by dougwilson** [comment]
Yes, there are no configuration options you can pass to this library to make it output in that format. @sidorares referenced some open issues that if they were fixed, would bring you much closer. Feel free to contribute an implementation as a PR! Barring that, you'll just have to process it on your server to transform it to the desired format, probably using Underscore.js or lodash.
