### ISSUE TITLE
How to parameters in query option?

### ISSUE THREAD

**Issue by sapkal-manish** [felixge/node-mysql#998]
I have written my code as follows:

```js
var query = "call some_storedProcedure(?,?,?,?)"
var param = [new Date(), 'string', 12562, true]
var queryObj = connection.query({ 'sql' : query, 'timeout': timeout}, function(err, rows, fields) {
     connection.release(); //send back to pool
     if (err) {
         // log error
     }
     console.log(rows);
})
```

I don't know How to pass param (eg. parameter value) in connection.query options? I can't find any detailed document for the same, If any let me send link.
Thanks

I don't know how to re-open issue which is closed. here is my old and full issue https://github.com/felixge/node-mysql/issues/994

**Comment by adrianblynch** [comment]
At first glance I would have expected it to be:
```
connection.query({ 'sql' : query, 'timeout': timeout, params: [1,2,3,4]}, function(err, rows, fields) {
```

But testing proves it's:
```
connection.query({ 'sql' : query, 'timeout': timeout}, [1,2,3,4], function(err, rows, fields) {
```

**Comment by sidorares** [comment]
@adrianblynch I think i can be 

```js
connection.query({ 'sql' : query, 'timeout': timeout, values: [1,2,3,4]}, function(err, rows, fields) {});
```
- see https://github.com/felixge/node-mysql/blob/master/lib/Connection.js#L42

**Comment by adrianblynch** [comment]
@sidorares - Good find. I went looking but didn't equate values as being params. I use the variable name params in my code so I was a bit blinkered.

I don't think there's an example of either way in the docs. I was looking to see if any of the `query({sql: "..."})` examples could be changed to include a param array or values field but it might take anyway from the original intent of the example code.

**Comment by sidorares** [comment]
yeah, might worth adding `query(obj, paramsArray, cb)` to docs

**Comment by sapkal-manish** [comment]
thanks for reply. now another problem is come while executing above query if my stored procedure has INOUT parameter in it.

**Comment by sidorares** [comment]
@sapkal-manish you need to make another query before and after call:

```js
connection.query("select @outParam=3");
connection.query(""call some_storedProcedure(?,?,@outParam,?)", [1,2,4]);
connection.query("select @outParam as foo", function(err, rows) {
   // if no error, rows should be one element array similar to [ { foo: 4567 } ]
});
```

**Comment by dougwilson** [comment]
This is now called out in the performing queries section: https://github.com/felixge/node-mysql#performing-queries

**Comment by leqnam** [comment]
it could be;:

If you paid attention, you may have noticed that this escaping allows you to do neat things like this:

```
var post  = {id: 1, title: 'Hello MySQL'};
var query = connection.query('INSERT INTO posts SET ?', post, function (error, results, fields) {
  if (error) throw error;
  // Neat!
});
console.log(query.sql); // INSERT INTO posts SET `id` = 1, `title` = 'Hello MySQL'
```
